import {useMemo,useState} from 'react';
import type {NetworkController} from '../../app/network-controller';
import {syncSelectionBudget,SYNC_MAX_BYTES,SYNC_MAX_ITEMS,type SyncInventory} from '../../runtime/save-sync';
const size=(bytes:number)=>`${(bytes/1024/1024).toFixed(bytes<1024*1024?2:1)} MiB`;
export function SyncSelection({controller,inventory,busy}:{controller:NetworkController;inventory:SyncInventory;busy:boolean}){
 const [selected,setSelected]=useState<string[]>([]),[settings,setSettings]=useState(true),[campaign,setCampaign]=useState(true),[query,setQuery]=useState(''),[page,setPage]=useState(0);
 const matching=useMemo(()=>inventory.items.filter(item=>`${item.key} ${item.local?.name??''} ${item.remote?.name??''}`.toLowerCase().includes(query.toLowerCase())),[inventory,query]),visible=matching.slice(page*40,(page+1)*40),chosen=inventory.items.filter(item=>selected.includes(item.key)),budget=syncSelectionBudget(chosen,settings,campaign);
 const choose=(key:string,checked:boolean)=>setSelected(current=>checked?[...current,key]:current.filter(value=>value!==key));
 const selectVisible=()=>{const next=[...selected];for(const item of visible)if(!next.includes(item.key)&&syncSelectionBudget(inventory.items.filter(value=>next.includes(value.key)||value.key===item.key),settings,campaign).fits)next.push(item.key);setSelected(next)};
 return <section className="network-sync-selection"><h4>Choose this copy batch</h4><p>Review up to {SYNC_MAX_ITEMS} items and {size(SYNC_MAX_BYTES)} at a time. Both local and host versions count toward the memory limit. No unselected save is downloaded.</p><div className="network-inline"><label className="network-check"><input type="checkbox" checked={settings} onChange={event=>setSettings(event.target.checked)}/>Include settings</label><label className="network-check"><input type="checkbox" checked={campaign} onChange={event=>setCampaign(event.target.checked)}/>Include campaign progress</label></div><p className={budget.fits?'network-kicker':'network-warning'} role="status">{selected.length} saves selected · {budget.count} / {SYNC_MAX_ITEMS} total slots · {size(budget.bytes)} / {size(SYNC_MAX_BYTES)} reserved</p><p className="network-hint">Settings and campaign progress reserve their maximum document sizes. If an older host omits a save size, that version reserves 64 MiB. Exact timestamps and mission progress appear in the next review.</p>
 <label>Find a save<input aria-label="Find archive save" value={query} onChange={event=>{setQuery(event.target.value);setPage(0)}}/></label><div className="button-row"><button type="button" onClick={selectVisible} disabled={busy}>Select visible saves that fit</button><button type="button" onClick={()=>setSelected([])} disabled={busy||!selected.length}>Clear selected saves</button></div>
 {visible.map(item=><label className="network-archive-choice" key={item.key}><input aria-label={`Include save ${item.key}`} type="checkbox" checked={selected.includes(item.key)} disabled={busy||!selected.includes(item.key)&&!syncSelectionBudget([...chosen,item],settings,campaign).fits} onChange={event=>choose(item.key,event.target.checked)}/><span><strong>{item.local?.name??item.remote?.name??item.key}</strong><code>{item.mapping.localId} ↔ {item.mapping.remoteId}</code><small>Browser: {item.local?`${new Date(item.local.updatedMs).toLocaleString()} · r${item.local.revision} · ${size(item.local.bytes)}`:'No local file'}</small><small>Host: {item.remote?`${new Date(item.remote.updatedMs).toLocaleString()} · r${item.remote.revision} · ${item.unknownRemoteSize?'size unknown, 64 MiB reserved':size(item.remote.bytes!)}`:'No host file'}</small></span></label>)}
 {!matching.length&&<p className="network-hint">No saves match this filter. Settings and campaign progress can still be compared.</p>}<div className="network-inline"><button disabled={page===0} onClick={()=>setPage(value=>value-1)}>Previous archive page</button><span>Page {page+1} / {Math.max(1,Math.ceil(matching.length/40))}</span><button disabled={(page+1)*40>=matching.length} onClick={()=>setPage(value=>value+1)}>Next archive page</button></div><div className="button-row"><button onClick={()=>controller.cancelSyncSelection()}>Cancel selection</button><button className="primary" disabled={busy||!budget.fits||!budget.count} onClick={()=>void controller.previewSelectedSync(selected,settings,campaign)}>Compare selected items</button></div></section>
}
