import {writeFile} from 'node:fs/promises';
import {TerrainSurface,compareSurfaceTriangles,type SurfaceTriangle} from './inputs/terrain-surface';
import {fogTopology as before} from './inputs/current-terrain';
import {fogTopology as after} from './inputs/candidate-terrain';
const results=[];
for(const size of [40,256])for(const raised of [false,true]){
 const surface=new TerrainSurface({width:size,height:size,tiles:Array.from({length:size*size},(_,i)=>({terrain:raised&&(i%size===16||Math.floor(i/size)%16===8)?'cliff':'open',height:raised?(i%size+Math.floor(i/size))%5:0}))});
 const row={size,raised,fragments:0,triangles:0,topTriangles:0,faceTriangles:0,beforeBytes:0,afterBytes:0,addedBytes:0,newFarIndexBytes:0,naiveEightIndicesPerTriangleBytes:0,dedupSavedBytes:0,addedDependencyEntries:0,maxFragmentBeforeBytes:0,maxFragmentAfterBytes:0,maxChunkBeforeBytes:0,maxChunkAfterBytes:0,maxConstructionNumericElements:0,maxConstructionPointMapEntries:0,maxConstructionTileMapEntries:0,maxConstructionFarMapEntries:0};
 for(let cy=0;cy*16<size;cy++)for(let cx=0;cx*16<size;cx++){
  const groups=new Map<string,SurfaceTriangle[]>();for(const t of surface.triangles({left:cx*16000,top:cy*16000,right:Math.min(cx*16+16,size)*1000,bottom:Math.min(cy*16+16,size)*1000})){if(!t.frontFacing)continue;const tier=t.kind==='face'&&Math.max(...t.vertices.map(v=>v.height))-Math.min(...t.vertices.map(v=>v.height))>1?2:1,key=`${t.depth.toFixed(6)}:${t.kind}:${tier}`;if(!groups.has(key))groups.set(key,[]);groups.get(key)!.push(t)}let chunkBefore=0,chunkAfter=0;
  for(const triangles of groups.values()){
   triangles.sort(compareSurfaceTriangles);const a=before(triangles,size,size),b=after(triangles,size,size),arrays=(x:object)=>Object.values(x).filter((v):v is Uint16Array|Uint32Array|Int32Array=>ArrayBuffer.isView(v)),bytes=(x:object)=>arrays(x).reduce((sum,v)=>sum+v.byteLength,0),ab=bytes(a),bb=bytes(b),topTiles=new Set(triangles.filter(t=>t.kind==='top').map(t=>t.tile));
   row.fragments++;row.triangles+=triangles.length;row.topTriangles+=triangles.filter(t=>t.kind==='top').length;row.faceTriangles+=triangles.filter(t=>t.kind==='face').length;row.beforeBytes+=ab;row.afterBytes+=bb;chunkBefore+=ab;chunkAfter+=bb;row.newFarIndexBytes+=b.fogFanFarStart.byteLength+b.fogFarCorners.byteLength;row.naiveEightIndicesPerTriangleBytes+=triangles.length*8*b.fogFarCorners.BYTES_PER_ELEMENT;row.addedDependencyEntries+=b.fogTiles.length-a.fogTiles.length;row.maxFragmentBeforeBytes=Math.max(row.maxFragmentBeforeBytes,ab);row.maxFragmentAfterBytes=Math.max(row.maxFragmentAfterBytes,bb);row.maxConstructionNumericElements=Math.max(row.maxConstructionNumericElements,arrays(b).reduce((sum,x)=>sum+x.length,0));row.maxConstructionPointMapEntries=Math.max(row.maxConstructionPointMapEntries,b.fogPointStart.length-1);row.maxConstructionTileMapEntries=Math.max(row.maxConstructionTileMapEntries,b.fogTiles.length);row.maxConstructionFarMapEntries=Math.max(row.maxConstructionFarMapEntries,topTiles.size);
  }row.maxChunkBeforeBytes=Math.max(row.maxChunkBeforeBytes,chunkBefore);row.maxChunkAfterBytes=Math.max(row.maxChunkAfterBytes,chunkAfter);
 }row.addedBytes=row.afterBytes-row.beforeBytes;row.dedupSavedBytes=row.naiveEightIndicesPerTriangleBytes-row.newFarIndexBytes;results.push(row);
}
const report={scope:'Source-executed topology storage accounting over actual TerrainSurface chunk/depth groups, one chunk at a time. Full-map totals are sums, not simultaneous measured residency. No browser, textures, GPU, heap high-water, timing or FPS measurement.',sizes:'40² and256² public maps, flat and a deterministic raised/cliff map',construction:'Each fragment creates numeric arrays and three temporary Maps, then typed arrays. Recorded maximum numeric element and Map-entry counts describe coexistence during conversion; engine object/string/Map overhead and garbage-collection timing are unmeasured. Face triangles allocate one unused far-start index, not eight far-corner slots. Far corners are shared per distinct top tile in each fragment; all points/dependency runs deduplicate through existing maps.',results};
if(!process.argv[2])throw Error('Explicit private output required');await writeFile(process.argv[2],JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
