// One accepted fighter handoff layered into an untouched private ordinary client.
// No sprite regeneration, source/runtime rebuild, browser, host, or live writes.
import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {mkdir,readFile,writeFile,copyFile,realpath} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {writeBasePack} from '../../../client/scripts/ui/art-plugin.mjs';import {verifyProduct,fileInventory,fileDigest} from '../../../scripts/package-integrity.mjs';
const work=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(work,'../../..'),sha=b=>createHash('sha256').update(b).digest('hex'),name=process.argv[2];assert(/^build-\d\d$/.test(name??''));const out=path.join(work,name),product=path.join(out,'product'),base=path.join(root,'work/graphics-integration-v1/build-02/package/client'),handoffPath=path.join(root,'work/art/aircraft-final-production-v1/runtime-handoff/unit.US.fighter.json'),pins={};await mkdir(out);const receipt={status:'building',scope:'Private component art overlay: accepted fighter896 only; unchanged ordinary client source bundles and Go/WASM. Not a rebuilt installer or shipping artifact.',started:new Date().toISOString()};const save=()=>writeFile(path.join(out,'receipt.json'),JSON.stringify(receipt,null,2)+'\n');await save();
async function pin(file,expected){const data=await readFile(file),hash=sha(data);if(expected)assert.equal(hash,expected,file);pins[file]=hash;return data}
try{
 await pin(fileURLToPath(import.meta.url));for(const p of ['client/scripts/ui/art-plugin.mjs','client/scripts/ui/effect-pack.mjs','scripts/package-integrity.mjs','work/art/roster-runtime-overlay-v1/overlay-v3.mjs'])await pin(path.join(root,p));
 const baseReceipt=await pin(path.join(root,'work/graphics-integration-v1/build-02/receipt.json')),baseVersion=await pin(path.join(base,'../version.json'),'a20da5913d75fb125fa0c03ada0eee76c2867be0ec9d2345d688d3b1816d1904'),basePackBytes=await pin(path.join(base,'assets/packs/base.json'),'56673aca898ee4344ceb323eae01f0b1e4f8af19ed5299f222569c0c9056afec'),basePack=JSON.parse(basePackBytes),indexBytes=await pin(path.join(base,'art/index.json')),index=JSON.parse(indexBytes);
 const validation=execFileSync(process.execPath,[path.join(root,'work/art/roster-runtime-overlay-v1/overlay-v3.mjs'),'--base-lock','work/art/aircraft-runtime-overlay-v1/base-locks/integration-v19.json','--check',path.relative(root,handoffPath)],{cwd:root,encoding:'utf8'});await writeFile(path.join(out,'handoff-validation.json'),validation);const v=JSON.parse(validation);assert.equal(v.check,'passed');assert.deepEqual(v.ids,['unit.US.fighter']);assert.equal(v.poses,896);
 const handoffBytes=await pin(handoffPath,'a251de3464e3e334122d53033524e8b4198548a31d68731de421f2459895662f'),handoff=JSON.parse(handoffBytes);assert.equal(handoff.id,'unit.US.fighter');assert(!index.sprites[handoff.id]);for(const [rel,hash] of Object.entries(handoff.checks))await pin(path.join(root,rel),hash);
 const spec=JSON.parse(await pin(path.join(root,handoff.stage,'assets/pipeline/specs/unit.US.fighter.json'),handoff.spec_sha256));await pin(path.join(root,handoff.reviewed_source??handoff.model),handoff.model_sha256);assert.equal(spec.id,handoff.id);
 await mkdir(product);execFileSync('cp',['-cR',base+'/.',product]);const baseInventory=await fileInventory(base),before=new Map();for(const row of baseInventory){const digest=await fileDigest(path.join(base,row.path));before.set(row.path,digest);assert.deepEqual(await fileDigest(path.join(product,row.path)),digest)}
 const copied=[];for(const [rel,f] of Object.entries(handoff.files)){assert(!path.isAbsolute(rel)&&!rel.split('/').includes('..'));assert(rel.startsWith('sprites/unit.US.fighter/')||rel.startsWith('ui/'));const src=path.join(root,f.source);assert((await realpath(src)).startsWith(path.join(root,handoff.stage)+path.sep));const data=await pin(src,f.sha256);assert.equal(data.length,f.bytes);const dest=path.join(product,'art',rel);await mkdir(path.dirname(dest),{recursive:true});await copyFile(src,dest);assert.deepEqual(await fileDigest(dest),{bytes:f.bytes,sha256:f.sha256});copied.push('/art/'+rel)}
 index.sprites[handoff.id]='sprites/unit.US.fighter/unit.US.fighter.sprite.json';const role=spec.role_id??spec.id;for(const field of ['portraits','buildIcons']){assert(Array.isArray(index[field]));if(!index[field].includes(role))index[field].push(role)}await writeFile(path.join(product,'art/index.json'),JSON.stringify(index));
 const pack=await writeBasePack(product),allowed=new Set(['art/index.json','content/index.json','assets/packs/base.json',...copied.map(x=>x.slice(1))]);let unchanged=0;for(const [rel,digest] of before){if(!allowed.has(rel)){assert.deepEqual(await fileDigest(path.join(product,rel)),digest,rel);unchanged++}assert.deepEqual(await fileDigest(path.join(base,rel)),digest,'Base changed '+rel)}
 const after=await fileInventory(product);for(const row of after)assert(before.has(row.path)||allowed.has(row.path),'Unowned product addition '+row.path);
 const oldContent=JSON.parse(await readFile(path.join(base,'content/index.json'))),newContent=JSON.parse(await readFile(path.join(product,'content/index.json')));assert.equal(newContent.packs.find(p=>p.id==='2.0.0').version,pack.version);newContent.packs.find(p=>p.id==='2.0.0').version=oldContent.packs.find(p=>p.id==='2.0.0').version;assert.deepEqual(newContent,oldContent,'Unexpected authored-content metadata change');
 const updated=JSON.parse(await readFile(path.join(product,'art/index.json')));delete updated.sprites[handoff.id];for(const field of ['portraits','buildIcons'])if(!JSON.parse(indexBytes)[field].includes(role))updated[field]=updated[field].filter(x=>x!==role);assert.deepEqual(updated,JSON.parse(indexBytes),'Unrelated art metadata changed');
 receipt.product=await verifyProduct(product);receipt.base={product:base,receiptSHA256:sha(baseReceipt),rootVersionSHA256:sha(baseVersion),packSHA256:sha(basePackBytes)};receipt.handoff={file:handoffPath,sha256:sha(handoffBytes),poses:896,files:copied.length,bytes:Object.values(handoff.files).reduce((s,f)=>s+f.bytes,0)};receipt.changedOrAdded=[...allowed].sort();receipt.unrelatedFilesByteIdentical=unchanged;receipt.runtime=pack.files.filter(f=>f.path.startsWith('/runtime/'));receipt.browser='UNRUN';receipt.installer='not rebuilt; this is a component product directory';receipt.baseUnchanged=true;
 for(const [file,hash] of Object.entries(pins))assert.equal(sha(await readFile(file)),hash,'Input changed '+file);receipt.pins=pins;receipt.status='built-browser-unrun';receipt.ended=new Date().toISOString();await save();console.log(JSON.stringify({status:receipt.status,product,packSHA256:receipt.product.packSHA256,handoff:receipt.handoff,unrelatedFilesByteIdentical:unchanged},null,2));
}catch(error){receipt.status='failed';receipt.error=String(error.stack??error);receipt.ended=new Date().toISOString();await save();throw error}
