import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
import {mkdir,readFile,writeFile,realpath,readdir,stat} from 'node:fs/promises';import {spawnSync} from 'node:child_process';import path from 'node:path';
import {build} from '../../client/node_modules/esbuild/lib/main.js';import {chromium} from '../../client/node_modules/playwright-core/index.mjs';
const root=process.cwd(),here=path.resolve('work/ui-polish-native-v1'),product=path.resolve('work/ui-polish-validation-v1/build-01/package/client'),source=path.resolve('work/ui-polish-validation-v1/build-01/source/client'),out=path.resolve(process.argv[2]??'');assert(process.argv[2],'New evidence directory required');const buildOnly=process.argv.includes('--build-only'),sha=b=>createHash('sha256').update(b).digest('hex');await mkdir(out);
const report={status:'preparing',started:new Date().toISOString(),buildOnly,product,scope:'Actual frozen App and ordinary skirmish entry with paused real Go, then synthetic display-only mission/events/captions/review stress. No fictional engine state, gameplay/mission/strike qualification or listening/performance claim.',pins:{},checks:[],errors:[],consoleErrors:[],httpErrors:[],requestFailures:[],served:{}};
let browser,page,server,phase='prepare';const save=()=>writeFile(path.join(out,'result.json'),JSON.stringify(report,null,2)+'\n');
const pin=async(file,expected)=>{if(file instanceof URL)file=fileURLToPath(file);const b=await readFile(file),digest=sha(b);if(expected)assert.equal(digest,expected,file);report.pins[file]=digest;return b};
const record=async(name,value)=>{report.checks.push({name,phase,...value});await save()};
try{
 const receipt=JSON.parse(await pin(path.resolve('work/ui-polish-validation-v1/build-01/receipt.json'),'2132092074abcc4522e16fb161a385eb6debd6bcdadf95a14f9e769019971728'));assert.equal(receipt.status,'built-browser-unrun');for(const row of receipt.candidateInputs.files)if(!row.directory)await pin(path.resolve('work/ui-polish-validation-v1/build-01/source',row.path),row.sha256);
 const packBytes=await pin(path.join(product,'assets/packs/base.json'),receipt.product.packSHA256),pack=JSON.parse(packBytes),listed=new Map(pack.files.map(f=>[f.path,f]));listed.set('/assets/packs/base.json',{path:'/assets/packs/base.json',sha256:sha(packBytes),bytes:packBytes.length});const admitted=new Set(pack.files.map(f=>f.sha256));
 const entry=path.join(here,'entry.tsx');await pin(entry);await pin(new URL(import.meta.url));await writeFile(path.join(out,'entry.tsx'),await readFile(entry));await writeFile(path.join(out,'browser.mjs'),await readFile(new URL(import.meta.url)));
 await writeFile(path.join(out,'css.d.ts'),"declare module '*.css';\n");const config={compilerOptions:{noEmit:true,strict:true,skipLibCheck:true,target:'ES2022',module:'ESNext',moduleResolution:'bundler',lib:['ES2022','DOM','DOM.Iterable'],jsx:'react-jsx',paths:{'frozen/*':[path.join(source,'src/*')],'react':[path.resolve('client/node_modules/@types/react/index.d.ts')],'react/jsx-runtime':[path.resolve('client/node_modules/@types/react/jsx-runtime.d.ts')],'react-dom/*':[path.resolve('client/node_modules/@types/react-dom/*')],'@bufbuild/protobuf':[path.resolve('client/node_modules/@bufbuild/protobuf/dist/esm/index.d.ts')]}},files:[entry,path.join(out,'css.d.ts')]};await writeFile(path.join(out,'tsconfig.json'),JSON.stringify(config,null,2));const tsc=spawnSync(path.resolve('client/node_modules/.bin/tsc'),['-p',path.join(out,'tsconfig.json')],{encoding:'utf8'});await writeFile(path.join(out,'typecheck.log'),(tsc.stdout??'')+(tsc.stderr??''));assert.equal(tsc.status,0,'Focused fixture TypeScript failed');
 const bundleDir=path.join(out,'bundle');const compiled=await build({entryPoints:[entry],outdir:bundleDir,entryNames:'stress',bundle:true,format:'esm',platform:'browser',target:'es2022',jsx:'automatic',metafile:true,external:['/art/*'],loader:{'.ttf':'file','.png':'file','.woff2':'file','.woff':'file','.svg':'file','.webp':'file'},nodePaths:[path.resolve('client/node_modules')],plugins:[{name:'immutable-app-sources',setup(b){b.onResolve({filter:/^frozen\//},async a=>{const prefix=path.join(source,'src',a.path.slice('frozen/'.length));for(const name of [prefix,prefix+'.ts',prefix+'.tsx',path.join(prefix,'index.ts')])try{if((await stat(name)).isFile())return {path:name}}catch{}throw Error('Unresolved frozen import '+a.path)})}}]});await writeFile(path.join(out,'bundle-metafile.json'),JSON.stringify(compiled.metafile,null,2));
 const outputs=new Map();for(const name of await readdir(bundleDir)){const b=await readFile(path.join(bundleDir,name));if(!/\.(?:js|css)$/.test(name))assert(admitted.has(sha(b)),'Bundled decoration not in immutable product pack: '+name);outputs.set('/__stress/'+name,{bytes:b,sha256:sha(b)})}report.outputHashes=Object.fromEntries([...outputs].map(([k,v])=>[k,{bytes:v.bytes.length,sha256:v.sha256}]));
 if(buildOnly){report.status='prepared-browser-unrun';report.noBrowserOrHostStarted=true}else{
  const mime={'.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp','.woff2':'font/woff2','.woff':'font/woff','.ttf':'font/ttf','.wasm':'application/wasm','.ogg':'audio/ogg','.mp3':'audio/mpeg'};
  server=createServer(async(req,res)=>{try{const route=decodeURIComponent(new URL(req.url,'http://local').pathname);assert(['GET','HEAD'].includes(req.method));if(route==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:,"><link rel="stylesheet" href="/__stress/stress.css"><div id="root"></div><script type="module" src="/__stress/stress.js"></script></html>');return}let b;if(outputs.has(route))b=outputs.get(route).bytes;else{const descriptor=listed.get(route);assert(descriptor,'Unlisted request '+route);const file=await realpath(path.join(product,route.slice(1)));assert(file.startsWith(product+path.sep));b=await readFile(file);assert.equal(b.length,descriptor.bytes);assert.equal(sha(b),descriptor.sha256)}report.served[route]={bytes:b.length,sha256:sha(b)};res.setHeader('Content-Type',mime[path.extname(route)]??'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(req.method==='HEAD'?undefined:b)}catch(e){report.httpErrors.push({phase,url:req.url,error:String(e)});res.statusCode=404;res.end('Unavailable frozen fixture resource')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const browserConfig=JSON.parse(await pin(path.resolve('work/full-app-native-body-v4/product-01.config.json')));await pin(browserConfig.executable,browserConfig.executableSHA256);browser=await chromium.launch({headless:false,executablePath:browserConfig.executable,args:['--mute-audio']});report.browserVersion=browser.version();const cdp=await browser.newBrowserCDPSession();report.gpu=(await cdp.send('SystemInfo.getInfo')).gpu;page=await browser.newPage({viewport:{width:1600,height:900},deviceScaleFactor:1});page.setDefaultTimeout(120000);page.on('pageerror',e=>report.errors.push({phase,error:String(e.stack??e)}));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({phase,error:m.text()})});page.on('response',r=>{if(r.status()>=400)report.httpErrors.push({phase,url:r.url(),status:r.status()})});page.on('requestfailed',r=>report.requestFailures.push({phase,url:r.url(),failure:r.failure()}));
  phase='ordinary-entry';await page.goto(`http://127.0.0.1:${server.address().port}`);await page.getByRole('button',{name:'Explore game modes',exact:true}).click();await page.evaluate(()=>window.presentationStress.stableCaption());await page.getByRole('button',{name:'Deploy to skirmish'}).click();await page.getByLabel('AI commanders').selectOption('0');await page.getByRole('button',{name:'Deploy forces',exact:true}).click();await page.waitForFunction(()=>{const s=window.presentationStress.ready();if(s.error)throw Error(s.error);return s.mounted&&!s.loading});await page.waitForTimeout(5500);await record('paused actual Go boundary',await page.evaluate(()=>window.presentationStress.begin(1)));
  const layout=async(label)=>{
   const value=await page.evaluate(()=>{
    const rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height}};
    const clip=e=>{let r=rect(e);r={left:Math.max(0,r.left),top:Math.max(0,r.top),right:Math.min(innerWidth,r.right),bottom:Math.min(innerHeight,r.bottom)};for(let p=e.parentElement;p;p=p.parentElement){const s=getComputedStyle(p);if(/auto|scroll|hidden|clip/.test(s.overflowX+' '+s.overflowY)){const b=rect(p);r={left:Math.max(r.left,b.left),top:Math.max(r.top,b.top),right:Math.min(r.right,b.right),bottom:Math.min(r.bottom,b.bottom)}}}return r.right>r.left&&r.bottom>r.top?r:null};
    const rows=[...document.querySelectorAll('.battle-alert,.audio-captions p,.mission-objectives,.strike-review,.targeting-hint,.resource-shoulder')].map((e,i)=>({key:e.className+'-'+i,text:e.textContent,rect:rect(e),clipped:clip(e),font:getComputedStyle(e).fontSize,horizontalOverflow:e.scrollWidth>e.clientWidth}));const overlap=[];for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){const a=rows[i].clipped,b=rows[j].clipped;if(a&&b&&Math.min(a.right,b.right)>Math.max(a.left,b.left)&&Math.min(a.bottom,b.bottom)>Math.max(a.top,b.top))overlap.push([rows[i].key,rows[j].key])}const sc=document.querySelector('.battle-information-scroll');return {rows,overlap,scroll:{top:sc.scrollTop,height:sc.clientHeight,total:sc.scrollHeight},observe:window.presentationStress.observe(),counts:{alerts:document.querySelectorAll('.battle-alert').length,captions:document.querySelectorAll('.audio-captions p').length,objectives:document.querySelectorAll('.mission-objectives p').length}};
   });await record(label,value);assert.deepEqual(value.overlap,[],label+' overlapping clipped regions');assert(value.rows.every(r=>!r.horizontalOverflow),label+' horizontal text overflow');assert.equal(value.counts.alerts,3);assert.equal(value.counts.captions,3);assert.equal(value.counts.objectives,12);await page.screenshot({path:path.join(out,label+'.png')});return value;
  };
  for(const [width,height,scale]of [[1600,900,1],[1280,720,1.5]]){
   phase=`layout-${width}-${height}-${scale}`;await page.setViewportSize({width,height});await page.evaluate(scale=>window.presentationStress.scale(scale),scale);await page.evaluate(()=>window.presentationStress.restore());await record('ordinary build target '+phase,await page.evaluate(()=>window.presentationStress.target()));await page.evaluate(()=>window.presentationStress.stress());await layout(phase+'-target-top');
   const overflowCue=await page.evaluate(()=>{const sc=document.querySelector('.battle-information-scroll'),below=document.querySelector('.information-overflow>.more-below');return {tabIndex:sc.getAttribute('tabindex'),state:sc.dataset.overflow,visible:getComputedStyle(below).visibility,text:getComputedStyle(below,'::before').content}});assert.equal(overflowCue.tabIndex,'0');assert.equal(overflowCue.visible,'visible');assert(overflowCue.text.includes('MORE'));await record('information overflow discovery '+phase,overflowCue);

   const missionButton=page.getByRole('button',{name:'Minimize mission objectives',exact:true});await missionButton.focus();const camera=await page.evaluate(()=>window.presentationStress.observe().camera);
   for(const key of ['End','Home','ArrowDown','ArrowUp']){const before=await page.locator('.battle-information-scroll').evaluate(e=>e.scrollTop);await page.keyboard.press(key);await page.waitForTimeout(250);const initial=await page.locator('.battle-information-scroll').evaluate(e=>({top:e.scrollTop,max:e.scrollHeight-e.clientHeight}));await record('native key initial '+key+' '+phase,{before,initial});if(key==='End'||key==='Home')await page.waitForFunction(key=>{const e=document.querySelector('.battle-information-scroll');return key==='End'?e.scrollTop>=e.scrollHeight-e.clientHeight:e.scrollTop===0},key,{timeout:3000});const after=await page.locator('.battle-information-scroll').evaluate(e=>({top:e.scrollTop,max:e.scrollHeight-e.clientHeight}));assert.deepEqual(await page.evaluate(()=>window.presentationStress.observe().camera),camera,'Native '+key+' moved camera');if(key==='End')assert(after.top>=after.max,'End did not reach reported scroll end');if(key==='Home')assert.equal(after.top,0,'Home did not reach scroll start');if(key==='ArrowDown')assert(after.top>before,'ArrowDown did not scroll');if(key==='ArrowUp')assert(after.top<before,'ArrowUp did not scroll');await record('native '+key+' '+phase,{before,after,camera})}
   const focusBefore=await page.evaluate(()=>{const e=document.activeElement;return {tag:e?.tagName,text:e?.textContent}});
   await page.evaluate(()=>window.presentationStress.review());await layout(phase+'-review-top');
   const reviewTop=await page.evaluate(()=>{const sc=document.querySelector('.battle-information-scroll'),card=document.querySelector('.strike-review'),heading=card.querySelector('h2'),keys=[...card.querySelectorAll('.button-row button')],rect=e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right}};return {sc:rect(sc),heading:rect(heading),keys:keys.map(e=>({text:e.textContent,rect:rect(e),font:parseFloat(getComputedStyle(e).fontSize)})),cells:[...card.querySelectorAll('td,th')].map(e=>parseFloat(getComputedStyle(e).fontSize)),focus:{tag:document.activeElement?.tagName,text:document.activeElement?.textContent},overflow:card.scrollWidth>card.clientWidth}});
   await record('opening review controls '+phase,reviewTop);assert.deepEqual(reviewTop.focus,focusBefore,'Review stole focus');assert(reviewTop.heading.top>=reviewTop.sc.top-1&&reviewTop.heading.bottom<=reviewTop.sc.bottom+1,'Review heading not initially visible');
   assert(reviewTop.keys.every(k=>k.rect.top>=reviewTop.sc.top-1&&k.rect.bottom<=reviewTop.sc.bottom+1),'Review decisions not initially visible');assert(!reviewTop.overflow,'Review horizontal overflow');if(scale===1.5){assert(reviewTop.keys.every(k=>k.font>=18));assert(reviewTop.cells.every(n=>n>=18))}
   const column=await page.locator('.battle-information').evaluate(e=>({width:e.getBoundingClientRect().width,field:innerWidth-document.querySelector('.command-sidebar').getBoundingClientRect().width}));assert(column.width<=column.field*.42+.1);if(scale===1)assert.equal(column.width,330);await record('information width '+phase,column);
await page.locator('.strike-review').getByRole('button',{name:/^Cancel(?:Esc)?$/}).scrollIntoViewIfNeeded();await layout(phase+'-review-bottom');await page.locator('.strike-review').getByRole('button',{name:/^Cancel(?:Esc)?$/}).click();await page.waitForFunction(()=>!document.querySelector('.strike-review'));await record('ordinary Cancel after display review '+phase,await page.evaluate(()=>window.presentationStress.cancel()));await layout(phase+'-cancel');
   await page.evaluate(()=>window.presentationStress.review());await page.locator('.strike-review').getByRole('button',{name:/^Cancel(?:Esc)?$/}).focus();await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('.strike-review'));await record('native Escape cancels review '+phase,await page.evaluate(()=>window.presentationStress.cancel()));
await record('restored display '+phase,await page.evaluate(()=>window.presentationStress.restore()));
   const gridRows=[];
   for(const type of await page.evaluate(()=>window.presentationStress.labelTypes())){
    await record('catalog display label '+type+' '+phase,await page.evaluate(type=>window.presentationStress.selectionLabel(type),type));
    const row=await page.evaluate(()=>{const grid=document.querySelector('.command-grid'),heading=document.querySelector('.selection-overview h2'),g=grid.getBoundingClientRect(),h=heading.getBoundingClientRect();return {heading:heading.textContent,fullAccessibleTitle:heading.getAttribute('title'),x:g.x,width:g.width,columns:getComputedStyle(grid).gridTemplateColumns.split(' ').length,headingHeight:h.height,headingScroll:heading.scrollHeight,headingClient:heading.clientHeight,headingLeft:h.left,headingRight:h.right,letters:[...heading.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE).flatMap(n=>Array.from({length:n.textContent.length},(_,i)=>{const range=document.createRange();range.setStart(n,i);range.setEnd(n,i+1);const r=range.getBoundingClientRect();return {text:n.textContent[i],left:r.left,right:r.right,top:r.top,bottom:r.bottom}})),keys:[...grid.querySelectorAll('button')].slice(0,6).map(e=>{const r=e.getBoundingClientRect();return {text:e.querySelector('span')?.textContent,visible:r.top>=g.top-1&&r.bottom<=g.bottom+1}})}});
    gridRows.push(row);await record('selection layout '+type+' '+phase,row);assert.equal(row.fullAccessibleTitle,row.heading);assert(row.keys.every(k=>k.visible),'Primary command not initially visible');assert.deepEqual(row.keys.map(k=>k.text),['Move','Attack-move','Attack','Stop','Hold','Force-fire']);
    if(type==='US.artillery'){assert(new Set(row.letters.map(c=>c.top)).size<=2,'Howitzer has more than two rendered text lines');assert(row.letters.every(c=>c.left>=row.headingLeft-.1&&c.right<=row.headingRight+.1),'Howitzer text extends beyond heading width')}await page.screenshot({path:path.join(out,phase+'-'+type.replace('.','-')+'-selection.png')});
   }
   assert(gridRows.every(row=>row.x===gridRows[0].x&&row.columns===gridRows[0].columns),'Selection type changes command positions');if(scale===1.5)assert(gridRows[0].columns>=4);await page.evaluate(()=>window.presentationStress.restore());
   const noOverflow=await page.locator('.battle-information-scroll').evaluate(e=>({tabIndex:e.getAttribute('tabindex'),height:e.clientHeight,total:e.scrollHeight}));if(noOverflow.total<=noOverflow.height+1)assert.equal(noOverflow.tabIndex,null);await record('nonoverflow region focus '+phase,noOverflow);
   const focusRows=[];const enabledCameos=page.locator('.production-cameo:enabled');
   for(let n=0;n<await enabledCameos.count();n++){
    await enabledCameos.nth(n).focus();
    const focus=await page.evaluate(()=>{const e=document.activeElement,r=e.getBoundingClientRect(),sidebar=document.querySelector('.command-sidebar'),s=sidebar.getBoundingClientRect(),footer=document.querySelector('.strategic-panel').getBoundingClientRect();return {text:e.textContent,top:r.top,bottom:r.bottom,sidebarTop:s.top,footerTop:footer.top,footerBottom:footer.bottom,viewport:innerHeight}});
    assert(focus.top>=focus.sidebarTop-1&&focus.bottom<=Math.min(focus.footerTop,focus.viewport)+1,'Focused production key covered by pinned status');assert(focus.footerBottom<=focus.viewport+1,'Strategic status below viewport');focusRows.push(focus);
   }
   await record('production focus and strategic status '+phase,{rows:focusRows});await page.screenshot({path:path.join(out,phase+'-sidebar-focus.png')});await page.locator('.command-sidebar').evaluate(e=>e.scrollTop=0);


  }
  phase='cleanup';await record('ordinary menu caption identity',await page.evaluate(()=>window.presentationStress.menu()));report.disposal=await page.evaluate(()=>window.presentationStress.dispose());assert.equal(report.disposal.sendCalls,0);assert.equal(report.disposal.canvases,0);assert.equal(report.disposal.frames,0);assert.equal(report.disposal.art.residentPages,0);assert.equal(report.disposal.audio.pending,0);assert(report.disposal.captionDisconnected);report.functional='passed';report.status='passed';
 }
}catch(e){report.status='failed';report.failure=String(e.stack??e);process.exitCode=1;if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{})}
finally{
 if(page&&!report.disposal)report.failureCleanup=await page.evaluate(()=>window.presentationStress?.dispose()).catch(e=>({error:String(e)}));try{await browser?.close()}catch(e){report.errors.push({phase,error:String(e)})}if(server?.listening)await new Promise(r=>server.close(r));
 report.inputsUnchanged=true;for(const[file,digest]of Object.entries(report.pins))if(sha(await readFile(file))!==digest)report.inputsUnchanged=false;
 report.diagnostics=report.errors.length||report.consoleErrors.length||report.httpErrors.length||report.requestFailures.length?'failed':'passed';if(report.diagnostics==='failed'||!report.inputsUnchanged){report.status='failed';process.exitCode=1}report.finished=new Date().toISOString();await save();console.log(JSON.stringify({status:report.status,functional:report.functional,diagnostics:report.diagnostics,failure:report.failure,out}));
}
