import {randomUUID} from '../runtime/crypto';
import {useEffect,useState} from 'react';
import type {Application} from '../app/application';
import type {LocalSaveSummary,LocalReplay} from '../runtime/storage';
import {BackupPanel} from './BackupPanel';
import {Icon,Modal,Empty} from './primitives';
export function downloadFile(blob:Blob,name:string){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
export function Archives({app,replays}:{app:Application;replays:boolean}){
 const [saves,setSaves]=useState<LocalSaveSummary[]>([]),[records,setRecords]=useState<Array<Omit<LocalReplay,'data'>>>([]),[deleting,setDeleting]=useState<{id:string;name:string;revision:number}>();
 const reload=()=>replays?app.store.listReplays().then(setRecords):app.store.listSaveSummaries().then(setSaves);
 useEffect(()=>{void reload().catch(error=>app.error(error))},[app,replays]);const list=replays?records:saves;
 const importFile=(file:File)=>void app.task('Validating imported file…',async()=>{try{if(file.size>(replays?64:96)*1024*1024)throw Error('The file exceeds the supported size.');if(replays)await app.store.putReplay(randomUUID(),file.name.slice(0,100),new Uint8Array(await file.arrayBuffer()));else{const prepared=await app.store.previewImport(file);await app.store.putSave(randomUUID(),prepared.name,prepared.save,0)}await reload();app.patch({notice:'Imported as a new local copy. Existing records were preserved.'})}catch(error){if(file.size<=96*1024*1024)await app.store.preserveRecovery(file,file.name.slice(0,100),error instanceof Error?error.message:'Import failed');throw error}});
 return <><BackupPanel app={app} onRestored={reload}/><p className="muted">Stored in this browser. Imported files are checked for compatibility before loading.</p><label className="file-action">Import {replays?'replay':'save copy'}<input aria-label={replays?'Import replay':'Import save'} type="file" onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)importFile(file)}}/></label>{!list.length?<Empty>No {replays?'replays':'saved operations'} yet.</Empty>:<div className="archive-list">{list.map(record=><div key={record.id} className="archive-row"><Icon id={replays?'i-replay':'i-save'}/><div><strong>{record.name}</strong><small>{new Date(record.updated).toLocaleString()} · {record.metadata.ruleset}</small></div><button onClick={()=>void app.task(replays?'Opening replay…':'Loading operation…',async()=>{if(replays)await app.sessions.openStoredReplay(record.id);else await app.sessions.continueSave(record.id)})}>{replays?'Watch':'Load'}</button><button onClick={()=>void app.task('Exporting original…',async()=>downloadFile(await (replays?app.store.exportReplay(record.id):app.store.exportSave(record.id)),`${record.id}.${replays?'replay':'save'}.json`))}>Export</button><button aria-label={`Delete ${record.name}`} onClick={()=>setDeleting(record)}>Delete</button></div>)}</div>}{deleting&&<Modal title="Delete local record" onClose={()=>setDeleting(undefined)}><p>Delete “{deleting.name}” from this browser? Export it first if you need a copy.</p><div className="button-row"><button className="danger" onClick={()=>void app.task('Deleting local record…',async()=>{if(replays)await app.store.deleteReplay(deleting.id,deleting.revision);else await app.store.deleteSave(deleting.id,deleting.revision);setDeleting(undefined);await reload()})}>Delete permanently</button><button onClick={()=>setDeleting(undefined)}>Keep record</button></div></Modal>}</>;
}
