import {useEffect,useState} from 'react';
import type {Application} from '../app/application';
import type {BackupPreview,BackupRecordSummary,RestoreDecision} from '../runtime/storage';
import {validateCampaignProgress,type CampaignProgress} from '../runtime/progress';
import {randomUUID} from '../runtime/crypto';
import {downloadFile} from './Archives';
function Details({record}:{record?:BackupRecordSummary}){if(!record)return <p>No current local record</p>;let progress:CampaignProgress|undefined;if(record.id==='campaign')try{validateCampaignProgress(record.data as CampaignProgress);progress=record.data as CampaignProgress}catch{}return <><strong>{record.name??record.id}</strong><small>Revision {record.revision} · {new Date(record.updated).toLocaleString()}</small>{record.tick!==undefined&&<small>Simulation tick {record.tick}</small>}{progress&&<><small>{progress.results.length} story completions · {Object.keys(progress.missions).length} mission records</small>{Object.values(progress.missions).map(mission=><small key={`${mission.mission}:${mission.mission_version}:${mission.difficulty}`}>{mission.mission} · {mission.difficulty} · v{mission.mission_version} · {mission.completions} completed · best tick {mission.best_tick}</small>)}</>}</>}
export function BackupPanel({app,onRestored}:{app:Application;onRestored:()=>Promise<unknown>}){
 const [preview,setPreview]=useState<BackupPreview>(),[name,setName]=useState('Imported backup'),[choices,setChoices]=useState<Record<string,'restore'|'copy'>>({}),[page,setPage]=useState(0),[recovery,setRecovery]=useState<Array<{id:string;name:string;reason:string;bytes:number}>>([]);
 const reload=()=>app.store.listRecoveryFiles().then(setRecovery);useEffect(()=>{void reload().catch(error=>app.error(error))},[app]);
 const prepare=(file:File)=>void app.task('Validating backup records…',async()=>{setPreview(undefined);setChoices({});setPage(0);setName(file.name.slice(0,100)||'Imported backup');setPreview(await app.store.previewBackup(file))});
 const apply=()=>void app.task('Restoring reviewed local records…',async()=>{if(!preview)return;const decisions:RestoreDecision[]=preview.entries.map(entry=>choices[entry.key]==='copy'?{key:entry.key,action:'copy',id:`copy-${randomUUID()}`,expectedRevision:0}:choices[entry.key]==='restore'?{key:entry.key,action:'restore',expectedRevision:entry.current?.revision??0}:{key:entry.key,action:'keep'});const result=await app.store.restoreBackup(preview,decisions,name);setPreview(undefined);setChoices({});await Promise.all([reload(),onRestored(),app.reloadSettings()]);app.patch({notice:`Restored ${result.restored.length} records; kept ${result.kept}.${result.recoveryId?' Original file preserved for recovery.':''}`})});
 return <section className="archive-backup"><h3>Portable browser backup</h3><p>Export saves, replays, settings and campaign progress together. Profiles and credentials are excluded. Editor drafts use <strong>Export draft</strong> in the Editor. Keep that file separately.</p><div className="button-row"><button onClick={()=>void app.task('Exporting browser backup…',async()=>downloadFile(await app.store.backup(),`frontline-backup-${new Date().toISOString().slice(0,10)}.json`))}>Export browser backup</button><label className="file-action">Review backup file<input type="file" aria-label="Review browser backup" onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)prepare(file)}}/></label></div><p className="muted">Backups are limited to 256 MiB. Larger archives can export individual saves and replays. A review never changes your current records.</p>
 {preview&&<div className="backup-review"><h4>Review local restore</h4><p>{preview.entries.length} records · {Object.keys(choices).length} selected for restore or copy. Unselected records stay unchanged. No story completions are merged.</p>{preview.message&&<p className="network-warning">{preview.message}</p>}{preview.preserveOriginal&&<p className="network-warning">Unsupported or damaged records cannot replace current files. Applying this review retains the original backup for recovery.</p>}{preview.entries.slice(page*30,(page+1)*30).map(entry=><article className="network-sync-item" key={entry.key}><header><strong>{entry.store} · {entry.incoming.name??entry.incoming.id}</strong><span>{entry.status}</span></header><div className="network-sync-versions"><div><span className="eyebrow">THIS BROWSER</span><Details record={entry.current}/></div><div><span className="eyebrow">BACKUP FILE</span><Details record={entry.incoming}/></div></div>{entry.message&&<p className="network-warning">{entry.message}</p>}<label>Restore decision<select aria-label={`Restore decision ${entry.key}`} value={choices[entry.key]??'keep'} disabled={entry.status!=='ready'} onChange={event=>setChoices(previous=>{const next={...previous};if(event.target.value==='keep')delete next[entry.key];else next[entry.key]=event.target.value as 'restore'|'copy';return next})}><option value="keep">Keep current local record</option><option value="restore">{entry.current?'Replace reviewed local record':'Restore missing record'}</option>{(entry.store==='saves'||entry.store==='replays')&&<option value="copy">Create a new local copy</option>}</select></label></article>)}{preview.entries.length>30&&<div className="button-row"><button disabled={!page} onClick={()=>setPage(value=>value-1)}>Previous backup page</button><span>{page+1} / {Math.ceil(preview.entries.length/30)}</span><button disabled={(page+1)*30>=preview.entries.length} onClick={()=>setPage(value=>value+1)}>Next backup page</button></div>}<div className="button-row"><button onClick={()=>{setPreview(undefined);setChoices({})}}>Cancel backup review</button><button className="primary" onClick={apply}>{preview.preserveOriginal?'Apply choices and preserve original':'Apply reviewed restore choices'}</button></div></div>}
 {!!recovery.length&&<details><summary>Preserved recovery files ({recovery.length})</summary>{recovery.map(file=><div className="archive-row" key={file.id}><div><strong>{file.name}</strong><small>{file.bytes.toLocaleString()} bytes · {file.reason}</small></div><button onClick={()=>void app.task('Exporting recovery original…',async()=>downloadFile(await app.store.exportRecovery(file.id),file.name))}>Export recovery original</button></div>)}</details>}</section>
}
