import {useState} from 'react';
import type {Application} from '../app/application';
import {useObservable} from '../app/store';
import {ownerTeamColor} from '../design/team-colors';
import {credits,formatClock} from '../content/labels';
export function DebriefStats({app}:{app:Application}){
 const state=useObservable(app.state),[metric,setMetric]=useState<'income'|'spent'|'supply'|'stations'>('income'),[events,setEvents]=useState(false),snapshot=state.snapshot,debrief=snapshot?.debrief;if(!snapshot?.outcome?.finished||!debrief)return null;
 const series=debrief.players.map(player=>({player,points:player.metrics?.timeline??[]})),max=Math.max(metric==='income'||metric==='spent'?1000:1,...series.flatMap(series=>series.points.map(point=>Number(point[metric])))),ticks=Math.max(1,snapshot.tick),money=metric==='income'||metric==='spent';
 return <div className="debrief-details"><div className="button-row">{(['income','spent','supply','stations'] as const).map(value=><button key={value} onClick={()=>setMetric(value)} className={metric===value?'active':''}>{value}</button>)}</div><figure className="debrief-chart"><svg viewBox="0 0 700 200" role="img" aria-label={`Recorded ${metric} over match time`}><path d="M45 10V175H690" fill="none" stroke="#737559"/>{[0,.5,1].map(fraction=><g key={fraction}><path d={`M45 ${175-fraction*160}H690`} stroke="#8a92752a"/><text x="39" y={179-fraction*160} textAnchor="end">{Math.round(max*fraction/(money?1000:1)).toLocaleString()}</text></g>)}{series.map(({player,points})=><polyline key={player.player} fill="none" stroke={ownerTeamColor(player.player,snapshot.players,state.settings.palette).css} strokeWidth="2" points={points.map(point=>`${45+point.tick/ticks*645},${175-Number(point[metric])/max*160}`).join(' ')}/>)}<text x="45" y="194">00:00</text><text x="690" y="194" textAnchor="end">{formatClock(ticks)}</text></svg><figcaption>{debrief.players.map(player=><span key={player.player}><i style={{background:ownerTeamColor(player.player,snapshot.players,state.settings.palette).css}}/>{player.name}</span>)}<small>Recorded match samples{money?' · credits':''}; values between samples are connected for readability.</small></figcaption></figure><details><summary>Production, service & losses</summary><div className="debrief-metrics">{debrief.players.map(player=><section key={player.player}><h3>{player.name}</h3><p>{player.exploredTiles} tiles explored · {formatClock(player.metrics?.stationControlTicks??0)} total station control</p><p>Repair spending {credits(player.metrics?.repairSpent??0n)} · Missile spending {credits(player.metrics?.missileSpent??0n)} · {player.metrics?.interceptorsFired??0} interceptors fired</p><p>Lost: {player.metrics?.unitsLost??0} units / {player.metrics?.buildingsLost??0} structures</p><p>Produced: {player.metrics?.unitsProduced.map(entry=>`${entry.count} ${state.catalog?.name(entry.type)??entry.type}`).join(', ')||'none'}</p><p>Constructed: {player.metrics?.buildingsConstructed.map(entry=>`${entry.count} ${state.catalog?.name(entry.type)??entry.type}`).join(', ')||'none'}</p></section>)}</div></details><button onClick={()=>setEvents(!events)}>{events?'Hide':'Show'} operation timeline</button>{events&&<div className="debrief-event-list">{debrief.events.map((event,index)=><p key={index}><time>{formatClock(event.tick)}</time><strong>{debrief.players.find(player=>player.player===event.player)?.name??'Operation'}</strong><span>{event.text||`${event.kind.replaceAll('_',' ')}${event.type?` · ${state.catalog?.name(event.type)??event.type}`:''}`}</span></p>)}{!!debrief.omittedEvents&&<p>{debrief.omittedEvents} earlier events omitted from this bounded summary. The replay preserves the command record.</p>}</div>}</div>;
}
