import {useState} from 'react';
import type {Application} from '../app/application';
import type {BattleController} from '../app/battle-controller';
import {useObservable} from '../app/store';
import {OfflineTransport,type Faction,type OrderIntent} from '../runtime';
import {FACTIONS,reason} from '../content/labels';
import {Modal} from './primitives';
export function PracticeSetup({app}:{app:Application}){
 const state=useObservable(app.state),maps=state.index?.maps.filter(map=>map.kind==='skirmish')??[],[map,setMap]=useState(maps[0]?.id??''),[faction,setFaction]=useState<Faction>('US'),[enemy,setEnemy]=useState<Faction>('IR');
 return <><p>Place forces freely, restore damage, change resources, and test orders. Practice has no competitive rewards or campaign completion.</p><label>Battlefield<select aria-label="Practice battlefield" value={map} onChange={event=>setMap(event.target.value)}>{maps.map(map=><option value={map.id} key={map.id}>{map.title}</option>)}</select></label>{[{label:'Your faction',value:faction,set:setFaction},{label:'Opposing faction',value:enemy,set:setEnemy}].map(choice=><label key={choice.label}>{choice.label}<select aria-label={choice.label} value={choice.value} onChange={event=>choice.set(event.target.value as Faction)}>{Object.entries(FACTIONS).map(([id,value])=><option value={id} key={id}>{value.name}</option>)}</select></label>)}<p className="muted">Both sides are controlled locally. Use the practice panel to switch perspective or add opposing forces.</p><button className="primary" onClick={()=>void app.task('Opening practice range…',async()=>{const loaded=await app.library.loadMap(map);await app.sessions.startSolo({map:loaded.map,seed:crypto.getRandomValues(new Uint32Array(1))[0]||1,ruleset:'practice-v1',players:[{id:1,name:'Practice commander',faction,team:1},{id:2,name:'Practice opponent',faction:enemy,team:2}]})})}>Open practice range</button></>;
}
export function PracticeTools({app,control,onClose}:{app:Application;control:BattleController;onClose:()=>void}){
 const state=useObservable(app.state),battle=useObservable(control.state),[owner,setOwner]=useState(state.snapshot?.player??1),[type,setType]=useState(''),[count,setCount]=useState(1),[cash,setCash]=useState(6000),[fog,setFog]=useState(false),[pending,setPending]=useState(false),[result,setResult]=useState('');
 const faction=state.snapshot?.players.find(player=>player.id===owner)?.faction,units=[...state.catalog!.units.values()].filter(unit=>unit.faction===faction),selected=type&&units.some(unit=>unit.id===type)?type:units[0]?.id??'';
 const order=async(order:OrderIntent)=>{const runtime=app.sessions.transport;if(!(runtime instanceof OfflineTransport)||app.sessions.state.kind!=='practice')return;setPending(true);try{const preview=await runtime.previewOrders([order]);if(!preview.results[0]?.accepted)throw Error(reason(preview.results[0]?.code));await runtime.sendOrders([order]);setResult('Practice order submitted; the simulation revalidates it.')}catch(error){setResult(error instanceof Error?error.message:'Practice order failed.')}finally{setPending(false)}};
 return <Modal title="Practice tools" onClose={onClose}><p className="muted">Practice changes are recorded in replays. They never apply to ranked or standard matches.</p><label>Player<select aria-label="Practice player" value={owner} onChange={event=>setOwner(Number(event.target.value))}>{state.snapshot?.players.map(player=><option value={player.id} key={player.id}>{player.name} · {player.faction}</option>)}</select></label><button onClick={()=>void app.sessions.setPerspective(owner).catch(error=>app.error(error))}>Control this player</button><h3>Place forces</h3><label>Unit<select aria-label="Practice unit" value={selected} onChange={event=>setType(event.target.value)}>{units.map(unit=><option value={unit.id} key={unit.id}>{unit.name}</option>)}</select></label><label>Count<input aria-label="Practice count" type="number" min="1" max="20" value={count} onChange={event=>setCount(Number(event.target.value))}/></label><button disabled={pending} onClick={()=>{control.placePractice({kind:'practice_spawn',type:selected,target:owner,index:count});onClose()}}>Choose placement on battlefield</button><h3>Selection</h3><div className="button-row"><button disabled={pending||!battle.ids.length} onClick={()=>void order({kind:'practice_restore',target:battle.ids[0]})}>Restore selected</button><button disabled={pending||!battle.ids.length} onClick={()=>void order({kind:'practice_remove',target:battle.ids[0]})}>Remove selected</button></div><h3>Resources & fog</h3><label>Credits<input aria-label="Practice credits" type="number" min="0" value={cash} onChange={event=>setCash(Number(event.target.value))}/></label><button disabled={pending} onClick={()=>void order({kind:'practice_resources',target:owner,index:cash})}>Set player credits</button><label className="check"><input type="checkbox" checked={fog} onChange={event=>{const reveal=event.target.checked;setFog(reveal);void order({kind:'practice_fog',index:reveal?1:0})}}/>Reveal the practice map</label><p role="status">{result}</p></Modal>;
}
