import {useEffect,useRef,useState,type ReactNode} from 'react';
import {art} from '../render/art';
import type {CatalogIndex} from '../content/catalog';
import {isShahed,SHAHED_ROLE_LABEL,SHAHED_ICON_BODY,SHAHED_ICON_IMPACT} from '../render/shahed-presentation';
export function Icon({id,className=''}:{id:string;className?:string}){return <svg className={`icon ${className}`} aria-hidden="true"><use href={`/art/ui/icons/fc-icons.svg#${({'i-chevron-left':'i-chevron-right','i-settings':'i-gear','i-home':'i-building','i-info':'i-help','i-save':'i-download','i-crosshair':'i-attack','i-units':'i-tank'} as Record<string,string>)[id]??id}`}/></svg>}
export function Emblem({faction}:{faction:string}){return <svg className="emblem" aria-hidden="true"><use href={`/art/ui/emblems/fc-emblems.svg#em-${faction}`}/></svg>}
export function Cameo({type,faction,catalog,color='#4daf62',purpose='portrait'}:{type:string;faction?:string;catalog:CatalogIndex;color?:string;purpose?:'build'|'portrait'}){
 const [image,setImage]=useState<{generation:string|undefined;assetId:string;url:string|undefined}>();const generation=art.generationIdentity?.key,resolved=art.resolve(type,faction,catalog);
 useEffect(()=>{let canceled=false;setImage(undefined);if(resolved?.id)void art.cameo(resolved.id,color,'idle',undefined,purpose).then(url=>{if(!canceled)setImage({generation,assetId:resolved.id,url})}).catch(()=>{});return()=>{canceled=true}},[resolved?.id,color,purpose,generation]);
 const url=image?.generation===generation&&(!isShahed(type)||resolved?.id==='unit.IR.shahed'&&image?.assetId===resolved.id)?image?.url:undefined;
 return url?<img className="cameo-art" src={url} alt=""/>:isShahed(type)?<span className="cameo-unavailable" role="img" aria-label={`${catalog.name(type)} · ${SHAHED_ROLE_LABEL}`} title={`${catalog.name(type)} · ${SHAHED_ROLE_LABEL}`} style={{opacity:1,color}}><svg viewBox="0 0 64 52" width="80%" height="80%" aria-hidden="true"><polygon points={SHAHED_ICON_BODY} fill="currentColor" stroke="#15130f" strokeWidth={1.5}/><path d={SHAHED_ICON_IMPACT} fill="none" stroke="#e2a232" strokeWidth={1.5}/><text x={32} y={49} textAnchor="middle" fontSize={6.5} textLength={54} lengthAdjust="spacingAndGlyphs" fill="#eee6ca">{catalog.name(type)}</text></svg></span>:<span className="cameo-unavailable"><Icon id={catalog.isBuilding(type)?'i-building':'i-units'}/></span>;
}
export function Modal({title,onClose,children,wide=false}:{title:string;onClose?:()=>void;children:ReactNode;wide?:boolean}){
 const dialog=useRef<HTMLDivElement>(null),close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const node=dialog.current;if(!node)return;const focusable=()=>[...node.querySelectorAll<HTMLElement>('a[href],button,input,select,textarea,summary,[tabindex]')].filter(element=>element.tabIndex>=0&&!element.matches(':disabled')&&!element.closest('[inert]')&&element.getClientRects().length);(focusable()[0]??node).focus();
 const key=(event:KeyboardEvent)=>{if(event.defaultPrevented||document.querySelectorAll('[role="dialog"]').item(document.querySelectorAll('[role="dialog"]').length-1)!==node)return;if(event.key==='Escape'&&close.current){event.preventDefault();close.current()}if(event.key==='Tab'){const controls=focusable();if(!controls.length){event.preventDefault();return}const i=controls.indexOf(document.activeElement as HTMLElement);if(event.shiftKey&&i<=0){event.preventDefault();controls.at(-1)?.focus()}else if(!event.shiftKey&&(i<0||i===controls.length-1)){event.preventDefault();controls[0].focus()}}};node.addEventListener('keydown',key);return()=>{node.removeEventListener('keydown',key);previous?.focus()};},[]);
 return <div className="scrim"><div ref={dialog} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} className={`modal console ${wide?'wide':''}`}><header><h2>{title}</h2>{onClose&&<button className="icon-button" onClick={onClose} aria-label="Close"><Icon id="i-close"/></button>}</header><div className="modal-body">{children}</div></div></div>;
}
export function Empty({children}:{children:ReactNode}){return <p className="empty">{children}</p>}
