import {useEffect,useRef,useState} from 'react';
import {DEFAULT_SETTINGS} from '../app/settings';
import type {Application} from '../app/application';
import {useObservable} from '../app/store';
import {SHORTCUT_DEFINITIONS,defaultBindings,remapBindings,validateBindings,type ControlBindings,type Modifier} from '../runtime';
import {shortcutLabel as chordName} from './shortcut-presentation';
export function SettingsPanel({app}:{app:Application}){
 const panel=useRef<HTMLDivElement>(null);
 const audioState=useObservable(app.audio.state);
 const {settings}=useObservable(app.state),[capture,setCapture]=useState<string>(),[message,setMessage]=useState(''),[category,setCategory]=useState('orders');
 const update=(change:Partial<typeof settings>)=>app.setSettings({...app.state.get().settings,...change});
 const bindings=(next:ControlBindings)=>{const issues=validateBindings(next);if(issues.length){setMessage(issues.map(issue=>issue.message).join(' '));return}update({bindings:next});setMessage('Bindings saved.')};
 useEffect(()=>{if(!capture)return;const key=(event:KeyboardEvent)=>{const dialogs=document.querySelectorAll('[role="dialog"]'),top=dialogs.item(dialogs.length-1);if(!panel.current||top&&!top.contains(panel.current))return;event.preventDefault();event.stopImmediatePropagation();if(event.key==='Escape'&&!event.ctrlKey&&!event.altKey&&!event.shiftKey&&!event.metaKey){setCapture(undefined);setMessage('Shortcut capture canceled.');return}if(event.isComposing||['Control','Alt','Shift','Meta'].includes(event.key)||event.repeat)return;const modifiers:Modifier[]=[];if(event.ctrlKey)modifiers.push('ctrl');if(event.altKey)modifiers.push('alt');if(event.shiftKey)modifiers.push('shift');if(event.metaKey)modifiers.push('meta');const result=remapBindings(app.state.get().settings.bindings,{[capture]:[{code:event.code,modifiers}]});if(result.bindings){app.setSettings({...app.state.get().settings,bindings:result.bindings});setMessage('Shortcut saved.');setCapture(undefined)}else setMessage(result.issues.map(issue=>issue.message).join(' '))};window.addEventListener('keydown',key,true);return()=>window.removeEventListener('keydown',key,true)},[app,capture]);
 return <div ref={panel} className="settings-form"><button onClick={()=>{app.setSettings({...structuredClone(DEFAULT_SETTINGS),firstRunComplete:settings.firstRunComplete});setMessage('Preferences reset to defaults.')}}>Reset preferences to defaults</button><button onClick={()=>void app.task('Reloading saved preferences…',()=>app.reloadSettings())}>Reload saved preferences</button><h3>Display & accessibility</h3><label>Interface scale<select aria-label="Interface scale" value={settings.uiScale} onChange={event=>update({uiScale:Number(event.target.value)})}>{[.85,1,1.15,1.25,1.5].map(value=><option key={value} value={value}>{Math.round(value*100)}%</option>)}</select></label><label>Team colors<select aria-label="Team colors" value={settings.palette} onChange={event=>update({palette:event.target.value as typeof settings.palette})}><option value="standard">Standard</option><option value="cvd_safe">Color-vision safe</option></select></label><label>Health bars<select aria-label="Health bars" value={settings.healthBars} onChange={event=>update({healthBars:event.target.value as typeof settings.healthBars})}><option value="selected">Selected</option><option value="damaged">Damaged</option><option value="always">Always</option></select></label>{(['captions','reducedMotion','reducedFlashing','keyboardCamera','edgeScroll'] as const).map(key=><label className="check" key={key}><input type="checkbox" checked={settings[key]} onChange={event=>update({[key]:event.target.checked})}/>{({captions:'Captions',reducedMotion:'Reduce motion',reducedFlashing:'Reduce flashing',keyboardCamera:'Arrow-key camera',edgeScroll:'Edge scrolling'})[key]}</label>)}
 <label>Art quality (next operation)<select aria-label="Art quality" value={settings.artQuality} onChange={event=>update({artQuality:event.target.value as typeof settings.artQuality})}><option value="auto">Automatic · standard atlas</option><option value="standard">Standard · lower memory</option><option value="high">High · larger atlas</option></select></label><label>Minimap scale<input aria-label="Minimap scale" type="range" min=".8" max="1.4" step=".1" value={settings.minimapScale} onChange={event=>update({minimapScale:Number(event.target.value)})}/></label><label>Screen shake<input aria-label="Screen shake" type="range" min="0" max="1" step=".1" value={settings.screenShake} onChange={event=>update({screenShake:Number(event.target.value)})}/></label><p className="muted">Reduced motion or reduced flashing disables camera shake. Zero also disables it.</p><h3>Camera & selection</h3>{([{key:'scrollSpeed',label:'Camera pan speed',min:.4,max:2,step:.1},{key:'zoomSpeed',label:'Zoom speed',min:.4,max:2,step:.1},{key:'selectionTolerance',label:'Selection tolerance (pixels)',min:2,max:16,step:1},{key:'dragThreshold',label:'Drag threshold (pixels)',min:3,max:20,step:1}] as const).map(({key,label,min,max,step})=><label key={key}>{label}<span>{settings[key]}<input aria-label={label} type="range" min={min} max={max} step={step} value={settings[key]} onChange={event=>update({[key]:Number(event.target.value)})}/></span></label>)}
 <h3>Controls</h3><label>Mouse preset<select aria-label="Mouse preset" value={settings.bindings.preset} onChange={event=>bindings(defaultBindings(event.target.value as 'standard'|'classic'))}><option value="standard">Standard · right-click orders</option><option value="classic">Classic · left-click orders</option></select></label><p className="muted">Changing presets resets all shortcuts. Individual changes are checked for conflicts before they are saved.</p>
 {(['select','context','pan','cancel'] as const).map(key=><label key={key}>{({select:'Select / confirm',context:'Context order',pan:'Drag camera',cancel:'Cancel target'})[key]}<select aria-label={`Mouse ${key}`} value={settings.bindings.pointer[key]} onChange={event=>bindings({...settings.bindings,pointer:{...settings.bindings.pointer,[key]:Number(event.target.value)}})}>{['Left','Middle','Right','Back','Forward'].map((label,index)=><option value={index} key={index}>{label} button</option>)}</select></label>)}
 {(['queue','multiSelect','forceFire'] as const).map(key=><label key={key}>{({queue:'Queue modifier',multiSelect:'Add-selection modifier',forceFire:'Force-fire modifier'})[key]}<select aria-label={key} value={settings.bindings.modifiers[key]} onChange={event=>bindings({...settings.bindings,modifiers:{...settings.bindings.modifiers,[key]:event.target.value as Modifier}})}>{['ctrl','shift','alt','meta'].map(modifier=><option key={modifier}>{modifier}</option>)}</select></label>)}
 <label>Shortcut category<select aria-label="Shortcut category" value={category} onChange={event=>setCategory(event.target.value)}>{['orders','selection','camera','interface','groups'].map(value=><option key={value}>{value}</option>)}</select></label><p role="status" className="binding-message">{capture?`Press the new key combination for ${SHORTCUT_DEFINITIONS.find(item=>item.id===capture)?.label}. Escape cancels capture. ${message}`:message}</p>{capture&&<button onClick={()=>setCapture(undefined)}>Cancel key capture</button>}<div className="shortcut-list">{SHORTCUT_DEFINITIONS.filter(item=>item.category===category).map(item=><div className="shortcut-row" key={item.id}><span>{item.label}</span><button aria-label={`Remap ${item.label}`} className={capture===item.id?'active':''} onClick={()=>{setCapture(item.id);setMessage('')}}>{settings.bindings.keys[item.id]?.map(chordName).join(' / ')||'Unbound'}</button><button aria-label={`Clear ${item.label}`} onClick={()=>{const result=remapBindings(settings.bindings,{[item.id]:[]});if(result.bindings)bindings(result.bindings)}}>Clear</button></div>)}</div>
 <h3>Audio</h3><p className="muted">{audioState.status==='ready'?'Sound ready. Levels apply immediately.':audioState.status==='disabled'?'Sound is disabled. Warning captions remain available.':audioState.status==='gesture'?'Click any control to start sound.':'Audio files are unavailable; the operation remains playable.'}</p>{audioState.error&&<p role="status">{audioState.error} <button onClick={()=>void app.audio.loadIndex(true)}>Retry audio files</button></p>}<button onClick={()=>app.audio.play('sfx.ui_confirm')}>Test interface sound</button><label className="check"><input type="checkbox" checked={settings.audioConsent} onChange={event=>update({audioConsent:event.target.checked})}/>Enable game sound</label>{(['master','music','effects','voice','ui'] as const).map(channel=><label key={channel}>{channel==='ui'?'Interface':channel[0].toUpperCase()+channel.slice(1)} volume<input aria-label={`${channel} volume`} type="range" min="0" max="1" step=".05" value={settings.audio[channel]} onChange={event=>update({audio:{...settings.audio,[channel]:Number(event.target.value)}})}/></label>)}</div>;
}
