import {useEffect,useState} from 'react';
import type {Application} from '../app/application';
import type {BattleController} from '../app/battle-controller';
import {useObservable} from '../app/store';
interface Step{id:string;kind:string;text?:string;objective?:string}
export function TutorialGuide({app,control}:{app:Application;control:BattleController}){
 const state=useObservable(app.state),battle=useObservable(control.state),[steps,setSteps]=useState<Step[]>([]),[hidden,setHidden]=useState(false),mission=state.snapshot?.mission;
 const entry=state.index?.missions.find(entry=>entry.id===mission?.id&&entry.mode==='tutorial');
 useEffect(()=>{if(!entry?.presentation_url||state.session.kind!=='solo')return;const abort=new AbortController();void(async()=>{try{const response=await fetch(entry.presentation_url!,{signal:abort.signal});if(!response.ok)throw Error('Training presentation is unavailable.');const text=await response.text();if(text.length>256*1024)throw Error('Training presentation is too large.');const value=JSON.parse(text);if(value.mission_id!==entry.id||value.mission_version!==entry.version||!Array.isArray(value.tutorial_steps)||value.tutorial_steps.length>64)throw Error('Training presentation does not match this mission.');const allowed=['select','move','attack','stop','control_group','rally','rejected_order'];if(value.tutorial_steps.some((step:Step)=>!step||typeof step.id!=='string'||!allowed.includes(step.kind)||step.text!==undefined&&(typeof step.text!=='string'||step.text.length>2000)||step.objective!==undefined&&typeof step.objective!=='string'))throw Error('Training reminders are malformed.');setSteps(value.tutorial_steps)}catch(error){if(!abort.signal.aborted)app.patch({notice:error instanceof Error?error.message:'Training reminders unavailable.'})}})();return()=>abort.abort()},[app,entry?.id,entry?.presentation_url,state.session.id]);
 const complete=(step:Step)=>step.objective?mission?.objectives.some(objective=>objective.id===step.objective&&objective.complete):step.kind==='select'?battle.learned.includes('single_select')&&battle.learned.includes('box_select'):step.kind==='control_group'?battle.learned.includes('group_store')&&battle.learned.includes('group_recall'):battle.learned.includes(step.kind);
 const next=steps.find(step=>!complete(step));if(!entry||!next||hidden)return null;const text=next.text??mission?.objectives.find(objective=>objective.id===next.objective)?.text??next.kind;
 return <aside className="tutorial-guide console" aria-label="Training reminder"><span>FIELD INSTRUCTION {steps.filter(complete).length+1}/{steps.length}</span><p>{text}</p><small>Uses your current control bindings in Options.</small><button aria-label="Hide training reminders" onClick={()=>setHidden(true)}>Hide reminders</button></aside>;
}
