// Generate client/src/design/tokens.css and tokens.ts from tokens.json.
// Zero dependencies: `node client/scripts/build-tokens.mjs`
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const designDir = join(here, '..', 'src', 'design');
const t = JSON.parse(readFileSync(join(designDir, 'tokens.json'), 'utf8'));

const kebab = (s) => String(s).replace(/_/g, '-');
const lines = [];
const px = (v) => (typeof v === 'number' ? `${v}px` : v);

function flatten(prefix, obj) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    const name = `${prefix}-${kebab(k)}`;
    if (Array.isArray(v)) v.forEach((x, i) => lines.push(`  ${name}-${i}: ${x};`));
    else if (v && typeof v === 'object') flatten(name, v);
    else lines.push(`  ${name}: ${v};`);
  }
}

// Colours and families
flatten('--fc-color', t.color);
for (const [k, v] of Object.entries(t.font.family)) lines.push(`  --fc-font-${k}: ${v};`);
for (const [k, v] of Object.entries(t.space)) lines.push(`  --fc-space-${k}: calc(${v}px * var(--fc-ui-scale));`);
for (const [k, v] of Object.entries(t.radius)) lines.push(`  --fc-radius-${k}: ${v}px;`);
for (const [k, v] of Object.entries(t.chamfer)) lines.push(`  --fc-chamfer-${k}: calc(${v}px * var(--fc-ui-scale));`);
for (const [k, v] of Object.entries(t.shadow)) lines.push(`  --fc-shadow-${k}: ${v};`);
for (const [k, v] of Object.entries(t.motion.duration)) lines.push(`  --fc-dur-${k}: ${v}ms;`);
for (const [k, v] of Object.entries(t.motion.easing)) lines.push(`  --fc-ease-${k}: ${v};`);
for (const [k, v] of Object.entries(t.layout.hud)) {
  if (k === 'reference') continue;
  lines.push(`  --fc-hud-${kebab(k)}: calc(${v}px * var(--fc-ui-scale));`);
}
for (const [k, v] of Object.entries(t.layout.z)) lines.push(`  --fc-z-${k}: ${v};`);
lines.push(`  --fc-min-hit: calc(${t.layout.min_hit_target}px * var(--fc-ui-scale));`);
for (const [k, v] of Object.entries(t.type)) {
  lines.push(`  --fc-type-${kebab(k)}-size: calc(${v.size}px * var(--fc-ui-scale));`);
  lines.push(`  --fc-type-${kebab(k)}-line: calc(${v.line}px * var(--fc-ui-scale));`);
}

const fontFaces = [
  ['Barlow', 'barlow/Barlow', [['Regular', 400], ['Medium', 500], ['SemiBold', 600], ['Bold', 700]]],
  ['Barlow Condensed', 'barlowcondensed/BarlowCondensed', [['Regular', 400], ['Medium', 500], ['SemiBold', 600], ['Bold', 700]]],
  ['Share Tech Mono', 'sharetechmono/ShareTechMono', [['Regular', 400]]],
].flatMap(([fam, path, ws]) => ws.map(([w, n]) =>
  `@font-face { font-family: '${fam}'; src: url('../../../assets/fonts/${path}-${w}.ttf') format('truetype'); font-weight: ${n}; font-style: normal; font-display: block; }`))
  .concat([`@font-face { font-family: 'Big Shoulders Stencil Display'; src: url('../../../assets/fonts/bigshouldersstencil/BigShouldersStencilDisplay-wght.ttf') format('truetype'); font-weight: 100 900; font-style: normal; font-display: block; }`]);

// Raster chrome materials (9-slice) generated by assets/pipeline/ui/gen_chrome.py
for (const [k, v] of Object.entries(t.material)) {
  if (k.startsWith('$')) continue;
  lines.push(`  --fc-material-${kebab(k)}: url('../../../${v.file}');`);
  if (v.slice) lines.push(`  --fc-material-${kebab(k)}-slice: ${v.slice};`);
}

const typeClasses = Object.entries(t.type).map(([k, v]) => `.fc-t-${kebab(k)} {
  font-family: var(--fc-font-${v.family});
  font-size: var(--fc-type-${kebab(k)}-size);
  line-height: var(--fc-type-${kebab(k)}-line);
  font-weight: ${v.weight};
  letter-spacing: ${v.tracking};${v.case === 'upper' ? '\n  text-transform: uppercase;' : ''}${v.family === 'mono' ? '\n  font-variant-numeric: tabular-nums;' : ''}
}`).join('\n');

const cvd = t.color.team.cvd_safe.map((c, i) => `  --fc-color-team-standard-${i}: ${c};`).join('\n');

const css = `/* GENERATED from tokens.json by client/scripts/build-tokens.mjs — do not edit by hand. */
${fontFaces.join('\n')}

:root {
  --fc-ui-scale: 1;
${lines.join('\n')}
}

/* 1600-class layouts: larger HUD metrics at the same UI scale */
@media (min-width: 1500px) and (min-height: 840px) {
  :root {
${Object.entries(t.layout.hud_1600).map(([k, v]) => `    --fc-hud-${kebab(k)}: calc(${v}px * var(--fc-ui-scale));`).join('\n')}
  }
}

/* Colour-vision-safe team palette (Settings > Accessibility > Colour alternatives) */
:root[data-palette='cvd'] {
${cvd}
}

/* Reduced motion: transitions collapse to <= ${t.motion.reduced.duration_max}ms opacity/colour only */
:root[data-reduced-motion='true'] {
  --fc-dur-fast: 0ms; --fc-dur-base: ${t.motion.reduced.duration_max}ms; --fc-dur-slow: ${t.motion.reduced.duration_max}ms; --fc-dur-panel: 0ms;
}
@media (prefers-reduced-motion: reduce) {
  :root:not([data-reduced-motion='false']) {
    --fc-dur-fast: 0ms; --fc-dur-base: ${t.motion.reduced.duration_max}ms; --fc-dur-slow: ${t.motion.reduced.duration_max}ms; --fc-dur-panel: 0ms;
  }
}

${typeClasses}
`;
writeFileSync(join(designDir, 'tokens.css'), css);

const ts = `// GENERATED from tokens.json by client/scripts/build-tokens.mjs — do not edit by hand.
export const tokens = ${JSON.stringify(t, null, 2)} as const;
export type Tokens = typeof tokens;
export type ProductionCameoState = (typeof tokens.state.production_cameo)[number];
export type AlertPriority = (typeof tokens.state.alert_priority)[number];
`;
writeFileSync(join(designDir, 'tokens.ts'), ts);
console.log(`tokens.css (${css.length} bytes), tokens.ts written`);
