/** Check a private copy; replace only missing type-import and fixture module paths. */
import {readFile,writeFile,mkdir,mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {createHash} from 'node:crypto';
const root=process.cwd(),temp=await mkdtemp(path.join(tmpdir(),'fog-types-')),folders=['work/terrain-polish-review/inputs-v4','work/claude/presentation-polish-v1/fog-inputs','work/terrain-spur-v1/inputs'],redirects=new Map(),inputs=[];
try{
 for(const [i,folder]of folders.entries()){const dest=path.join(temp,String(i));await mkdir(dest);for(const file of [...(i===0?['baseline-terrain.ts']:['candidate-terrain.ts']),'terrain-surface.ts','terrain-materials.ts','iso.ts']){
  const src=path.join(root,folder,file),bytes=await readFile(src),out=path.join(dest,file);let text=bytes.toString().replaceAll("from '../runtime'",`from '${root}/client/src/runtime/index'`).replaceAll("from '../runtime/types'",`from '${root}/client/src/runtime/types'`).replaceAll("from './art'",`from '${root}/client/src/render/art'`);await writeFile(out,text);redirects.set(src,out.replace(/\.ts$/,''));inputs.push({src,sha256:createHash('sha256').update(bytes).digest('hex')});
 }}
 const fixture=path.join(root,'work/terrain-spur-v1/fixture.ts');let text=await readFile(fixture,'utf8');text=text.replace(/from '([^']+)'/g,(whole,name)=>{if(!name.startsWith('.'))return whole;const absolute=path.resolve(path.dirname(fixture),name),redirect=redirects.get(absolute+'.ts');return `from '${redirect??absolute}'`});await writeFile(path.join(temp,'fixture.ts'),text);
 await writeFile(path.join(temp,'tsconfig.json'),JSON.stringify({compilerOptions:{strict:true,noEmit:true,skipLibCheck:true,target:'ES2022',module:'ESNext',moduleResolution:'bundler',lib:['ES2022','DOM','DOM.Iterable'],jsx:'react-jsx',paths:{'pixi.js':[path.join(root,'client/node_modules/pixi.js/lib/index.d.ts')]}},include:['fixture.ts']},null,2));
 const result=spawnSync(path.join(root,'client/node_modules/.bin/tsc'),['-p',path.join(temp,'tsconfig.json')],{encoding:'utf8'});process.stdout.write(result.stdout??'');process.stderr.write(result.stderr??'');console.log(JSON.stringify({exitCode:result.status,scope:'Semantic check of fixture with private type-import context; runtime build uses original immutable files.',inputs}));process.exitCode=result.status??1;
}finally{await rm(temp,{recursive:true,force:true})}
