package sim

// Exact Core16 updateAI function body, with only this test-only method name
// changed. Narrow no-public-task oracle; never called by production updateAI.
// No execution or competence evidence is generated by this source copy.
import "frontlinecommand/pkg/content"

func (e *Engine) updateAILegacyCore16PublicHoldControl() {
	for _, p := range e.state.Players {
		if p.AI == "" || p.Defeated {
			continue
		}
		period := seconds(2)
		if p.AI == "easy" {
			period = seconds(4)
		}
		if p.AI == "hard" {
			period = seconds(1)
		}
		if e.state.Tick-p.AILast < period {
			continue
		}
		p.AILast = e.state.Tick
		view, _ := e.PlayerView(p.ID)
		// Retire known hostile targets before observation drops defeated owners.
		// Cancellation is an ordinary command and wins the per-actor priority.
		orders := e.aiRetireDefeatedTargets(p, view)
		e.aiObserve(p, view)
		budget := p.Credits
		own := []EntityView{}
		counts := map[string]int32{}
		var rig *Entity
		var hq *Entity
		for _, v := range view.Entities {
			if v.Owner != p.ID {
				continue
			}
			own = append(own, v)
			unit := e.entity(v.ID)
			counts[e.role(unit)]++
			for _, job := range unit.Jobs {
				if u, ok := e.catalog.Unit(job.Type); ok {
					counts[u.Role]++
				}
			}
			if e.role(unit) == "rig" && len(unit.Orders) == 0 && unit.Channel == "" {
				rig = unit
			}
			if e.role(unit) == "hq" {
				hq = unit
			}
		}
		budget = e.aiPlanningBudget(p, own)
		planningCredits := budget
		needSupplyScout := true
		for _, field := range p.AIFields {
			if field.Remaining > 0 {
				needSupplyScout = false
				break
			}
		}
		replacementProducer := ID(0)
		if replacement, ok := e.aiReplacementHauler(p, own, &budget); ok {
			orders = append(orders, replacement)
			replacementProducer = replacement.Entities[0]
			counts["hauler"]++
		}
		serviceMargin := e.aiServiceMargin(own)
		plannedSupply := p.Supply + p.ReservedSupply
		for _, v := range own {
			for _, job := range e.entity(v.ID).Jobs {
				if !job.Started && !job.Research {
					u, _ := e.catalog.Unit(job.Type)
					plannedSupply += u.Supply
				}
			}
		}
		if recovery, ok := e.aiEmergencyRigRecovery(p, own, &budget); ok {
			orders = append(orders, recovery)
			if recovery.Kind == "train" {
				counts["rig"]++
			}
		}
		buildType := ""
		expansion, expand := e.aiExpansion(p, own)
		var buildCenter Vec
		if hq != nil {
			buildCenter = hq.Position
		} else if rig != nil {
			buildCenter = rig.Position
		}
		if rig != nil {
			// Resume paid foundations after losing their original builder.
			for _, v := range own {
				foundation := e.entity(v.ID)
				if !foundation.Building || foundation.Complete {
					continue
				}
				builder := e.aiOwnEntity(own, foundation.Builder)
				working := builder != nil && builder.HP > 0 && len(builder.Orders) > 0 && builder.Orders[0].Target == foundation.ID
				if !working {
					orders = append(orders, Order{Kind: "resume", Entities: []ID{rig.ID}, Target: foundation.ID})
					rig = nil
					break
				}
			}
		}
		if rig != nil {
			switch {
			case counts["hq"] == 0:
				buildType = "hq"
			case e.aiPowerMargin(p, own) < 35:
				buildType = "power"
			case counts["power"] == 0:
				buildType = "power"
			case counts["supply"] == 0:
				buildType = "supply"
				for _, field := range p.AIFields {
					if field.Remaining > 0 && distance(field.Position, buildCenter) < 14000 {
						buildCenter = field.Position
						break
					}
				}
			case counts["barracks"] == 0:
				buildType = "barracks"
			case needSupplyScout && counts["recon"] == 0:
				// Sight must precede optional infrastructure when no supplies
				// are known. Otherwise the last credits can strand both haulers
				// and prevent buying the ordinary scout that would find income.
			case counts["factory"] == 0:
				buildType = "factory"
			case expand:
				buildCenter = expansion
				buildType = "supply"
				if !e.aiInBuildRadius(p, "supply", expansion) {
					buildType = "outpost"
				}
			case counts["radar"] == 0:
				buildType = "radar"
			case counts["airfield"]+counts["drone_hub"]+counts["workshop_air"] == 0 && p.Supply >= 18 || serviceMargin < 0:
				buildType = content.AirProducer(p.Faction)
			case counts["tech"] == 0 && p.Supply >= 28:
				buildType = "tech"
			case counts["depot"] == 0 && p.Credits > 1600000:
				buildType = "depot"
			case counts["abm"] == 0 && p.Tier >= 2 && p.Credits > 2200000:
				buildType = "abm"
			case counts["strategic"] == 0 && p.Tier == 3 && p.Credits > 5500000:
				buildType = "strategic"
			case p.Faction == "SY" && p.Tier >= 2 && counts["safehouse"] < 2 && p.Credits > 1600000:
				buildType = "SY.safehouse"
				if counts["safehouse"] > 0 {
					for _, v := range own {
						if v.Type == "outpost" && distance(v.Position, p.AIGoal) < distance(buildCenter, p.AIGoal) {
							buildCenter = v.Position
						}
					}
				}
			}
			if buildType != "" {
				b, _ := e.buildingRule(buildType)
				// Save toward legal future purchases, including when the current
				// bank is short. An impossible cap/prerequisite goal must not
				// consume the budget available to ordinary production.
				planning := *p
				planning.Credits = max(planning.Credits, b.Cost)
				if _, code := e.buildingCatalogRequirements(&planning, rig, buildType); code == "ok" {
					if pos, ok := e.aiConstructionPosition(p, buildType, buildCenter); ok {
						if budget >= b.Cost {
							orders = append(orders, Order{Kind: "build", Entities: []ID{rig.ID}, Type: buildType, Position: pos})
						}
						// Save toward an affordable, visible construction goal instead
						// of spending each arriving shipment on another infantry squad.
						budget = max(int64(0), budget-b.Cost)
					} else if expand && budget >= b.Cost && distance(rig.Position, expansion) > 5000 {
						orders = append(orders, Order{Kind: "move", Entities: []ID{rig.ID}, Position: expansion})
					}
				}
			}
		}
		earlyUsed := map[ID]bool{}
		for _, order := range orders {
			for _, id := range order.Entities {
				earlyUsed[id] = true
			}
		}
		// The sole builder restores construction. Save its ordinary HQ cost
		// before a charged operation or optional purchases claim those credits.
		if counts["rig"] == 0 {
			for _, v := range own {
				producer := e.entity(v.ID)
				if e.role(producer) != "hq" || !producer.Active(e.Tick()) || len(producer.Jobs) != 0 || earlyUsed[producer.ID] {
					continue
				}
				order := Order{Kind: "train", Entities: []ID{producer.ID}, Type: p.Faction + ".rig"}
				job, code := e.productionJob(p, producer, order)
				if code != "ok" || !e.jobReady(p, producer, &job) {
					continue
				}
				_, _, _, code = e.productionAllocation(p, &job)
				// Allocation errors omit prices; keep the catalog saving goal.
				u, _ := e.catalog.Unit(job.Type)
				cost, supply := u.Cost, u.Supply
				if code != "ok" && code != "insufficient_credits" || plannedSupply+supply > 100 {
					continue
				}
				if budget >= cost {
					orders = append(orders, order)
					earlyUsed[producer.ID] = true
					counts["rig"]++
					plannedSupply += supply
					p.AIStage++
				}
				budget = max(int64(0), budget-cost)
				break
			}
		}
		// A legal charged operation gets the remaining construction/recovery
		// budget before routine research and army production can consume it.
		for _, v := range own {
			site := e.entity(v.ID)
			if e.role(site) != "strategic" || !site.Active(e.Tick()) {
				continue
			}
			if order, ok := e.aiStrategicOrder(p, view, own, site, p.AIGoal, earlyUsed, max(int32(0), 100-plannedSupply)); ok {
				cost, _, supply := e.aiOrderReservation(p, &order)
				if budget >= cost && plannedSupply+supply <= 100 {
					orders = append(orders, order)
					budget -= cost
					plannedSupply += supply
				}
			}
			break
		}
		if !needSupplyScout {
			orders = append(orders, e.aiResearchOrders(p, own, &budget)...)
		}
		enemyAir, enemyArmor := false, false
		enemyAirCount := int32(0)
		for _, v := range p.AIKnowledge {
			if !aiActiveOpponent(p, view, v.Owner) || e.Tick()-v.Seen > seconds(30) {
				continue
			}
			u, ok := e.catalog.Unit(v.Type)
			if ok && u.Weapon != "" {
				if u.Armor == "air" {
					enemyAir = true
					enemyAirCount++
				}
				if u.Armor == "heavy" {
					enemyArmor = true
				}
			}
		}
		committedAirSupply := e.aiCommittedAirSupply(own)
		plannedAirSlots := map[string]int32{}
		knownAirThreat := e.aiKnownAirThreat(p)
		for _, v := range own {
			unit := e.entity(v.ID)
			if unit.Building && unit.Active(e.state.Tick) && len(unit.Jobs) == 0 && unit.ID != replacementProducer {
				role := e.role(unit)
				typ := ""
				switch role {
				case "supply":
					if (!needSupplyScout || counts["hauler"] == 0) && counts["hauler"] < min(int32(6), max(int32(2), counts["supply"]*2)) {
						typ = p.Faction + ".hauler"
					}
				case "hq":
					if counts["rig"] < 1 {
						typ = p.Faction + ".rig"
					}
				case "barracks":
					choose := []string{"rifle", "at", "rifle", "recon", "medic"}[p.AIStage%5]
					if choose == "medic" && counts["medic"] >= 2 || choose == "recon" && counts["recon"] >= 2 {
						choose = "rifle"
					}
					// Counters supplement the infantry screen; an unarmed hauler
					// or old sighting must not erase scouting and rifle production.
					if enemyArmor && p.AIStage%2 == 0 && counts["at"] < max(int32(1), (counts["rifle"]+counts["elite"]+1)/2) {
						choose = "at"
					}
					if choose == "at" && counts["at"] > 0 && counts["at"] >= counts["rifle"]+counts["elite"] {
						choose = "rifle"
					}
					if counts["recon"] == 0 {
						choose = "recon"
					} else if counts["engineer"] == 0 {
						choose = "engineer"
					}
					typ = p.Faction + "." + choose
				case "factory":
					if needSupplyScout && counts["recon"] == 0 {
						break
					}
					choose := []string{"car", "tank", "aa", "apc", "tank", "repair"}[p.AIStage%6]
					// Keep a small ordinary AA reserve, and scale a bounded
					// supplement to recent armed air evidence instead of replacing
					// every factory purchase with the same damage layer.
					aaLimit := max(int32(1), min(int32(4), enemyAirCount))
					if enemyAir && counts["aa"] < aaLimit {
						choose = "aa"
					}
					if choose == "aa" && counts["aa"] >= aaLimit {
						choose = "tank"
					}
					if p.Tier >= 2 && p.AIStage%7 == 6 {
						choose = "artillery"
					}
					if choose == "repair" && counts["repair"] >= 2 {
						choose = "tank"
					}
					if counts["repair"] == 0 && p.Supply >= 24 && (!enemyAir || counts["aa"] > 0) {
						choose = "repair"
					}
					if p.Tier >= 3 && p.AIStage%9 == 8 && counts["launcher"] < 2 {
						choose = "launcher"
					}
					if p.Faction == "SA" && p.Tier >= 2 && counts["mobile_abm"] == 0 && p.Supply >= 35 {
						choose = "mobile_abm"
					}
					typ = p.Faction + "." + choose
					urgent := enemyAir && counts["aa"] < aaLimit || choose == "mobile_abm"
					typ = e.aiFirstFactoryVehicle(p, unit, own, typ, budget, plannedSupply, orders, urgent)
				case "airfield", "drone_hub", "workshop_air":
					if needSupplyScout && counts["recon"] == 0 || e.aiRapidSortieUseful(p, unit, own) {
						break
					}
					choose := "strike"
					if p.Faction == "SY" {
						choose = "scout_drone"
					} else if p.Faction == "IR" && counts["isr"] == 0 {
						choose = "isr"
					} else if p.AIStage%3 == 0 && (knownAirThreat || counts["fighter"] == 0) {
						choose = "fighter"
					} else if p.AIStage%3 == 2 {
						choose = "gunship"
					}
					typ = p.Faction + "." + choose
					air, valid := e.catalog.Unit(typ)
					if !valid || committedAirSupply+air.Supply > 28 || (choose == "strike" || choose == "gunship") && (e.aiAirDanger(p, p.AIGoal) || e.aiAirRouteDanger(p, unit.Position, p.AIGoal)) {
						typ = ""
					}
				}
				if typ != "" {
					u, valid := e.catalog.Unit(typ)
					if valid && u.Tier <= p.Tier && (u.Armor != "air" || e.aiAirProductionMargin(own, u.Producer)-plannedAirSlots[u.Producer] > 0) && budget >= u.Cost+300000 && plannedSupply+u.Supply <= 100 {
						orders = append(orders, Order{Kind: "train", Entities: []ID{unit.ID}, Type: typ})
						budget -= u.Cost
						plannedSupply += u.Supply
						if u.Armor == "air" {
							plannedAirSlots[u.Producer]++
							committedAirSupply += u.Supply
						}
						counts[u.Role]++
						p.AIStage++
					}
				}
			}
		}
		goal, haveGoal := e.aiGoal(p, view)
		p.AIGoal = goal
		orders = append(orders, e.aiRecoveryOrders(p, own, goal)...)
		orders = append(orders, e.aiTransportOrders(p, own, goal)...)
		orders = append(orders, e.aiEscortOrders(p, own)...)
		// Choosing compacts its slice, so preserve the planning prefix explicitly.
		priorOrders := append([]Order(nil), orders...)
		priorOrders = e.aiChooseOrders(p, own, priorOrders, planningCredits)
		orders = append(orders, e.aiSpecialOrdersWithBudget(p, view, own, goal, budget, priorOrders...)...)
		if needSupplyScout && counts["recon"] == 0 {
			if scout, ok := e.aiSupplyScoutOrder(p, own, orders, period); ok {
				orders = append(orders, scout)
			}
		}
		var scoutTerrain *aiScoutTerrain
		for _, v := range own {
			unit := e.entity(v.ID)
			if unit.Building || unit.Container != 0 {
				continue
			}
			role := e.role(unit)
			u, _ := e.catalog.Unit(v.Type)
			if role == "hauler" && (len(unit.Orders) == 0 || !needSupplyScout && unit.Blocked && len(unit.Orders) == 1 && unit.Orders[0].Kind == "move" && e.Tick()-unit.StationarySince >= seconds(12)) {
				orders = append(orders, Order{Kind: "gather", Entities: []ID{v.ID}})
			}
			if unit.Channel != "" || unit.DeployUntil > 0 || unit.PackingUntil > 0 {
				continue
			}
			if recovery, ok := e.aiStalledRallyOrder(unit, own, goal); ok {
				orders = append(orders, recovery)
				continue
			}
			if e.isAircraft(unit) && (!e.aiAirReady(unit, own) || len(unit.Orders) > 0 && unit.Orders[0].Kind == "return") {
				continue
			}
			if role == "fighter" {
				if len(unit.Orders) > 0 && unit.Orders[0].Kind == "attack" && !e.aiFighterAttackVisible(p, view, unit.Orders[0].Target) {
					kind := "return"
					if unit.Landed {
						kind = "stop"
					}
					orders = append(orders, Order{Kind: kind, Entities: []ID{unit.ID}})
				} else if len(unit.Orders) == 0 {
					if target, ok := e.aiFighterTarget(p, view, unit); ok {
						orders = append(orders, Order{Kind: "attack", Entities: []ID{unit.ID}, Target: target.ID})
					} else if !unit.Landed {
						orders = append(orders, Order{Kind: "return", Entities: []ID{unit.ID}})
					}
				}
				continue
			}
			if role == "recon" || role == "isr" || role == "scout_drone" {
				failed := len(unit.Orders) == 1 && unit.Orders[0].Kind == "move" && unit.Blocked && e.Tick()-unit.StationarySince >= seconds(12)
				if (len(unit.Orders) == 0 || failed) && (!e.isAircraft(unit) || unit.ServiceWork == 0) {
					if !e.isAircraft(unit) && scoutTerrain == nil {
						scoutTerrain = e.aiScoutTerrainKnowledge(p)
					}
					avoid := Vec{}
					if failed {
						avoid = unit.Orders[0].Position
					}
					if scout, ok := e.aiScoutWaypoint(p, unit.Position, avoid, failed, e.isAircraft(unit), scoutTerrain); ok {
						orders = append(orders, Order{Kind: "move", Entities: []ID{unit.ID}, Position: scout})
					}
				}
				continue
			}
			if u.Weapon == "" {
				continue
			}
			if !e.isAircraft(unit) && !unit.Active(e.Tick()) {
				continue
			}
			if e.isAircraft(unit) && (e.aiAirDanger(p, goal) || e.aiAirRouteDanger(p, unit.Position, goal)) {
				continue
			}
			if unit.Deployed {
				continue
			}
			if unit.HP*3 < unit.MaxHP && hq != nil && p.AI != "easy" {
				if len(unit.Orders) > 0 && unit.Orders[0].Kind == "guard" {
					if source := e.aiOwnEntity(own, unit.Orders[0].Target); source != nil && source.Active(e.Tick()) && source.Channel == "" && e.repairRate(source, unit) > 0 {
						continue
					}
				}
				if len(unit.Orders) == 0 || unit.Orders[0].Kind != "move" {
					orders = append(orders, Order{Kind: "move", Entities: []ID{unit.ID}, Position: hq.Position})
				}
				continue
			}
			// A fresh observed defense goal can preempt a single AI assault
			// waypoint. Preserve queued work and units currently dealing damage;
			// ordinary movement still enforces its shared route-work budget.
			if !e.isAircraft(unit) && p.AIIntent == "defend" && len(unit.Orders) == 1 && unit.Orders[0].Kind == "attack_move" && distance(unit.Orders[0].Position, goal) > 4000 && (!unit.EverDealt || e.Tick()-unit.LastDealt >= seconds(3)) {
				orders = append(orders, Order{Kind: "attack_move", Entities: []ID{unit.ID}, Position: goal})
				continue
			}
			if haveGoal && (p.Supply >= 12 || p.AIIntent == "defend") && len(unit.Orders) == 0 && (!e.isAircraft(unit) || unit.ServiceWork == 0) {
				orders = append(orders, Order{Kind: "attack_move", Entities: []ID{unit.ID}, Position: goal})
			}
		}

		e.aiDispatchOrders(p, e.aiChooseOrders(p, own, orders, planningCredits))
	}
}

