// Real product / frozen Go host. Only faults are explicit HTTP-advisor responses;
// admission, reconnect and paid production use visible ordinary UI controls.
import {chromium} from 'playwright-core';
import {spawn} from 'node:child_process';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import {prepareProduct,root,evidence,buildDir,product} from './multiplayer-combat-build.mjs';
const build=await prepareProduct(),runDir=path.join(evidence,'advice-recovery-'+new Date().toISOString().replaceAll(':','-'));await mkdir(runDir,{recursive:true});
const driver=await readFile(new URL(import.meta.url));await writeFile(path.join(runDir,'driver.mjs'),driver);
const report={started:new Date().toISOString(),driverSHA256:createHash('sha256').update(driver).digest('hex'),build,scope:'One custom human on ordinary authored map, unchanged 6000-credit opening, real profile/lobby/readiness and Go host. Controlled advisor faults only; no simulation edits, combat-win or physical-LAN claim. Browser plugin unavailable; Playwright fallback.',checks:[],injections:[],httpErrors:[],errors:[]};
const json=value=>JSON.stringify(value,(_key,item)=>typeof item==='bigint'?item.toString():item,2),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function until(check,message,timeout=30000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw Error(message);await sleep(100)}}
const child=spawn(path.join(buildDir,'frontline'),['-addr','127.0.0.1:0','-data',path.join(runDir,'data'),'-static',product,'-maps',path.join(product,'content/maps'),'-missions',path.join(product,'content/missions')],{cwd:root,stdio:['ignore','pipe','pipe']});let hostLog='';
const origin=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Host startup timeout')),30000);child.stdout.on('data',bytes=>{hostLog+=bytes;const found=hostLog.match(/http:\/\/127\.0\.0\.1:\d+/);if(found){clearTimeout(timeout);resolve(found[0])}});child.stderr.on('data',bytes=>hostLog+=bytes);child.once('exit',code=>reject(Error('Host exit '+code)))});
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1600,height:900}}),page=await context.newPage();page.setDefaultTimeout(30000);report.browser=browser.version();report.origin=origin;
const {fromBinary,EnvelopeSchema,applyDelta}=await import(pathToFileURL(path.join(buildDir,'decode.mjs')));let sockets=0,snapshot;const sent=[],receipts=[];let fault;
page.on('websocket',socket=>{sockets++;socket.on('framesent',frame=>{if(typeof frame.payload!=='string'){const message=fromBinary(EnvelopeSchema,new Uint8Array(frame.payload)).message;if(message.case==='orders')sent.push(message.value)}});socket.on('framereceived',frame=>{if(typeof frame.payload!=='string'){const message=fromBinary(EnvelopeSchema,new Uint8Array(frame.payload)).message;if(message.case==='orderResult')receipts.push(message.value);if(message.case==='snapshot')snapshot=message.value;else if(message.case==='delta')snapshot=applyDelta(snapshot,message.value);if(['snapshot','delta'].includes(message.case))receipts.push(...snapshot.results)}})});
page.on('pageerror',error=>report.errors.push({kind:'pageerror',message:error.message,stack:error.stack}));page.on('console',message=>{if(message.type()==='error')report.errors.push({kind:'console',message:message.text(),location:message.location()})});page.on('response',async response=>{if(response.status()<400)return;const entry={path:new URL(response.url()).pathname,status:response.status()};report.httpErrors.push(entry);try{Object.assign(entry,await response.json())}catch(error){entry.readError=String(error)}});
await page.route('**/api/v1/matches/*/advice',async route=>{const body=route.request().postDataJSON();if(fault&&((fault.phase==='command')===(body.orders?.length>0))){const active=fault;fault=undefined;report.injections.push({phase:active.phase,code:active.code,status:503,path:new URL(route.request().url()).pathname,orders:body.orders??[],time:new Date().toISOString()});await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({code:active.code,message:'Command advice timed out.'})});return}await route.continue()});
async function idle(){await until(async()=>await page.locator('.network-operation,.loading-screen').count()===0,'Operation remained busy',120000);assert.equal(await page.locator('.network-error').count(),0)}
async function view(){return JSON.parse(await page.evaluate(()=>window.multiplayerCombat.view()))}
async function capture(name){await page.screenshot({path:path.join(runDir,name+'.png')});await writeFile(path.join(runDir,name+'.dom.txt'),await page.locator('body').innerText())}
function check(name,details={}){report.checks.push({name,...details});console.log(name)}
try{
 await page.goto(origin);assert.equal(await page.title(),'Frontline Command');await page.getByRole('button',{name:'Explore game modes',exact:true}).click();await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle();await page.getByLabel('Commander name',{exact:true}).fill('Advice recovery');await page.getByRole('button',{name:'Create local profile',exact:true}).click();await page.getByLabel('Your profile ID').waitFor();await idle();
 await page.getByLabel('Operation name',{exact:true}).fill('Controlled advice recovery');await page.getByLabel('Lobby battlefield',{exact:true}).selectOption('industrial-valley');await page.getByLabel('Battle format',{exact:true}).selectOption('custom');await page.getByLabel('Host faction',{exact:true}).selectOption('US');await page.getByRole('button',{name:'Create operation',exact:true}).click();await idle();await page.getByRole('button',{name:'Ready to deploy',exact:true}).click();await idle();await page.getByRole('button',{name:'Start operation',exact:true}).click();await page.getByRole('complementary',{name:'Command sidebar'}).waitFor();await page.locator('.scene-loading').waitFor({state:'hidden',timeout:120000});await until(async()=>(await view()).tick>130,'Countdown');
 await page.getByRole('button',{name:'HQ',exact:true}).click();await page.getByRole('tab',{name:'vehicles',exact:true}).click();const rig=page.locator('.production-cameo').filter({hasText:'Engineering rig'});await until(()=>rig.isEnabled(),'Actual HQ rig option unavailable');const opening=await view();assert.equal(opening.economy.credits,'6000000');check('Actual profile, custom lobby, readiness, countdown and 6000-credit HQ production');await capture('ready');
 fault={phase:'background',code:'advice_timeout'};await page.locator('.notice').filter({hasText:'Command options are temporarily unavailable. Retrying…'}).waitFor();assert.equal(report.injections.length,1);assert.equal(await page.getByRole('heading',{name:'Command interrupted',exact:true}).count(),0);assert(await rig.isDisabled());await capture('background-timeout');check('Injected background 503 is visible nonblocking notice and disables stale choice');
 await page.getByRole('button',{name:'Open pause menu',exact:true}).click();await page.getByRole('region',{name:'Online operation controls'}).first().waitFor();check('Normal operation menu remains clickable after advisor failure');const beforeReconnect={tick:(await view()).tick,sockets};await page.getByRole('button',{name:'Reconnect',exact:true}).click();await idle();await until(async()=>sockets>beforeReconnect.sockets&&(await view()).tick>=beforeReconnect.tick,'Reconnect failed');await capture('reconnected-menu');check('Normal reconnect recovers authoritative stream',{before:beforeReconnect,after:{tick:(await view()).tick,sockets}});await page.getByRole('button',{name:'Return to battlefield',exact:true}).click();await until(()=>rig.isEnabled(),'Production did not recover after fresh advice');await until(async()=>await page.locator('.notice').filter({hasText:'temporarily unavailable'}).count()===0,'Advice notice persisted after recovery');check('Fresh server advice restores actual production choices');
 const sentBefore=sent.length,creditsBefore=(await view()).economy.credits;fault={phase:'command',code:'advice_timeout'};await rig.click();await page.locator('.notice').filter({hasText:'Order not sent: command options are temporarily unavailable. Try again.'}).waitFor();assert.equal(await page.getByRole('heading',{name:'Command interrupted',exact:true}).count(),0);assert.equal(sent.length,sentBefore);assert.equal((await view()).economy.credits,creditsBefore);await capture('command-timeout');await sleep(4200);assert.equal(sent.length,sentBefore);check('Explicit production-advisor failure sends no command and never auto-retries');
 await until(()=>rig.isEnabled(),'Retry option unavailable');await rig.click();await until(()=>sent.length===sentBefore+1,'Explicit retry did not submit command');const order=sent.at(-1);assert.deepEqual(order.orders.map(order=>({kind:order.kind,type:order.type})),[{kind:'train',type:'US.rig'}]);await until(()=>receipts.some(receipt=>receipt.sequence===order.sequence&&receipt.accepted),'No accepted paid production receipt');await until(async()=>(await view()).economy.credits==='5200000','Expected ordinary 800-credit payment missing');const paid=await view();await writeFile(path.join(runDir,'paid-view.json'),json(paid));await capture('paid-production');check('Explicit retry accepted by Go and pays exactly 800 credits',{sequence:order.sequence,receipt:receipts.find(receipt=>receipt.sequence===order.sequence&&receipt.accepted),creditsBefore,creditsAfter:paid.economy.credits});
 await until(async()=>(await view()).entities.filter(entity=>entity.owner===1&&entity.type==='US.rig').length===2,'Paid rig did not complete',60000);await capture('paid-rig-complete');check('Paid 400-tick engineering rig queue actually completes',{tick:(await view()).tick});
 await page.setViewportSize({width:1280,height:720});await capture('recovered-1280');assert.equal(await page.locator('vite-error-overlay').count(),0);assert.equal(await page.getByRole('heading',{name:'Command interrupted',exact:true}).count(),0);assert.equal(report.injections.length,2);assert.equal(report.httpErrors.length,2);assert(report.httpErrors.every(error=>error.status===503&&error.code==='advice_timeout'));assert.equal(report.errors.filter(error=>error.kind==='pageerror').length,0);assert.equal(report.errors.length,2,'Only two injected HTTP failures may reach console');assert(report.errors.every(error=>error.kind==='console'&&/503/.test(error.message)&&error.location.url.endsWith('/advice')));check('Both expected injected HTTP errors retained; no other page/console/HTTP errors');report.assets=JSON.parse(await page.evaluate(()=>window.multiplayerCombat.info())).assets;report.status='passed';
}catch(error){report.status='failed';report.failure=String(error.stack??error);process.exitCode=1;await capture('failure').catch(()=>{});await writeFile(path.join(runDir,'failure-view.json'),json(await view().catch(()=>null)))}
finally{report.completed=new Date().toISOString();report.sent=sent;report.receipts=receipts;await writeFile(path.join(runDir,'browser.json'),json(report));await context.close();await browser.close();if(child.exitCode===null){const ended=new Promise(resolve=>child.once('exit',resolve));child.kill('SIGTERM');await ended}await writeFile(path.join(runDir,'host.log'),hostLog);console.log(report.status,runDir)}
