import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{streamingSHA256}from'./streaming-sha256.mjs';import{allArtConsumedBodyTrace,allArtBodyIntegrity}from'./all-art-consumed-body-trace.mjs';
const url='http://local/art/a.png',sha=b=>createHash('sha256').update(b).digest('hex');
function setup(response,options={}){let fetches=0;const o=allArtConsumedBodyTrace(()=>{fetches++;return Promise.resolve(response)},{scope:'doc',baseURL:url,hashFactory:streamingSHA256,...options});return{o,fetches:()=>fetches}}
function response(body){const r=new Response(body);Object.defineProperty(r,'url',{value:url,configurable:true});return r}
async function done(o,bytes){await o.finish();const s=o.snapshot(),r=s.records[0];return{s,r,proof:allArtBodyIntegrity(r,{bytes:bytes.length,sha256:sha(bytes)})}}
test('all art original reader identity and mutated chunks hash without retaining body chunks',async()=>{
 const chunk=new Uint8Array([1,2,3]),item={done:false,value:chunk},eof={done:true};let i=0,released=0,canceled=0;const reader={read:()=>Promise.resolve(i++?eof:item),cancel:()=>{canceled++;return Promise.resolve()},releaseLock:()=>released++},r={status:200,url,redirected:false,body:{getReader:()=>reader}},f=setup(r);
 assert.equal(await f.o.fetch(url),r);assert.equal(r.body.getReader(),reader);assert.equal(await reader.read(),item);chunk.fill(0);assert.equal(await reader.read(),eof);assert.equal(released,0);reader.releaseLock();assert.equal(canceled,0);const d=await done(f.o,new Uint8Array([1,2,3]));assert.equal(d.proof.complete,true);assert.equal(d.s.accounting.activeHashes,0);assert.equal(d.s.accounting.retainedResponseChunkBytes,0);assert.equal(d.s.accounting.peakActiveHashes,1);assert.equal(f.fetches(),1);
});
test('native json/text remain the same parsed value but can never be reserialized as byte proof',async()=>{
 for(const method of ['json','text']){const bytes=new TextEncoder().encode(' { "a" : 1 } '),nativeValue=method==='json'?{a:1}:' { "a" : 1 } ',r={status:200,url,redirected:false,[method]:()=>Promise.resolve(nativeValue)},f=setup(r);await f.o.fetch(url);const value=await r[method]();assert.equal(value,nativeValue);if(method==='json')assert.deepEqual(value,{a:1});else assert.equal(value,' { "a" : 1 } ');const d=await done(f.o,bytes);assert.equal(d.proof.complete,false);assert.equal(d.proof.reason,'native-'+method+'-does-not-expose-original-bytes');assert.equal(d.r.sha256,undefined);assert.equal(d.r.bodyMethodSettledOrder>0,true)}
});
test('native arrayBuffer retains its exact result and hashes before caller mutation',async()=>{const bytes=new Uint8Array([5,6,7]),value=bytes.buffer,r={status:200,url,redirected:false,arrayBuffer:()=>Promise.resolve(value)},f=setup(r);await f.o.fetch(url);assert.equal(await r.arrayBuffer(),value);bytes.fill(0);const d=await done(f.o,new Uint8Array([5,6,7]));assert.equal(d.proof.complete,true);assert.equal(d.proof.completion,'native-arrayBuffer-fulfilled')});
test('native returned Blob identity/delivery is not held for local proof, storage is bounded, no extra fetch',async()=>{
 const bytes=new Uint8Array(1<<20).fill(7),blob=new Blob([bytes]),r={status:200,url,redirected:false,blob:()=>Promise.resolve(blob)},f=setup(r);await f.o.fetch(url);assert.equal(await r.blob(),blob);assert(f.o.snapshot().accounting.pendingBlobProofs>0);const d=await done(f.o,bytes);assert.equal(d.proof.complete,true);assert.equal(d.proof.completion,'native-blob-fulfilled');assert.equal(d.s.accounting.retainedBlobBytes,0);assert.equal(d.s.accounting.peakRetainedBlobBytes,blob.size);assert.equal(f.fetches(),1);
});
test('large/parallel Blob proof limits preserve original delivery and leave unsupported proof explicit',async()=>{
 const blob=new Blob([new Uint8Array(1024)]),r={status:200,url,redirected:false,blob:()=>Promise.resolve(blob)},f=setup(r,{maxBlob:100});await f.o.fetch(url);assert.equal(await r.blob(),blob);const d=await done(f.o,new Uint8Array(1024));assert.equal(d.proof.reason,'native-blob-proof-limit');assert.equal(d.s.accounting.peakRetainedBlobBytes,0);
 const r2={status:200,url,redirected:false,blob:()=>Promise.resolve(blob)},f2=setup(r2,{maxBlobRetained:100});await f2.o.fetch(url);assert.equal(await r2.blob(),blob);assert.equal((await done(f2.o,new Uint8Array(1024))).proof.reason,'native-blob-proof-limit');
});
test('per-body/total/active limits do not cancel original streams or hide truncation/error identity',async()=>{
 for(const options of [{maxBody:2},{maxTotal:2}]){const r=response(new Uint8Array([1,2,3])),f=setup(r,options);await f.o.fetch(url);const reader=r.body.getReader();assert.deepEqual((await reader.read()).value,new Uint8Array([1,2,3]));assert.equal((await reader.read()).done,true);reader.releaseLock();const d=await done(f.o,new Uint8Array([1,2,3]));assert.equal(d.proof.complete,false);assert(d.r.hashOverflow);assert.equal(d.s.accounting.activeHashes,0)}
 const marker=Error('native'),reader={read:()=>Promise.reject(marker)},r={status:200,url,redirected:false,body:{getReader:()=>reader}},f=setup(r);await f.o.fetch(url);await assert.rejects(r.body.getReader().read(),e=>e===marker);assert.equal((await done(f.o,new Uint8Array())).proof.complete,false);assert.equal(f.o.snapshot().accounting.activeHashes,0);
});
test('actual caller cancellation remains exact; observation never supplies EOF or hash',async()=>{const reason={cancel:1};let call;const reader={read:()=>Promise.resolve({done:false,value:new Uint8Array([1])}),cancel:x=>{call=x;return Promise.resolve(x)}},r={status:200,url,redirected:false,body:{getReader:()=>reader}},f=setup(r);await f.o.fetch(url);const rd=r.body.getReader();await rd.read();assert.equal(await rd.cancel(reason),reason);assert.equal(call,reason);const d=await done(f.o,new Uint8Array([1]));assert.equal(d.proof.complete,false);assert.equal(d.r.eofOrder,undefined);assert.equal(d.s.accounting.activeHashes,0)});
test('concurrent original readers honor active-state ceiling without canceling either consumer',async()=>{
 const a=response(new Uint8Array([1])),b=response(new Uint8Array([2]));Object.defineProperty(b,'url',{value:'http://local/art/b.png',configurable:true});let i=0;const o=allArtConsumedBodyTrace(()=>Promise.resolve(i++?b:a),{scope:'A',baseURL:url,hashFactory:streamingSHA256,maxActive:1});await o.fetch(url);await o.fetch(b.url);const ra=a.body.getReader(),rb=b.body.getReader();assert.equal((await rb.read()).value[0],2);assert.equal((await rb.read()).done,true);assert.equal((await ra.read()).value[0],1);assert.equal((await ra.read()).done,true);ra.releaseLock();rb.releaseLock();await o.finish();const s=o.snapshot();assert.equal(s.accounting.peakActiveHashes,1);assert.equal(s.accounting.activeHashes,0);assert.equal(s.records[1].hashOverflow,'active-hash-limit');assert.equal(s.records[1].sha256,undefined);
});
