/** Isolated acceptance entry: real product, inspected only through public transports. */
import {createRoot} from 'react-dom/client';
import {Application} from '../../src/app/application';
import {App} from '../../src/ui/App';
import {BattlefieldRenderer} from '../../src/render/battlefield';
import {OfflineTransport} from '../../src/runtime/offline';
import type {OrderIntent,Point,SaveData} from '../../src/runtime';
import '../../src/design/tokens.css';
import '../../src/styles/game.css';
const app=new Application();let renderer:BattlefieldRenderer|undefined,mirror:OfflineTransport|undefined,opening:SaveData|undefined;
const create=BattlefieldRenderer.create;BattlefieldRenderer.create=async function(...args){renderer=await create.apply(this,args);return renderer};
createRoot(document.getElementById('root')!).render(<App app={app}/>);void app.boot();
const log:unknown[]=[],checkpoints:unknown[]=[],notices:string[]=[];app.state.subscribe(()=>{const n=app.state.get().notice;if(n&&notices[notices.length-1]!==n)notices.push(n)});const runtime=()=>app.sessions.transport as OfflineTransport;
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function mounted(){for(let n=0;n<1000;n++){if(renderer&&!document.querySelector('.scene-loading')&&!app.state.get().paused)break;if(app.state.get().error)throw Error(app.state.get().error);await sleep(100)}if(!renderer)throw Error('Product renderer did not mount');await runtime().pause();await renderer.whenAssetsReady()}
async function settle(){await renderer!.whenAssetsReady();await sleep(150)}
async function parity(label:string){const hash=await runtime().hash(),bare=await mirror!.hash();if(hash!==bare)throw Error(`Scenery/mirror hash mismatch at ${label}: ${hash} != ${bare}`);const result={label,tick:runtime().current!.tick,hash};checkpoints.push(result);return result}
async function step(ticks:number){while(ticks>0){const count=Math.min(200,ticks);await Promise.all([runtime().step(count),mirror!.step(count)]);ticks-=count}}
async function order(value:OrderIntent,allowRejection=false){const preview=await runtime().previewOrders([value]);if(!preview.results[0]?.accepted)throw Error(`Ordinary order rejected: ${JSON.stringify({value,preview})}`);await Promise.all([runtime().sendOrders([value]),mirror!.sendOrders([value])]);await step(2);const results=runtime().current!.results;log.push({tick:runtime().current!.tick,order:value,results});const accepted=!results.some(r=>!r.accepted);if(!accepted&&!allowRejection)throw Error('Execution rejected '+JSON.stringify({value,results}));return accepted;}
function unit(type:string){const found=runtime().current!.entities.find(e=>e.owner===1&&e.type===type&&e.complete);if(!found)throw Error(`Missing paid ${type}`);return found}
async function until(test:()=>boolean,label:string,limit=6000){for(let ticks=0;ticks<limit&&!test();ticks+=40)await step(40);if(!test())throw Error(`${label}: ${JSON.stringify(runtime().current!.entities.map(e=>({id:e.id,type:e.type,state:e.state,p:e.position,complete:e.complete})))}`)}
async function funds(cost:number){await until(()=>runtime().current!.economy!.credits>=BigInt(cost),'Insufficient ordinary income',12000)}
async function build(type:string,near:Point){const catalog=app.state.get().catalog!,def=catalog.buildings.get(type)!;await funds(def.cost);const rig=unit('US.rig'),candidates:OrderIntent[]=[];
 for(let r=0;r<=12;r++)for(let dx=-r;dx<=r;dx++)for(let dy=-r;dy<=r;dy++){if(Math.max(Math.abs(dx),Math.abs(dy))!==r)continue;const p={x:(Math.floor(near.x/1000)+dx)*1000+(def.width%2?500:0),y:(Math.floor(near.y/1000)+dy)*1000+(def.height%2?500:0)};candidates.push({kind:'build',entities:[rig.id],type,position:p})}
 const before=new Set(runtime().current!.entities.map(e=>e.id));let accepted:OrderIntent|undefined;for(const candidate of candidates){const p=await runtime().previewOrders([candidate]);if(p.results[0]?.accepted&&await order(candidate,true)){accepted=candidate;break}await step(20)}if(!accepted)throw Error('No ordinary legal construction candidate for '+type);await until(()=>runtime().current!.entities.some(e=>e.type===type&&e.complete&&!before.has(e.id)),'Paid construction '+type,6000);await parity('built '+type);return unit(type)}
async function train(type:string){const def=app.state.get().catalog!.units.get(type)!;await funds(def.cost);const producer=unit(def.producer==='airfield'?'US.airfield':def.producer),before=new Set(runtime().current!.entities.map(e=>e.id));await order({kind:'train',entities:[producer.id],type});await until(()=>runtime().current!.entities.some(e=>e.type===type&&e.complete&&!before.has(e.id)),'Paid production '+type,4000);await parity('trained '+type);return runtime().current!.entities.find(e=>e.type===type&&!before.has(e.id))!}
async function move(id:number,p:Point){await order({kind:'move',entities:[id],position:p});await until(()=>{const current=runtime().current!.entities.find(e=>e.id===id)!;return !!current.position&&Math.hypot(current.position.x-p.x,current.position.y-p.y)<650},'Ordinary traversal',6000)}
function nodes(){const env=(renderer as any).environment;return [...env.nodes].map(([key,n]:any)=>({key,asset:n.item.asset,state:n.item.state,visible:n.root.visible,beauty:n.beauty.visible,remembered:n.item.remembered}))}
const qa={
 async initialize(){await mounted();opening=await runtime().save();mirror=new OfflineTransport();await mirror.ready;await mirror.load(opening.data,opening.local_players);await step(Math.max(0,105-runtime().current!.tick));return {version:runtime().version,metadata:opening.metadata,openingData:Array.from(opening.data),environment:app.environmentFor(app.sessions.state.map!),opening:await parity('opening'),nodes:nodes()};},
 async economy(){await build('power',{x:23000,y:69000});await build('supply',{x:22000,y:58500});const hauler=await train('US.hauler');await order({kind:'gather',entities:[hauler.id],target:1});await build('barracks',{x:27000,y:63500});const recon=await train('US.recon');const rifle=await train('US.rifle');return {tick:runtime().current!.tick,credits:runtime().current!.economy!.credits.toString(),recon:recon.id,rifle:rifle.id,log:[...log]};},
 async west(){const recon=unit('US.recon'),rifle=unit('US.rifle');await move(recon.id,{x:34500,y:53500});await move(recon.id,{x:35500,y:57500});await move(rifle.id,{x:38500,y:80000});const garrison=runtime().current!.entities.find(e=>e.mapObject===3)!;if(!garrison)throw Error('Actual scouting did not reveal west ruin');await order({kind:'board',entities:[rifle.id],target:garrison.id});await until(()=>runtime().current!.entities.find(e=>e.id===rifle.id)?.private?.container===garrison.id,'Actual garrison boarding',2400);renderer!.center({x:39500,y:81500});await settle();return {checkpoint:await parity('west cover and occupied garrison'),garrison:runtime().current!.entities.find(e=>e.id===garrison.id),passenger:runtime().current!.entities.find(e=>e.id===rifle.id),nodes:nodes()};},
 async coverWest(){renderer!.center({x:35000,y:55500});await settle();return {nodes:nodes()};},
 async air(){await build('radar',{x:27500,y:68000});await build('power',{x:16000,y:71000});await build('US.airfield',{x:18000,y:76500});const fighter=await train('US.fighter');await order({kind:'move',entities:[fighter.id],position:{x:45500,y:46500}});await until(()=>runtime().current!.visible[46*128+45]===true,'Paid scouting west plateau',3000);renderer!.center({x:45500,y:46500});await settle();return {checkpoint:await parity('paid air scouts west plateau'),nodes:nodes(),log:[...log]};},
 async east(){const fighter=unit('US.fighter');await order({kind:'move',entities:[fighter.id],position:{x:82500,y:81500}});await until(()=>runtime().current!.visible[81*128+82]===true,'Paid scouting east plateau',4000);renderer!.center({x:82500,y:81500});await settle();return {checkpoint:await parity('east plateau'),nodes:nodes()};},
 async eastCover(){const recon=unit('US.recon');for(const p of [{x:40500,y:75500},{x:87500,y:52500},{x:93500,y:74500},{x:92500,y:70500}])await move(recon.id,p);renderer!.center({x:93000,y:72500});await settle();return {checkpoint:await parity('ground traverses four cover pockets'),nodes:nodes(),position:unit('US.recon').position};},
 async ruinEast(){const recon=unit('US.recon');await move(recon.id,{x:88500,y:38500});renderer!.center({x:88500,y:43500});await settle();const g=runtime().current!.entities.find(e=>e.mapObject===4);if(!g)throw Error('East garrison not visible');return {checkpoint:await parity('east ruin'),garrison:g,nodes:nodes()};},
 async damage(){await build('factory',{x:30000,y:73000});const tank=await train('US.tank');await move(tank.id,{x:83500,y:43500});const g=runtime().current!.entities.find(e=>e.mapObject===4)!;await order({kind:'attack',entities:[tank.id],target:g.id});await until(()=>{const target=runtime().current!.entities.find(e=>e.mapObject===4);return !!target&&target.health<=500},'Actual weapon damage',3000);renderer!.center({x:88500,y:43500});await settle();return {checkpoint:await parity('paid tank damages east ruin'),health:runtime().current!.entities.find(e=>e.mapObject===4)!.health,nodes:nodes()};},
 async destroy(){await until(()=>runtime().current!.rubble.includes(4),'Actual ruin destruction',4000);await settle();return {checkpoint:await parity('paid tank destroys east ruin'),rubble:runtime().current!.rubble,nodes:nodes(),log:[...log]};},
 async final(){const save=await runtime().save();await mirror!.load(save.data,save.local_players);return {checkpoint:await parity('exact save restoration'),checkpoints,orders:log,credits:runtime().current!.economy!.credits.toString(),save:{...save,data:Array.from(save.data)},replay:Array.from(await runtime().exportReplay()),map:app.sessions.state.map,errors:app.state.get().error};},
 async fallback(){mirror?.dispose();await app.leave();renderer=undefined;await app.sessions.loadSave(opening!);await mounted();return {notices:[...notices],notice:app.state.get().notice,environment:app.environmentFor(app.sessions.state.map!),hash:await runtime().hash(),openingHash:opening!.hash,map:app.sessions.state.map?.id};},
 async dispose(){mirror?.dispose();await app.leave();return {canvases:document.querySelectorAll('.battlefield-canvas canvas').length};}
};Object.assign(window,{qa});
