import {BattlefieldRenderer} from '../../src/render/battlefield';
import {ArtLibrary} from '../../src/render/art';
import {CatalogIndex,type Catalog} from '../../src/content/catalog';
import {decodeMapEnvironment} from '../../src/content/environment';
import {DEFAULT_SETTINGS} from '../../src/app/settings';
import {OfflineTransport} from '../../src/runtime/offline';
import {sha256Hex} from '../../src/runtime/crypto';
import type {GameMap,OrderIntent} from '../../src/runtime';
import type {ActorVisual} from '../../src/render/actors';
const raw:GameMap={id:'sidecar-integration',title:'Synthetic public environment acceptance',author:'test',version:'1',format_version:1,ruleset:'standard-v2',width:64,height:64,tiles:Array.from({length:4096},()=>({terrain:'open',height:0})),spawns:[{position:{x:8000,y:8000}},{position:{x:56000,y:56000}}],shipment:{x:12000,y:30000},fields:[],stations:[],objects:[{id:90,class:'garrison',position:{x:26500,y:17500}}],required_packs:['2.0.0']};
for(let y=0;y<64;y++)for(let x=30;x<=33;x++)raw.tiles[y*64+x]={terrain:'water',height:0};
for(let y=29;y<=31;y++)for(let x=30;x<=33;x++)raw.tiles[y*64+x]={terrain:'road',height:0,mandatory:true};
for(let y=20;y<=28;y++)for(let x=16;x<=22;x++)raw.tiles[y*64+x]={terrain:'blocked',height:0,sight_blocker:true};
for(let y=13;y<=16;y++)for(let x=18;x<=21;x++)raw.tiles[y*64+x]={terrain:'cover',height:0};
const definition={schema:'fc-map-environment/1',map:{id:raw.id,version:raw.version,sha256:''},object_skins:[{object_id:90,asset:'prop.ruined_house_garrisonable',direction:2}],placements:[{id:'containers',asset:'prop.container_stack',position:{x:18000,y:22000},direction:0,state:'idle'},{id:'fence',asset:'prop.fence_chainlink',position:{x:18000,y:27000},direction:1,state:'idle'},{id:'cover-scrub',asset:'prop.forest_edge_scrub',position:{x:20000,y:14500},direction:0,state:'idle'}]};
for(let x=30;x<=33;x++)for(let y=29;y<=31;y++)definition.placements.push({id:`bridge-${x}-${y}`,asset:'prop.bridge_permanent',position:{x:x*1000+500,y:y*1000+500},direction:0,state:y===29?'edge_right':y===31?'edge_left':'deck'});
const runtime=new OfflineTransport();await runtime.ready;const mapBytes=new TextEncoder().encode(JSON.stringify(raw)),map=await runtime.validateMap(mapBytes);definition.map.sha256=await sha256Hex(mapBytes);const environment=decodeMapEnvironment(new TextEncoder().encode(JSON.stringify(definition)),map,{mapSHA256:definition.map.sha256});
const mission={id:'sidecar-test',version:'1',title:'Public dressing acceptance',map_id:map.id,faction:'US',mode:'tutorial',default_bases:true,players:[{id:1,faction:'US',name:'Crossing commander',team:1,credits:6000000,controller:'human'},{id:2,faction:'IR',name:'Far opponent',team:2,credits:6000000,controller:'script'}],initial:[{tag:'airfield',type:'US.airfield',owner:1,position:{x:10000,y:35500},count:1},{tag:'scouting-wing',type:'US.fighter',owner:1,position:{x:10500,y:35500},count:1},{tag:'tank',type:'US.tank',owner:1,position:{x:24500,y:30500},count:1},{tag:'engineer',type:'US.engineer',owner:1,position:{x:24500,y:20500},count:1},{tag:'recon',type:'US.recon',owner:1,position:{x:20500,y:16500},count:1}],objectives:[{id:'timer',text:'Environment test duration',condition:{kind:'timer',tick:100000}}],triggers:[]};
await runtime.validateMission(mapBytes,new TextEncoder().encode(JSON.stringify(mission)));await runtime.create({map,mission,seed:31,skip_countdown:true});
const catalog=new CatalogIndex(await runtime.content() as unknown as Catalog),art=new ArtLibrary(),errors:string[]=[],renderer=await BattlefieldRenderer.create(document.getElementById('field')!,{map,environment,catalog,art,settings:{...DEFAULT_SETTINGS,edgeScroll:false,screenShake:0},onGesture:()=>{},onError:e=>errors.push(e.message)});
runtime.subscribe(e=>{if(e.type==='snapshot')renderer.setSnapshot(e.snapshot);if(e.type==='error')errors.push(e.error.message)});renderer.setSnapshot(runtime.current!);renderer.center({x:24000,y:24000});await renderer.whenAssetsReady();const opening=await runtime.save();
const internals=renderer as unknown as {actors:Map<number,ActorVisual>;environment:{count:number;nodes:Map<string,{item:{kind:string;asset:string;direction?:number;state:string;remembered:boolean};root:{visible:boolean;alpha:number};sheet?:{id:string};beauty:{visible:boolean}}>}},nodes=()=>[...internals.environment.nodes].map(([key,n])=>({key,item:n.item,sheet:n.sheet?.id,visible:n.root.visible,alpha:n.root.alpha,beauty:n.beauty.visible}));
async function settle(){await renderer.whenAssetsReady();await new Promise(resolve=>setTimeout(resolve,100));await art.settle()}
async function order(o:OrderIntent){const p=await runtime.previewOrders([o]);if(!p.results[0]?.accepted)throw Error('Ordinary order rejected '+JSON.stringify({o,p}));await runtime.sendOrders([o]);await runtime.step(2)}
const tank=()=>runtime.current!.entities.find(e=>e.type==='US.tank')!;
const qa={errors,
 async opening(){await settle();const target=runtime.current!.entities.find(e=>e.type==='map.garrison')!,actor=internals.actors.get(target.id)! as unknown as {sheet?:{id:string};parts:{poses:Record<string,{state:string;direction:number}>}[]};return {version:runtime.version,tick:runtime.current!.tick,definition,mapSHA256:definition.map.sha256,skin:{sheet:actor.sheet?.id,actualGoFacing:target.facing,poses:actor.parts.map(p=>p.poses)},nodes:nodes(),missing:renderer.missingArt}},
 async revealIndustry(){const fighter=runtime.current!.entities.find(e=>e.type==='US.fighter')!;await order({kind:'move',entities:[fighter.id],position:{x:18000,y:23000}});for(let n=0;n<500&&(!runtime.current!.visible[22*64+18]||!runtime.current!.visible[27*64+18]);n++)await runtime.step(4);if(!runtime.current!.visible[22*64+18]||!runtime.current!.visible[27*64+18])throw Error('Ordinary aircraft scouting did not disclose industrial terrain');await settle();return {tick:runtime.current!.tick,nodes:nodes(),aircraft:runtime.current!.entities.find(e=>e.id===fighter.id)}},
 async cull(){renderer.center({x:56000,y:8000});await settle();const offscreen=nodes().filter(n=>n.item.kind==='dressing');renderer.center({x:24000,y:24000});await settle();return {offscreen,restored:nodes()}},
 async returnScout(){await order({kind:'return',entities:[runtime.current!.entities.find(e=>e.type==='US.fighter')!.id]});return {tick:runtime.current!.tick}},
 async destroy(){const target=runtime.current!.entities.find(e=>e.type==='map.garrison')!,poses=new Set<string>();await order({kind:'attack',entities:[tank().id],target:target.id});for(let n=0;n<500&&!runtime.current!.rubble.includes(90);n++){await runtime.step(4);const e=runtime.current!.entities.find(e=>e.id===target.id);if(e){await settle();const actor=internals.actors.get(e.id)! as unknown as {state:(now:number)=>{name:string}|undefined};poses.add(actor.state(performance.now())?.name??'missing')}}if(!runtime.current!.rubble.includes(90))throw Error('Garrison destruction did not complete');await settle();return {tick:runtime.current!.tick,poses:[...poses],rubble:runtime.current!.rubble,nodes:nodes()}},
 async cross(){await order({kind:'move',entities:[tank().id],position:{x:40500,y:30500}});const positions:{tick:number;x:number;y:number;terrain:string}[]=[];for(let n=0;n<450;n++){await runtime.step(4);const p=tank().position!;if(p.x>=30000&&p.x<34000)positions.push({tick:runtime.current!.tick,x:p.x,y:p.y,terrain:map.tiles[Math.floor(p.y/1000)*64+Math.floor(p.x/1000)].terrain});if(Math.hypot(p.x-40500,p.y-30500)<500)break}const p=tank().position!;if(Math.hypot(p.x-40500,p.y-30500)>=500)throw Error('Tank did not traverse the actual legal road crossing');renderer.center({x:32000,y:30500});await settle();return {tick:runtime.current!.tick,position:p,positions,nodes:nodes()}},
 async fog(){const ids=runtime.current!.entities.filter(e=>['US.engineer','US.recon'].includes(e.type)).map(e=>e.id);await order({kind:'move',entities:ids,position:{x:10000,y:14000}});for(let n=0;n<300&&runtime.current!.visible[17*64+26];n++)await runtime.step(4);renderer.center({x:22000,y:21000});await settle();return {garrisonVisible:runtime.current!.visible[17*64+26],nodes:nodes()}},
 async restore(){const save=await runtime.save(),hash=await runtime.hash();await runtime.load(save.data,save.local_players);await settle();const restored=await runtime.hash();await runtime.load(opening.data,opening.local_players);renderer.center({x:24000,y:24000});await settle();return {hash,restored,openingHash:opening.hash,rewoundHash:await runtime.hash(),rubble:runtime.current!.rubble,nodes:nodes()}},
 async dispose(){renderer.dispose();runtime.dispose();await art.release();return {environment:internals.environment.count,canvases:document.querySelectorAll('canvas').length,art:art.statistics}},
};Object.assign(window,{qa});document.body.dataset.ready='true';
