// Real restarted Go host, copied earned DB/replay. Only test credential hash is
// reissued in the copy; original result/replay/DB are immutable. No token output.
import {chromium} from 'playwright-core';
import {spawn,execFileSync} from 'node:child_process';
import {readFile,writeFile,mkdir,cp} from 'node:fs/promises';
import {createHash,randomBytes} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../../',import.meta.url)),base=path.join(root,'work/multiplayer-combat'),original=path.join(base,'2026-09-28T14-32-48.454Z'),buildDir=path.resolve(process.env.FRONTLINE_HISTORY_BUILD??path.join(base,'build-history-recovery')),product=path.join(buildDir,'product'),out=path.join(base,'history-recovery-'+new Date().toISOString().replaceAll(':','-')),data=path.join(out,'data');await mkdir(data,{recursive:true});
const sha=bytes=>createHash('sha256').update(bytes).digest('hex'),old=JSON.parse(await readFile(path.join(original,'browser.json'),'utf8')),match=old.cases[0],profile=match.profiles[0],matchID=match.result.matchId,db=path.join(original,'host-3h-data/frontline.db'),replayFile=path.join(original,`host-3h-data/objects/${matchID}.replay`),dbSHA=sha(await readFile(db)),replaySHA=sha(await readFile(replayFile));
let token=randomBytes(32).toString('hex');
const credentialSetup=JSON.parse(execFileSync('python3',['-c',`import sqlite3,sys,hashlib,json
source=sqlite3.connect('file:'+sys.argv[1]+'?mode=ro',uri=True); copy=sqlite3.connect(sys.argv[2]);source.backup(copy)
secret=sys.stdin.read(); changed=copy.execute('UPDATE profiles SET token_hash=? WHERE id=?',(hashlib.sha256(secret.encode()).hexdigest(),sys.argv[3])).rowcount;copy.commit();assert changed==1
checks={}
for (name,) in source.execute("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name"):
 columns=[r[1] for r in source.execute('PRAGMA table_info("'+name+'")')];columns=[x for x in columns if not(name=='profiles' and x=='token_hash')];query='SELECT '+','.join('"'+x+'"' for x in columns)+' FROM "'+name+'"';a=source.execute(query).fetchall();b=copy.execute(query).fetchall();assert a==b,name;checks[name]=len(a)
print(json.dumps({'reissued_test_profile':sys.argv[3],'unchanged_table_rows_except_token_hash':checks}));copy.close();source.close()`,db,path.join(data,'frontline.db'),profile],{input:token,encoding:'utf8'}));
await cp(path.join(original,'host-3h-data/objects'),path.join(data,'objects'),{recursive:true});const script=await readFile(new URL(import.meta.url));await writeFile(path.join(out,'driver.mjs'),script);
const report={started:new Date().toISOString(),scope:'Earned3H data on a copied restarted host, one test token hash reissued only. Actual product profile restore/history/archive; separate explicitly labeled retained-client memory fixture polls real host. No live simulation or replacement/fabricated final snapshot. Browser plugin unavailable; Playwright fallback.',build:JSON.parse(await readFile(path.join(buildDir,'build.json'),'utf8')),originalDBSHA256:dbSHA,replaySHA256:replaySHA,driverSHA256:sha(script),credentialSetup,checks:[],errors:[],httpErrors:[]};
const json=value=>JSON.stringify(value,(_key,v)=>typeof v==='bigint'?v.toString():v,2),sleep=ms=>new Promise(r=>setTimeout(r,ms));async function until(fn,message,timeout=30000){const start=Date.now();while(!await fn()){if(Date.now()-start>timeout)throw Error(message);await sleep(100)}}
const child=spawn(path.join(buildDir,'frontline'),['-addr','127.0.0.1:0','-data',data,'-static',product,'-maps',path.join(product,'content/maps'),'-missions',path.join(product,'content/missions')],{cwd:root,stdio:['ignore','pipe','pipe']});let hostLog='';const origin=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error('Host startup timed out')),30000);child.stdout.on('data',b=>{hostLog+=b;const found=hostLog.match(/http:\/\/127\.0\.0\.1:\d+/);if(found){clearTimeout(timeout);resolve(found[0])}});child.stderr.on('data',b=>hostLog+=b);child.once('exit',code=>reject(Error('Host startup exit '+code)))});report.origin=origin;
const browser=await chromium.launch({headless:true}),contexts=[];report.browser=browser.version();let page,retained;
function observe(p,scope){p.on('pageerror',error=>report.errors.push({scope,kind:'pageerror',message:error.message,stack:error.stack}));p.on('console',message=>{if(message.type()==='error')report.errors.push({scope,kind:'console',message:message.text(),location:message.location()})});p.on('response',async response=>{if(response.status()<400)return;const entry={scope,path:new URL(response.url()).pathname,status:response.status()};report.httpErrors.push(entry);try{const v=await response.json();entry.code=v.code}catch{}})}
async function capture(p,name){await p.screenshot({path:path.join(out,name+'.png')});await writeFile(path.join(out,name+'.dom.txt'),await p.locator('body').innerText())}
async function idle(p){await until(async()=>await p.locator('.network-operation,.loading-screen').count()===0,'UI stayed busy',120000);assert.equal(await p.locator('.network-error').count(),0)}
function check(name,values={}){report.checks.push({name,...values});console.log(name)}
try{
 const context=await browser.newContext({viewport:{width:1600,height:900}});contexts.push(context);page=await context.newPage();observe(page,'product');page.setDefaultTimeout(30000);await page.goto(origin);assert.equal(await page.title(),'Frontline Command');await page.getByRole('button',{name:'Explore game modes',exact:true}).click();await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(page);await page.getByRole('button',{name:'Restore an existing token',exact:true}).click();await page.getByLabel('Local profile token',{exact:true}).fill(token);await page.getByRole('button',{name:'Restore profile',exact:true}).click();await idle(page);assert.equal(await page.getByLabel('Your profile ID').inputValue(),profile);check('Ordinary product profile restore on restarted copied host');
 await page.getByRole('button',{name:'Load recorded operations',exact:true}).click();await idle(page);const row=page.locator(`[data-match-id="${matchID}"]`);assert.equal(await row.count(),1);await row.getByRole('button',{name:'View recorded result',exact:true}).click();assert.match(await row.innerText(),/Team 2 victorious/);assert.match(await row.innerText(),/elimination/);await capture(page,'recorded-result-1600');check('Actual authenticated history exposes earned result without a lobby');
 await row.getByRole('button',{name:'Save match replay',exact:true}).click();await idle(page);let saved;await until(async()=>!!(saved=await page.evaluate(()=>window.multiplayerCombat.replay())),'Replay was not archived',120000);assert.equal(saved.sha256,replaySHA);assert.equal(sha(Buffer.from(saved.data)),replaySHA);check('Normal replay download and Go inspector archive exact earned bytes',{bytes:saved.data.length,sha256:saved.sha256});await page.setViewportSize({width:1280,height:720});await capture(page,'recorded-result-1280');
 await page.getByRole('button',{name:'Sign out',exact:true}).click();await idle(page);assert.equal((await page.evaluate(()=>window.multiplayerCombat.replay())).sha256,replaySHA);if(await page.getByRole('button',{name:'Create a new profile',exact:true}).count())await page.getByRole('button',{name:'Create a new profile',exact:true}).click();await page.getByLabel('Commander name',{exact:true}).fill('Separate history profile');await page.getByRole('button',{name:'Create local profile',exact:true}).click();await idle(page);assert.notEqual(await page.getByLabel('Your profile ID').inputValue(),profile);await page.getByRole('button',{name:'Load recorded operations',exact:true}).click();await idle(page);assert.equal(await page.locator('[data-match-id]').count(),0);await page.getByText('No recorded operations for this profile.',{exact:true}).waitFor();await capture(page,'profile-isolation');check('Different real profile sees no prior result; browser replay survives sign-out');await context.close();contexts.pop();
 const ctx=await browser.newContext({viewport:{width:1280,height:720}});contexts.push(ctx);retained=await ctx.newPage();observe(retained,'retained-client');await retained.goto(origin+'/tests/render/retained-result-fixture.html');const frozen=JSON.parse(await readFile(path.join(original,'3h-failure-view-1.json'),'utf8')),frozenString=JSON.stringify(frozen),lobby=match.clients[0].final.info.lobby;
 await retained.evaluate(input=>window.retainedResult.start(input),{host:origin,token,lobby,frozen});token='';await retained.getByText('Recorded result recovered',{exact:true}).waitFor();const recovered=await retained.evaluate(()=>window.retainedResult.inspect());assert.equal(recovered.frozen,frozenString);assert.equal(recovered.tick,9020);assert.equal(recovered.result.outcome.tick,16074);assert.equal(recovered.lobbyUnavailable,true);assert.equal(recovered.connection,'closed');await retained.getByRole('region',{name:'Recorded match result',exact:true}).waitFor();await capture(retained,'frozen-result-cue');check('Automatic retained-lobby poll observes real404, recovers exact durable history, leaves own tick9020 unchanged');
 const cue=retained.getByRole('button',{name:'View result and replay',exact:true});await cue.focus();await retained.keyboard.press('Enter');await retained.getByRole('dialog',{name:'Network operation',exact:true}).waitFor();await retained.getByText('Team 2 victorious · elimination',{exact:true}).waitFor();await retained.getByRole('button',{name:'Save match replay',exact:true}).click();await idle(retained);await until(async()=>(await retained.evaluate(()=>window.retainedResult.replay()))?.sha256===replaySHA,'Retained menu did not archive exact replay',120000);await capture(retained,'retained-result-menu');check('Keyboard result cue opens normal network menu and archives exact replay');await retained.getByRole('button',{name:'Return to frozen view',exact:true}).click();assert.equal((await retained.evaluate(()=>window.retainedResult.inspect())).frozen,frozenString);await retained.evaluate(()=>window.retainedResult.dispose());
 assert.equal(report.httpErrors.length,1);assert.equal(report.httpErrors[0].code,'lobby_missing');assert.equal(report.errors.length,1);assert.equal(report.errors[0].kind,'console');assert.equal(report.errors[0].scope,'retained-client');assert.match(report.errors[0].message,/404/);assert.equal(await page?.isClosed(),true);check('Only expected missing-lobby404 retained; no page or unrelated console/HTTP errors');report.status='passed';
}catch(error){report.status='failed';report.failure=String(error.stack??error);process.exitCode=1;for(const [name,p] of [['product-failure',page],['retained-failure',retained]])if(p&&!p.isClosed())await capture(p,name).catch(()=>{})}
finally{token='';for(const c of contexts)await c.close();await browser.close();if(child.exitCode===null){const ended=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await ended}report.originalUnchanged={database:sha(await readFile(db))===dbSHA,replay:sha(await readFile(replayFile))===replaySHA};if(!report.originalUnchanged.database||!report.originalUnchanged.replay){report.status='failed';process.exitCode=1}report.completed=new Date().toISOString();await writeFile(path.join(out,'browser.json'),json(report));await writeFile(path.join(out,'host.log'),hostLog);console.log(report.status,out)}
