// Host-specific browser load/parity baseline, not Intel/Safari certification.
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,mkdtemp,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {tmpdir,cpus,totalmem,platform,release} from 'node:os';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import path from 'node:path';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {chromium} from 'playwright-core';
const root=fileURLToPath(new URL('../../../',import.meta.url)),out=process.env.FRONTLINE_LOAD_OUTPUT??path.join(root,'work/evidence/browser-load'),fixture=path.join(root,'work/evidence/browser-load'),frozen=process.env.FRONTLINE_LOAD_PRODUCT??path.join(root,'work/evidence/rendered-multiplayer/build-terminal/product'),temp=await mkdtemp(path.join(tmpdir(),'frontline-load-'));await mkdir(out,{recursive:true});
await build({entryPoints:[path.join(root,'client/tests/render/load-fixture.ts')],outfile:path.join(temp,'main.js'),bundle:true,format:'esm',platform:'browser',target:'es2022'});
const headed=process.env.FRONTLINE_LOAD_HEADED==='1';
const mime={'.js':'text/javascript','.json':'application/json','.wasm':'application/wasm','.png':'image/png','.svg':'image/svg+xml'},digest=bytes=>createHash('sha256').update(bytes).digest('hex');
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://local'),p=decodeURIComponent(url.pathname);if(p.split('/').some(s=>s==='..'))throw Error('badpath');if(p==='/'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Maximum Go browser load</title><link rel="icon" href="data:,"><style>html,body,#field{margin:0;width:100%;height:100%;overflow:hidden}</style><div id="field"></div><script type="module" src="/main.js"></script>');return}const file=p==='/main.js'?path.join(temp,'main.js'):p.startsWith('/fixture/')?path.join(fixture,p.slice(9)):path.join(frozen,p);res.setHeader('Content-Type',mime[path.extname(file)]??'application/octet-stream');res.end(await readFile(file))}catch(error){res.statusCode=404;res.end(String(error))}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:!headed,...(headed?{channel:'chromium'}:{})}),page=await browser.newPage({viewport:{width:1600,height:900}}),cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');
const report={time:new Date().toISOString(),headed,browser:browser.version(),host:{os:platform(),release:release(),cpu:cpus()[0].model,logicalCPUs:cpus().length,memory:totalmem()},scope:'688 Go actors,64 aircraft return,336 scouts moving;natural authorized perspective. Two consecutive30-second synthetic segments, not long matches. Four-tick manual batches reproduce5Hz snapshot delivery; reported RPC cost includes Go/protobuf/IPC/render update, not isolated tick time. Graphics backend recorded per segment; shared-host functional/performance evidence with incomplete art. No reference hardware FPS claim.',artBuild:JSON.parse(await readFile(path.join(frozen,'../build.json'),'utf8')),sha256:{bundle:digest(await readFile(path.join(temp,'main.js'))),opening:digest(await readFile(path.join(fixture,'opening.json'))),wasm:digest(await readFile(path.join(frozen,'runtime/frontline.wasm')))},errors:[],warnings:[],segments:[]};
page.on('pageerror',error=>report.errors.push(String(error)));page.on('console',message=>{if(message.type()==='error')report.errors.push(message.text());if(message.type()==='warning')report.warnings.push(message.text())});
try{await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>document.body.dataset.ready==='true');for(let i=0;i<2;i++){const value=await page.evaluate(i=>window.qa.run(i),i);assert.deepEqual(value.errors,[]);if(headed)assert(value.graphics.unmaskedRenderer&&!/SwiftShader|llvmpipe/i.test(value.graphics.unmaskedRenderer),'Headed run did not obtain hardware graphics');value.pageHeap=Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.filter(m=>['JSHeapUsedSize','JSHeapTotalSize','Documents','Nodes'].includes(m.name)).map(m=>[m.name,m.value]));await page.screenshot({path:path.join(out,`segment-${i+1}.png`)});value.disposal=await page.evaluate(()=>window.qa.dispose());assert.equal(value.disposal.canvases,0);assert.equal(value.disposal.art.residentPages,0);report.segments.push(value);console.log(JSON.stringify(value))}assert.deepEqual(report.errors,[]);report.status='passed'}catch(error){report.status='failed';report.error=String(error.stack??error);process.exitCode=1;await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{})}finally{await writeFile(path.join(out,'browser.json'),JSON.stringify(report,null,2));await browser.close();await new Promise(resolve=>server.close(resolve));await rm(temp,{recursive:true,force:true});console.log(report.status,report.error??'')}
