// Bounded diagnostic, not a whole-match acceptance or replacement for its failure.
import assert from 'node:assert/strict';
import {chromium} from 'playwright-core';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
import {MatrixCommander} from './multiplayer-v24-contract.mjs';
import {installConsumedBodyCDP,reconcileConsumedBodies,explicitControlDiagnostics} from './native-consumed-body-cdp.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),sha=b=>createHash('sha256').update(b).digest('hex');
const prepared=path.join(root,'work/multiplayer-combat/v24-34-prepared-02'),product=path.join(prepared,'product'),bodyBuild=path.resolve(process.env.FRONTLINE_BODY_BUILD??path.join(root,'work/multiplayer-combat/readiness-trace-build-01'));
const out=path.resolve(process.env.FRONTLINE_BODY_OUT??path.join(root,'work/multiplayer-combat/readiness-trace-'+new Date().toISOString().replaceAll(':','-')));await mkdir(out);
const build=JSON.parse(await readFile(path.join(prepared,'build.json'))),diagnosticBuild=JSON.parse(await readFile(path.join(bodyBuild,'build.json'))),executable=path.join(root,'work/tools/browsers/20260929-prerequisites/apps/Google Chrome.app/Contents/MacOS/Google Chrome');
const staticPaths=['/art/sprites/unit.IR.strike/unit.IR.strike.sprite.json','/art/sprites/unit.SY.elite/unit.SY.elite@1x.beauty.json','/art/sprites/unit.SA.hauler/unit.SA.hauler@1x.beauty.4.png','/art/sprites/unit.US.fighter/unit.US.fighter@1x.beauty.8.png'];
const controls=['valid','network','truncated','wrong-hash','redirect','cancel'],controlBody='Native consumed-body integrity control.\n',controlPaths=controls.map(k=>'/__diagnostics__/body-proof/'+k);
const expectedFiles=[];for(const p of staticPaths){const b=await readFile(path.join(product,p));expectedFiles.push({path:p,bytes:b.length,sha256:sha(b)})}
assert.equal(diagnosticBuild.sourceLockSHA256,build.sourceLockSHA256);assert.equal(sha(await readFile(path.join(bodyBuild,'diagnostic-host.test'))),diagnosticBuild.files['diagnostic-host.test'].sha256);assert.equal(sha(await readFile(path.join(product,'runtime/frontline.wasm'))),build.sha256.wasm);
const helpers=['multiplayer-readiness-trace.browser.mjs','native-consumed-body-trace.mjs','native-consumed-body-cdp.mjs','native-response-cdp.mjs','native-response-trace.mjs','multiplayer-v24-contract.mjs','expansion-commander.mjs'],sourceFiles={};for(const name of helpers){const b=await readFile(new URL(name,import.meta.url));sourceFiles[name]=sha(b);await writeFile(path.join(out,name),b)}
const report={started:new Date().toISOString(),scope:'Actual immutable v24 four-faction readiness and a small paid opening, plus separate native HTTP fault controls. Diagnostic host observes successful advice Write bytes only. Selected original JS chunks/EOF are observed and hashed without extra fetch/read/clone, retry or production mutation; observation has overhead, no performance claim. Original long FFA strict failure is unchanged.',build:build.sha256,diagnosticBuild,sourceFiles,expectedFiles,executable:{path:executable,sha256:sha(await readFile(executable))},errors:[],consoleErrors:[],httpErrors:[],requestFailures:[],commands:[],negativeControls:[]};
const {fromBinary,EnvelopeSchema,applyDelta}=await import(pathToFileURL(path.join(prepared,'decode.mjs')));const map=JSON.parse(await readFile(path.join(product,'content/maps/industrial-valley.json')));
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms)),json=v=>JSON.stringify(v,(_k,x)=>typeof x==='bigint'?x.toString():x,2);
let phase='setup',browser,context,page,host,collector,origin,hostLog='',view;const receipts=new Map();
async function until(fn,message,ms=90000){const start=Date.now();while(!await fn()){if(Date.now()-start>ms)throw Error(message);await sleep(150)}}
async function idle(){await until(async()=>await page.locator('.network-operation,.loading-screen').count()===0,'App remained busy',120000);assert.equal(await page.locator('.network-error').count(),0)}
async function capture(name){await page.screenshot({path:path.join(out,name+'.png')})}
try{
 const data=path.join(out,'host-data');await mkdir(data);host=spawn(path.join(bodyBuild,'diagnostic-host.test'),['-addr','127.0.0.1:0','-data',data,'-static',product,'-maps',path.join(product,'content/maps'),'-missions',path.join(product,'content/missions'),'-body-trace',path.join(out,'server-advice.jsonl')],{cwd:root,env:{...process.env,GOMAXPROCS:'1',FRONTLINE_NATIVE_BODY_HOST:'1'},stdio:['ignore','pipe','pipe']});
 report.hostPID=host.pid;const exit=new Promise(resolve=>{host.once('exit',(code,signal)=>resolve({code,signal}));host.once('error',error=>{report.errors.push({phase:'host-spawn',message:String(error)});resolve({error:String(error)})})});host.closed=exit;
 host.stdout.on('data',b=>{hostLog+=b});host.stderr.on('data',b=>{hostLog+=b});await until(()=>{origin=hostLog.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];return !!origin},'Diagnostic host did not start',30000);report.origin=origin;
 browser=await chromium.launch({executablePath:executable,headless:false});report.browser=browser.version();context=await browser.newContext({viewport:{width:1600,height:900}});page=await context.newPage();page.setDefaultTimeout(90000);
 collector=await installConsumedBodyCDP(page,{caseId:'readiness-paid-opening',origin,paths:[...staticPaths,...controlPaths],stamp:()=>({phase})});await writeFile(path.join(out,'observer-source.js'),collector.source);
 page.on('pageerror',e=>report.errors.push({phase,message:e.message,stack:e.stack}));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({phase,message:m.text(),location:m.location()})});page.on('requestfailed',r=>report.requestFailures.push({phase,url:r.url(),message:r.failure()?.errorText}));page.on('response',r=>{if(r.status()>=400)report.httpErrors.push({phase,url:r.url(),status:r.status()})});
 page.on('websocket',socket=>socket.on('framereceived',frame=>{if(typeof frame.payload==='string')return;try{const m=fromBinary(EnvelopeSchema,new Uint8Array(frame.payload)).message;if(m.case==='snapshot')view=m.value;else if(m.case==='delta')view=applyDelta(view,m.value);else if(m.case==='orderResult')receipts.set(`${m.value.sequence}:${m.value.index}`,m.value);if(['snapshot','delta'].includes(m.case)){for(const r of view.results)receipts.set(`${r.sequence}:${r.index}`,r);for(const e of view.entities)assert(!e.private||e.owner===view.player,'Foreign private state')}}catch(error){report.errors.push({phase,message:String(error)})}}));
 phase='readiness';await page.goto(origin);assert.equal(await page.title(),'Frontline Command');await page.getByRole('button',{name:'Explore game modes',exact:true}).click();await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle();
 await page.getByLabel('Commander name',{exact:true}).fill('Native body diagnostic');await page.getByRole('button',{name:'Create local profile',exact:true}).click();await page.getByLabel('Your profile ID').waitFor();await idle();
 await page.getByLabel('Operation name',{exact:true}).fill('Bounded readiness diagnostic');await page.getByLabel('Lobby battlefield',{exact:true}).selectOption('industrial-valley');await page.getByLabel('Battle format',{exact:true}).selectOption('ffa');await page.getByLabel('Host faction',{exact:true}).selectOption('US');await page.getByRole('button',{name:'Create operation',exact:true}).click();await idle();
 for(const faction of ['IR','SY','SA']){await page.getByLabel('Add AI faction',{exact:true}).selectOption(faction);await page.getByLabel('Add AI difficulty',{exact:true}).selectOption('normal');await page.getByRole('button',{name:'Add AI commander',exact:true}).click();await idle()}
 await page.getByLabel('Commander 1 faction',{exact:true}).selectOption('US');await idle();await page.getByRole('button',{name:'Ready to deploy',exact:true}).click();await idle();await until(()=>page.getByRole('button',{name:'Start operation',exact:true}).isEnabled(),'Readiness incomplete');await collector.capture('ready-boundary');await capture('ready');
 report.readyAssets=JSON.parse(await page.evaluate(()=>window.multiplayerCombat.info())).assets;
 await page.getByRole('button',{name:'Start operation',exact:true}).click();await page.getByRole('complementary',{name:'Command sidebar'}).waitFor();await page.locator('.scene-loading').waitFor({state:'hidden'});await until(()=>view?.tick>130,'Countdown incomplete');
 phase='paid-opening';const catalog=JSON.parse(await page.evaluate(()=>window.multiplayerCombat.catalog()));report.openingBefore=JSON.parse(await page.evaluate(()=>window.multiplayerCombat.view()));
 const commander=new MatrixCommander({player:1,map,catalog,view:()=>view,send:async(orders,note)=>{const tick=view.tick,sequence=await page.evaluate(orders=>window.multiplayerCombat.send(orders),orders);await until(()=>orders.every((_x,i)=>receipts.has(`${sequence}:${i}`)),'Missing actual receipt',10000);const results=orders.map((_x,i)=>receipts.get(`${sequence}:${i}`));report.commands.push({tick,note,sequence,orders,results});return results},advice:(ids,orders,independent)=>page.evaluate(({ids,orders,independent})=>window.multiplayerCombat.advice(ids,orders,independent),{ids,orders,independent})});
 const openingStart=Date.now();while(!view.entities.some(e=>e.owner===1&&e.type==='power'&&e.complete)){assert(Date.now()-openingStart<90000,'Paid power did not complete within bounded opening');await commander.step();await sleep(1800)}
 assert(report.commands.some(c=>c.orders.some((o,i)=>o.kind==='build'&&o.type==='power'&&c.results[i]?.accepted)),'No ordinary paid power receipt');report.openingAfter=JSON.parse(await page.evaluate(()=>window.multiplayerCombat.view()));assert.equal(view.outcome?.finished??false,false,'Bounded opening unexpectedly ended a match');
 phase='advice-sample';report.adviceSamples=[];for(let i=0;i<24;i++){const rig=view.entities.find(e=>e.owner===1&&e.type==='US.rig');assert(rig);const answer=await page.evaluate(id=>window.multiplayerCombat.advice([id],[],true),rig.id);report.adviceSamples.push({index:i,clientTick:view.tick,responseTick:answer.tick,keys:Object.keys(answer)});await sleep(300)}
 await collector.capture('paid-opening-complete');await capture('paid-opening');report.lifecycleBeforeMenu=await page.evaluate(()=>window.multiplayerCombat.lifetime());
 phase='menu-cleanup';await page.getByRole('button',{name:'Open pause menu',exact:true}).click();await page.getByRole('region',{name:'Online operation controls'}).first().waitFor();await page.getByRole('button',{name:'Return to command center',exact:true}).click();await until(async()=>{const x=await page.evaluate(()=>window.multiplayerCombat.lifetime());return x.phase==='menu'&&!x.transportPresent&&x.frameSubscribers===0},'Menu cleanup incomplete');report.menuLifetime=await page.evaluate(()=>window.multiplayerCombat.lifetime());await collector.capture('menu-boundary');await capture('menu');
 phase='explicit-negative-controls';
 for(const kind of controls){
  const url=new URL('/__diagnostics__/body-proof/'+kind+'?case=body-proof-'+kind,origin).href;
  const outcome=await page.evaluate(async({url,kind})=>{const controller=new AbortController();let response,reader,error,bytes=0;try{response=await fetch(url,{signal:controller.signal});reader=response.body.getReader();for(;;){const r=await reader.read();if(r.done)break;bytes+=r.value.byteLength;if(kind==='cancel')controller.abort()}}catch(e){error={name:e.name,message:e.message}}finally{reader?.releaseLock()}return{status:response?.status,redirected:response?.redirected,error,bytes}}, {url,kind});
  report.negativeControls.push({kind,url,...outcome});if(['network','truncated','cancel'].includes(kind))assert(outcome.error,`Missing real ${kind} rejection`);else assert.equal(outcome.error,undefined);
 }
 await collector.capture('all-controls-complete');report.courseStatus='completed';
}catch(error){report.courseStatus='failed';report.failure=String(error.stack??error);process.exitCode=1;if(page)await capture('failure').catch(()=>{})}
finally{
 phase='closing';if(collector)await collector.capture('before-context-close');await context?.close().catch(e=>report.errors.push({phase,message:String(e)}));await browser?.close().catch(e=>report.errors.push({phase,message:String(e)}));
 if(host){if(host.exitCode===null&&host.signalCode===null)host.kill('SIGTERM');report.hostExit=await host.closed}await writeFile(path.join(out,'host.log'),hostLog);
 report.closed=new Date().toISOString();if(collector){
  report.ledger=collector.ledger.snapshot();const serverText=await readFile(path.join(out,'server-advice.jsonl'),'utf8');report.serverAdvice=serverText.trim()?serverText.trim().split('\n').map(JSON.parse):[];
  const served=new Map(expectedFiles.map(r=>[new URL(r.path,origin).href,{bytes:r.bytes,sha256:r.sha256}]));for(const c of report.negativeControls)served.set(c.url,{bytes:Buffer.byteLength(controlBody),sha256:sha(controlBody)});
  report.reconciliation=reconcileConsumedBodies({snapshot:report.ledger,served,serverAdvice:report.serverAdvice});
  const counts=rs=>{const m=new Map();for(const r of rs){const k=JSON.stringify([r.url,r.message]);m.set(k,(m.get(k)??0)+1)}return [...m].sort()};report.diagnosticsAgree=JSON.stringify(counts(report.requestFailures))===JSON.stringify(counts(report.ledger.failures));
  report.rawDiagnosticStatus=report.ledger.failures.length?'raw-failures-retained':'no-raw-failures';
  report.explicitControlDiagnostics=explicitControlDiagnostics({controls:report.negativeControls,consoleErrors:report.consoleErrors,failures:report.ledger.failures});
  const provenIds=new Set(report.reconciliation.knownNativeReports.map(r=>r.requestId));report.unprovenOtherFailures=report.explicitControlDiagnostics.otherNetwork.filter(r=>!provenIds.has(r.requestId));
  report.controlProofs=report.negativeControls.map(c=>({kind:c.kind,native:c,proof:report.reconciliation.proofs.find(p=>p.native.url===c.url)}));
  try{assert.equal(report.diagnosticsAgree,true);assert.deepEqual(report.reconciliation.faults,[]);for(const c of report.controlProofs){assert(c.proof,'Missing control reader observation');assert.equal(c.proof.complete,c.kind==='valid',`Incorrect ${c.kind} integrity result`)}assert(report.reconciliation.proofs.some(p=>p.complete&&p.native.method==='GET'&&new URL(p.native.url).pathname.startsWith('/art/')),'No actual static native hash proof');assert(report.reconciliation.proofs.some(p=>p.complete&&p.native.method==='POST'),'No actual advice native/server hash proof');assert.equal(report.errors.length,0);assert.deepEqual(report.httpErrors,[]);assert.deepEqual(report.explicitControlDiagnostics.unexpectedConsole,[]);report.integrityStatus='passed'}catch(error){report.integrityStatus='failed';report.integrityFailure=String(error.stack??error);process.exitCode=1}
 }
 await writeFile(path.join(out,'browser.json'),json(report));console.log(json({out,courseStatus:report.courseStatus,integrityStatus:report.integrityStatus,rawDiagnosticStatus:report.rawDiagnosticStatus,raw:report.ledger?.failures.length,knownNativeReports:report.reconciliation?.knownNativeReports.length,failure:report.failure,integrityFailure:report.integrityFailure}));
}
