// CSS-only production-layout regression. Synthetic statuses/queues, actual UI
// selectors/fonts/chrome/build illustration. No game, fabricated progress or art.
import {chromium} from 'playwright-core';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const root=fileURLToPath(new URL('../../../',import.meta.url)),out=path.join(root,'work/evidence/production-cameo-layout'),product=path.join(root,'work/multiplayer-combat/build-advice-recovery/product');
await mkdir(out,{recursive:true});const before=await readFile(path.join(out,'before.css')),after=await readFile(path.join(root,'client/src/styles/game.css')),tokens=await readFile(path.join(root,'client/src/design/tokens.css'));
const cases=[{name:'Engineering rig',reason:'Wait: Queued.',state:'waiting'},{name:'Engineering rig',reason:'Options unavailable',state:'locked'},{name:'Precision missile carrier',reason:'Requires tier 3',state:'locked'},{name:'Special operations team',reason:'Insufficient supply',state:'locked'},{name:'Engineering rig',progress:42,state:'queued'},{name:'Tactical missile launcher',progress:75,state:'queued'},{name:'Strategic operations site',reason:'Construction prerequisites are not available yet.',state:'locked'},{name:'Engineering rig',state:'ready'}];
const icon='<svg class="icon" aria-hidden="true"><use href="/art/ui/icons/fc-icons.svg#i-lock"/></svg>';
const tiles=cases.map((item,index)=>`<button class="production-cameo" data-case="${index}" data-state="${item.state}" ${item.state==='locked'?'disabled':''} title="${item.name} · 800 credits${item.reason?' — '+item.reason:''}"><img class="cameo-art" src="/art/ui/icons/build/US.rig@2x.beauty.png" alt=""><span class="cameo-name">${item.name}</span><span class="cameo-price">800</span>${item.progress?'<span class="cameo-queue" aria-hidden="true">1</span><i class="cameo-progress" style="width:'+item.progress+'%"></i>':''}${item.reason?'<span class="disabled-reason">'+(item.state==='locked'?icon:'')+item.reason+'</span>':''}</button>`).join('');
const html=`<!doctype html><meta charset="utf-8"><title>Production tile layout fixture</title><link rel="icon" href="data:,"><link rel="stylesheet" href="/client/src/design/tokens.css"><link rel="stylesheet" href="/client/src/styles/game.css"><main class="battlefield-screen"><p style="margin:32px;max-width:520px">Synthetic production tile layout fixture. Actual styles, fonts and illustration; no simulation or gameplay completion claim.</p><aside class="command-sidebar console"><header class="sidebar-identity"><strong>PRODUCTION LAYOUT TEST</strong></header><div class="production-heading"><h2>Production</h2><span>FIXTURE</span></div><div class="production-body"><div class="power-gauge"><span>PWR</span><div><i style="height:20%"></i></div><small>0<br>40</small></div><div class="cameo-grid">${tiles}</div></div><section class="production-queue"><h3>Synthetic states only</h3></section></aside></main>`;
const mime={'.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.ttf':'font/ttf'},sha=bytes=>createHash('sha256').update(bytes).digest('hex');let variant='after';
const server=createServer(async(req,res)=>{try{const p=decodeURIComponent(new URL(req.url,'http://local').pathname);if(p.split('/').includes('..'))throw Error('Invalid path');let data;if(p==='/'){res.setHeader('Content-Type','text/html');data=html}else if(p==='/client/src/styles/game.css')data=variant==='before'?before:after;else if(p==='/client/src/design/tokens.css')data=tokens;else data=await readFile(p.startsWith('/assets/fonts/')?path.join(root,p):path.join(product,p));res.setHeader('Content-Type',p==='/'?'text/html':mime[path.extname(p)]??'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(data)}catch(error){res.statusCode=404;res.end(String(error))}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true}),report={started:new Date().toISOString(),browser:browser.version(),scope:'CSS-only synthetic state fixtures; actual current product selectors/styles and frozen existing art. Browser plugin unavailable; Playwright fallback. Not a gameplay or performance course.',sha256:{before:sha(before),after:sha(after),tokens:sha(tokens),app:sha(await readFile(path.join(root,'client/src/ui/App.tsx')))},cases:[],errors:[]};
try{
 for(variant of ['before','after'])for(const [width,height,scale] of [[1280,720,1],[1600,900,1],[1280,720,1.5],[1600,900,1.5]]){
  const page=await browser.newPage({viewport:{width,height}});page.on('pageerror',error=>report.errors.push(String(error)));page.on('console',message=>{if(message.type()==='error')report.errors.push(message.text())});await page.goto(`http://127.0.0.1:${server.address().port}`);assert.equal(await page.title(),'Production tile layout fixture');assert.equal(await page.locator('.production-cameo').count(),cases.length);await page.evaluate(async scale=>{document.documentElement.style.setProperty('--fc-ui-scale',String(scale));await document.fonts.ready;await Promise.all([...document.images].map(image=>image.decode()))},scale);
  const dimensions=await page.locator('.production-cameo').evaluateAll(tiles=>tiles.map(tile=>{const rect=selector=>{const node=tile.querySelector(selector);if(!node)return;const r=node.getBoundingClientRect();return {top:r.top,bottom:r.bottom,left:r.left,right:r.right,height:r.height}};return {name:tile.querySelector('.cameo-name').textContent,title:tile.title,nameRect:rect('.cameo-name'),reason:rect('.disabled-reason'),price:rect('.cameo-price'),progress:rect('.cameo-progress'),tile:rect('.cameo-art')}}));
  const failures=[];for(const [index,d] of dimensions.entries()){if(d.reason&&d.reason.bottom>d.nameRect.top+.5)failures.push({index,kind:'reason-name-overlap',pixels:d.reason.bottom-d.nameRect.top});if(d.progress&&d.progress.bottom>d.nameRect.top+.5)failures.push({index,kind:'progress-name-overlap',pixels:d.progress.bottom-d.nameRect.top});if(d.reason&&d.price.bottom>d.reason.top+.5)failures.push({index,kind:'price-reason-overlap',pixels:d.price.bottom-d.reason.top});if(cases[index].reason&&!d.title.includes(cases[index].reason))failures.push({index,kind:'full-reason-lost'})}
  const id=`${variant}-${width}-${height}-${Math.round(scale*100)}`;await page.screenshot({path:path.join(out,id+'.png')});const last=page.locator('.production-cameo').last();await last.scrollIntoViewIfNeeded();await last.focus();await page.locator('.cameo-grid').hover();await page.mouse.wheel(0,1000);await page.waitForFunction(()=>{const node=document.querySelector('.production-cameo:last-child'),r=node.getBoundingClientRect(),s=node.closest('.cameo-grid').getBoundingClientRect();return r.top>=s.top-1&&r.bottom<=s.bottom+1},{},{timeout:2000}).catch(async error=>{throw Error(error.message+' '+JSON.stringify(await last.evaluate(node=>{const r=node.getBoundingClientRect(),grid=node.closest('.cameo-grid'),s=grid.getBoundingClientRect();return {tile:r.toJSON(),grid:s.toJSON(),scrollTop:grid.scrollTop,scrollHeight:grid.scrollHeight,clientHeight:grid.clientHeight}})))});assert.equal(await last.evaluate(node=>document.activeElement===node),true);const lastVisible=await last.evaluate(node=>{const r=node.getBoundingClientRect(),s=node.closest('.cameo-grid').getBoundingClientRect();return r.top>=s.top-1&&r.bottom<=s.bottom+1});assert(lastVisible,'Last tile must remain reachable in the existing scroller');if(scale===1.5)await page.screenshot({path:path.join(out,id+'-scrolled.png')});report.cases.push({id,width,height,scale,dimensions,failures,lastTileReached:true});await page.close();if(variant==='after')assert.deepEqual(failures,[],id);
 }
 assert(report.cases.filter(item=>item.id.startsWith('before')).some(item=>item.failures.length),'Original overlap must reproduce');assert.deepEqual(report.errors,[]);report.status='passed';
}catch(error){report.status='failed';report.error=String(error.stack??error);process.exitCode=1}
finally{report.completed=new Date().toISOString();await writeFile(path.join(out,'browser.json'),JSON.stringify(report,null,2)+'\n');await browser.close();await new Promise(resolve=>server.close(resolve));console.log(report.status,report.error??'',out)}
