// Browser plugin unavailable. Small Playwright component course; no host,
// simulation, credentials or frozen comparison build is modified.
import {chromium} from 'playwright-core';
import {build} from 'esbuild';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../../',import.meta.url)),out=path.join(root,'work/multiplayer-combat/session-status-'+new Date().toISOString().replaceAll(':','-')),original=path.join(root,'work/multiplayer-combat/2026-09-28T15-55-02.270Z'),art=path.join(root,'work/multiplayer-combat/build-optimized-recovery/product');await mkdir(out,{recursive:true});
const sha=b=>createHash('sha256').update(b).digest('hex'),driver=await readFile(new URL(import.meta.url)),old=JSON.parse(await readFile(path.join(original,'browser.json'),'utf8')).cases[0],frozenBytes=await readFile(path.join(original,'4h2v2-failure-view-1.json')),finishedBytes=await readFile(path.join(original,'4h2v2-failure-view-2.json')),input={frozen:JSON.parse(frozenBytes),finished:JSON.parse(finishedBytes),result:old.result,lobby:old.clients[0].final.info.lobby};
assert.equal(input.frozen.tick,11138);assert.equal(input.frozen.players.find(p=>p.id===1).defeated,true);assert.equal(input.frozen.outcome.finished,false);assert.equal(input.finished.outcome.finished,true);assert.equal(input.finished.tick,13475);
await writeFile(path.join(out,'driver.mjs'),driver);
const files=['src/app/session-presentation.ts','src/ui/BattlefieldStatus.tsx','src/ui/App.tsx','src/ui/network/index.tsx','src/design/tokens.css','src/styles/game.css','src/ui/network/network.css','tests/render/session-status-fixture.tsx'];const sources=[];
for(const file of files){const bytes=await readFile(path.join(root,'client',file));sources.push({path:file,sha256:sha(bytes),bytes:bytes.length});const copy=path.join(out,'source',file);await mkdir(path.dirname(copy),{recursive:true});await copyFile(path.join(root,'client',file),copy)}
await build({entryPoints:[path.join(root,'client/tests/render/session-status-fixture.tsx')],outfile:path.join(out,'fixture.js'),bundle:true,format:'esm',platform:'browser',target:'es2022',sourcemap:true,jsx:'automatic',loader:{'.ttf':'file','.png':'file','.woff2':'file'},external:['/art/*'],plugins:[{name:'snapshot-css',setup(builder){builder.onLoad({filter:/\.css$/},async args=>{const bytes=await readFile(args.path),relative=path.relative(path.join(root,'client'),args.path),copy=path.join(out,'source',relative);await mkdir(path.dirname(copy),{recursive:true});await writeFile(copy,bytes);const entry={path:relative,sha256:sha(bytes),bytes:bytes.length},index=sources.findIndex(value=>value.path===relative);if(index<0)sources.push(entry);else sources[index]=entry;return {contents:bytes.toString(),loader:'css',resolveDir:path.dirname(args.path)}})}}]});
const html='<!doctype html><html><head><meta charset="UTF-8"><link rel="icon" href="data:,"><title>Frontline session status acceptance</title><link rel="stylesheet" href="/fixture.css"></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>';
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://fixture');let file=url.pathname==='/'?undefined:path.resolve(url.pathname.startsWith('/art/')||url.pathname.startsWith('/assets/')?art:out,'.'+url.pathname);if(file&&!file.startsWith(art+path.sep)&&!file.startsWith(out+path.sep))throw Error('path');const bytes=file?await readFile(file):Buffer.from(html);res.setHeader('Content-Type',!file?'text/html':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream');res.end(bytes)}catch{res.statusCode=404;res.end('missing')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
const report={started:new Date().toISOString(),origin,scope:'Actual production badge and NetworkMatchPanel over immutable earned4H frozen/winner snapshots. Explicit synthetic stale MatchStatus. No live simulation, server, result creation or multiplayer acceptance.',browserPath:'Browser plugin not available; existing Playwright fallback',driverSHA256:sha(driver),sources,original:{directory:path.relative(root,original),frozenSHA256:sha(frozenBytes),finishedSHA256:sha(finishedBytes)},checks:[],errors:[]};
const browser=await chromium.launch({headless:true});report.browser=browser.version();let page;
try{for(const [width,height,scale] of [[1600,900,1],[1280,720,1],[1600,900,1.5],[1280,720,1.5]]){const context=await browser.newContext({viewport:{width,height}});page=await context.newPage();page.on('pageerror',e=>report.errors.push({kind:'pageerror',message:e.message,stack:e.stack}));page.on('console',m=>{if(m.type()==='error')report.errors.push({kind:'console',message:m.text()})});page.on('response',r=>{if(r.status()>=400)report.errors.push({kind:'http',status:r.status(),path:new URL(r.url()).pathname})});await page.goto(origin);assert.equal(await page.title(),'Frontline session status acceptance');await page.evaluate(({value,scale})=>{document.documentElement.style.setProperty('--fc-ui-scale',String(scale));window.sessionStatusFixture.start(value)},{value:input,scale});await page.getByRole('heading',{name:'Session status acceptance'}).waitFor();const originalFrozen=await page.evaluate(()=>window.sessionStatusFixture.frozen());const badge=page.locator('.live-led');assert.equal(await badge.innerText(),'FROZEN');assert.match(await badge.getAttribute('aria-label'),/no live battlefield updates/);await page.getByRole('button',{name:'Toggle operation menu',exact:true}).click();await page.getByRole('dialog',{name:'Network operation'}).waitFor();assert.equal(await page.getByText('Commander 1: connected',{exact:true}).count(),0);assert.equal(await page.getByText(/^Pause votes:/).count(),0);assert.match(await page.locator('.network-connection-line').innerText(),/Last update · 09:16/);const tag=width+'-'+Math.round(scale*100);await page.screenshot({path:path.join(out,'eliminated-'+tag+'.png')});await page.getByRole('button',{name:'result',exact:true}).click();await page.getByText('RESULT RECORDED',{exact:true}).waitFor();assert.equal(await badge.innerText(),'FROZEN');assert.match(await page.locator('.network-connection-line').innerText(),/Result time · 11:13/);assert.equal(await page.getByRole('button',{name:'Save match replay',exact:true}).count(),1);assert.equal(await page.getByText('Commander 1: connected',{exact:true}).count(),0);await page.screenshot({path:path.join(out,'recorded-'+tag+'.png')});
 for(const [mode,label] of [['finished','ENDED'],['observer','OBSERVER'],['replay','REPLAY'],['paused','FROZEN']]){await page.getByRole('button',{name:mode,exact:true}).click();await page.waitForFunction(expected=>document.querySelector('.live-led')?.textContent===expected,label);const bounds=await badge.boundingBox();assert(bounds&&bounds.x>=0&&bounds.x+bounds.width<=width);const geometry=await badge.evaluate(node=>({scroll:node.scrollWidth,client:node.clientWidth}));assert(geometry.scroll<=geometry.client+1)}await page.getByRole('button',{name:'eliminated',exact:true}).click();assert.equal(await page.evaluate(()=>window.sessionStatusFixture.frozen()),originalFrozen);report.checks.push({width,height,scale,labels:['FROZEN','ENDED','OBSERVER','REPLAY'],staleStatusHidden:true,sourceSnapshotUnchanged:true});await context.close()}
 assert.deepEqual(report.errors,[]);report.status='passed';
}catch(error){report.status='failed';report.failure=String(error.stack??error);process.exitCode=1;if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{})}
finally{await browser.close();await new Promise(r=>server.close(r));report.completed=new Date().toISOString();await writeFile(path.join(out,'browser.json'),JSON.stringify(report,null,2)+'\n');console.log(report.status,out)}
