import {minimapLayout,minimapProject} from '../../src/render/minimap.ts';
// Browser plugin not available. Existing Playwright exercises actual product controls.
// Read-only worker observation verifies public frames and submitted orders; no test API mutates the game.
import {chromium} from 'playwright-core';
import {build} from 'esbuild';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const compact=process.env.FRONTLINE_TUTORIAL_COMPACT==='1';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),client=path.join(root,'client'),out=path.join(root,compact?'work/evidence/tutorial-product-compact':'work/evidence/tutorial-product');await mkdir(out,{recursive:true});
await build({stdin:{contents:"export {fromBinary} from '@bufbuild/protobuf';export {PlayerSnapshotSchema,OrderBatchSchema} from './protocol/frontline_pb';",resolveDir:path.join(client,'src')},outfile:path.join(out,'decode.mjs'),bundle:true,platform:'node',format:'esm'});
const {fromBinary,PlayerSnapshotSchema,OrderBatchSchema}=await import(pathToFileURL(path.join(out,'decode.mjs'))),map=JSON.parse(await readFile(path.join(root,'content/maps/us-01-first-foothold-layout.json'),'utf8'));
const report={time:new Date().toISOString(),url:process.env.FRONTLINE_UI_URL??'http://127.0.0.1:5173',scope:'Actual first tutorial from original mission start; visible input lessons plus Go world objectives.',checks:{},errors:[],consoleErrors:[]};
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:compact?{width:1280,height:720}:{width:1600,height:900}});report.browser=browser.version();report.viewport=compact?{width:1280,height:720,scale:1.5}:{width:1600,height:900,scale:1};
page.on('pageerror',error=>report.errors.push(error.message));page.on('console',message=>{if(message.type()==='error')report.consoleErrors.push(message.text())});
await page.addInitScript(()=>{const Native=window.Worker;window.orderBytes=[];window.Worker=class extends Native{constructor(...args){super(...args);this.addEventListener('message',event=>{if(event.data.event==='frame')window.frameBytes=Array.from(event.data.bytes)});const post=this.postMessage;this.postMessage=function(message,...rest){if(message.method==='submit')window.orderBytes.push(Array.from(message.args[0]));return post.call(this,message,...rest)}}}});
async function snapshot(){const bytes=await page.evaluate(()=>window.frameBytes);return bytes?fromBinary(PlayerSnapshotSchema,new Uint8Array(bytes)):undefined}
async function until(check,label,timeout=45000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw Error(label);await new Promise(resolve=>setTimeout(resolve,150))}}
async function memory(){return page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('frontline-command');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,r=db.transaction('settings').objectStore('settings').getAll();r.onsuccess=()=>{db.close();resolve(r.result.find(record=>record.data?.mission==='tutorial-1-give-an-order')?.data.skills??[])};r.onerror=()=>reject(r.error)}}))}
let center;
async function centerAt(p){const box=await page.getByLabel('Tactical minimap').boundingBox();const projected=minimapProject(minimapLayout(map.width,map.height,box.width,box.height),p);await page.mouse.click(box.x+projected.x,box.y+projected.y);center={...p}}
async function screen(p,dy=0){const box=await page.locator('.battlefield-canvas canvas').boundingBox();return {x:box.x+box.width/2+(p.x-p.y-center.x+center.y)/1000*32,y:box.y+box.height/2+(p.x+p.y-center.x-center.y)/1000*16+dy}}
async function clickWorld(p,button='left',dy=0){const s=await screen(p,dy);await page.mouse.click(s.x,s.y,{button})}
async function selected(){return page.locator('.production-heading span').innerText()}
async function skill(name){await until(async()=>(await memory()).includes(name),'Input skill not recorded: '+name);report.checks[name]=true;console.log('Input',name)}
async function objective(name){await until(async()=>(await snapshot())?.mission?.objectives.find(value=>value.id===name)?.complete,'World objective incomplete: '+name,120000);report.checks[name]={tick:(await snapshot()).tick};console.log('Objective',name,report.checks[name])}
try{
 await page.goto(report.url);assert.equal(await page.title(),'Frontline Command');await page.getByRole('button',{name:'Explore game modes',exact:true}).click({timeout:60000});if(compact){await page.getByRole('button',{name:'Options',exact:true}).click();await page.getByLabel('Interface scale',{exact:true}).selectOption('1.5');await page.getByRole('button',{name:'Remap Stop',exact:true}).click();await page.keyboard.press('F7');await page.getByRole('button',{name:'Remap Set rally point',exact:true}).click();await page.keyboard.press('F6');report.checks.remapped='Stop F7, rally F6, interface150%';}await page.getByRole('button',{name:'Field training',exact:true}).click();await page.getByRole('button').filter({hasText:'Give an Order'}).click();await page.getByRole('button',{name:'Begin operation',exact:true}).click();await page.locator('.battlefield-canvas canvas').waitFor({timeout:60000});await page.locator('.scene-loading').waitFor({state:'hidden',timeout:60000});await page.locator('.countdown').waitFor({state:'hidden',timeout:15000});await page.getByRole('button',{name:'Locate First movement marker',exact:true}).waitFor();
 await page.getByRole('button',{name:'Hide training reminders',exact:true}).click();await page.getByRole('button',{name:'Show training reminders',exact:true}).click();assert.match(await page.getByRole('complementary',{name:'Training reminder',exact:true}).innerText(),/Left mouse selects/);report.checks.reopenReminder=true;await page.screenshot({path:path.join(out,'opening-guide.png')});await page.getByRole('button',{name:'Minimize mission objectives',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Locate First movement marker',exact:true}).count(),0);report.checks.minimizeObjectives=true;
 let frame=await snapshot(),rifles=frame.entities.filter(entity=>entity.owner===1&&entity.type==='US.rifle'),p={x:rifles.reduce((n,e)=>n+e.position.x,0)/rifles.length,y:rifles.reduce((n,e)=>n+e.position.y,0)/rifles.length};await centerAt(p);await clickWorld(rifles[0].position,'left',-15);await skill('single_select');
 const corners=await Promise.all(rifles.map(entity=>screen(entity.position)));const left=Math.min(...corners.map(p=>p.x))-40,right=Math.max(...corners.map(p=>p.x))+40,top=Math.min(...corners.map(p=>p.y))-60,bottom=Math.max(...corners.map(p=>p.y))+15;await page.mouse.move(left,top);await page.mouse.down();await page.mouse.move(right,bottom,{steps:12});await page.mouse.up();await skill('box_select');await page.locator('.unit-subgroups button').filter({hasText:/Ranger squad/i}).click();
 await page.getByRole('button',{name:'Show mission objectives',exact:true}).click();await page.getByRole('button',{name:'Locate First movement marker',exact:true}).click();center={x:32999,y:98499};await page.screenshot({path:path.join(out,'movement-marker.png')});await clickWorld(center,'right');await objective('move');assert.equal(await page.getByRole('button',{name:'Locate First movement marker',exact:true}).count(),0);
 await page.getByRole('button',{name:'Locate Second training marker',exact:true}).click();center={x:50499,y:82499};await page.keyboard.press('KeyA');await clickWorld(center);await objective('attack');
 await page.locator('.battlefield-canvas canvas').focus();if(compact)assert.match(await page.getByRole('complementary',{name:'Training reminder',exact:true}).innerText(),/F7/);await page.keyboard.press(compact?'F7':'KeyS');await skill('stop');await page.keyboard.press('Control+Digit1');await skill('group_store');await clickWorld({x:center.x-9000,y:center.y+7000});await page.keyboard.press('Digit1');await skill('group_recall');assert.match(await selected(),/4 SELECTED/);
 frame=await snapshot();const barracks=frame.entities.find(entity=>entity.owner===1&&entity.type==='barracks');await centerAt(barracks.position);await clickWorld(barracks.position,'left',-25);await until(async()=>/Barracks/i.test(await page.locator('.production-heading h2').innerText()),'Barracks not selected');if(compact)assert.match(await page.getByRole('complementary',{name:'Training reminder',exact:true}).innerText(),/F6/);await page.keyboard.press(compact?'F6':'KeyL');const rally={x:barracks.position.x+6500,y:barracks.position.y-3000};await clickWorld(rally);await skill('rally');
 // The Go pathfinder may legally adjust cliff-edge destinations; occupied construction is an actual rejected command.
 frame=await snapshot();const hq=frame.entities.find(entity=>entity.owner===1&&entity.type==='hq'),beforeCredits=frame.economy.credits;await centerAt(hq.position);await page.getByRole('button',{name:'Build',exact:true}).click();await page.locator('.production-cameo').filter({hasText:'Power station'}).click();await clickWorld(hq.position);await skill('rejected_order');assert.match(await page.locator('.notice').innerText(),/occupied|space|blocked/i);assert.equal((await snapshot()).economy.credits,beforeCredits);await page.locator('.targeting-hint').waitFor({state:'hidden'});report.checks.rejectedWithoutSpending=true;await page.screenshot({path:path.join(out,'blocked-order-feedback.png')});
 await centerAt(barracks.position);await clickWorld(barracks.position,'left',-25);await page.locator('.production-cameo').filter({hasText:'Ranger squad'}).click();await until(async()=>(await snapshot()).entities.filter(e=>e.owner===1&&e.type==='US.rifle').length>rifles.length,'Paid rifle production did not finish',60000);await until(async()=>(await snapshot())?.outcome?.finished,'Tutorial did not reach real victory',60000);await page.getByRole('dialog',{name:'Victory',exact:true}).waitFor();report.checks.victory={tick:(await snapshot()).tick,outcome:(await snapshot()).outcome.reason,skills:await memory()};assert.equal(report.checks.victory.outcome,'mission_complete');await page.screenshot({path:path.join(out,'tutorial-victory.png')});
 const submitted=await page.evaluate(()=>window.orderBytes);report.orderKinds=submitted.flatMap(bytes=>fromBinary(OrderBatchSchema,new Uint8Array(bytes)).orders.map(order=>order.kind));await page.getByRole('button',{name:'Command center',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Field training',exact:true}).click({timeout:60000});assert.match(await page.locator('.mission-row').first().innerText(),/Completed/);assert.deepEqual((await memory()).sort(),['box_select','group_recall','group_store','rally','rejected_order','single_select','stop']);report.checks.persistentLessonsAndVictory=true;
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.consoleErrors,[]);assert.equal(await page.locator('vite-error-overlay').count(),0);report.status='passed';
}catch(error){report.status='failed';report.error=String(error.stack??error);report.memory=await memory().catch(()=>[]);const frame=await snapshot();report.frame=frame?{tick:frame.tick,outcome:frame.outcome,objectives:frame.mission?.objectives}:undefined;await page.screenshot({path:path.join(out,'failure.png'),fullPage:true}).catch(()=>{});await writeFile(path.join(out,'failure.txt'),await page.locator('body').innerText().catch(()=>''));process.exitCode=1}
finally{await writeFile(path.join(out,'result.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify(report,null,2))}
