import {useEffect,useRef,useState,type FormEvent} from 'react';
import {NetworkController,type NetworkState} from '../../app/network-controller';
import {useObservable} from '../../app/store';
import {FACTIONS,formatClock} from '../../content/labels';
import type {ContentIndex} from '../../runtime/content-library';
import type {Lobby,LobbySlot} from '../../runtime/api';
import type {Difficulty,Faction} from '../../runtime/types';
import type {SaveSyncPreview,SyncDecision,SyncEntry,SyncSaveVersion,SyncSettingVersion} from '../../runtime/save-sync';
import {randomUUID} from '../../runtime/crypto';
import {Emblem,Icon,Empty} from '../primitives';
import './network.css';
import {NetworkMapPreview} from './map-preview';

type Props={controller:NetworkController};
const factions=Object.keys(FACTIONS) as Faction[];
const difficulties:Difficulty[]=['easy','normal','hard'];
const colors=['Crimson','Azure','Emerald','Gold','Violet','Orange','Teal','Ivory'];
function FactionOptions({random=true}:{random?:boolean}){return <>{random&&<option value="random">Random faction</option>}{factions.map(f=><option key={f} value={f}>{FACTIONS[f].name}</option>)}</>}
function Difficulties(){return <>{difficulties.map(value=><option key={value} value={value}>{value[0].toUpperCase()+value.slice(1)}</option>)}</>}
function Block({title,children,aside}:{title:string;children:React.ReactNode;aside?:React.ReactNode}){return <section className="network-block"><header><h3>{title}</h3>{aside}</header>{children}</section>}
function ErrorStrip({controller,state}:{controller:NetworkController;state:NetworkState}){return <>{state.error&&<div className="network-error" role="alert"><div><strong>Transmission interrupted</strong><p>{state.error.message}</p><small>{state.error.code}</small></div><button aria-label="Dismiss network error" onClick={()=>controller.dismissError()}>×</button></div>}{state.pollError&&<p className="network-warning" role="status">Host update unavailable: {state.pollError} <button onClick={()=>void controller.refresh()}>Retry host</button></p>}{state.busy&&<p className="network-operation" role="status"><span className="network-pulse"/>{state.busy}</p>}</>}

export function NetworkPanel({controller,index}:{controller:NetworkController;index?:ContentIndex}){
 const state=useObservable(controller.state),[tab,setTab]=useState('operations');
 useEffect(()=>{void controller.initialize()},[controller]);
 const tabs=[['operations','Operations'],['coop','Co-op'],['contacts','Contacts'],['files','Save copies'],['observer','Observe'],['ranked','Local ranked']];
 return <div className="network-panel"><div className="network-banner"><Icon id="i-users"/><div><span className="eyebrow">LOCAL COMMAND NETWORK</span><h3>Rally your commanders.</h3><p>Up to four independent commanders on your game host.</p></div><span className={`network-link ${state.connected?'connected':''}`}>{state.connected?`HOST REACHED · ${state.hostLatency??'?'} ms`:'DISCONNECTED'}</span></div>
 <ErrorStrip controller={controller} state={state}/><ProfilePanel controller={controller}/>
 {state.account?.phase==='signed-in'||state.account?.phase==='offline'?<><nav className="network-tabs" aria-label="Multiplayer sections">{tabs.map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}{id==='contacts'&&state.invites.length>0&&<b>{state.invites.length}</b>}</button>)}</nav>
 {state.lobby&&<LobbyPanel controller={controller}/>}
 {tab==='operations'?<OperationPanel controller={controller} index={index}/>:tab==='coop'?<CoopPanel controller={controller}/>:tab==='contacts'?<ContactsPanel controller={controller}/>:tab==='files'?<SyncPanel controller={controller}/>:tab==='observer'?<ObserveSetup controller={controller}/>:<RankedPanel controller={controller}/>}</>:<p className="network-guest-note">Solo play and browser saves need no profile. Create a local profile only when you want to join this host or copy saves to it.</p>}
 </div>;
}

function ProfilePanel({controller}:Props){
 const state=useObservable(controller.state),[host,setHost]=useState(state.host),[name,setName]=useState(''),[remember,setRemember]=useState(true),[token,setToken]=useState(''),[restore,setRestore]=useState(false);
 useEffect(()=>setHost(state.host),[state.host]);const account=state.account;let openHost:string|undefined;try{const url=new URL(host);if(['http:','https:'].includes(url.protocol)&&!url.username&&!url.password&&url.origin!==globalThis.location?.origin)openHost=url.origin}catch{};
 return <Block title="Host & commander" aside={<span className="network-kicker">{account?.phase==='signed-in'?'LOCAL PROFILE':'GUEST'}</span>}>
 <form className="network-host" onSubmit={event=>{event.preventDefault();void controller.connect(host)}}><label>Game host<input aria-label="Game host" value={host} onChange={event=>setHost(event.target.value)} placeholder="http://192.168.1.20:8080" type="url" required spellCheck={false}/></label><button disabled={!!state.busy} type="submit">Connect host</button></form>
 <p className="network-hint">Open the host’s LAN address on each computer. The host must explicitly enable LAN access.</p>{openHost&&<p className="network-hint"><a href={openHost}>Open this host’s game page</a> to use its own origin. The host may reject connections from another game page.</p>}
 {account?.profile?<div className="network-profile"><span className="network-profile-mark"><Icon id="i-users"/></span><div><strong>{account.profile.name}</strong><small>{account.persistent?'Remembered on this browser':'This browser session only'} · {account.phase==='offline'?'Host connection lost':'Local host profile'}</small><label className="network-id">Profile ID<input aria-label="Your profile ID" readOnly value={account.profile.id}/></label></div><button disabled={!!state.busy} onClick={()=>void controller.logout()}>Sign out</button></div>:<form onSubmit={event=>{event.preventDefault();if(restore){const value=token;setToken('');void controller.restoreProfile(value,remember)}else void controller.createProfile(name,remember)}}><div className="network-host"><label>{restore?'Local profile token':'Commander name'}<input aria-label={restore?'Local profile token':'Commander name'} type={restore?'password':'text'} autoComplete="off" maxLength={restore?64:32} value={restore?token:name} onChange={event=>restore?setToken(event.target.value):setName(event.target.value)} required/></label><button type="submit" className="primary" disabled={!!state.busy||!state.connected}>{restore?'Restore profile':'Create local profile'}</button></div><div className="network-inline"><label className="network-check"><input type="checkbox" checked={remember} onChange={event=>setRemember(event.target.checked)}/>Remember sign-in on this browser</label><button type="button" className="text-button" onClick={()=>{setRestore(!restore);setToken('')}}>{restore?'Create a new profile':'Restore an existing token'}</button></div></form>}
 {account?.error&&<p className="network-warning">{account.error.message}</p>}
 </Block>;
}

function OperationPanel({controller,index}:Props&{index?:ContentIndex}){
 const state=useObservable(controller.state),[name,setName]=useState('Frontline operation'),[map,setMap]=useState(''),[mode,setMode]=useState<'1v1'|'2v2'|'ffa'|'custom'>('custom'),[faction,setFaction]=useState<Faction|'random'>('US'),[privateLobby,setPrivate]=useState(false),[pause,setPause]=useState(true),[observers,setObservers]=useState(false),[id,setID]=useState(''),[code,setCode]=useState('');
 const mapChoices=state.maps.filter(value=>value.installed&&(!index?.maps.find(entry=>entry.id===value.id)||index.maps.some(entry=>entry.id===value.id&&entry.kind==='skirmish')));
 useEffect(()=>{if(!mapChoices.some(value=>value.id===map))setMap(mapChoices[0]?.id??'')},[state.maps,index,map]);
 const available=state.lobbies.filter(lobby=>lobby.id!==state.lobby?.id);
 return <><Block title="Open operations" aside={<button disabled={!!state.busy} onClick={()=>void controller.refresh()}><Icon id="i-refresh"/>Refresh</button>}>
 {available.length?<div className="network-lobby-list">{available.map(lobby=><div key={lobby.id} className="network-lobby-list-row"><div><strong>{lobby.name}</strong><small>{lobby.mode.toUpperCase()} · {state.maps.find(map=>map.id===lobby.map_id)?.title??lobby.map_id} · {lobby.slots.length} commanders{lobby.match_id?' · IN PROGRESS':''}</small></div><button disabled={!!state.busy||!!state.lobby||!!lobby.match_id} onClick={()=>void controller.joinLobby(lobby.id)}>Join operation</button></div>)}</div>:<Empty>No open lobbies on this host. Create an operation or join with a lobby ID.</Empty>}
 <form className="network-direct" onSubmit={event=>{event.preventDefault();void controller.joinLobby(id,{code:code||undefined})}}><label>Lobby ID<input aria-label="Join lobby ID" value={id} onChange={event=>setID(event.target.value)} required spellCheck={false}/></label><label>Access code <small>Private lobbies</small><input aria-label="Join access code" value={code} onChange={event=>setCode(event.target.value)} autoComplete="off"/></label><button disabled={!!state.busy||!!state.lobby}>Join by ID</button></form>
 </Block>{!state.lobby&&<Block title="Establish an operation"><form onSubmit={event=>{event.preventDefault();void controller.createLobby({name,map_id:map,mode,faction,private:privateLobby,pause_enabled:mode==='custom'&&pause,live_observers:privateLobby&&observers})}}><div className="network-form-grid"><label>Operation name<input value={name} onChange={event=>setName(event.target.value)} maxLength={60} required/></label><label>Battlefield<select aria-label="Lobby battlefield" value={map} onChange={event=>setMap(event.target.value)}>{mapChoices.map(value=><option key={value.id} value={value.id}>{value.title} · {value.players??'?'} slots</option>)}</select></label><label>Battle format<select aria-label="Battle format" value={mode} onChange={event=>setMode(event.target.value as typeof mode)}><option value="custom">Custom · 1–4 commanders</option><option value="1v1">1 vs 1</option><option value="2v2">2 vs 2</option><option value="ffa">Free for all · 3–4 commanders</option></select></label><label>Your faction<select aria-label="Host faction" value={faction} onChange={event=>setFaction(event.target.value as typeof faction)}><FactionOptions/></select></label></div><div className="network-inline"><label className="network-check"><input type="checkbox" checked={privateLobby} onChange={event=>setPrivate(event.target.checked)}/>Private access code</label>{mode==='custom'&&<label className="network-check"><input type="checkbox" checked={pause} onChange={event=>setPause(event.target.checked)}/>Shared pause</label>}{privateLobby&&<label className="network-check"><input type="checkbox" checked={observers} onChange={event=>setObservers(event.target.checked)}/>Live observers</label>}</div><NetworkMapPreview controller={controller} id={map}/><p className="network-hint">Standard rules: 6,000 credits, 100 Supply, normal speed, fog of war and strategic operations.</p><button className="primary" disabled={!!state.busy||!map}>Create operation</button></form></Block>}</>;
}

function LobbyPanel({controller}:Props){
 const state=useObservable(controller.state),lobby=state.lobby!,me=lobby.slots.find(slot=>slot.profile===state.account?.profile?.id),host=lobby.host===state.account?.profile?.id,forming=state.lobbyState==='forming';
 const [aiDifficulty,setAIDifficulty]=useState<Difficulty>('normal'),[aiFaction,setAIFaction]=useState<Faction|'random'>('random'),[aiTeam,setAITeam]=useState(2);
 return <Block title={lobby.name} aside={<span className="network-kicker">{state.lobbyState?.toUpperCase()} / {lobby.mode.toUpperCase()}</span>}>
 <div className="network-lobby-heading"><div><strong>{state.maps.find(map=>map.id===lobby.map_id)?.title??lobby.map_id}</strong><small>{lobby.scenario_rules?lobby.scenario_rules.rules_notice:'Standard v2 · 6,000 credits · 100 Supply · normal speed'}</small>{lobby.resume_tick!==undefined&&<small>Shared checkpoint at {formatClock(lobby.resume_tick)}</small>}</div><div className="network-lobby-code"><label>Lobby ID<input aria-label="Current lobby ID" value={lobby.id} readOnly/></label>{state.joinCode&&<label>Access code<input aria-label="Current access code" value={state.joinCode} readOnly/></label>}</div></div>
 <NetworkMapPreview controller={controller} id={lobby.map_id}/><div className="network-roster" aria-label="Lobby commanders">{lobby.slots.map(slot=><CommanderRow key={slot.player} controller={controller} lobby={lobby} slot={slot} host={host} own={slot.profile===state.account?.profile?.id} forming={forming}/>)}</div>
 {forming&&host&&<div className="network-host-controls">{!lobby.scenario_id&&<label>Battlefield<select aria-label="Change lobby battlefield" disabled={!!state.busy} value={lobby.map_id} onChange={event=>void controller.changeLobby({map_id:event.target.value})}>{state.maps.filter(map=>map.installed).map(map=><option key={map.id} value={map.id}>{map.title}</option>)}</select></label>}{(lobby.mode==='custom'||lobby.mode==='coop')&&<label className="network-check"><input type="checkbox" disabled={!!state.busy} checked={lobby.pause_enabled} onChange={event=>void controller.changeLobby({pause_enabled:event.target.checked})}/>Shared pause</label>}{!lobby.scenario_id&&<label className="network-check"><input type="checkbox" disabled={!!state.busy} checked={lobby.private} onChange={event=>void controller.changeLobby({private:event.target.checked,live_observers:event.target.checked&&lobby.live_observers})}/>Private lobby</label>}{lobby.private&&<label className="network-check"><input type="checkbox" disabled={!!state.busy} checked={lobby.live_observers} onChange={event=>void controller.changeLobby({live_observers:event.target.checked})}/>Allow live observers</label>}</div>}
 {forming&&host&&lobby.slots.length<4&&!lobby.rated&&<form className="network-ai-add" onSubmit={event=>{event.preventDefault();void controller.addAI({difficulty:aiDifficulty,...(lobby.scenario_id?{}:{faction:aiFaction,team:aiTeam})})}}><label>AI faction<select aria-label="Add AI faction" disabled={!!lobby.scenario_id} value={aiFaction} onChange={event=>setAIFaction(event.target.value as typeof aiFaction)}><FactionOptions/></select></label><label>AI difficulty<select aria-label="Add AI difficulty" value={aiDifficulty} onChange={event=>setAIDifficulty(event.target.value as Difficulty)}><Difficulties/></select></label>{!lobby.scenario_id&&lobby.mode!=='ffa'&&<label>AI team<select aria-label="Add AI team" value={aiTeam} onChange={event=>setAITeam(Number(event.target.value))}>{[1,2,3,4].map(team=><option key={team}>{team}</option>)}</select></label>}<button disabled={!!state.busy}>Add AI commander</button></form>}
 <div className="network-launch-line">{forming?<><span>{lobby.slots.filter(slot=>slot.ready&&slot.assets_ready).length} / {lobby.slots.length} ready <small>Configuration changes clear readiness.</small></span><div className="button-row"><button disabled={!!state.busy} onClick={()=>void controller.leaveLobby()}>Leave lobby</button>{me&&<button className={me.ready?'':'primary'} disabled={!!state.busy} onClick={()=>void controller.ready(!me.ready)}>{me.ready?'Not ready':'Ready to deploy'}</button>}{host&&<button className="primary" disabled={!!state.busy||!lobby.slots.every(slot=>slot.ready&&slot.assets_ready)} onClick={()=>void controller.start()}>Start operation</button>}</div></>:<><span>{state.lobbyState==='completed'?'Operation completed':'Operation in progress'}</span><button disabled={!!state.busy} onClick={()=>void controller.joinMatch()}>{state.lobbyState==='completed'?'View operation result':'Reconnect to operation'}</button></>}</div>
 {state.lobbyState==='completed'&&<button disabled={!!state.busy} onClick={()=>void controller.leaveLobby()}>Close completed lobby</button>}{state.lobbyState!=='forming'&&<NetworkMatchPanel controller={controller} embedded/>}<ChatPanel controller={controller}/>
 </Block>;
}

function CommanderRow({controller,lobby,slot,host,own,forming}:{controller:NetworkController;lobby:Lobby;slot:LobbySlot;host:boolean;own:boolean;forming:boolean}){
 const state=useObservable(controller.state),editable=forming&&(own||host&&!!slot.ai)&&!slot.script,locked=!!lobby.scenario_id,change=(value:{faction?:Faction;team?:number;color?:number;difficulty?:Difficulty})=>slot.ai?controller.changeAI(slot.player,value):controller.changeLobby(value);
 return <div className={`network-commander ${own?'own':''}`}><span className="network-slot">0{slot.player}</span><Emblem faction={slot.faction}/><div className="network-commander-name"><strong>{slot.name}{own?' · YOU':''}</strong><small>{slot.script?'Scenario opponent':slot.ai?`${slot.ai.toUpperCase()} AI`:'Human commander'}{slot.profile===lobby.host?' · HOST':''}</small></div><label>Faction<select aria-label={`Commander ${slot.player} faction`} value={slot.faction} disabled={!editable||locked||!!state.busy} onChange={event=>void change({faction:event.target.value as Faction})}><FactionOptions random={false}/></select></label><label>Team<select aria-label={`Commander ${slot.player} team`} value={slot.team} disabled={!editable||locked||lobby.mode==='ffa'||lobby.mode==='1v1'||!!state.busy} onChange={event=>void change({team:Number(event.target.value)})}>{[1,2,3,4].map(team=><option key={team}>{team}</option>)}</select></label><label>Color<select aria-label={`Commander ${slot.player} color`} value={slot.color} disabled={!editable||!!state.busy} onChange={event=>void change({color:Number(event.target.value)})}>{colors.map((color,index)=><option key={color} value={index+1}>{index+1} · {color}</option>)}</select></label>{slot.ai&&!slot.script&&<label>AI<select aria-label={`Commander ${slot.player} difficulty`} value={slot.ai} disabled={!editable||!!state.busy} onChange={event=>void change({difficulty:event.target.value as Difficulty})}><Difficulties/></select></label>}<span className={`network-readiness ${slot.ready&&slot.assets_ready?'ready':''}`}>{slot.ready&&slot.assets_ready?'READY':'WAITING'}</span>{host&&forming&&!own&&!slot.script&&<button className="network-remove" disabled={!!state.busy} onClick={()=>void controller.removeSlot(slot.player)} aria-label={`Remove commander ${slot.player}`}>×</button>}{slot.profile&&!own&&<details className="network-slot-contact"><summary>Commander contact</summary><code>{slot.profile}</code><div className="button-row"><button disabled={!!state.busy} onClick={()=>void controller.social(slot.profile!,'request')}>Request friendship</button><button disabled={!!state.busy} onClick={()=>void controller.social(slot.profile!,'mute')}>Mute commander</button><button disabled={!!state.busy} onClick={()=>void controller.social(slot.profile!,'block')}>Block commander</button></div></details>}</div>;
}

function ChatPanel({controller}:Props){
 const state=useObservable(controller.state),[text,setText]=useState(''),[team,setTeam]=useState(false),log=useRef<HTMLDivElement>(null),follow=useRef(true);
 useEffect(()=>{follow.current=true},[state.lobby?.id]);useEffect(()=>{if(follow.current&&log.current)log.current.scrollTop=log.current.scrollHeight},[state.chat]);
 return <div className="network-chat"><h4>Command channel</h4><div ref={log} onScroll={()=>{const node=log.current;if(node)follow.current=node.scrollHeight-node.scrollTop-node.clientHeight<32}} className="network-chat-log" role="log" aria-label="Lobby chat" aria-relevant="additions text">{state.chat.length?state.chat.map(message=><p key={message.id}><span>{message.team?'TEAM':'ALL'}</span><strong>{message.name}</strong> {message.text}</p>):<p className="muted">Your lobby channel is clear.</p>}</div><form onSubmit={event=>{event.preventDefault();void controller.sendChat(text,team).then(sent=>{if(sent)setText('')})}}><label className="network-check"><input type="checkbox" checked={team} onChange={event=>setTeam(event.target.checked)}/>Team only</label><input aria-label="Chat message" value={text} onChange={event=>setText(event.target.value)} maxLength={400} placeholder="Transmit to commanders…" required/><button disabled={!!state.busy||!text.trim()}>Send</button></form></div>;
}

export function NetworkMatchPanel({controller,embedded=false}:Props&{embedded?:boolean}){
 const state=useObservable(controller.state),[confirm,setConfirm]=useState(false),[reason,setReason]=useState(''),[reportOpen,setReportOpen]=useState(false),[reportTick,setReportTick]=useState(0);const lobby=state.lobby,status=state.status;
 if(!lobby?.match_id)return null;const own=lobby.slots.find(slot=>slot.profile===state.account?.profile?.id),hasHumanAlly=lobby.slots.some(slot=>slot.profile&&slot.profile!==own?.profile&&slot.team===own?.team);
 return <section className="network-match" aria-label="Online operation controls">{!embedded&&<ErrorStrip controller={controller} state={state}/>}<div className="network-connection-line"><strong>{state.result?.committed?'RESULT RECORDED':status?.paused?'SHARED PAUSE':status?.waitingForPlayers?'WAITING FOR COMMANDERS':state.connection.toUpperCase()}</strong><span>{formatClock(state.tick)}{state.latency!==undefined?` · ${Math.round(state.latency)} ms`:''}</span></div>{state.remainingMs!==undefined&&state.connection==='reconnecting'&&<p>Reconnecting your commander · {Math.ceil(state.remainingMs/1000)} seconds remaining.</p>}{status?.teammates.map(player=><p className="network-hint" key={player.player}>Commander {player.player}: {player.connected?'connected':`disconnected · ${Math.ceil(player.reconnectRemainingMs/1000)}s to return`}</p>)}
 {state.eliminated&&!state.result?.committed&&<p className="network-warning">Your commander was eliminated. This frozen view receives no live battlefield updates. Watch an authorized observer feed or wait here for the recorded result.</p>}{state.eliminated&&own&&<button disabled={!!state.busy} onClick={()=>void controller.observe(lobby.match_id!,own.player)}>Watch authorized observer view</button>}<details className="network-share"><summary>Share observer connection</summary><label>Match ID<input aria-label="Current match ID" value={lobby.match_id} readOnly/></label>{state.joinCode&&<label>Private access code<input aria-label="Observer access code to share" value={state.joinCode} readOnly/></label>}<p className="network-hint">{lobby.live_observers?'Live observation was enabled before readiness.':'Observers see a 120-second delayed perspective.'}</p></details>{state.result&&<p className="network-result">{state.result.void?'Voided operation':state.result.outcome?.draw?'Draw':state.result.outcome?.winningTeam?`Team ${state.result.outcome.winningTeam} victorious`:'Operation failed'} · {state.result.outcome?.reason}{!state.result.committed?' · waiting for durable host confirmation':''}</p>}
 <div className="button-row">{!state.result?.committed&&!state.eliminated&&<><button disabled={!!state.busy} onClick={()=>void controller.reconnect()}>Reconnect</button>{lobby.pause_enabled&&<><button disabled={!!state.busy||status?.paused} onClick={()=>void controller.pause(true)}>Request shared pause</button><button disabled={!!state.busy} onClick={()=>void controller.pause(false)}>Resume / withdraw vote</button></>}{hasHumanAlly&&<><button disabled={!!state.busy} onClick={()=>void controller.surrenderVote(true)}>Vote team surrender</button><button disabled={!!state.busy} onClick={()=>void controller.surrenderVote(false)}>Withdraw surrender vote</button></>}<button className="danger" onClick={()=>setConfirm(true)} disabled={!!state.busy}>Surrender…</button></>}{(state.result?.committed||state.lobbyState==='completed')&&<><button className="primary" disabled={!!state.busy} onClick={()=>void controller.rematch()}>Create rematch lobby</button><button disabled={!!state.busy||state.result?.void} onClick={()=>void controller.saveReplay()}>Save match replay</button></>}<button onClick={()=>{setReportOpen(!reportOpen);setReportTick(state.tick)}}>Report an incident</button></div>
 {status&&lobby.pause_enabled&&<p className="network-hint">Pause votes: {status.pauseVotes.length?status.pauseVotes.join(', '):'none'}. The host applies the shared-pause policy.</p>}{confirm&&<div className="network-confirm" role="alert"><p>Surrender your commander? Your surviving teammates continue fighting.</p><div className="button-row"><button onClick={()=>setConfirm(false)}>Keep fighting</button><button className="danger" disabled={!!state.busy} onClick={()=>{setConfirm(false);void controller.surrender()}}>Confirm surrender</button></div></div>}
 {reportOpen&&<form className="network-report" onSubmit={event=>{event.preventDefault();void controller.report(reason,reportTick).then(ok=>{if(ok){setReason('');setReportOpen(false)}})}}><label>Incident game time (seconds)<input aria-label="Incident game time" type="number" min={0} max={state.tick/20} step={.05} value={reportTick/20} onChange={event=>setReportTick(Math.max(0,Math.round(Number(event.target.value)*20)))} required/></label><label>What happened at {formatClock(reportTick)}?<input aria-label="Incident details" value={reason} onChange={event=>setReason(event.target.value)} minLength={3} maxLength={2000} required/></label><p className="network-hint">Recorded on this local host for its operator. Include enough detail to find the incident in the replay.</p><button disabled={!!state.busy}>Record report</button></form>}
 {!embedded&&!state.eliminated&&<ChatPanel controller={controller}/>}</section>;
}

function CoopPanel({controller}:Props){
 const state=useObservable(controller.state),[difficulty,setDifficulty]=useState<Difficulty>('normal'),[ally,setAlly]=useState('human'),[save,setSave]=useState(''),[player,setPlayer]=useState(1),missions=state.missions.filter(mission=>mission.mode==='coop');
 return <><Block title="Joint operations"><p>Two allied commanders, separate ownership and shared vision. The host saves shared checkpoints automatically.</p><div className="network-form-grid"><label>Scenario difficulty<select value={difficulty} onChange={event=>setDifficulty(event.target.value as Difficulty)}><Difficulties/></select></label><label>Allied commander<select value={ally} onChange={event=>setAlly(event.target.value)}><option value="human">Another human</option><option value="easy">Easy AI</option><option value="normal">Normal AI</option><option value="hard">Hard AI</option></select></label></div>{missions.length?missions.map(mission=><article className="network-mission" key={mission.id}><Emblem faction={mission.faction}/><div><h4>{mission.title}</h4><p>{mission.briefing}</p><small>{mission.rules_notice}</small></div><button className="primary" disabled={!!state.busy||!!state.lobby} onClick={()=>void controller.createCoop(mission.id,difficulty,ally==='human'?undefined:ally as Difficulty)}>Create co-op lobby</button></article>):<Empty>This host has no co-op scenario installed.</Empty>}</Block>
 <Block title="Shared checkpoints" aside={<button disabled={!!state.busy} onClick={()=>void controller.refresh()}>Refresh checkpoints</button>}><p className="network-hint">Choose a shared checkpoint owned by your profile. The host validates scenario saves and preserves every saved commander; all human slots must rejoin.</p><form className="network-direct" onSubmit={event=>{event.preventDefault();void controller.resumeCoop(save,player)}}><label>Host save<select aria-label="Shared checkpoint" value={save} onChange={event=>setSave(event.target.value)} required><option value="">Choose a checkpoint</option>{state.saves.map(value=><option key={value.id} value={value.id}>{value.name} · {new Date(value.updated*1000).toLocaleString()} · r{value.revision}</option>)}</select></label><label>Your saved commander<select value={player} onChange={event=>setPlayer(Number(event.target.value))}><option value={1}>Commander 1</option><option value={2}>Commander 2</option></select></label><button disabled={!!state.busy||!!state.lobby||!save}>Resume co-op lobby</button></form></Block></>;
}

function ContactsPanel({controller}:Props){
 const state=useObservable(controller.state),[target,setTarget]=useState('');
 return <><Block title="Local contacts"><p className="network-hint">Profiles belong to this host. Share your profile ID to connect with another commander.</p><form className="network-host" onSubmit={event=>{event.preventDefault();void controller.social(target,'request').then(ok=>{if(ok)setTarget('')})}}><label>Commander profile ID<input aria-label="Contact profile ID" value={target} onChange={event=>setTarget(event.target.value)} required/></label><button disabled={!!state.busy}>Send friend request</button></form><div className="button-row"><button disabled={!!state.busy||!target.trim()} onClick={()=>void controller.social(target,'mute')}>Mute entered profile</button><button disabled={!!state.busy||!target.trim()} onClick={()=>void controller.social(target,'block')}>Block entered profile</button></div>{state.relations.length?state.relations.map(relation=><div className="network-contact" key={`${relation.target}:${relation.kind}:${relation.incoming}`}><div><strong>{relation.name}</strong><small>{relation.kind==='request'?(relation.incoming?'Incoming request':'Request sent'):relation.kind}</small><code>{relation.target}</code></div><div className="button-row">{relation.kind==='request'&&relation.incoming&&<><button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'accept')}>Accept friend</button><button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'decline')}>Decline</button></>}{relation.kind==='request'&&!relation.incoming&&<button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'remove')}>Cancel request</button>}{relation.kind==='friend'&&<><button disabled={!!state.busy||!state.lobby||state.lobbyState!=='forming'} onClick={()=>void controller.invite(relation.target)}>Invite to lobby</button><button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'remove')}>Remove friend</button></>}{relation.kind==='mute'?<button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'unmute')}>Unmute</button>:<button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'mute')}>Mute</button>}{relation.kind==='block'?<button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'unblock')}>Unblock</button>:<button disabled={!!state.busy} onClick={()=>void controller.social(relation.target,'block')}>Block</button>}</div></div>):<Empty>No local contacts yet.</Empty>}</Block>
 <Block title="Lobby invitations" aside={<button disabled={!!state.busy} onClick={()=>void controller.refresh()}>Refresh invitations</button>}>{state.invites.length?state.invites.map(invite=><div className="network-contact" key={invite.id}><div><strong>{invite.lobby_name}</strong><small>From {invite.sender_name} · expires {new Date(invite.expires*1000).toLocaleTimeString()}</small></div><div className="button-row"><button className="primary" disabled={!!state.busy||!!state.lobby} onClick={()=>void controller.acceptInvite(invite.id)}>Accept invitation</button><button disabled={!!state.busy} onClick={()=>void controller.dismissInvite(invite.id)}>Dismiss</button></div></div>):<Empty>No pending invitations.</Empty>}</Block>
 <Block title="Your incident reports" aside={<button disabled={!!state.busy} onClick={()=>void controller.loadReports()}>Load reports</button>}>{state.reports.map(report=><div className="network-contact" key={report.id}><div><strong>{report.decision.replaceAll('_',' ')}</strong><p>{report.reason}</p><small>Match {report.match_id} · {formatClock(report.tick)} · revision {report.revision}</small></div></div>)}</Block></>;
}

function VersionDetails({version}:{version?:SyncSaveVersion|SyncSettingVersion}){if(!version)return <p className="muted">No file at this target</p>;return <><strong>{'name' in version?version.name:'Settings'}</strong><small>Revision {version.revision} · {version.updatedMs?new Date(version.updatedMs).toLocaleString():'Host timestamp unavailable'}</small>{'tick' in version&&<small>Game time {formatClock(version.tick??0)} · {version.bytes.toLocaleString()} bytes</small>}{'mission' in version&&version.mission&&<small>{version.mission.id} · {version.mission.difficulty} · {version.mission.checkpoint||'Opening'} · {version.mission.objectives.filter(value=>value.complete).length}/{version.mission.objectives.length} objectives</small>}{version.error&&<small className="network-warning">{version.error.message}</small>}</>}
function SyncPanel({controller}:Props){
 const state=useObservable(controller.state),[choices,setChoices]=useState<Record<string,string>>({}),[players,setPlayers]=useState<Record<string,number[]>>({});
 useEffect(()=>{setChoices({});setPlayers({})},[state.sync]);
 const preview=state.sync;
 const execute=(event:FormEvent)=>{event.preventDefault();if(!preview)return;const decisions=preview.entries.map(entry=>({key:entry.key,action:choices[entry.key],...(choices[entry.key]==='download'&&entry.kind==='save'?{localPlayers:players[entry.key]??entry.remote?.humanPlayers}: {})})) as SyncDecision[];void controller.copySync(decisions)};
 const keepBoth=(entry:SyncEntry,direction:'upload'|'download')=>{if(!preview||entry.kind!=='save')return;const mappings=preview.entries.filter((value):value is Extract<SyncEntry,{kind:'save'}>=>value.kind==='save').map(value=>({localId:value.localId,remoteId:value.remoteId,uploadName:value.uploadName,downloadName:value.downloadName}));const target=mappings.find(value=>value.localId===entry.localId)!;if(direction==='download')target.localId=`copy-${randomUUID()}`;else target.remoteId=`copy-${randomUUID()}`;void controller.previewSync(preview.mode==='migration',mappings)};
 return <Block title="Optional save copies"><p>Compare timestamps, mission progress and revisions before copying. Each choice names the exact local and host target. Existing files are replaced only by your explicit choice.</p><div className="button-row"><button disabled={!!state.busy} onClick={()=>void controller.previewSync(false)}>Compare saves & settings</button><button disabled={!!state.busy} onClick={()=>void controller.previewSync(true)}>Preview guest migration</button>{state.busy?.includes('files')&&<button onClick={()=>controller.cancelSync()}>Cancel copying</button>}</div>
 {state.syncProgress&&<p role="status">{state.syncProgress}</p>}{preview&&<form onSubmit={execute}><p className="network-kicker">{preview.mode==='migration'?'GUEST → HOST PREVIEW':'COPY PREVIEW'} · {preview.profileName}</p>{preview.entries.map(entry=><article className="network-sync-item" key={entry.key}><header><strong>{entry.kind==='save'?'Saved operation':'Settings'}</strong><span>{entry.comparison.replaceAll('-',' ')}</span></header><div className="network-sync-versions"><div><span className="eyebrow">THIS BROWSER</span><code>{entry.localId}</code><VersionDetails version={entry.local}/></div><div><span className="eyebrow">LOCAL HOST</span><code>{entry.remoteId}</code><VersionDetails version={entry.remote}/></div></div><label>Copy decision<select aria-label={`Copy decision ${entry.key}`} value={choices[entry.key]??''} onChange={event=>setChoices({...choices,[entry.key]:event.target.value})} required><option value="">Choose for this item…</option><option value="skip">Keep both unchanged</option>{entry.local?.compatible&&entry.comparison!=='unavailable'&&<option value="upload">Copy browser → host{entry.remote?' · replace reviewed host revision':''}</option>}{preview.mode==='sync'&&entry.remote?.compatible&&entry.comparison!=='unavailable'&&<option value="download">Copy host → browser{entry.local?' · replace reviewed browser revision':''}</option>}</select></label>{choices[entry.key]==='download'&&entry.kind==='save'&&(entry.remote?.humanPlayers?.length??0)>1&&<fieldset><legend>Human commanders controlled on this browser</legend>{entry.remote?.humanPlayers?.map(player=><label className="network-check" key={player}><input type="checkbox" checked={(players[entry.key]??entry.remote!.humanPlayers!).includes(player)} onChange={event=>{const current=players[entry.key]??entry.remote!.humanPlayers!;setPlayers({...players,[entry.key]:event.target.checked?[...current,player]:current.filter(value=>value!==player)})}}/>Commander {player}</label>)}</fieldset>}{entry.kind==='save'&&entry.remote&&(entry.local||entry.localId.startsWith('autosave-'))&&preview.mode==='sync'&&<button type="button" disabled={!!state.busy} onClick={()=>keepBoth(entry,'download')}>Preview host copy under a new local ID</button>}{entry.kind==='save'&&entry.local&&entry.remote&&<button type="button" disabled={!!state.busy} onClick={()=>keepBoth(entry,'upload')}>Preview browser copy under a new host ID</button>}</article>)}<ul className="network-hint">{preview.unsupported.map(item=><li key={item.kind}>{item.reason}</li>)}</ul><button className="primary" disabled={!!state.busy||preview.entries.some(entry=>!choices[entry.key])}>Apply reviewed choices</button></form>}
 {state.syncResult&&<div className="network-sync-receipts" role="status"><h4>Copy operation {state.syncResult.status}</h4>{state.syncResult.receipts.map(receipt=><p key={receipt.key}><strong>{receipt.status}</strong> {receipt.action}: {receipt.localId} ↔ {receipt.remoteId}{receipt.revision!==undefined?` · revision ${receipt.revision}`:''}{receipt.error&&<span> — {receipt.error.message}</span>}{receipt.sourceChanged&&<span> — source changed after the reviewed copy</span>}{receipt.warning&&<span> — {receipt.warning.message}</span>}</p>)}<p>Cancellation preserves completed copies and never deletes existing files.</p></div>}</Block>;
}

function RankedPanel({controller}:Props){const state=useObservable(controller.state),[faction,setFaction]=useState<Faction|'random'>('random'),[maps,setMaps]=useState<string[]>([]);return <Block title="Local ranked queue"><p>This queue and its ratings belong to this host. Only reviewed two-player maps are eligible.</p><p className="network-warning">Online play continues while this tab is unfocused. Use a stable connection; a disconnected commander has 120 seconds to return. Ranked matches cannot pause, and surrender is final.</p><button disabled={!!state.busy} onClick={()=>void controller.loadRanked()}>Check reviewed maps</button>{state.rankedMessage&&<p className="network-warning">{state.rankedMessage}</p>}{state.rankedMaps.length>0&&<form onSubmit={event=>{event.preventDefault();void controller.queue(faction,maps.length?maps:state.rankedMaps.map(map=>map.id))}}><label>Your faction<select value={faction} onChange={event=>setFaction(event.target.value as typeof faction)}><FactionOptions/></select></label><fieldset><legend>Eligible maps · no selection allows all</legend>{state.rankedMaps.map(map=><label className="network-check" key={map.id}><input type="checkbox" checked={maps.includes(map.id)} onChange={event=>setMaps(event.target.checked?[...maps,map.id]:maps.filter(id=>id!==map.id))}/>{map.title} · {map.version}</label>)}</fieldset><button className="primary" disabled={!!state.busy||!!state.lobby}>Join local ranked queue</button></form>}{state.queue&&state.queue.status!=='idle'&&<div className="network-inline"><strong>Queue: {state.queue.status}</strong>{state.queue.status==='searching'&&<button disabled={!!state.busy} onClick={()=>void controller.leaveQueue()}>Cancel queue</button>}</div>}</Block>}

function ObserveSetup({controller}:Props){const state=useObservable(controller.state),[match,setMatch]=useState(''),[code,setCode]=useState(''),[player,setPlayer]=useState(1);return <Block title="Observer station"><p>Watch one commander’s authorized perspective. Standard feeds are delayed by 120 seconds. A private host can enable live observation before commanders mark ready.</p><form onSubmit={event=>{event.preventDefault();void controller.observe(match,player,code)}}><div className="network-form-grid"><label>Match ID<input aria-label="Observe match ID" value={match} onChange={event=>setMatch(event.target.value)} required spellCheck={false}/></label><label>Private access code<input aria-label="Observe access code" value={code} onChange={event=>setCode(event.target.value)} autoComplete="off"/></label><label>Perspective<select aria-label="Observer perspective" value={player} onChange={event=>setPlayer(Number(event.target.value))}>{[1,2,3,4].map(id=><option key={id} value={id}>Commander {id}</option>)}</select></label></div><p className="network-hint">Ask a participant for the match ID. Active players cannot switch into an observer feed.</p><button className="primary" disabled={!!state.busy}>Open observer feed</button></form></Block>}
export function NetworkObserverPanel({controller}:Props){const state=useObservable(controller.state),observer=state.observer;if(!observer)return null;return <section className="network-match" aria-label="Observer feed controls"><ErrorStrip controller={controller} state={state}/><div className="network-connection-line"><strong>READ-ONLY OBSERVER</strong><span>{observer.delayTicks===0?'HOST-ENABLED LIVE VIEW':`${observer.delayTicks/20}s DELAY`}</span></div><p>Commander {observer.player} perspective · {formatClock(state.tick)} · {state.connection}</p>{observer.error&&<p className="network-warning" role="status">{observer.error}</p>}{observer.buffering&&<p className="network-warning" role="status">Waiting for the authorized delay buffer. No live battlefield state is shown.</p>}<p className="network-hint">The host controls this feed. Observer credentials cannot issue orders, pause the operation or transmit to active players.</p><button disabled={!!state.busy} onClick={()=>void controller.reconnectObserver()}>Reconnect observer feed</button></section>}
