import {useEffect,useState} from 'react';
import {NetworkController} from '../../app/network-controller';
import {useObservable} from '../../app/store';
import {NetworkMapPreview} from './map-preview';
export function MapsPanel({controller}:{controller:NetworkController}){
 const state=useObservable(controller.state),[selected,setSelected]=useState(''),[reporting,setReporting]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{void controller.loadMaps()},[controller]);
 const ownIDs=new Set(state.ownMaps.map(map=>map.id)),published=state.maps.filter(map=>!map.installed&&!ownIDs.has(map.id));
 return <><section className="network-block"><header><h3>Local map workshop</h3><button disabled={!!state.busy} onClick={()=>void controller.loadMaps()}>Refresh map library</button></header><p>Validate an exported map, upload a private copy, then choose whether to publish it on this host. Publishing never makes a custom map ranked.</p>
 <label className="network-map-file">Choose exported map JSON<input aria-label="Upload map file" type="file" accept=".json,application/json" disabled={!!state.busy} onChange={event=>{const file=event.target.files?.[0];event.target.value='';if(file)void controller.prepareMapUpload(file,file.name)}}/></label><p className="network-hint">The map editor exports compatible files. Your original file and local editor draft are retained. Uploading a newer revision makes that revision private until you publish it again.</p>
 {state.mapUpload&&<div className="network-map-upload network-confirm"><span className="eyebrow">REVIEWED UPLOAD</span><h4>{state.mapUpload.map.title}</h4><p>{state.mapUpload.filename} · {state.mapUpload.bytes.toLocaleString()} bytes · Go validation passed</p><p className="network-map-metadata">ID {state.mapUpload.map.id} · version {state.mapUpload.map.version} · {state.mapUpload.map.width} × {state.mapUpload.map.height} · {state.mapUpload.map.spawns.length} commanders</p><p>{state.mapUpload.expectedRevision?`Replaces your reviewed host revision ${state.mapUpload.expectedRevision}. Existing matches retain their original map.`:'Creates a new private map on this host.'}</p><div className="button-row"><button onClick={()=>controller.cancelMapUpload()}>Cancel map upload</button><button className="primary" disabled={!!state.busy} onClick={()=>void controller.uploadMap()}>Upload private map</button></div></div>}
 <h4>Your host maps</h4>{!state.ownMaps.length&&<p className="network-hint">You have not uploaded any maps to this host.</p>}{state.ownMaps.map(map=><article className="network-map-card" key={map.id}><header><div><strong>{map.title}</strong><p className="network-map-metadata">{map.id} · revision {map.revision} · author {map.owner_name}</p></div><span className="network-map-badge">{map.removed?'REMOVED BY OPERATOR':map.published?'PUBLISHED':'PRIVATE'}</span></header><div className="button-row"><button disabled={!!state.busy} onClick={()=>setSelected(map.id)}>Preview your map</button><button disabled={!!state.busy||map.removed} onClick={()=>void controller.publishMap(map.id,!map.published)}>{map.published?'Make map private':'Publish map'}</button>{!map.removed&&<button disabled={!!state.busy||!!state.lobby} onClick={()=>void controller.createLobby({name:map.title.slice(0,60),map_id:map.id,mode:'custom',faction:'US',private:!map.published,pause_enabled:true})}>Create {map.published?'public':'private'} map operation</button>}</div>{map.removed&&<p className="network-warning">This map is unavailable for new operations until the host operator restores it. Restoration leaves it private.</p>}</article>)}
 </section><section className="network-block"><header><h3>Community maps on this host</h3></header>{published.length?published.map(map=><article className="network-map-card" key={map.id}><header><div><strong>{map.title}</strong><p>By {map.owner_name??map.author??'Local commander'} · {map.players??'?'} slots · {map.version??'Custom revision'}</p></div><span className="network-map-badge">UNRANKED</span></header><div className="button-row"><button disabled={!!state.busy} onClick={()=>setSelected(map.id)}>Preview published map</button><button disabled={!!state.busy||!!state.lobby} onClick={()=>void controller.createLobby({name:map.title.slice(0,60),map_id:map.id,mode:'custom',faction:'US',pause_enabled:true})}>Create custom operation</button><button disabled={!!state.busy} onClick={()=>{setReporting(map.id);setReason('')}}>Report published map</button></div></article>):<p className="network-hint">No other published maps are available.</p>}{reporting&&<form className="network-map-upload" onSubmit={event=>{event.preventDefault();void controller.reportMap(reporting,reason).then(ok=>{if(ok){setReporting('');setReason('')}})}}><h4>Report map {reporting}</h4><label>Map report details<textarea aria-label="Map report details" value={reason} onChange={event=>setReason(event.target.value)} minLength={3} maxLength={2000} required/></label><p className="network-hint">Describe the issue in plain text. The host preserves the current published map revision for its operator.</p><div className="button-row"><button type="button" onClick={()=>setReporting('')}>Cancel map report</button><button disabled={!!state.busy}>Record map report</button></div></form>}{selected&&<><h4>Battlefield preview</h4><NetworkMapPreview controller={controller} id={selected}/></>}</section><section className="network-block"><header><h3>Your map reports</h3><button disabled={!!state.busy} onClick={()=>void controller.loadMapReports()}>Load your map reports</button></header>{state.mapReports.map(report=><article className="network-map-card" key={report.id}><strong>{report.decision.replaceAll('_',' ')}</strong><p>{report.reason}</p><small>{report.map_id} · content revision {report.map_revision} · review revision {report.revision}</small></article>)}{state.mapReportCursor&&<button disabled={!!state.busy} onClick={()=>void controller.loadMapReports(true)}>Load older map reports</button>}</section></>;
}
