import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,readdir,access} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {gzipSync,gunzipSync,deflateSync} from 'node:zlib';
import assert from 'node:assert/strict';
import {chromium} from '../../client/node_modules/playwright-core/index.mjs';
const work=path.dirname(fileURLToPath(import.meta.url)),sha=b=>createHash('sha256').update(b).digest('hex'),lock=JSON.parse(await readFile(path.join(work,'supplement-prepared/lock.json'),'utf8'));
const arg=(flag,fallback)=>process.argv.includes(flag)?process.argv[process.argv.indexOf(flag)+1]:fallback;
const out=path.resolve(arg('--out',path.join(work,'chrome-pressure-01'))),execute=process.argv.includes('--execute');
for(const [file,expected] of Object.entries(lock.pins))assert.equal(sha(await readFile(file)),expected,`Input drift: ${file}`);
assert.equal(sha(await readFile(lock.browser.executable)),lock.browser.sha256);
for(const payload of Object.values(lock.payloads))for(const file of Object.values(payload.files))assert.equal(sha(await readFile(file.file)),file.sha256);
assert.equal(sha(await readFile(path.join(work,'supplement-prepared/catalog.json'))),lock.catalog.sha256);
for(const variant of ['original','performance','memory']){
 for(const [leaf,expected] of Object.entries(lock.bundlePins[variant]))assert.equal(sha(await readFile(path.join(work,'supplement-prepared',variant,leaf))),expected);
 const pins=JSON.parse(await readFile(path.join(work,'supplement-prepared',variant,'build-input-pins.json'),'utf8'));for(const [file,expected] of Object.entries(pins))assert.equal(sha(await readFile(file)),expected,`Bundle input drift: ${file}`);
 assert.equal((await readFile(path.join(work,'supplement-prepared',variant,'typecheck-final.log'),'utf8')).trim(),'');
}
const html='<!doctype html><html><head><meta charset="utf-8"><title>Frozen renderer acceptance</title><link rel="icon" href="data:,"><style>html,body{margin:0;background:#14130f;width:640px;height:480px;overflow:hidden}#field{width:640px;height:480px}canvas{display:block}</style></head><body><div id="field"></div><script type="module" src="/fixture.js"></script></body></html>';
if(!execute){console.log(JSON.stringify({status:'preflight-pass-browser-unrun',sourceFiles:Object.keys(lock.sources.original).length,variants:3,cases:'pressure only: later actual rifle snapshot, actual fighter page loads, completed-frame trim and real-page reload',browser:lock.browser.executable}));process.exit(0)}
try{await access(out);throw Error('Output directory already exists; retain prior run and choose another explicit output')}catch(error){if(error.code!=='ENOENT')throw error}await mkdir(out,{recursive:true});await mkdir(path.join(out,'fixture-inputs'));for(const leaf of ['supplement-fixture.ts','pressure.mjs','supplement-prepare.mjs','README.md'])await writeFile(path.join(out,'fixture-inputs',leaf),await readFile(path.join(work,leaf)));await writeFile(path.join(out,'fixture-inputs/lock.json'),await readFile(path.join(work,'supplement-prepared/lock.json')));
const report={status:'running',started:new Date().toISOString(),scope:'Pressure-only diagnosed successor over unchanged performance source: actual later rifle snapshot and real decoded fighter pages. Prior air/memory receipts remain separate.',priorSetupFailure:'chrome-supplement-01 remains FAILED; initial crowded snapshot was not a proven picking target.',lockSHA256:sha(await readFile(path.join(work,'supplement-prepared/lock.json'))),limits:['Component fixture, not ordinary App acceptance.','Synthetic terrain/visibility payloads do not assert Go gameplay.','Fighter snapshot pair is earlier actual Go source c7e0 owner view; authorized absence is a rewind, not a claimed foreign sight-loss transition.','Recorded source c7e0 snapshots do not qualify new cadence gameplay.','No WASM execution here; original current WASM remains pinned and unchanged.','No FPS, GPU-total, final-art, 256-square or multiplayer qualification; pressure evidence concerns actual decoded atlas resources and texture lifecycle only.','Frozen performance.now only during synchronous setSnapshot/render/paint; no live simulation or network clock change.'],runnerSHA256:sha(await readFile(fileURLToPath(import.meta.url))),fixtureSHA256:sha(await readFile(path.join(work,'supplement-fixture.ts'))),consoleLog:[],overlay:lock.overlay,browserFallback:lock.browserFallback,raw:{page:[],console:[],requestfailed:[],http:[],cdp:[],server:[]},requests:[],cases:[],comparisons:[],lifecycle:[],guards:[],pending:[],runtimeErrors:[]};
let server,browser,browserServer,page,variant='original',requestID=0;const pinsAfter={};
function crc32(data){let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function pngChunk(name,body){const tag=Buffer.from(name),len=Buffer.alloc(4),crc=Buffer.alloc(4);len.writeUInt32BE(body.length);crc.writeUInt32BE(crc32(Buffer.concat([tag,body])));return Buffer.concat([len,tag,body,crc])}
function png(w,h,rgba){const header=Buffer.alloc(13);header.writeUInt32BE(w,0);header.writeUInt32BE(h,4);header[8]=8;header[9]=6;const scan=Buffer.alloc(h*(w*4+1));for(let y=0;y<h;y++)rgba.copy(scan,y*(w*4+1)+1,y*w*4,(y+1)*w*4);return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),pngChunk('IHDR',header),pngChunk('IDAT',deflateSync(scan)),pngChunk('IEND',Buffer.alloc(0))])}
function cap(stats){assert(stats.terrainBytes+stats.art.residentBytes<512*1024*1024,`Known terrain+art nominal RGBA exceeded 512 MiB safety stop: ${JSON.stringify(stats)}`);assert.equal(stats.canvasCount,1);report.runtimeErrors.push(...stats.errors.map(error=>({variant,error})))}
async function capture(name){const value=await page.evaluate(()=>window.qa.capture()),bytes=Buffer.from(value.rgba,'base64');cap(value.stats);assert.equal(bytes.length,value.width*value.height*4);const colors=new Set();for(let i=0;i<bytes.length;i+=4)colors.add(bytes.readUInt32LE(i));const nonblankRequired=!name.startsWith('pending-')||name.endsWith('-final');if(nonblankRequired)assert(colors.size>8,'Blank or near-blank warmed renderer capture');const stem=`${variant}-${name}`;await writeFile(path.join(out,`${stem}.rgba.gz`),gzipSync(bytes));await writeFile(path.join(out,`${stem}.native-extract.png`),png(value.width,value.height,bytes));await page.locator('#field > canvas').screenshot({path:path.join(out,`${stem}.screen.png`)});const row={variant,name,width:value.width,height:value.height,rgbaSHA256:sha(bytes),distinctRGBA:colors.size,nonblankRequired,stats:value.stats};report.cases.push(row);await flush();return row}
async function flush(){await writeFile(path.join(out,'result.json'),JSON.stringify(report,null,2)+'\n')}
async function dispose(){const value=await page.evaluate(()=>window.qa.dispose());report.lifecycle.push({variant,...value});assert(value.unchangedSnapshots);assert.equal(value.canvases,0);assert.equal(value.actors,0);assert.equal(value.chunks,0);assert.equal(value.art.residentBytes,0);report.runtimeErrors.push(...value.errors.map(error=>({variant,error})));await page.close();page=undefined;await flush()}
async function newPage(){assert(!page,'One active page/canvas at a time');page=await browser.newPage({viewport:{width:640,height:480},deviceScaleFactor:1,reducedMotion:'reduce'});page.setDefaultTimeout(60000);page.on('pageerror',e=>report.raw.page.push({variant,error:String(e)}));page.on('console',m=>{report.consoleLog.push({variant,type:m.type(),text:m.text()});if(['error','warning'].includes(m.type()))report.raw.console.push({variant,type:m.type(),text:m.text()})});page.on('requestfailed',r=>report.raw.requestfailed.push({variant,url:r.url(),failure:r.failure(),method:r.method()}));page.on('response',r=>{if(r.status()>=400)report.raw.http.push({variant,url:r.url(),status:r.status()})});const cdp=await page.context().newCDPSession(page);await cdp.send('Network.enable');cdp.on('Network.loadingFailed',e=>report.raw.cdp.push({variant,...e}));await page.goto(`http://127.0.0.1:${server.address().port}/`,{waitUntil:'load'});await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.title(),'Frozen renderer acceptance');assert.equal(await page.locator('#field').count(),1);assert.equal(await page.locator('vite-error-overlay').count(),0)}
async function compare(name,beforeVariant,afterVariant,beforeName=name,afterName=name){const a=report.cases.find(r=>r.variant===beforeVariant&&r.name===beforeName),b=report.cases.find(r=>r.variant===afterVariant&&r.name===afterName);assert(a&&b);assert.equal(a.width,b.width);assert.equal(a.height,b.height);const before=gunzipSync(await readFile(path.join(out,`${beforeVariant}-${beforeName}.rgba.gz`))),after=gunzipSync(await readFile(path.join(out,`${afterVariant}-${afterName}.rgba.gz`))),diff=Buffer.alloc(before.length);let pixels=0,channels=0,maxDelta=0,left=a.width,top=a.height,right=-1,bottom=-1;for(let i=0;i<before.length;i+=4){let changed=false;for(let k=0;k<4;k++){const d=Math.abs(before[i+k]-after[i+k]);if(d){channels++;changed=true;maxDelta=Math.max(maxDelta,d)}diff[i+k]=k===3?255:d}if(changed){pixels++;const p=i/4,x=p%a.width,y=Math.floor(p/a.width);left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y)}}const result={name,beforeVariant,afterVariant,beforeName,afterName,exact:pixels===0,changedPixels:pixels,changedChannels:channels,maxChannelDelta:maxDelta,bounds:pixels?{left,top,right,bottom}:null};report.comparisons.push(result);if(pixels)await writeFile(path.join(out,`${name}.diff.png`),png(a.width,a.height,diff));await flush();return result}

try{
 server=createServer(async(req,res)=>{const id=++requestID,started=Date.now(),v=variant;try{const pathname=decodeURIComponent(new URL(req.url,'http://local').pathname);assert(!pathname.split('/').includes('..'));let bytes,file;if(pathname==='/'){bytes=Buffer.from(html);file='fixture HTML'}else if(pathname==='/fixture.js'||pathname==='/fixture.js.map'){file=path.join(work,'supplement-prepared',v,pathname.slice(1));bytes=await readFile(file)}else if(pathname.startsWith('/fixture/')){assert(/^\/(fixture)\/(catalog|ground-(map|before|after)|air-(map|before|after|absence))\.json$/.test(pathname));file=path.join(work,'supplement-prepared',pathname.slice('/fixture/'.length));bytes=await readFile(file)}else{file=path.join(lock.products[v].product,pathname);bytes=await readFile(file);const expected=lock.products[v].files.find(f=>f.path===pathname);if(expected){assert.equal(sha(bytes),expected.sha256);assert.equal(bytes.length,expected.bytes)}else assert.equal(sha(bytes),lock.pins[file],`Undeclared product request: ${pathname}`)}const row={id,variant:v,path:pathname,file,bytes:bytes.length,sha256:sha(bytes),started,finished:false};report.requests.push(row);res.once('finish',()=>{row.finished=true;row.ended=Date.now()});res.setHeader('Content-Type',pathname.endsWith('.png')?'image/png':pathname.endsWith('.js')?'text/javascript':pathname==='/'?'text/html':pathname.endsWith('.wasm')?'application/wasm':'application/json');res.setHeader('Content-Length',String(bytes.length));res.setHeader('Cache-Control','no-store');res.end(bytes)}catch(e){report.raw.server.push({id,variant:v,url:req.url,error:String(e.stack??e)});res.statusCode=404;res.end(String(e))}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
 browserServer=await chromium.launchServer({executablePath:lock.browser.executable,headless:false,args:['--mute-audio'],timeout:30000});report.browserPID=browserServer.process().pid;browser=await chromium.connect(browserServer.wsEndpoint());report.browserVersion=browser.version();assert(report.browserVersion.startsWith('154.'),'Pinned genuine browser version mismatch');
 variant='performance';await newPage();const start=await page.evaluate(()=>window.qa.pressureStart());report.guards.push({variant,stage:'initial-pressure-picking-before-assertion',start});await flush();assert(start.pick&&start.actor.visible&&!start.actor.standIn);await capture('pressure-before');const loaded=await page.evaluate(()=>window.qa.pressureLoad());cap(loaded.stats);assert(loaded.stats.art.residentBytes>192*1024*1024);const trimmed=await page.evaluate(()=>window.qa.pressureTrim());cap(trimmed.stats);assert(trimmed.stats.art.residentBytes<=192*1024*1024);assert(trimmed.pick&&trimmed.actor.visible);assert(trimmed.observation.evicted.length>0);assert(trimmed.observation.evicted.every(p=>p.textureDestroyed&&p.bitmapWidthAfterClose===0));await capture('pressure-after-trim');await compare('pressure-trim-pixels','performance','performance','pressure-before','pressure-after-trim');const reloaded=await page.evaluate(()=>window.qa.pressureReload());cap(reloaded.stats);assert(reloaded.pick&&reloaded.reloaded.width>0);await capture('pressure-after-reload');await compare('pressure-reload-pixels','performance','performance','pressure-before','pressure-after-reload');await page.mouse.click(reloaded.pick.point.x,reloaded.pick.point.y);const clicks=await page.evaluate(()=>window.qa.gestures());assert(clicks.some(g=>g.kind==='click'&&g.hit?.kind==='entity'&&g.hit.id===27));report.guards.push({variant,stage:'real-page-pressure',start,loaded,trimmed,reloaded,clicks});await dispose();
 report.functionalComplete=true;report.status=report.comparisons.every(c=>c.exact)&&Object.values(report.raw).every(a=>a.length===0)&&report.runtimeErrors.length===0?'passed':'failed';
}catch(error){report.status='failed';report.error=String(error.stack??error);if(page)try{await page.screenshot({path:path.join(out,'failure.png')});report.failureState=await page.evaluate(()=>({title:document.title,ready:document.body.dataset.ready,text:document.body.innerText,canvases:document.querySelectorAll('canvas').length}))}catch(e){report.failureCaptureError=String(e)}}finally{
 if(page)try{report.finalEmergencyDisposal=await page.evaluate(()=>window.qa?.dispose())}catch(e){report.cleanupError=String(e)}
 if(browser)await browser.close();if(browserServer)await browserServer.close();if(server)await new Promise(resolve=>server.close(resolve));report.closedAt=new Date().toISOString();report.browserAndHTTPClosed=true;
 for(const [file,expected] of Object.entries(lock.pins)){const actual=sha(await readFile(file));if(actual!==expected)pinsAfter[file]={expected,actual}}report.inputDrift=pinsAfter;if(Object.keys(pinsAfter).length)report.status='failed';await flush();console.log(JSON.stringify({status:report.status,functionalComplete:report.functionalComplete,captures:report.cases.length,comparisons:report.comparisons.length,pixelDifferences:report.comparisons.filter(c=>!c.exact),raw:Object.fromEntries(Object.entries(report.raw).map(([k,v])=>[k,v.length])),error:report.error,out},null,2));if(report.status!=='passed')process.exitCode=1;
}
