import {minimapLayout,minimapProject} from '../../src/render/minimap.ts';
import {createHash} from 'node:crypto';
// DOM admission/readiness/reconnect/debrief + a disclosed scripted commander
// using normal product transport/advice. No engine state, opponent-private view,
// resource grants, spawns, surrender, fixture missions, or altered deadlines.
import {chromium} from 'playwright-core';
import {spawn} from 'node:child_process';
import {mkdir,readFile,writeFile,appendFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
import {prepareProduct,root,evidence,buildDir,product} from './multiplayer-combat-build.mjs';
const build=await prepareProduct(),runDir=path.join(evidence,new Date().toISOString().replaceAll(':','-'));await mkdir(runDir,{recursive:true});
const {fromBinary,EnvelopeSchema,applyDelta}=await import(pathToFileURL(path.join(buildDir,'decode.mjs')));
const map=JSON.parse(await readFile(path.join(product,'content/maps/industrial-valley.json'),'utf8'));
const rules=JSON.parse(await readFile(path.join(root,'pkg/content/rules.json'),'utf8'));
const factions=['US','IR','SY','SA'];
const definitions=[{id:'1h1ai',humans:1,bots:1,mode:'custom'}, {id:'1h3ai',humans:1,bots:3,mode:'ffa'}, {id:'2h',humans:2,bots:0,mode:'1v1'}, {id:'2h2ai',humans:2,bots:2,mode:'custom',teams:true}, {id:'3h',humans:3,bots:0,mode:'ffa'}, {id:'4h2v2',humans:4,bots:0,mode:'2v2',teams:true}];
const selected=process.env.FRONTLINE_COMBAT_CASE?.split(',')??['1h1ai'];assert(selected.every(id=>definitions.some(d=>d.id===id)));
const browser=await chromium.launch({headless:process.env.FRONTLINE_COMBAT_HEADED!=='1',...(process.env.FRONTLINE_COMBAT_HEADED==='1'?{channel:'chromium'}:{})});
const driver=await readFile(new URL(import.meta.url));await writeFile(path.join(runDir,'driver.mjs'),driver);
const report={headless:process.env.FRONTLINE_COMBAT_HEADED!=='1',driverSHA256:createHash('sha256').update(driver).digest('hex'),started:new Date().toISOString(),browser:browser.version(),build,conditions:process.env.FRONTLINE_COMBAT_CONDITIONS??'Shared host; no performance claim.',scope:'Actual rendered product; DOM lobby/readiness/reconnect/debrief, scripted normal-transport economy/combat. Separate loopback browser contexts, not physical LAN. Frozen combined 0.3.4, incomplete art recorded per client. No simulation mutations or deliberate loss.',cases:[]};
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),json=value=>JSON.stringify(value,(_k,v)=>typeof v==='bigint'?v.toString():v,2);
async function until(check,message,timeout=30000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw Error(message);await sleep(150)}}
async function idle(page){await until(async()=>await page.locator('.network-operation,.loading-screen').count()===0,'Operation remained busy',120000);if(await page.locator('.network-error').count())throw Error(await page.locator('.network-error').allInnerTexts())}
async function saveReport(){await writeFile(path.join(runDir,'browser.json'),json(report));await writeFile(path.join(evidence,'latest.json'),json({runDir,status:report.status??'running',cases:report.cases.map(({id,status,progress})=>({id,status,progress}))}))}
async function hostStart(id){const data=path.join(runDir,`host-${id}-data`);await mkdir(data,{recursive:true});const child=spawn(path.join(buildDir,'frontline'),['-addr','127.0.0.1:0','-data',data,'-static',product,'-maps',path.join(product,'content/maps'),'-missions',path.join(product,'content/missions')],{cwd:root,stdio:['ignore','pipe','pipe']});let log='';const origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Host startup timed out')),30000);child.stdout.on('data',b=>{log+=b;const found=log.match(/http:\/\/127\.0\.0\.1:\d+/);if(found){clearTimeout(timer);resolve(found[0])}});child.stderr.on('data',b=>log+=b);child.once('exit',code=>{clearTimeout(timer);reject(Error('Host exited '+code))})});await writeFile(path.join(runDir,`host-${id}.pid`),String(child.pid));return {origin,async close(){if(child.exitCode===null){const ended=new Promise(r=>child.once('exit',r));child.kill('SIGTERM');await ended}await writeFile(path.join(runDir,`host-${id}.log`),log)}}}
function observe(page,record,player){const state={snapshot:undefined,sockets:0,results:new Map(),orders:[],events:new Map(),result:undefined};page.on('pageerror',e=>record.errors.push({player,kind:'pageerror',message:e.message,stack:e.stack}));page.on('console',m=>{if(m.type()==='error')record.errors.push({player,kind:'console',message:m.text(),location:m.location()})});page.on('response',async response=>{const pathname=new URL(response.url()).pathname;if(pathname==='/api/v1/history'&&response.ok()){try{const records=await response.json();(record.historyResponses??=[]).push({player,time:new Date().toISOString(),matchIDs:records.map(item=>item.id)})}catch(error){record.errors.push({player,kind:'history-response',message:String(error)})}return}if(response.status()<400)return;const item={player,path:pathname,status:response.status()};if(pathname.endsWith('/advice')){const request=response.request();item.requestTiming=request.timing();try{const body=request.postDataJSON();item.adviceRequest={entities:body.entities,orders:body.orders,independent:body.independent}}catch{item.adviceRequest='unreadable'}}(record.httpErrors??=[]).push(item);try{const body=await response.json();item.code=body.code;item.message=body.message}catch(error){item.readError=String(error)}});page.on('websocket',socket=>{state.sockets++;socket.on('framereceived',frame=>{if(typeof frame.payload==='string')return;try{const message=fromBinary(EnvelopeSchema,new Uint8Array(frame.payload)).message;if(message.case==='snapshot')state.snapshot=message.value;else if(message.case==='delta')state.snapshot=applyDelta(state.snapshot,message.value);else if(message.case==='result')state.result=message.value;else if(message.case==='orderResult'){const r=message.value;state.results.set(`${r.sequence}:${r.index}`,r)}if(['snapshot','delta'].includes(message.case)){for(const r of state.snapshot.results)state.results.set(`${r.sequence}:${r.index}`,r);for(const e of state.snapshot.events)state.events.set(String(e.id),{kind:e.kind,tick:e.tick,owner:e.owner,entity:e.entity});for(const e of state.snapshot.entities)assert(!e.private||e.owner===player,'Foreign private data exposed')}}catch(e){record.errors.push({player,kind:'decoder',message:e.message})}});socket.on('framesent',frame=>{if(typeof frame.payload==='string')return;const message=fromBinary(EnvelopeSchema,new Uint8Array(frame.payload)).message;if(message.case==='orders')state.orders.push(message.value)})});return state}
async function focus(page,position){const box=await page.getByLabel('Tactical minimap',{exact:true}).boundingBox();if(box){const point=minimapProject(minimapLayout(map.width,map.height,box.width,box.height),position);await page.mouse.click(box.x+point.x,box.y+point.y);await sleep(150)}}
async function capture(page,id){await page.screenshot({path:path.join(runDir,id+'.png')})}
class Commander {
 constructor(page,frame,record,player){this.page=page;this.frame=frame;this.record=record;this.player=player;this.failedBuilds=new Map();this.lastAttack=new Map();this.lastBuild=0;this.lastLog=0;this.started=false;this.search=0;this.lastSearch=0;this.busy=false;this.adviceErrors=0}
 get view(){return this.frame.snapshot}
 async send(orders,note){if(!orders.length)return;const tick=this.view.tick;const sequence=await this.page.evaluate(orders=>window.multiplayerCombat.send(orders),orders);await until(()=>orders.every((_o,i)=>this.frame.results.has(`${sequence}:${i}`)),'Missing command receipts',10000);const receipts=orders.map((_o,i)=>this.frame.results.get(`${sequence}:${i}`));const item={player:this.player,tick,sequence,note,orders,receipts};await appendFile(path.join(runDir,`${this.record.id}-commands.jsonl`),json(item).replaceAll('\n','')+'\n');this.record.commands++;return receipts}
 async advice(ids,orders=[],independent=false){try{return await this.page.evaluate(async({ids,orders,independent})=>window.multiplayerCombat.advice(ids,orders,independent),{ids,orders,independent})}catch(error){if(/advice|Wait for|selection|current command|provide current|current selection/i.test(error.message)){this.adviceErrors++;return}throw error}}
 async construct(type,rig,base,view){
  if(view.tick-this.lastBuild<40)return;this.lastBuild=view.tick;
  const center=type==='supply'?[...map.fields].sort((a,b)=>distance(a.position,base)-distance(b.position,base))[0].position:base;
  const positions=[];
  // Candidate points, not a placement validator: every decision goes to Go.
  for(let radius=4500;radius<=16500;radius+=2000)for(const [x,y] of [[1,0],[0,1],[-1,0],[0,-1],[1,1],[-1,1],[-1,-1],[1,-1]]){const position={x:Math.floor((center.x+x*radius)/1000)*1000+500,y:Math.floor((center.y+y*radius)/1000)*1000+500};if(position.x>3000&&position.y>3000&&position.x<map.width*1000-3000&&position.y<map.height*1000-3000){const key=`${type}:${position.x}:${position.y}`;if(view.tick-(this.failedBuilds.get(key)??-10000)>600)positions.push(position)}}
  positions.sort((a,b)=>type==='supply'?distance(a,center)+distance(a,base)*.3-distance(b,center)-distance(b,base)*.3:distance(a,base)-distance(b,base));
  for(let offset=0;offset<positions.length;offset+=24){const choices=positions.slice(offset,offset+24).map(position=>({kind:'build',entities:[rig.id],type,position})),advice=await this.advice([],choices,false);if(!advice)return;const index=advice.results.findIndex(r=>r.accepted);if(index<0)continue;const choice=choices[index],receipts=await this.send([choice],'Go-previewed paid construction');if(receipts?.[0].accepted)return;this.failedBuilds.set(`${type}:${choice.position.x}:${choice.position.y}`,view.tick);return}
 }
 async step(){const view=this.view;if(!view||view.countdown||view.outcome?.finished)return;const me=view.players.find(p=>p.id===this.player);if(me?.defeated)return;const own=view.entities.filter(e=>e.owner===this.player),units=own.filter(e=>rules.units.some(u=>u.id===e.type)),hq=own.find(e=>e.type==='hq'),base=hq?.position??map.spawns[this.player-1].position;const building=(type,complete=true)=>own.filter(e=>e.type===type&&(!complete||e.complete)),rig=units.find(e=>e.type===me.faction+'.rig'&&!e.private?.orders.length),funds=Number(view.economy?.credits??0);const pending=own.some(e=>rules.buildings.some(b=>b.id===e.type)&&!e.complete);
  if(!this.started){this.started=true;this.record.clients.push({player:this.player,faction:me.faction,team:me.team,openingTick:view.tick,base,assets:JSON.parse(await this.page.evaluate(()=>window.multiplayerCombat.info())).assets});const scout=units.find(e=>e.type===me.faction+'.rifle');if(scout){const field=[...map.fields].sort((a,b)=>distance(a.position,base)-distance(b.position,base))[0];await this.send([{kind:'move',entities:[scout.id],position:field.position}],'Ordinary field scouting')}}
  let buildType;
  if(!building('power',false).length)buildType='power';else if(!building('supply',false).length)buildType='supply';else if(!building('barracks',false).length)buildType='barracks';else if(view.economy.powerCapacity-view.economy.powerDemand<30)buildType='power';else if(!building('factory',false).length&&funds>=2200000)buildType='factory';else if(building('factory').length&&building('barracks',false).length<2&&funds>=1600000)buildType='barracks';
  if(rig&&!pending&&buildType&&funds>=(rules.buildings.find(b=>b.id===buildType)?.cost??Infinity)){await this.construct(buildType,rig,base,view);return}
  const train=[];let budget=funds;const supply=building('supply')[0];const haulers=units.filter(e=>e.type===me.faction+'.hauler').length+(supply?.private?.jobs.filter(j=>j.type===me.faction+'.hauler').length??0);
  if(supply&&haulers<3&&budget>=900000&&supply.private?.jobs.length===0){train.push({kind:'train',entities:[supply.id],type:me.faction+'.hauler'});budget-=900000}
  // Keep ordinary economics ahead of optional army spending.
  if(building('supply').length&&building('barracks').length){const reserve=building('factory').length?0:1500000;
   for(const producer of [...building('factory'),...building('barracks')]){if(producer.private?.jobs.length||budget<reserve+300000||view.economy.supply+view.economy.reservedSupply>=96)continue;let type;if(producer.type==='factory'){const tanks=units.filter(e=>e.type===me.faction+'.tank').length,aas=units.filter(e=>e.type===me.faction+'.aa').length;type=aas<Math.floor(tanks/3)?me.faction+'.aa':me.faction+'.tank'}else{const rifles=units.filter(e=>e.type===me.faction+'.rifle').length,ats=units.filter(e=>e.type===me.faction+'.at').length;type=ats<Math.ceil(rifles*.65)?me.faction+'.at':me.faction+'.rifle'}const u=rules.units.find(u=>u.id===type);if(u&&u.cost+reserve<=budget){train.push({kind:'train',entities:[producer.id],type});budget-=u.cost}}
  }
  if(train.length)await this.send(train,'Paid producer queues');
  const army=units.filter(e=>{const u=rules.units.find(u=>u.id===e.type);return u?.weapon&&['rifle','at','tank','aa','recon'].includes(u.role)&&!e.private?.container});
  const foes=view.players.filter(p=>p.team!==me.team&&!p.defeated);if(!foes.length)return;const enemyIDs=new Set(foes.map(p=>p.id)),seen=view.entities.filter(e=>enemyIDs.has(e.owner));
  let destination=map.spawns[foes[0].id-1].position;
  const valuable=seen.filter(e=>rules.buildings.find(b=>b.id===e.type)?.qualifying||e.type.endsWith('.rig'));
  if(valuable.length){valuable.sort((a,b)=>distance(a.position,base)-distance(b.position,base));destination=valuable[0].position}
  if(!this.record.ownershipRejections?.some(r=>r.player===this.player)&&seen.length){const receipts=await this.send([{kind:'stop',entities:[seen[0].id]}],'Expected rejection: cannot command visible enemy');assert.equal(receipts[0].accepted,false);assert.equal(receipts[0].code,'not_owner');(this.record.ownershipRejections??=[]).push({player:this.player,tick:view.tick,target:seen[0].id,code:receipts[0].code})}
  const threats=seen.filter(e=>rules.units.find(u=>u.id===e.type)?.weapon&&distance(e.position,base)<18000);
  if(threats.length)destination=threats[0].position;
  const attacking=army.length>=8||view.tick>7200||threats.length>0;
  if(attacking){
   if(!valuable.length&&army.some(e=>distance(e.position,destination)<3000)&&view.tick-this.lastSearch>400){this.search++;this.lastSearch=view.tick;const offset=[[0,0],[9000,0],[0,9000],[-9000,0],[0,-9000],[15000,15000],[-15000,15000],[-15000,-15000],[15000,-15000]][this.search%9];destination={x:Math.max(1000,Math.min(map.width*1000-1000,destination.x+offset[0])),y:Math.max(1000,Math.min(map.height*1000-1000,destination.y+offset[1]))}}
   const ready=army.filter(e=>{const previous=this.lastAttack.get(e.id),order=e.private?.orders[0];return !order||!previous||view.tick-previous.tick>400&&distance(previous.position,destination)>5000});
   if(ready.length){const enemyArmy=seen.filter(e=>rules.units.find(u=>u.id===e.type)?.weapon);const target=valuable.find(e=>distance(e.position,destination)<100&&!enemyArmy.some(enemy=>distance(enemy.position,e.position)<12000)),orders=[];for(let i=0;i<ready.length;i+=60)orders.push(target?{kind:'attack',entities:ready.slice(i,i+60).map(e=>e.id),target:target.id}:{kind:'attack_move',entities:ready.slice(i,i+60).map(e=>e.id),position:destination});const receipts=await this.send(orders,'Visible target attack / public-spawn attack-move');if(receipts?.some(r=>r.accepted))for(const e of ready)this.lastAttack.set(e.id,{tick:view.tick,position:destination})}
  }
 }
}
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
async function scenario(config){const record={...config,status:'running',phase:'lobby',clients:[],commands:0,errors:[],milestones:[]};report.cases.push(record);const server=await hostStart(config.id),contexts=[],pages=[],frames=[];try{
 record.origin=server.origin;for(let i=0;i<config.humans;i++){const context=await browser.newContext({viewport:{width:i%2?1280:1600,height:i%2?720:900},acceptDownloads:true}),page=await context.newPage();page.setDefaultTimeout(90000);contexts.push(context);pages.push(page);frames.push(observe(page,record,i+1));await page.goto(server.origin);assert.equal(await page.title(),'Frontline Command');await page.getByRole('button',{name:'Explore game modes',exact:true}).click();await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(page);await page.getByLabel('Commander name',{exact:true}).fill(`Combat ${config.id} ${i+1}`);await page.getByRole('button',{name:'Create local profile',exact:true}).click();await page.getByLabel('Your profile ID').waitFor();await idle(page)}
 const host=pages[0];record.profiles=await Promise.all(pages.map(p=>p.getByLabel('Your profile ID').inputValue()));assert.equal(new Set(record.profiles).size,pages.length);await host.getByLabel('Operation name',{exact:true}).fill(`Ordinary combat ${config.id}`);await host.getByLabel('Lobby battlefield',{exact:true}).selectOption('industrial-valley');await host.getByLabel('Battle format',{exact:true}).selectOption(config.mode);await host.getByLabel('Host faction',{exact:true}).selectOption('US');await host.getByRole('button',{name:'Create operation',exact:true}).click();await idle(host);record.lobby=await host.getByLabel('Current lobby ID').inputValue();
 for(let i=1;i<pages.length;i++){await pages[i].getByLabel('Join lobby ID').fill(record.lobby);await pages[i].getByRole('button',{name:'Join by ID',exact:true}).click();await idle(pages[i])}
 for(let i=0;i<pages.length;i++){await pages[i].getByLabel(`Commander ${i+1} faction`,{exact:true}).selectOption(factions[i]);await idle(pages[i]);if(config.teams){await pages[i].getByLabel(`Commander ${i+1} team`,{exact:true}).selectOption(i<2?'1':'2');await idle(pages[i])}}
 for(let i=0;i<config.bots;i++){await host.getByLabel('Add AI faction',{exact:true}).selectOption(factions[config.humans+i]);await host.getByLabel('Add AI difficulty',{exact:true}).selectOption('normal');if(config.mode!=='ffa')await host.getByLabel('Add AI team',{exact:true}).selectOption(config.teams?'2':String(config.humans+i+1));await host.getByRole('button',{name:'Add AI commander',exact:true}).click();await idle(host)}
 await until(async()=>await host.locator('.network-commander').count()===config.humans+config.bots,'Roster not complete');await sleep(2200);assert(await host.getByRole('button',{name:'Start operation',exact:true}).isDisabled());record.startBlockedBeforeReady=true;
 for(let i=0;i<pages.length;i++){await pages[i].getByRole('button',{name:'Ready to deploy',exact:true}).click();await idle(pages[i]);if(i<pages.length-1)assert(await host.getByRole('button',{name:'Start operation',exact:true}).isDisabled())}
 await until(()=>host.getByRole('button',{name:'Start operation',exact:true}).isEnabled(),'Readiness did not unlock start');await capture(host,`${config.id}-lobby`);await host.getByRole('button',{name:'Start operation',exact:true}).click();for(const page of pages){await page.getByRole('complementary',{name:'Command sidebar'}).waitFor();await page.locator('.scene-loading').waitFor({state:'hidden'})}await until(()=>frames.every(f=>f.snapshot?.tick>130),'Countdown did not finish',90000);
 const gpuSession=await browser.newBrowserCDPSession();try{record.gpu=(await gpuSession.send('SystemInfo.getInfo')).gpu}finally{await gpuSession.detach()}
 if(!report.headless){const renderer=record.gpu.auxAttributes?.glRenderer??'';assert.match(renderer,/Metal|Apple/i,'Headed acceptance must verify actual hardware renderer');assert.doesNotMatch(renderer,/SwiftShader|software/i,'Headed launch alone does not prove hardware acceleration')}

 record.phase='ordinary-combat';record.started=new Date().toISOString();const commanders=pages.map((p,i)=>new Commander(p,frames[i],record,i+1));let reconnected=false,lastLog=0,lastCapture=0;const started=Date.now(),wallLimit=Number(process.env.FRONTLINE_COMBAT_MINUTES??60)*60000;
 while(!frames.some(f=>f.result?.committed||f.snapshot?.outcome?.finished)&&!JSON.parse(await host.evaluate(()=>window.multiplayerCombat.info())).result?.committed){
  if(Date.now()-started>wallLimit)throw Error(`Incomplete ordinary match after ${wallLimit/60000} wall minutes; no forced result`);
  for(const commander of commanders)await commander.step();
  const tick=Math.max(...frames.map(f=>f.snapshot?.tick??0));
  if(!reconnected&&tick>3600&&!frames[0].snapshot.players.find(p=>p.id===1)?.defeated){const before={tick:frames[0].snapshot.tick,sequence:frames[0].snapshot.economy.lastSequence,sockets:frames[0].sockets};await host.getByRole('button',{name:'Open pause menu',exact:true}).click();await host.getByRole('region',{name:'Online operation controls'}).first().waitFor();await host.getByRole('button',{name:'Reconnect',exact:true}).click();await idle(host);await until(()=>frames[0].sockets>before.sockets&&frames[0].snapshot.tick>=before.tick,'Reconnect did not recover');record.reconnect={before,after:{tick:frames[0].snapshot.tick,sequence:frames[0].snapshot.economy.lastSequence,sockets:frames[0].sockets}};await host.getByRole('button',{name:'Return to battlefield',exact:true}).click();reconnected=true}
  if(tick-lastLog>=600){lastLog=tick;record.progress=frames.map(f=>({player:f.snapshot.player,tick:f.snapshot.tick,economy:f.snapshot.economy,owned:f.snapshot.entities.filter(e=>e.owner===f.snapshot.player).reduce((out,e)=>(out[e.type]=(out[e.type]??0)+1,out),{}),players:f.snapshot.players.map(p=>({id:p.id,defeated:p.defeated})),events:[...f.events.values()].reduce((out,e)=>(out[e.kind]=(out[e.kind]??0)+1,out),{})}));console.log(config.id,'tick',tick,record.progress.map(p=>`P${p.player} credits ${p.economy?.credits} supply ${p.economy?.supply}`).join(' | '));await appendFile(path.join(runDir,`${config.id}-progress.jsonl`),json({time:new Date().toISOString(),players:record.progress}).replaceAll('\n','')+'\n');await saveReport()}
  if(tick-lastCapture>=2400){lastCapture=tick;const view=frames[0].snapshot,army=view.entities.filter(e=>e.owner===view.player&&rules.units.find(u=>u.id===e.type)?.weapon),engaged=army.find(e=>['firing','aiming'].includes(e.state))??army.at(-1);if(engaged)await focus(host,engaged.position);await capture(host,`${config.id}-tick-${tick}`);await writeFile(path.join(runDir,`${config.id}-view-${tick}.json`),json(view))}await sleep(1800);
 }
 record.phase='committed-result';await until(async()=>frames.some(f=>f.result?.committed)||JSON.parse(await host.evaluate(()=>window.multiplayerCombat.info())).result?.committed,'Result not committed',30000);for(let i=0;i<pages.length;i++){const info=JSON.parse(await pages[i].evaluate(()=>window.multiplayerCombat.info()));record.clients[i].final={tick:frames[i].snapshot.tick,info,events:[...frames[i].events.values()].reduce((out,e)=>(out[e.kind]=(out[e.kind]??0)+1,out),{})};assert(!frames[i].orders.some(batch=>batch.orders.some(o=>['surrender','surrender_vote','sell'].includes(o.kind))),'Forbidden acceleration order');await capture(pages[i],`${config.id}-player-${i+1}-debrief`)}
 const result=frames.find(f=>f.result?.committed)?.result??JSON.parse(await host.evaluate(()=>window.multiplayerCombat.info())).result;record.result=result;record.adviceRetries=commanders.map(c=>({player:c.player,count:c.adviceErrors}));assert.equal(result.outcome.reason,'elimination');assert(!result.outcome.draw);
 // An eliminated host must independently recover the exact committed result;
 // another participant receiving it is insufficient proof of host durability.
 const frozenBefore=frames[0].snapshot.players.find(p=>p.id===1)?.defeated?json(frames[0].snapshot):undefined;let hostResult;
 await until(async()=>{hostResult=JSON.parse(await host.evaluate(()=>window.multiplayerCombat.info())).result;return hostResult?.committed&&hostResult.matchId===result.matchId},'Eliminated host did not recover its committed result',30000);
 record.hostRecoveredResult={result:hostResult,liveTick:frames[0].snapshot.tick,ownSnapshotUnchanged:frozenBefore===undefined?undefined:json(frames[0].snapshot)===frozenBefore};
 if(frozenBefore!==undefined)assert.equal(json(frames[0].snapshot),frozenBefore,'Durable result recovery must preserve the eliminated private snapshot');
 // The real product archive action validates bytes in its Go WASM inspector.
 const archiveButton=host.getByRole('button',{name:'Save match replay',exact:true}).first();
 // Earlier-eliminated participants retain a frozen private view; their durable
 // result is correctly exposed by the ordinary network menu, not a final live
 // snapshot/debrief. Use that public path rather than assume an auto-open modal.
 if(!await archiveButton.count()){await host.getByRole('button',{name:'Open pause menu',exact:true}).click();await host.getByRole('region',{name:'Online operation controls'}).first().waitFor();record.archiveViaMenu=true;await capture(host,`${config.id}-recorded-result-menu`)}
 await archiveButton.click();await idle(host);let replay;await until(async()=>{replay=await host.evaluate(()=>window.multiplayerCombat.replay());return !!replay},'Replay not archived',120000);await writeFile(path.join(runDir,`${config.id}.replay.gz`),new Uint8Array(replay.data));record.replay={sha256:replay.sha256,bytes:replay.data.length};assert.deepEqual(record.errors,[]);assert.deepEqual(record.httpErrors??[],[]);record.status='passed';record.completed=new Date().toISOString();
 }catch(error){record.status='failed';record.failure=String(error.stack??error);for(let i=0;i<pages.length;i++){await capture(pages[i],`${config.id}-failure-${i+1}`).catch(()=>{});await writeFile(path.join(runDir,`${config.id}-failure-view-${i+1}.json`),json(frames[i].snapshot??null))}process.exitCode=1}
 finally{await saveReport();for(const context of contexts)await context.close();await server.close()}}
async function nativeAudit(record){
 const target=path.join(runDir,`${record.id}-native-audit`),replay=path.join(runDir,`${record.id}.replay.gz`);let log='';
 const child=spawn(path.join(evidence,'audit-replay'),['-replay',replay,'-out',target],{cwd:root,stdio:['ignore','pipe','pipe']});for(const stream of [child.stdout,child.stderr])stream.on('data',chunk=>log+=chunk);
 const code=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve)});await writeFile(path.join(runDir,`${record.id}-native-audit.log`),log);assert.equal(code,0,'Native replay/save verification failed');record.nativeProof=JSON.parse(await readFile(path.join(target,'audit.json'),'utf8'));await saveReport();
}
try{for(const config of definitions.filter(d=>selected.includes(d.id))){await scenario(config);const record=report.cases.at(-1);if(record.status!=='passed')break;try{record.phase='native-replay-verification';await saveReport();await nativeAudit(record);record.phase='complete'}catch(error){record.status='failed';record.failure=String(error.stack??error);process.exitCode=1;break}}}finally{report.completed=new Date().toISOString();report.status=report.cases.every(c=>c.status==='passed')?'passed':'failed';await saveReport();await browser.close();console.log(report.status,runDir)}
