import test from 'node:test';
import assert from 'node:assert/strict';
import {reconcileGenerationDiagnostic} from './native-diagnostic.mjs';
const url='http://127.0.0.1:1234/art/page.png',hash='1'.repeat(64),phase='pending-network-A-host-swap';
function fixture(){return {snapshots:[{network:[{id:'page:7',scope:'document-A',method:'GET',url,ordinal:1,realm:'window-fetch',proof:{targetId:'page',executionContextId:2},status:200,redirected:false,fromServiceWorker:false,responseURL:url,stamp:{phase}}],traces:[{scope:'document-A',faults:[],overflow:0,records:[{scope:'document-A',method:'GET',url,ordinal:1,startedOrder:1,eofOrder:5,sha256:hash,status:200,redirected:false,responseURL:url,bytesRead:12,hashedBytes:12,completion:'explicit-native-reader',readerCount:1,readerMode:'default',bodyMethods:[],cdpObserved:{eofOrder:10}}]}],faults:[],captureFailures:[],failures:[{requestId:'page:7',url,message:'net::ERR_ABORTED',order:13,phase}]}],playwrightFailures:[{url,reason:'net::ERR_ABORTED'}],planned:[{phase,path:'/art/page.png',bytes:12,sha256:hash}]}}
test('exact original EOF/hash joins unique native request identity without claiming cancellation cause',()=>{const result=reconcileGenerationDiagnostic(fixture());assert.equal(result.diagnosticsAgree,true);assert.equal(result.exactBodyReports.length,1);assert.equal(result.exactBodyReports[0].requestId,'page:7');assert.equal(result.exactBodyReports[0].relativeEOFOrder,'failure-after-native-eof');assert.deepEqual(result.exactBodyReports[0].cancellation,[]);assert.equal(result.allRawFailures.length,1);assert.equal(result.proofs[0].complete,true)});
test('wrong/missing native bytes, reader mode, hash or EOF never attributes abort',()=>{for(const mutation of [r=>r.sha256='2'.repeat(64),r=>r.bytesRead=11,r=>r.hashedBytes=11,r=>delete r.eofOrder,r=>r.readError='truncated',r=>r.hashOverflow='limit',r=>r.readerCount=2,r=>r.readerMode='byob']){const input=fixture();mutation(input.snapshots[0].traces[0].records[0]);const result=reconcileGenerationDiagnostic(input);assert.equal(result.exactBodyReports.length,0);assert.equal(result.unprovenRawFailures.length,1)}});
test('wrong document/request provenance, service-worker responses and redirects remain unproved',()=>{for(const mutation of [r=>r.realm='unproven',r=>delete r.proof,r=>r.scope='other',r=>r.fromServiceWorker=true,r=>r.redirected=true,r=>r.responseURL=url+'?redirect',r=>r.ordinal=2]){const input=fixture();mutation(input.snapshots[0].network[0]);assert.equal(reconcileGenerationDiagnostic(input).exactBodyReports.length,0)}});
test('duplicates, overlapping ordinals and incomplete capture cannot manufacture identity',()=>{for(const mutate of [s=>s.network.push({...s.network[0]}),s=>s.failures.push({...s.failures[0]}),s=>s.faults.push('capture-error'),s=>s.traces[0].overflow=1,s=>s.traces[0].records.push({...s.traces[0].records[0],ordinal:2,startedOrder:4})]){const input=fixture();mutate(input.snapshots[0]);assert.equal(reconcileGenerationDiagnostic(input).exactBodyReports.length,0)}});
test('Playwright/native diagnostics disagreement remains explicit even if body was complete',()=>{const input=fixture();input.playwrightFailures=[];const result=reconcileGenerationDiagnostic(input);assert.equal(result.diagnosticsAgree,false);assert.equal(result.allRawFailures.length,1)});
test('native failure before EOF is recorded accurately, never relabeled as cancellation after EOF',()=>{const input=fixture();input.snapshots[0].failures[0].order=3;const result=reconcileGenerationDiagnostic(input);assert.equal(result.exactBodyReports.length,1);assert.equal(result.exactBodyReports[0].relativeEOFOrder,'failure-before-native-eof');assert.deepEqual(result.exactBodyReports[0].cancellation,[])});
test('known URL in a different phase does not receive a planned byte identity',()=>{const input=fixture();input.snapshots[0].network[0].stamp.phase='unplanned';const result=reconcileGenerationDiagnostic(input);assert.equal(result.proofs.length,0);assert.equal(result.unprovenRawFailures.length,1);assert.deepEqual(result.missingPlannedScenarios,[phase])});
