"""Exact old complete building handoffs; no rendered pixels or source edits."""
from pathlib import Path
import hashlib,json,shutil,re
B=Path(__file__).resolve().parent;R=B.parents[2];S=R/'work/art/building-polish-production-v2';F=S/'work/art/building-roster';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();rel=lambda p:str(p.relative_to(R));dump=lambda p,v:p.write_text(json.dumps(v,indent=2)+'\n')
audit=json.loads((B/'audit-v1.json').read_text());assert audit['failures']==0
for name,want in audit['inputs'].items():assert sha(R/name)==want,name
historical_lock=R/'work/art/faction-service-polish-opus-v1/render-lock.json';render_lock=json.loads(historical_lock.read_text())['files'];recovered={'assets/pipeline/blender/fclib.py':R/'work/art/producer-go-parking-pilot-v4/source/fclib.py','assets/pipeline/blender/models/building_common.py':R/'assets/pipeline/blender/models/building_common.py','assets/pipeline/blender/render_ui_shots.py':R/'assets/pipeline/blender/render_ui_shots.py'}
for name,p in recovered.items():assert sha(p)==render_lock[name],name
findings={'building.US.airfield':'Single broad hangar and side tower remain recognizable; doors expose a dark cavity, service arm moves clear of the door, critical roof loss reads distinctly.','building.SA.airfield':'Twin bays and rear control tower differ from US; the service arm stays ahead of the central pier, doors open independently of the modest service loop, and critical state loses one roof.','building.IR.drone_hub':'Compact ribbed hangar, dish and side canopy remain distinct; open doors/service arm readable, critical dish and roof loss clear.','building.SY.air_workshop':'Small improvised canopy/workshop and asymmetric apron remain compact; front arm visible clear of door/pier, critical roof removal clear.','building.IR.interceptor_battery':'Canted box launchers and dish remain distinct, two/one/zero warm missile noses correspond to state, dish stub remains in critical state.','building.SA.interceptor_battery':'Upright cells and phased array remain distinct; empty openings, one/two tips and launch departure are readable, disabled array differs from low-power.','building.SY.interceptor_battery':'Open rails and sandbag shelter remain distinct; spent rails, warm noses, team strips and lowered/dark disabled aerial retain reviewed differences.'}
results=[]
for row in audit['rows']:
 aid=row['id'];out=B/aid;assert not out.exists();out.mkdir();stage=out/'stage';evidence=out/'evidence';evidence.mkdir();sources={}
 # Model/spec are the accepted amended source. Renderer recovery uses exact old hashes,
 # not the later transparent-team helper. No old image is labeled as newly rendered.
 paths={name:S/name for name in audit['sources']if not name.startswith('assets/pipeline/specs/')or name.endswith('/'+aid+'.json')};paths.update(recovered)
 for p in (S/'assets/pipeline/tools').glob('*.py'):paths[str(p.relative_to(S))]=p
 provenance={}
 for name,p in paths.items():
  dest=stage/name;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dest);assert sha(dest)==sha(p);sources[name]=sha(p);provenance[name]={'source':rel(p),'sha256':sha(p),'scope':'Historical exact dependency recovered from original render lock'if name in recovered else 'Exact accepted stage source/tool'}
 spec=json.loads((stage/f'assets/pipeline/specs/{aid}.json').read_text());role=spec.get('role_id',aid);files=sorted(p for p in (S/f'assets/build/sprites/{aid}').iterdir()if p.is_file())+[S/f'assets/build/ui/{folder}/{role}@{scale}.{layer}.png'for folder in ['portraits','icons/build']for scale in ['1x','2x']for layer in ['beauty','team']];exports={}
 for p in files:
  dest=stage/p.relative_to(S);dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dest);assert sha(dest)==sha(p);exports[str(p.relative_to(S/'assets/build'))]={'source':rel(dest),'sha256':sha(dest),'bytes':dest.stat().st_size}
 blend=stage/f'assets/source/blender/{aid}.blend';blend.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(S/f'assets/source/blender/{aid}.blend',blend);assert sha(blend)==sha(S/f'assets/source/blender/{aid}.blend')
 original_files=[F/f'receipt-{aid}.json',F/f'check-{aid}.json',F/f'ui-check-{aid}.md',F/'production-lock.json',F/'source-amendment.json',S/'publication.json',historical_lock,R/row['pilot']/'render.json',R/row['pilot']/'check.json']
 original_pins={rel(p):sha(p)for p in original_files}
 for i,p in enumerate(original_files):shutil.copy2(p,evidence/f'{i:02d}-{p.name}')
 contact=out/'contacts'/aid;contact.mkdir(parents=True);images={};oldcontact=F/'production-contacts'/aid
 inspected=sorted(oldcontact.glob('poses-*@1x.png'))+[oldcontact/'ui-contact@1x-2x.png']
 for p in inspected:
  dest=contact/p.name;shutil.copy2(p,dest);assert sha(dest)==sha(p);images[rel(dest)]=sha(dest)
 dump(contact/'native-review.json',{'id':aid,'accepted_bounded_export':True,'scope':'Fresh direct native1x review of all packed pose pages and paired UI from the exact historical full export; no new render or runtime gameplay acceptance.','images':images,'findings':[findings[aid],'No observed clipping, floating fragments or arm/door overlap in these contact sheets.','Service motion, damage/material contrast and smallest UI details remain modest; source-image readability is not complete gameplay-camera acceptance.'],'previous_go_scene_receipt':'work/art/producer-go-parking-pilot-v4/native-review.json'})
 check=out/f'check-{aid}.json';shutil.copy2(F/f'check-{aid}.json',check);uitext=(F/f'ui-check-{aid}.md').read_text();uirows=[s for s in uitext.splitlines()if re.fullmatch(r'\| (portraits|icons/build) \| (1x|2x) \| [a-z-]+ \| (PASS|FAIL) \|',s)];assert len(uirows)==20 and all(s.endswith('PASS |')for s in uirows);dump(out/f'ui-check-{aid}.json',{'id':aid,'checks':20,'failures':0,'scope':'Parsed exact original UI report; not a new execution.','original_sha256':sha(F/f'ui-check-{aid}.md'),'rows':uirows})
 dump(out/'production-lock.json',{'stage':rel(stage),'sources':sources,'historical_source_chain':row,'original_evidence':original_pins,'source_bundle_provenance':provenance,'scope':'Exact copied historical complete export. Pixels predate the later team-mask helper. Six assets use accepted all-other58 equivalence from0878 to f69e; SY is rendered directly fromf69e. No reinterpretation of old checks as new tests.'})
 dump(out/'raw-identity.json',{'original_receipt':row['original_receipt'],'sha256':row['original_receipt_sha256'],'files':json.loads((F/f'receipt-{aid}.json').read_text())['raw_sha256'],'scope':'Original recorded raw identities rechecked by audit-v1, no raw copy/render.'})
 receipts=[check,out/f'ui-check-{aid}.json',contact/'native-review.json',out/'production-lock.json',out/'raw-identity.json',B/'audit-v1.json',Path(__file__)];model=stage/'assets/pipeline/blender/models/building_roster.py';sp=stage/f'assets/pipeline/specs/{aid}.json';handoff=out/'runtime-handoff.json';dump(handoff,{'id':aid,'stage':rel(stage),'poses':row['poses'],'model':rel(model),'model_sha256':sha(model),'spec':rel(sp),'spec_sha256':sha(sp),'editable_blend':rel(blend),'files':exports,'receipts':{rel(p):sha(p)for p in receipts},'scope':'Exact old complete quota-fallback building export, original Codex model/corrections and pipeline operation. Recovered original render dependency hashes and source amendment retained. No rerender, new pixels, live publication or final-game claim.'});results.append({'id':aid,'handoff':rel(handoff),'sha256':sha(handoff),'files':len(exports),'bytes':sum(v['bytes']for v in exports.values()),'poses':row['poses']})
dump(B/'result.json',{'assets':results,'totals':{'assets':len(results),'files':sum(v['files']for v in results),'bytes':sum(v['bytes']for v in results),'poses':sum(v['poses']for v in results)},'audit_sha256':sha(B/'audit-v1.json'),'script_sha256':sha(Path(__file__))});print('FC_OLD_BUILDING_HANDOFFS',len(results),sum(x['files']for x in results),sum(x['bytes']for x in results))
