import {Rectangle,type Application} from 'pixi.js';
import {create,fromJson,toBinary} from '@bufbuild/protobuf';
import {BattlefieldRenderer,type BattlefieldGesture} from '@source/render/battlefield';
import {ArtLibrary} from '@source/render/art';
import {TerrainSurface,projectSurfaceVertex} from '@source/render/terrain-surface';
import {CatalogIndex,type Catalog} from '@source/content/catalog';
import {DEFAULT_SETTINGS} from '@source/app/settings';
import {PlayerSnapshotSchema} from '@source/protocol/frontline_pb';
import type {ActorVisual} from '@source/render/actors';
import type {GameMap,PlayerSnapshot,Point} from '@source/runtime';
interface Inside {app:Application;actors:Map<number,ActorVisual>;chunks:Map<string,{texture:{source:{pixelWidth:number;pixelHeight:number}};visible:boolean;fragments:Array<{mesh:{visible:boolean;zIndex:number};fog:{visible:boolean};triangles:Array<{id:string}>}>}>;terrainKey:string;frame:number;render():void;environment:{ready():Promise<void>};combat:{settle():Promise<void>};world:{x:number;y:number};camera:{zoom:number};hit(p:Point):unknown;project(p:Point):Point;ground:{children:Array<{zIndex:number}>}}
const catalog=new CatalogIndex(await (await fetch('/fixture/catalog.json')).json() as Catalog),host=document.getElementById('field')!;
let renderer:BattlefieldRenderer|undefined,art:ArtLibrary|undefined,inside:Inside|undefined,map:GameMap|undefined,snapshots:PlayerSnapshot[]=[],originals:string[]=[],paintTime=1000;
const errors:string[]=[],gestures:BattlefieldGesture[]=[];
const now=performance.now.bind(performance),descriptor=Object.getOwnPropertyDescriptor(performance,'now');
function painted<T>(fn:()=>T):T{Object.defineProperty(performance,'now',{configurable:true,value:()=>paintTime});try{return fn()}finally{if(descriptor)Object.defineProperty(performance,'now',descriptor);else delete (performance as unknown as {now?:unknown}).now}}
function need(){if(!renderer||!inside||!art||!map)throw Error('No active renderer');return {renderer,inside,art,map}}
function b64(data:Uint8Array){let s='';for(let i=0;i<data.length;i+=16384)s+=String.fromCharCode(...data.subarray(i,i+16384));return btoa(s)}
async function digest(bytes:Uint8Array){const d=await crypto.subtle.digest('SHA-256',new Uint8Array(bytes).buffer);return [...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function storeSnapshot(s:PlayerSnapshot){snapshots.push(s);originals.push(await digest(toBinary(PlayerSnapshotSchema,s)))}
function synthetic(kind:string,size:number):GameMap{return {id:`synthetic-${kind}-${size}`,title:`Synthetic ${kind}`,author:'renderer acceptance fixture',version:'1',format_version:1,ruleset:'standard-v2',width:size,height:size,tiles:Array.from({length:size*size},(_,i)=>{const x=i%size,y=Math.floor(i/size);let height=0,terrain='open';if(kind==='raised')height=4;if(kind==='ramp')height=Math.min(4,Math.max(0,x-14));if(kind==='cliff'){height=x>=16&&y>=14?4:0;terrain=x>=16&&x<=17?'cliff':'open'}if(kind==='partial-edge'){height=x>=size-3?4:0;terrain=x===size-2?'cliff':'road'}if(kind==='mixed-visibility'){height=Math.min(4,Math.max(0,y-14));terrain=x===17?'cliff':'open'}return {terrain,height}}),spawns:[{position:{x:4000,y:4000}},{position:{x:(size-4)*1000,y:(size-4)*1000}}],shipment:{x:size*500,y:size*500},fields:[],stations:[],objects:[],required_packs:['2.0.0']}}
function fog(kind:string,size:number){const visible:boolean[]=[],explored:boolean[]=[];for(let y=0;y<size;y++)for(let x=0;x<size;x++){const state=kind==='mixed-visibility'?(x<16?0:y<16?1:2):(kind==='partial-edge'?(x+y<2*size-4?0:x+y<2*size-3?1:2):(x+y<32?0:x+y<35?1:2));visible.push(state===0);explored.push(state<2)}return {visible,explored}}
async function createRenderer(m:GameMap,s:PlayerSnapshot,zoom:number,center:Point){
 if(renderer)throw Error('Dispose the previous renderer before creation');errors.length=0;gestures.length=0;paintTime=1000;map=m;art=new ArtLibrary();art.onError=e=>errors.push(e.message);
 renderer=await BattlefieldRenderer.create(host,{map:m,catalog,art,settings:{...DEFAULT_SETTINGS,artQuality:'standard',edgeScroll:false,reducedMotion:true,reducedFlashing:true,screenShake:0},onGesture:e=>gestures.push(e),onError:e=>errors.push(e.message)});
 inside=renderer as unknown as Inside;inside.app.stop();if(inside.chunks.size!==0)throw Error('Unexpected automatic terrain frame before manual course');
 painted(()=>renderer!.setSnapshot(s));renderer.center(center);renderer.zoomBy(zoom);await Promise.all([...inside.actors.values()].map(a=>a.ready));await inside.environment.ready();return stats();
}
function paint(){const {inside}=need();painted(()=>{inside.render();inside.app.render()});return stats()}
function stats(){const {inside,art}=need();let bytes=0,visibleChunks=0,visibleFragments=0;for(const c of inside.chunks.values()){bytes+=c.texture.source.pixelWidth*c.texture.source.pixelHeight*4;if(c.visible)visibleChunks++;for(const f of c.fragments)if(f.mesh.visible)visibleFragments++}const z=new Map<number,number>();for(const n of inside.ground.children)z.set(n.zIndex,(z.get(n.zIndex)??0)+1);return {frame:inside.frame,chunks:inside.chunks.size,visibleChunks,visibleFragments,terrainBytes:bytes,art:art.statistics,terrainReady:!!inside.terrainKey,errors:[...errors],missingArt:renderer!.missingArt,canvasCount:document.querySelectorAll('canvas').length,tieGroups:[...z].filter(([,v])=>v>1).length}}
async function warm(){const {inside,art}=need();let calls=0;for(;calls<180;calls++){paint();await art.settle();await inside.combat.settle();if(inside.terrainKey&&calls>=3){paint();await art.settle();break}}if(!inside.terrainKey)throw Error('Terrain never completed within 180 explicit frames');return {...stats(),warmCalls:calls+2}}
function coverage(){const {inside,map}=need(),surface=new TerrainSurface(map),view={left:(-inside.world.x-2)/inside.camera.zoom,top:(-inside.world.y-2)/inside.camera.zoom,right:(inside.app.screen.width-inside.world.x+2)/inside.camera.zoom,bottom:(inside.app.screen.height-inside.world.y+2)/inside.camera.zoom},required=new Set<string>();for(const t of surface.triangles()){if(!t.frontFacing)continue;const points=t.vertices.map(projectSurfaceVertex);if(Math.max(...points.map(p=>p.x))>=view.left&&Math.min(...points.map(p=>p.x))<=view.right&&Math.max(...points.map(p=>p.y))>=view.top&&Math.min(...points.map(p=>p.y))<=view.bottom)required.add(`${Math.floor(t.tile%map.width/16)}:${Math.floor(Math.floor(t.tile/map.width)/16)}`)}return {scope:'Projected triangle bounds intersecting two-pixel-fringe viewport, not measured pixel coverage',requiredChunks:required.size,residentRequired:[...required].filter(k=>inside.chunks.has(k)).length,missing:[...required].filter(k=>!inside.chunks.has(k))}}
function actor(id:number){const {inside}=need(),a=inside.actors.get(id);if(!a)throw Error(`Actor ${id} not present`);const bounds=renderer!.bounds(a.entity),projected=inside.project(a.entity.position!);return {id,type:a.entity.type,position:a.entity.position,visible:a.root.visible,root:{x:a.root.x,y:a.root.y},bounds,projected,standIn:a.standIn,missingArt:a.missingArt,missingPayloadArt:a.missingPayloadArt,painted:!!a.paintedBodyBounds()}}
function pickPoint(id:number){const {inside}=need(),a=inside.actors.get(id)!,b=renderer!.bounds(a.entity);if(!b)return;for(let y=Math.max(1,Math.ceil(b.top));y<Math.min(inside.app.screen.height-1,b.bottom);y+=2)for(let x=Math.max(1,Math.ceil(b.left));x<Math.min(inside.app.screen.width-1,b.right);x+=2){const p={x,y},iso={x:(x-inside.world.x)/inside.camera.zoom,y:(y-inside.world.y)/inside.camera.zoom};if(a.containsPaintedBody(iso,0)===true){const hit=inside.hit(p) as {kind:string;id?:number};if(hit.kind==='entity'&&hit.id===id)return {point:p,hit}}}return undefined}
const qa={
 async terrain(kind:string,zoom:number){const size=kind==='partial-edge'?33:32,m=synthetic(kind,size),s=create(PlayerSnapshotSchema,{player:1,tick:100,players:[{id:1,team:1,faction:'US'}],...fog(kind,size)});await storeSnapshot(s);await createRenderer(m,s,zoom,kind==='partial-edge'?{x:31500,y:31500}:{x:16000,y:16000});return warm()},
 async pending(){const m=synthetic('ramp',96),s=create(PlayerSnapshotSchema,{player:1,tick:100,players:[{id:1,team:1,faction:'US'}],visible:Array(96*96).fill(true),explored:Array(96*96).fill(true)});await storeSnapshot(s);await createRenderer(m,s,.45,{x:48000,y:48000});return {stats:stats(),coverage:coverage()}},
 step(){return {stats:paint(),coverage:coverage()}},
 focusCorner(){need().renderer.center({x:7500,y:7500});return {stats:stats(),coverage:coverage()}},
 warm,
 async native(kind:'ground'|'air'){const m=await (await fetch(`/fixture/${kind}-map.json`)).json() as GameMap,before=fromJson(PlayerSnapshotSchema,await (await fetch(`/fixture/${kind}-before.json`)).json()),after=fromJson(PlayerSnapshotSchema,await (await fetch(`/fixture/${kind}-after.json`)).json()),id=kind==='ground'?27:66;await storeSnapshot(before);await storeSnapshot(after);const e=before.entities.find(e=>e.id===id)!;await createRenderer(m,before,1,e.position!);await warm();return {stage:'before',snapshotTicks:[before.tick,after.tick],actor:actor(id),stats:stats(),pick:pickPoint(id)}},
 cull(kind:'ground'|'air'){const id=kind==='ground'?27:66,after=snapshots.at(-1)!;need().renderer.center(after.entities.find(e=>e.id===id)!.position!);paint();return {stage:'culled',actor:actor(id),stats:stats()}},
 async reenter(kind:'ground'|'air'){const id=kind==='ground'?27:66,after=snapshots.at(-1)!;painted(()=>need().renderer.setSnapshot(after));paintTime+=500;await warm();return {stage:'after',actor:actor(id),stats:stats(),pick:pickPoint(id)}},
 gestures(){return gestures},
 capture(){const {inside}=need();painted(()=>inside.app.render());const {pixels,width,height}=inside.app.renderer.extract.pixels({target:inside.app.stage,frame:new Rectangle(0,0,inside.app.screen.width,inside.app.screen.height),resolution:1});return {width,height,rgba:b64(new Uint8Array(pixels)),stats:stats()}},
 async dispose(){const hashes=await Promise.all(snapshots.map(s=>digest(toBinary(PlayerSnapshotSchema,s))));const unchanged=hashes.every((h,i)=>h===originals[i]);if(renderer){renderer.dispose();await renderer.whenEffectsReleased()}if(art)await art.release();const result={unchangedSnapshots:unchanged,snapshotHashes:hashes,originalHashes:[...originals],canvases:document.querySelectorAll('canvas').length,actors:inside?.actors.size,chunks:inside?.chunks.size,art:art?.statistics,errors:[...errors],nativeClockAdvances:now()>0};renderer=undefined;inside=undefined;art=undefined;map=undefined;snapshots=[];originals=[];return result},
};
Object.assign(window,{qa});document.body.dataset.ready='true';
