import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,cp,readdir,symlink,lstat} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {build} from '../../../client/node_modules/esbuild/lib/main.js';
const work=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),root=path.resolve(work,'../..'),out=path.join(work,'evidence'),stage=path.join(work,'combined-test-stage'),client=path.join(stage,'client'),delta=path.join(work,'combined-candidate/client/src/render');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const pins=JSON.parse(await readFile(path.join(out,'source-lock.json'),'utf8'));
for(const pin of pins)assert.equal(sha(await readFile(path.join(root,pin.path))),pin.sha256,`Live source drift: ${pin.path}`);
let scene=await readFile(path.join(work,'terrain-priority-candidate/client/src/render/battlefield.ts'),'utf8'),terrain=await readFile(path.join(work,'terrain-priority-candidate/client/src/render/terrain.ts'),'utf8');
const art=await readFile(path.join(root,'work/art-residency-v1/candidate-art.ts'),'utf8');assert.equal(sha(art),'ea018ee1df9aaddb3a42b34d530cf188929049bc551a47ebef809990a5ce49f8');
const palette=await readFile(path.join(work,'candidate/client/src/render/terrain.ts'),'utf8');
const paletteLine=palette.split('\n').find(line=>line.startsWith('const MINIMAP_BASE:'));assert(paletteLine);
terrain=terrain.replace('export class TerrainBaker {',`/** Shared read-only palette; each minimap sample still returns its own RGB tuple. */\n${paletteLine}\n\nexport class TerrainBaker {`);
const localPalette="  const base:Record<string,[number,number,number]>={open:[128,110,76],road:[74,72,66],rubble:[98,90,80],cover:[104,100,62],water:[44,62,60],cliff:[70,62,50],blocked:[58,52,44],ramp:[120,102,72]};\n";
assert(terrain.includes(localPalette));terrain=terrain.replace(localPalette,'').replace('const [r,g,b]=base[t]??base.open;','const [r,g,b]=MINIMAP_BASE[t]??MINIMAP_BASE.open;');
const culled=await readFile(path.join(work,'culling-candidate/client/src/render/battlefield.ts'),'utf8'),comment=culled.slice(culled.indexOf('   // Culled actors skip painting'),culled.indexOf('   const bounds=this.bounds(actor.entity);',culled.indexOf('   // Culled actors skip painting')));
assert(comment.includes('if(!actor.root.visible)'));assert.equal(scene.split('   const bounds=this.bounds(actor.entity);').length,2);scene=scene.replace('   const bounds=this.bounds(actor.entity);',comment+'   const bounds=this.bounds(actor.entity);');
assert(scene.includes('if(this.frame%60===0){this.options.art.trim();void this.combat.trim()}'));scene=scene.replace('if(this.frame%60===0){this.options.art.trim();void this.combat.trim()}','if(this.frame%60===0)void this.combat.trim();');
assert(scene.includes('  this.paintMinimap(now);\n }'));scene=scene.replace('  this.paintMinimap(now);\n }','  this.paintMinimap(now);\n  // Every displayed world/placement page has now been touched for this frame.\n  if(this.frame%60===0)this.options.art.trim(now);\n }');
await mkdir(delta,{recursive:true});
const files={'battlefield.ts':scene,'terrain.ts':terrain,'art.ts':art};
for(const [name,contents] of Object.entries(files))await writeFile(path.join(delta,name),contents);
await mkdir(path.join(client,'src'),{recursive:true});
for(const pin of pins){const target=path.join(stage,pin.path);await mkdir(path.dirname(target),{recursive:true});await cp(path.join(work,'baseline',pin.path),target)}
for(const [name,contents] of Object.entries(files))await writeFile(path.join(client,'src/render',name),contents);
for(const relative of ['tsconfig.json','package.json','tests/runtime','scripts/runtime','scripts/ui'])await cp(path.join(root,'client',relative),path.join(client,relative),{recursive:true});
async function link(target,name){try{await lstat(name)}catch(error){if(error.code!=='ENOENT')throw error;await symlink(target,name)}}
await link(path.join(root,'client/node_modules'),path.join(client,'node_modules'));
for(const name of ['assets','content','pkg'])await link(path.join(root,'work/art-residency-v1/candidate',name),path.join(stage,name));
const appCheck=spawnSync(path.join(root,'client/node_modules/.bin/tsc'),['-p',path.join(client,'tsconfig.json'),'--noEmit'],{cwd:client,encoding:'utf8'}),runtimeCheck=spawnSync(path.join(root,'client/node_modules/.bin/tsc'),['-p',path.join(client,'tests/runtime/tsconfig.json'),'--noEmit'],{cwd:client,encoding:'utf8'});
await writeFile(path.join(out,'combined-app-typecheck.log'),(appCheck.stdout??'')+(appCheck.stderr??''));await writeFile(path.join(out,'combined-runtime-typecheck.log'),(runtimeCheck.stdout??'')+(runtimeCheck.stderr??''));
assert.equal(appCheck.status,0,appCheck.stdout||appCheck.stderr);assert.equal(runtimeCheck.status,0,runtimeCheck.stdout||runtimeCheck.stderr);
const entries=(await readdir(path.join(client,'tests/runtime'))).filter(n=>n.endsWith('.test.ts')).map(n=>path.join(client,'tests/runtime',n)),testOut=path.join(client,'.test-runtime');await mkdir(testOut,{recursive:true});
await build({entryPoints:entries,outdir:testOut,outExtension:{'.js':'.mjs'},bundle:true,platform:'node',format:'esm',target:'node24',packages:'external'});
const test=spawnSync(process.execPath,['--test','--test-concurrency=1',...entries.map(n=>path.join(testOut,path.basename(n,'.ts')+'.mjs'))],{cwd:client,encoding:'utf8',maxBuffer:20*1024*1024});
await writeFile(path.join(out,'combined-runtime-tests-run01.log'),(test.stdout??'')+(test.stderr??''));assert.equal(test.status,0,test.stdout?.slice(-2000)||test.stderr);
for(const pin of pins)assert.equal(sha(await readFile(path.join(root,pin.path))),pin.sha256,`Live input changed during validation: ${pin.path}`);
const report={status:'PASS',scope:'Private combined source only; no browser, GPU, raster, wall-clock performance or complete-art acceptance.',guardedLiveSources:pins.length,liveSourcesUnchanged:true,sourceSHA256:Object.fromEntries(Object.entries(files).map(([name,value])=>[name,sha(value)])),inputs:{palette:'ee19d88',culling:'ee19d88',art:'6b49db7',artSHA256:sha(art)},appTypecheck:appCheck.status,runtimeTypecheck:runtimeCheck.status,runtimeTestsExitCode:test.status,testSummary:test.stdout.split('\n').filter(line=>/^(ℹ|#) (tests|suites|pass|fail|cancelled|skipped|todo)\b/.test(line)),callerInvariant:'Art trim(now) remains every60frames and follows drawTactical and paintMinimap. Combat trim remains at its prior position.',limits:['Priority admission changes equal-zIndex creation order; actual warmed native pixel equivalence remains mandatory.','Culling reentry has actual ActorVisual Node evidence only; actual-App art/picking/service/replay remains open.','Active/pending sprite pages may exceed the soft residency target.','Large/minzoom terrain still exceeds36chunks because original prefetch guards remain.']};
await writeFile(path.join(out,'combined-validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
