import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {transform} from '../../../client/node_modules/esbuild/lib/main.js';
const work=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const source=await readFile(path.join(work,'combined-candidate/client/src/render/battlefield.ts'),'utf8');
const start=source.indexOf(' private render(){'),end=source.indexOf(' /** Attaches one HUD minimap.',start);assert(start>=0&&end>start);
const js=(await transform(source.slice(start,end).replace(' private render(){','function render(){'),{loader:'ts',format:'esm'})).code;
const render=new Function(`${js};return render;`)(),calls=[];
let paintedAt,trimmedAt;
const actor={root:{visible:true},entity:{owner:1},id:1,shadowPlates:[],render(){calls.push('actor-page-read')}};
const scene={disposed:false,lost:false,frame:58,app:{screen:{width:100,height:100}},world:{x:0,y:0},camera:{zoom:1},settings:{edgeScroll:false,healthBars:'selected',reducedMotion:false},actors:new Map([[1,actor]]),deaths:[],selected:new Set(),surface:{},environment:{render(){calls.push('environment-page-read')},shadowPlates:[]},surfaceShadows:{update(){calls.push('shadow-read')}},options:{art:{trim(now){calls.push('art-trim');trimmedAt=now}}},combat:{trim(){calls.push('combat-trim')},draw(){calls.push('combat-read')}},memoryLabels:[],overlay:{clear(){}},bounds:()=>({left:0,top:0,right:10,bottom:10}),team:()=>0xffffff,updateShake(){},cameraTransform(){},terrainFrame(){},drawTactical(){calls.push('placement-page-read')},paintMinimap(now){paintedAt=now;calls.push('minimap')} };
render.call(scene);assert(!calls.includes('art-trim'));
calls.length=0;render.call(scene);
assert.deepEqual(calls,['environment-page-read','actor-page-read','shadow-read','combat-trim','combat-read','placement-page-read','minimap','art-trim']);
assert.equal(trimmedAt,paintedAt);assert.equal(typeof trimmedAt,'number');
const trimFrameCalls=[...calls];calls.length=0;render.call(scene);assert(!calls.includes('art-trim'));
const report={status:'PASS',scope:'Exact combined render method with recorded page consumers; no browser or GPU.',candidateSHA256:createHash('sha256').update(source).digest('hex'),trimFrame:60,previousAndFollowingFramesDoNotTrim:true,passedSameFrameTimestamp:true,trimFrameCalls};
await writeFile(path.join(work,'evidence/trim-caller.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
