import assert from 'node:assert/strict';import{readFile,writeFile}from'node:fs/promises';import{createHash}from'node:crypto';
import {ArtLibrary} from '../../art-generation-consumer-v1/frozen-v1/client/src/render/art';
import {authoredArtId} from '../../art-generation-consumer-v1/frozen-v1/client/src/render/art-id';
const origin='http://127.0.0.1:17990',encode=(x:unknown)=>new TextEncoder().encode(JSON.stringify(x)),sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
const catalog=JSON.parse(await readFile('pkg/content/rules.json','utf8')),ids=[...new Set(['US','IR','SY','SA'].flatMap(f=>[...catalog.units.filter((u:any)=>u.faction===f),...catalog.buildings.filter((b:any)=>!b.faction||b.faction===f)].map((v:any)=>authoredArtId(v.id,f))))].filter(Boolean) as string[];assert.equal(ids.length,136);
async function fixture(selected:string[],version='A',marker='A'){
 const source=encode({format_version:1,version,packs:[{id:'2.0.0',version,manifest_url:'/assets/packs/base.json'}],maps:[],missions:[]}),art={format:1,sprites:Object.fromEntries(selected.map((id,i)=>[id,`s${i}.json`])),terrain:[],portraits:[],chrome:[],icons:false,emblems:false,marker},bodies=new Map([['/content/index.json',source],['/art/index.json',encode(art)],['/art/test.png',new Uint8Array([1,2,3])]]);
 for(let i=0;i<selected.length;i++)bodies.set('/art/s'+i+'.json',encode({id:selected[i],marker,frame_size_2x:[2,2],anchor_2x:[1,1],layers:[],atlases:{'1x':{},'2x':{}},states:[]}));
 bodies.set('/assets/packs/base.json',encode({id:'2.0.0',version,files:[...bodies].map(([path,b])=>({path,bytes:b.length,sha256:sha(b)}))}));return{source,bodies};
}
function host(initial:Awaited<ReturnType<typeof fixture>>){let current=initial,fail='';const requests:string[]=[];return{requests,set(x:typeof initial){current=x},fail(path:string){fail=path},fetcher:async(input:any,init:any)=>{init?.signal?.throwIfAborted();const p=new URL(String(input),origin).pathname;requests.push(p);const b=current.bodies.get(p);return new Response(p===fail?'transient':b?.slice().buffer,{status:p===fail?503:b?200:404})}}}
const result:any={scope:'Nonbrowser metadata-only probes against immutable frozen-v1 consumer/core. Actual 136 catalog IDs; synthetic tiny declared byte bodies exercise normal ArtLibrary APIs, not visual art or Go gameplay.'};
const a=await fixture(ids),net=host(a),lib=new ArtLibrary({origin,indexSource:a.source,fetcher:net.fetcher});const errors:any[]=[];lib.onError=e=>errors.push({code:(e as any).code,message:e.message});await lib.init();const warn=console.warn;console.warn=()=>{};
try{const all=await Promise.all(ids.map(id=>lib.sheet(id)));const missing=ids.filter((_id,i)=>!all[i]);const count=net.requests.length;const retry=await lib.sheet(missing[0]);result.fanout={ids:ids.length,loaded:all.filter(Boolean).length,missing:missing.length,errorCodes:[...new Set(errors.map(e=>e.code))],retryStillMissing:retry===undefined,retryAdditionalRequests:net.requests.length-count,statistics:lib.generationStatistics};assert(missing.length>0);assert.equal(net.requests.length,count);assert.equal(retry,undefined)}finally{console.warn=warn;await lib.dispose()}
const x=await fixture([ids[0]],'same','A'),y=await fixture([ids[0]],'same','B');assert.equal(sha(x.source),sha(y.source));const n=host(x),l=new ArtLibrary({origin,indexSource:x.source,fetcher:n.fetcher});await l.init();const before=l.generationIdentity;n.set(y);const at=n.requests.length;await l.useIndex(y.source);result.sameIndexReload={sameIndexBytes:true,indexMarker:(l.index as any).marker,manifestIdentityUnchanged:before?.key===l.generationIdentity?.key,additionalRequests:n.requests.length-at};assert.equal((l.index as any).marker,'A');await l.dispose();
const z=await fixture([ids[0]]),n2=host(z),l2=new ArtLibrary({origin,indexSource:z.source,fetcher:n2.fetcher});await l2.init();n2.fail('/art/s0.json');console.warn=()=>{};try{assert.equal(await l2.sheet(ids[0]),undefined);n2.fail('');const at=n2.requests.length;assert.equal(await l2.sheet(ids[0]),undefined);result.metadataRetry={additionalRequests:n2.requests.length-at,stillMissing:true};await l2.release();assert(await l2.sheet(ids[0]));result.metadataRetry.afterReleaseRecovered=true}finally{console.warn=warn}
n2.fail('/art/test.png');await assert.rejects(l2.image('/art/test.png'));n2.fail('');const imageAt=n2.requests.length;await l2.useIndex(z.source);await assert.rejects(l2.image('/art/test.png'));result.imageRetry={afterExplicitSameIndexReload:true,additionalRequests:n2.requests.length-imageAt,stillRejected:true};await l2.dispose();
await writeFile('work/evidence/art-generation-review/proof-result.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
