// Nonvisual browser-to-Go integration; this fixture is not product UI.
import {chromium,firefox,webkit} from 'playwright-core';
import {build} from 'esbuild';
import {spawn} from 'node:child_process';
import {mkdir,mkdtemp,symlink,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
import {scenario,map} from './scenario.mjs';
const insecure=process.env.FRONTLINE_TEST_INSECURE==='1';
const client=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),root=path.dirname(client),temp=await mkdtemp(path.join(tmpdir(),'frontline-account-integration-'));
const staticDir=path.join(temp,'static');await mkdir(staticDir,{recursive:true});await mkdir(path.join(temp,'maps'));await mkdir(path.join(temp,'missions'));await writeFile(path.join(temp,'maps/fixture.json'),JSON.stringify(map));await symlink(process.env.FRONTLINE_TEST_RUNTIME??path.join(client,'public/runtime'),path.join(staticDir,'runtime'),'dir');
await build({stdin:{contents:"export {LocalProfileSession,LocalCredentialVault} from './account'; export {SaveSynchronizer} from './save-sync'; export {LocalStore} from './storage'; export {OfflineTransport} from './offline'; export {sha256Hex,randomUUID} from './crypto'; export {MapEditorDocument,EditorDraftStore} from './editor'; export {offlineCapability,installPack} from './cache';",resolveDir:path.join(client,'src/runtime'),sourcefile:'account-integration.ts'},outfile:path.join(staticDir,'fixture.js'),bundle:true,platform:'browser',format:'iife',globalName:'AccountFixture',target:'es2022'});
await writeFile(path.join(staticDir,'index.html'),'<!doctype html><meta charset="utf-8"><title>Account integration fixture</title><link rel="icon" href="data:,"><script src="/fixture.js"></script>');
const host=spawn(process.env.FRONTLINE_TEST_HOST??path.join(root,'bin/frontline'),['-addr','127.0.0.1:0','-data',path.join(temp,'data'),'-static',staticDir,'-maps',path.join(temp,'maps'),'-missions',path.join(temp,'missions')],{cwd:root,stdio:['ignore','pipe','pipe']});
let log='';const hostOrigin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Host startup timed out')),15000);host.stdout.on('data',data=>{log+=data;const found=log.match(/http:\/\/127\.0\.0\.1:\d+/);if(found){clearTimeout(timer);resolve(found[0])}});host.stderr.on('data',data=>log+=data);host.once('exit',code=>{clearTimeout(timer);reject(new Error(`Host exited: ${code}`))})});
const origin=insecure?hostOrigin.replace('127.0.0.1','frontline-lan.test'):hostOrigin;
const report={originMode:insecure?'ordinary HTTP LAN-equivalent nonlocalhost host':'localhost secure context',date:new Date().toISOString(),scope:'Real Go host and Go WASM validation; profile vault, save/settings migration, exact bytes, hashing, draft/replay/recovery storage, ABA rejection at final write, logout.',browserPath:'Browser plugin not available; installed Playwright browsers used.',browsers:[]};
try{
 for(const type of (insecure?[chromium]:[chromium,firefox,webkit]).filter(type=>!process.env.FRONTLINE_TEST_BROWSER||type.name()===process.env.FRONTLINE_TEST_BROWSER)){
  const browser=await type.launch({headless:true,...(insecure?{args:['--host-resolver-rules=MAP frontline-lan.test 127.0.0.1','--no-proxy-server']}:{})});try{
   const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(origin);
   const result=await page.evaluate(async config=>{
    const R=globalThis.AccountFixture,runtime=new R.OfflineTransport();await runtime.ready;await runtime.create(config);await runtime.step(20);const save=await runtime.save();
    const files=new R.LocalStore('account-integration',data=>runtime.inspect(data),data=>runtime.inspectReplay(data)),vault=new R.LocalCredentialVault('account-integration-auth'),account=new R.LocalProfileSession({credentials:vault});
    await files.putSave('solo','Solo fixture',save);await files.putSetting('preferences',{uiScale:100,captions:true});await account.create('Integration commander');const profileID=account.context.profileId;const key=account.exportSignInKey(),keyContents=JSON.parse(await key.text()),keyVault=new R.LocalCredentialVault('explicit-key-import'),keySession=new R.LocalProfileSession({credentials:keyVault});await keySession.restoreSignInKey(key,{remember:true});const keyProof={profileMatches:keySession.state.profile.id===profileID,hiddenFromState:!JSON.stringify(keySession.state).includes(keyContents.token),excludedFromBackup:!(await(await files.backup()).text()).includes(keyContents.token)};await keyVault.close();
    const sync=new R.SaveSynchronizer(account,files,data=>runtime.inspect(data)),migration=await sync.previewMigration({settingsId:'preferences'}),target=migration.entries.find(entry=>entry.kind==='save').remoteId;
    const copied=await sync.execute(migration,migration.entries.map(entry=>({key:entry.key,action:'upload'})));const remote=await account.authenticated(api=>api.downloadSave(target));const exact=remote.data.length===save.data.length&&remote.data.every((value,index)=>value===save.data[index]);
    const downloadPreview=await sync.preview({mappings:[{localId:'from-host',remoteId:target}]}),download=await sync.execute(downloadPreview,[{key:downloadPreview.entries[0].key,action:'download'}]);const local=await files.getSave('from-host');const downloadExact=local.data.length===save.data.length&&local.data.every((value,index)=>value===save.data[index]);
    const stale=await sync.preview({mappings:[{localId:'solo',remoteId:target}]});await account.authenticated(api=>api.uploadSave(target,'New host revision',save.data,remote.revision));let conflict='';try{await sync.execute(stale,[{key:stale.entries[0].key,action:'upload'}])}catch(error){conflict=error.code}
    const capabilities={secure:isSecureContext,subtle:typeof crypto.subtle,uuid:typeof crypto.randomUUID,random:typeof crypto.getRandomValues,cache:R.offlineCapability().supported};
    const hash=await R.sha256Hex(new TextEncoder().encode('abc')),uuid=R.randomUUID();
    const replay=await runtime.exportReplay();await files.putReplay('replay','Replay fixture',replay);const replayExact=(await files.getReplay('replay')).data.every((value,index)=>value===replay[index]);
    const unknown=new Uint8Array([255,0,128,7]),recovery=await files.preserveRecovery(new Blob([unknown]),'Recovery fixture','Synthetic unreadable bytes');const recovered=new Uint8Array(await(await files.exportRecovery(recovery.id)).arrayBuffer());const recoveryExact=unknown.every((value,index)=>value===recovered[index]);
    const editor=new R.MapEditorDocument({map:config.map},{validateMap:data=>runtime.validateMap(data),validateMission:(map,mission)=>runtime.validateMission(map,mission)}),drafts=new R.EditorDraftStore('integration-drafts');const draft=await drafts.put(editor);await drafts.delete(editor.documentId,draft.revision);const nextDraft=await drafts.put(editor);const draftLoaded=await drafts.get(editor.documentId);const imported=await R.MapEditorDocument.importDraft(draftLoaded.data,{validateMap:data=>runtime.validateMap(data),validateMission:(map,mission)=>runtime.validateMission(map,mission)});const practice=await imported.prepareTest({seed:42});await drafts.close();
    // Cause a remote delete/recreate after all preview checks, immediately before
    // the real HTTP PUT. Only host CAS can prevent this in-flight ABA overwrite.
    const atomic=await sync.preview({mappings:[{localId:'solo',remoteId:target}]}),normalAuth=account.authenticated.bind(account);let armed=true;
    account.authenticated=(operation,options)=>normalAuth(async api=>{const upload=api.uploadSave.bind(api);api.uploadSave=async(id,name,data,expected,signal)=>{if(armed){armed=false;await api.deleteSave(id,expected);await upload(id,'Recreated during write',data,0)}return upload(id,name,data,expected,signal)};return operation(api)},options);
    const blocked=await sync.execute(atomic,[{key:atomic.entries[0].key,action:'upload'}]);account.authenticated=normalAuth;const afterABA=await account.authenticated(api=>api.downloadSave(target));
    await files.deleteSave('from-host',local.revision);const freshLocal=await files.putSave('from-host','Recreated local',save,0);let staleLocal='';try{await files.putSave('from-host','Stale overwrite',save,local.revision)}catch(error){staleLocal=error.code}
    let cacheError='';if(!capabilities.secure)try{await R.installPack({id:'fixture',version:'1',files:[]})}catch(error){cacheError=error.code}
    const persistence={hash,uuid,replayExact,recoveryExact,draftRevision:nextDraft.revision,practice:practice.config.ruleset,atomicStatus:blocked.status,atomicError:blocked.receipts[0].error?.code,remoteRevision:afterABA.revision,localRevision:freshLocal.revision,staleLocal,cacheError};
    const preferences=await account.authenticated(api=>api.settings()),restored=new R.LocalProfileSession({credentials:vault});const restoredID=(await restored.restore()).profile.id;await restored.logout();const guest=new R.LocalProfileSession({credentials:vault});const guestPhase=(await guest.restore()).phase;
    let invalid='';try{await guest.restoreToken('f'.repeat(64))}catch(error){invalid=error.code}
    const savesAfterLogout=(await files.listSaves()).length;await files.close();await vault.close();runtime.dispose();return {keyProof,capabilities,persistence,profileID,restoredID,copied:copied.receipts.filter(item=>item.status==='copied').length,download:download.status,exact,downloadExact,conflict,settings:preferences,guestPhase,invalid,savesAfterLogout};
   },scenario.config);
   assert.equal(result.capabilities.secure,!insecure);if(insecure){assert.equal(result.capabilities.subtle,'undefined');assert.equal(result.capabilities.uuid,'undefined');assert.equal(result.capabilities.random,'function');assert.equal(result.capabilities.cache,false);assert.equal(result.persistence.cacheError,'offline_unavailable')}
   assert.equal(result.persistence.hash,'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad');assert.match(result.persistence.uuid,/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);assert.ok(result.persistence.replayExact&&result.persistence.recoveryExact);assert.equal(result.persistence.draftRevision,2);assert.equal(result.persistence.practice,'practice-v1');assert.equal(result.persistence.atomicStatus,'stopped');assert.equal(result.persistence.atomicError,'save_conflict');assert.equal(result.persistence.remoteRevision,3);assert.equal(result.persistence.localRevision,2);assert.equal(result.persistence.staleLocal,'save_conflict');
   assert.deepEqual(result.keyProof,{profileMatches:true,hiddenFromState:true,excludedFromBackup:true});assert.equal(result.profileID,result.restoredID);assert.equal(result.copied,2);assert.equal(result.download,'completed');assert.ok(result.exact&&result.downloadExact);assert.equal(result.conflict,'sync_remote_changed');assert.deepEqual(result.settings,{revision:1,data:{uiScale:100,captions:true}});assert.equal(result.guestPhase,'guest');assert.equal(result.invalid,'sign_in_required');assert.equal(result.savesAfterLogout,2);assert.deepEqual(errors,[]);report.browsers.push({name:type.name(),version:browser.version(),status:'passed',result});console.log(`${type.name()}: Go account/save-sync integration passed`);
  }finally{await browser.close()}
 }
}finally{if(host.exitCode===null){const stopped=new Promise(resolve=>host.once('exit',resolve));host.kill('SIGTERM');await stopped}const evidence=path.join(root,'work/evidence/runtime');await mkdir(evidence,{recursive:true});await writeFile(path.join(evidence,insecure?'account-http-lan-results.json':'account-browser-results.json'),JSON.stringify(report,null,2))}
