import test from 'node:test';
import assert from 'node:assert/strict';
import {create} from '@bufbuild/protobuf';
import {ambienceFor,battlefieldSounds,impactSound} from '../../src/audio/battlefield-sound';
import {AudioDirector} from '../../src/audio/director';
import type {AudioMixer} from '../../src/audio/mixer';
import type {GameMap} from '../../src/runtime/types';
import {CatalogIndex,type Catalog} from '../../src/content/catalog';
import {EntitySchema,PlayerSnapshotSchema,EventSchema} from '../../src/protocol/frontline_pb';
const catalog=new CatalogIndex({units:[{id:'US.rig',role:'rig',armor:'light',faction:'US'},{id:'US.tank',role:'tank',armor:'heavy',faction:'US'},{id:'IR.drone',role:'fighter',armor:'air',faction:'IR'},{id:'US.heli',role:'airlift',armor:'air',faction:'US'},{id:'US.jet',role:'fighter',armor:'air',faction:'US'}],buildings:[{id:'US.hq'}],weapons:[],upgrades:[]} as unknown as Catalog);
const entity=(id:number,type='US.rig',x=50)=>create(EntitySchema,{id,type,owner:1,health:100,state:'moving',position:{x,y:50}});
const view={viewport:{left:0,right:100,top:0,bottom:100},bounds:(entity:ReturnType<typeof create<typeof EntitySchema>>)=>({left:entity.position!.x-1,right:entity.position!.x+1,top:49,bottom:51})};
test('continuous sound selects nearest three current screen actors, with quiet bed and no fog memory',()=>{
 const snapshot=create(PlayerSnapshotSchema,{player:1,entities:[entity(1,'US.rig',10),entity(2,'US.tank',40),entity(3,'IR.drone',60),entity(4,'US.heli',55),entity(5,'US.rig',150)],memory:[{id:99,type:'US.tank',owner:2}]});
 const sounds=battlefieldSounds(snapshot,catalog,view,'sfx.ambient_desert_wind');assert.deepEqual(sounds.map(x=>x.key),['map','actor:4','actor:2','actor:3']);assert.equal(sounds[0].gain,.07);assert.equal(sounds[1].id,'sfx.rotor_loop');assert.ok(sounds[2].pan!<0&&sounds[3].pan!>0);assert.ok(sounds.every(sound=>sound.gain<=.18));
 snapshot.entities=snapshot.entities.filter(entity=>entity.id!==4);assert.equal(battlefieldSounds(snapshot,catalog,view,'sfx.ambient_desert_wind').some(sound=>sound.key==='actor:4'),false);
 assert.deepEqual(battlefieldSounds(snapshot,catalog,view,'sfx.ambient_desert_wind',true),[]);snapshot.outcome={...create(PlayerSnapshotSchema,{outcome:{finished:true}}).outcome!};assert.deepEqual(battlefieldSounds(snapshot,catalog,view,'sfx.ambient_desert_wind'),[]);
});
test('stationary, dead, landed and embarked actors have no engine, jets use bounded passes',()=>{const idle=entity(1);idle.state='idle';const dead=entity(2);dead.health=0;const landed=entity(3,'US.heli');landed.landed=true;landed.state='landed';const embarked=entity(4);embarked.private={...create(EntitySchema,{private:{container:10}}).private!};const jet=entity(5,'US.jet');jet.state='flying';const snapshot=create(PlayerSnapshotSchema,{entities:[idle,dead,landed,embarked,jet]});const sounds=battlefieldSounds(snapshot,catalog,view,'sfx.ambient_desert_wind');assert.deepEqual(sounds.map(x=>x.key),['map','actor:5']);assert.equal(sounds[1].id,'sfx.jet_pass');assert.equal(sounds[1].repeatMs,8000)});
test('impact material requires an identified authorized entity, never a nearest-target guess',()=>{assert.equal(impactSound(undefined,catalog),'sfx.impact_ground');assert.equal(impactSound(entity(1,'unknown'),catalog),'sfx.impact_ground');assert.equal(impactSound(entity(1,'US.rig'),catalog),'sfx.impact_metal_light');assert.equal(impactSound(entity(1,'US.tank'),catalog),'sfx.impact_metal_heavy');assert.equal(impactSound(entity(1,'US.hq'),catalog),'sfx.impact_structure')});
test('map ambience derives solely from public map presentation',()=>{const base={id:'custom',title:'Untitled',tiles:[{terrain:'open'}]} as GameMap;assert.equal(ambienceFor(base),'sfx.ambient_desert_wind');assert.equal(ambienceFor({...base,title:'Port Outskirts'}),'sfx.ambient_coastal');assert.equal(ambienceFor({...base,tiles:[{terrain:'water'}]}),'sfx.ambient_river')});
function harness(){const sounds:string[]=[];const mixer={play:(id:string)=>sounds.push(id),music:()=>{},continuous:()=>{},caption:()=>{},reset:()=>{},manifest:undefined} as unknown as AudioMixer;return {sounds,director:new AudioDirector(mixer,()=>catalog)}}
function snapshot(tick:number,enemy=0,ally=0){return create(PlayerSnapshotSchema,{tick,player:1,players:[{id:1,team:1,faction:'US'},{id:2,team:2,faction:'IR',strategicProgress:enemy},{id:3,team:1,faction:'SA',strategicProgress:ally}]})}
test('enemy strategic alert uses only public threshold transition and never initial/seek catchup or ally charge',()=>{const h=harness();h.director.snapshot(snapshot(1,1000));assert.deepEqual(h.sounds,[]);h.director.snapshot(snapshot(2,1000,1000));assert.deepEqual(h.sounds,[]);h.director.snapshot(snapshot(3,900,1000));h.director.snapshot(snapshot(4,1000,1000));assert.deepEqual(h.sounds,['vo.announcer.US.enemy_strategic_ready']);h.director.discontinuity();h.director.snapshot(snapshot(100,1000));assert.equal(h.sounds.length,1)});
test('endurance event alone supplies exact loss reason and suppresses generic duplicate independent of array order',()=>{const h=harness(),first=snapshot(1);first.entities=[entity(5,'US.jet')];h.director.snapshot(first);const next=snapshot(2);next.events=[create(EventSchema,{id:1,tick:2,kind:'destroyed',entity:5,owner:1}),create(EventSchema,{id:2,tick:2,kind:'aircraft_endurance_lost',entity:5,owner:1})];h.director.snapshot(next);assert.ok(h.sounds.includes('vo.announcer.US.aircraft_lost_emergency'));assert.equal(h.sounds.includes('vo.announcer.US.unit_lost'),false);assert.equal(h.sounds.filter(id=>id.startsWith('sfx.explosion')).length,1)});
test('impact event material can use only current or immediately previous permitted target',()=>{const h=harness(),first=snapshot(1);first.entities=[entity(9,'US.tank')];h.director.snapshot(first);const next=snapshot(2);next.events=[create(EventSchema,{id:1,tick:2,kind:'impact',entity:9,owner:2}),create(EventSchema,{id:2,tick:2,kind:'impact',entity:100,owner:2})];h.director.snapshot(next);assert.deepEqual(h.sounds,['sfx.impact_metal_heavy','sfx.impact_ground'])});
test('battlefield attachment follows explicit pause and detachment without retaining renderer callbacks',()=>{const requests:string[][]=[];const mixer={continuous:(items:Array<{key:string}>)=>requests.push(items.map(item=>item.key)),music:()=>{},reset:()=>{}} as unknown as AudioMixer;const director=new AudioDirector(mixer,()=>catalog);const detach=director.attachBattlefield({id:'test',title:'Test',tiles:[{terrain:'open'}]} as GameMap,()=>view);try{const state=snapshot(1);state.entities=[entity(1)];director.snapshot(state);assert.deepEqual(requests.at(-1),['map','actor:1']);director.setPaused(true);assert.deepEqual(requests.at(-1),[]);director.setPaused(false);assert.deepEqual(requests.at(-1),['map','actor:1']);detach();assert.deepEqual(requests.at(-1),[]);director.snapshot(snapshot(2));assert.deepEqual(requests.at(-1),[])}finally{detach();director.dispose()}});
