// Browser plugin not available; existing Playwright drives actual product controls.
// The tutorial source is a genuine Go pre-victory checkpoint from ordinary orders.
import {chromium} from 'playwright-core';
import {build} from 'esbuild';
import {execFileSync,spawn} from 'node:child_process';
import {mkdir,mkdtemp,writeFile,readFile,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const client=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),root=path.dirname(client),work=await mkdtemp(path.join(tmpdir(),'frontline-campaign-sync-')),product=process.env.FRONTLINE_SYNC_PRODUCT??path.join(work,'product'),data=path.join(work,'host-data');
const run=(exe,args)=>execFileSync(exe,args,{cwd:root,stdio:'inherit'});
run('go',['build','-trimpath','-o',path.join(work,'frontline'),'./cmd/frontline']);if(!process.env.FRONTLINE_SYNC_PRODUCT)run(process.execPath,[path.join(client,'node_modules/vite/bin/vite.js'),'build','--config',path.join(client,'vite.config.ts'),'--outDir',product]);
const decoder=path.join(work,'decode.mjs');await build({stdin:{contents:"export {fromBinary} from '@bufbuild/protobuf';export {PlayerSnapshotSchema,OrderBatchSchema} from './protocol/frontline_pb';",resolveDir:path.join(client,'src')},outfile:decoder,bundle:true,platform:'node',format:'esm',target:'es2022'});const {fromBinary,PlayerSnapshotSchema,OrderBatchSchema}=await import(pathToFileURL(decoder));
const report={time:new Date().toISOString(),scope:'Actual offline tutorial victory, profile story backup and bounded archive product journeys; not full release acceptance.',cases:{},errors:[],consoleErrors:[],evidence:work};
const host=spawn(path.join(work,'frontline'),['-addr','127.0.0.1:0','-data',data,'-static',product,'-maps',path.join(root,'content/maps'),'-missions',path.join(root,'content/missions')],{cwd:root,stdio:['ignore','pipe','pipe']});let log='';const origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Host start timeout '+log)),20000);host.stdout.on('data',bytes=>{log+=bytes;const match=log.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0])}});host.stderr.on('data',bytes=>log+=bytes);host.once('exit',code=>reject(Error('Host exited '+code)))});
const browser=await chromium.launch({headless:true}),contexts=[],pages=[],tokens=[],downloads=[];report.browser=browser.version();
async function until(check,message,timeout=30000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw Error(message);await new Promise(resolve=>setTimeout(resolve,100))}}
async function idle(page,allowError=false){await until(async()=>await page.locator('.network-operation').count()===0&&await page.locator('.loading-screen').count()===0,'Request did not finish',90000);if(!allowError&&await page.locator('.network-error').count())throw Error(await page.locator('.network-error').allInnerTexts());if(!allowError&&await page.getByRole('dialog',{name:'Command interrupted'}).count())throw Error(await page.getByRole('dialog',{name:'Command interrupted'}).innerText())}
async function api(route,token,method='GET',body){return fetch(origin+'/api/v1'+route,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?typeof body==='string'?body:JSON.stringify(body):undefined})}
async function pageNew(index){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();contexts.push(context);pages.push(page);page.on('pageerror',error=>report.errors.push(error.message));page.on('console',message=>{if(message.type()==='error')report.consoleErrors.push(message.text())});page.on('response',async response=>{if(/\/saves\/[^/]+\/download$/.test(new URL(response.url()).pathname))downloads.push({index,url:response.url()})});await page.addInitScript(()=>{const Native=window.Worker;window.orderBytes=[];window.Worker=class extends Native{constructor(...args){super(...args);this.addEventListener('message',event=>{if(event.data.event==='frame')window.frameBytes=Array.from(event.data.bytes)});const post=this.postMessage;this.postMessage=function(message,...other){if(message.method==='submit')window.orderBytes.push(Array.from(message.args[0]));return post.call(this,message,...other)}}}});await page.goto(origin);assert.equal(await page.title(),'Frontline Command');await page.getByRole('button',{name:'Explore game modes',exact:true}).click({timeout:60000});return {context,page}}
async function snapshot(page){const bytes=await page.evaluate(()=>window.frameBytes);return bytes?fromBinary(PlayerSnapshotSchema,new Uint8Array(bytes)):undefined}
async function localProgress(page){return page.evaluate(()=>new Promise((resolve,reject)=>{const request=indexedDB.open('frontline-command');request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,r=db.transaction('progress').objectStore('progress').get('campaign');r.onsuccess=()=>{db.close();resolve(r.result)};r.onerror=()=>reject(r.error)}}))}
try{
 report.runtime=await api('/health').then(response=>response.json());const sourcePath=path.join(root,'work/evidence/mission-playthroughs/ui-checkpoints/tutorial-1-give-an-order-US-normal.midpoint.save.json'),engine=await readFile(sourcePath,'utf8'),raw=JSON.parse(engine),portable={format:'frontline-local-save',version:1,id:'tutorial-checkpoint',name:'Tutorial1 genuine midpoint',local_players:[1],hash:raw.sha256,engine};report.checkpoint={source:sourcePath,tick:raw.state.tick,provenance:'pkg/sim/authored_tutorial_acceptance_test.go, FRONTLINE_MISSION_CHECKPOINTS; no scenario mutation or practice'};
 const first=await pageNew(0),page=first.page;await page.getByRole('button',{name:'Installed content',exact:true}).click();await page.getByRole('button',{name:'Install',exact:true}).click();await page.getByText('Available offline',{exact:true}).waitFor({timeout:240000});await first.context.setOffline(true);await page.reload();await page.getByRole('button',{name:'Load operation',exact:true}).click({timeout:60000});await page.getByLabel('Import save',{exact:true}).setInputFiles({name:'tutorial-checkpoint.save.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(portable))});await idle(page);await page.locator('.archive-row').filter({hasText:portable.name}).getByRole('button',{name:'Load',exact:true}).click();await page.locator('.battlefield-canvas canvas').waitFor({timeout:60000});await page.locator('.scene-loading').waitFor({state:'hidden',timeout:90000});await page.locator('.countdown').waitFor({state:'hidden',timeout:15000});
 await page.locator('.battlefield-canvas canvas').click({position:{x:500,y:350}});await page.keyboard.press('Control+KeyA');await page.locator('.unit-subgroups button').filter({hasText:/Ranger squad/i}).click();await page.keyboard.press('KeyS');await until(async()=>{const bytes=await page.evaluate(()=>window.orderBytes);return bytes.some(bytes=>fromBinary(OrderBatchSchema,new Uint8Array(bytes)).orders.some(order=>order.kind==='stop'))},'UI stop did not reach worker');
 const map=raw.state.map,target={x:49999,y:82499},mini=await page.getByLabel('Tactical minimap').boundingBox();await page.mouse.click(mini.x+target.x/(map.width*1000)*mini.width,mini.y+target.y/(map.height*1000)*mini.height);await page.keyboard.press('KeyA');const canvas=await page.locator('.battlefield-canvas canvas').boundingBox();await page.mouse.click(canvas.x+canvas.width/2,canvas.y+canvas.height/2);await until(async()=>(await snapshot(page))?.outcome?.finished,'Real tutorial did not finish',90000);await page.getByRole('dialog',{name:'Victory',exact:true}).waitFor();await until(async()=>!!(await localProgress(page))?.data?.results?.length,'Authoritative victory did not persist progress');const earned=await localProgress(page),final=await snapshot(page);assert.equal(earned.data.results.length,1);report.cases.offlineLiveVictory={tick:final.tick,mission:final.mission.id,winningTeam:final.outcome.winningTeam,records:earned.data.results.length};await page.screenshot({path:path.join(work,'offline-tutorial-victory.png')});await page.getByRole('button',{name:'Save replay',exact:true}).click();await idle(page);await page.getByRole('button',{name:'Command center',exact:true}).click();await page.getByRole('button',{name:'Load operation',exact:true}).click();
 const backupEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export browser backup',exact:true}).click();const backupFile=await (await backupEvent).path(),backup=JSON.parse(await readFile(backupFile,'utf8'));assert.deepEqual(backup.progress.find(record=>record.id==='campaign').data,earned.data);assert.equal(backup.replays.length,1);assert.equal(JSON.stringify(backup).includes('Bearer'),false);report.cases.visibleOfflineBackup=true;
 await first.context.setOffline(false);await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(page);await page.getByLabel('Commander name',{exact:true}).fill('Campaign Commander');await page.getByRole('button',{name:'Create local profile',exact:true}).click();await page.getByLabel('Your profile ID').waitFor();await idle(page);await page.getByText('Private sign-in key',{exact:true}).click();const keyDownload=page.waitForEvent('download');await page.getByRole('button',{name:'Export private sign-in key',exact:true}).click();const signInKeyPath=await (await keyDownload).path(),signInKey=JSON.parse(await readFile(signInKeyPath,'utf8'));tokens[0]=signInKey.token;assert.equal(signInKey.origin,origin);assert.equal(JSON.stringify(backup).includes(tokens[0]),false);report.cases.explicitPrivateKeyExport=true;await page.getByRole('button',{name:'Save copies',exact:true}).click();await page.getByRole('button',{name:'Preview guest migration',exact:true}).click();await idle(page);assert.match(await page.locator('.network-sync-item').filter({hasText:'Campaign progress'}).innerText(),/tutorial-1-give-an-order/);for(const select of await page.locator('select[aria-label^="Copy decision "]').all())await select.selectOption((await select.getAttribute('aria-label'))==='Copy decision campaign'?'upload':'skip');await page.locator('.network-sync-item').filter({hasText:'Campaign progress'}).screenshot({path:path.join(work,'campaign-comparison.png')});await page.getByRole('button',{name:'Apply reviewed choices',exact:true}).click();await idle(page);assert.match(await page.locator('.network-sync-receipts').innerText(),/copied upload: campaign/);const remote=await api('/progress/campaign',tokens[0]).then(r=>r.json());assert.deepEqual(remote.data,earned.data);report.cases.profileUpload=true;await page.screenshot({path:path.join(work,'campaign-upload-review.png')});
 const second=await pageNew(1),other=second.page;await other.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(other);await other.getByLabel('Import private sign-in key',{exact:true}).setInputFiles(signInKeyPath);await other.getByLabel('Your profile ID').waitFor();await idle(other);await other.getByRole('button',{name:'Save copies',exact:true}).click();await other.getByRole('button',{name:'Compare saves & settings',exact:true}).click();await idle(other);for(const select of await other.locator('select[aria-label^="Copy decision "]').all())await select.selectOption((await select.getAttribute('aria-label'))==='Copy decision campaign'?'download':'skip');await other.getByRole('button',{name:'Apply reviewed choices',exact:true}).click();await idle(other);assert.deepEqual((await localProgress(other)).data,earned.data);await other.reload();await other.getByRole('button',{name:'Field training',exact:true}).click({timeout:60000});assert.match(await other.locator('.mission-row').first().innerText(),/Completed/i);assert.deepEqual((await localProgress(other)).data,earned.data);report.cases.freshBrowserDownloadReload=true;report.cases.userKeyFileRestore=true;await other.screenshot({path:path.join(work,'restored-tutorial-menu.png')});
 // Real validated host archive entries; no synthetic save payloads or engine state writes.
 for(let offset=0;offset<65;offset+=4)await Promise.all(Array.from({length:Math.min(4,65-offset)},async(_,j)=>{const response=await api('/saves/'+`archive-${String(offset+j).padStart(2,'0')}`,tokens[0],'PUT','{"name":"Archive '+(offset+j)+'","expected_revision":0,"data":'+engine+'}');assert.equal(response.status,200,await response.text())}));
 await other.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(other);await other.getByRole('button',{name:'Save copies',exact:true}).click();const before=downloads.length;await other.getByRole('button',{name:'Compare saves & settings',exact:true}).click();await idle(other);await other.getByRole('heading',{name:'Choose this copy batch',exact:true}).waitFor();assert.equal(downloads.length,before);await other.getByLabel('Include settings',{exact:true}).uncheck();await other.getByLabel('Include campaign progress',{exact:true}).uncheck();await other.getByLabel('Find archive save').fill('archive-64');await other.getByLabel('Include save archive-64',{exact:true}).check();await other.getByRole('button',{name:'Compare selected items',exact:true}).click();await idle(other);assert.equal(downloads.length,before+1);assert.ok(downloads.at(-1).url.endsWith('/archive-64/download'));await other.getByLabel('Copy decision save:0',{exact:true}).selectOption('download');await other.getByRole('button',{name:'Apply reviewed choices',exact:true}).click();await idle(other);assert.ok(downloads.slice(before).every(value=>value.url.endsWith('/archive-64/download')));report.cases.largeArchiveSelection={hostFiles:65,selected:1,downloadsOnlySelected:true};await other.screenshot({path:path.join(work,'selected-archive-copy.png')});await other.getByRole('button',{name:'Choose archive batch',exact:true}).click();await idle(other);await other.setViewportSize({width:800,height:900});assert.equal(await other.locator('.network-sync-selection').evaluate(el=>el.scrollWidth>el.clientWidth+2),false);await other.getByRole('heading',{name:'Choose this copy batch',exact:true}).scrollIntoViewIfNeeded();await other.locator('.network-sync-selection').evaluate(el=>el.scrollIntoView({block:'start'}));await other.screenshot({path:path.join(work,'archive-selector-compact.png'),fullPage:true});
 // A distinct real profile cannot see the campaign or saves.
 const third=await pageNew(2),isolated=third.page;await isolated.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(isolated);await isolated.getByLabel('Commander name',{exact:true}).fill('Separate Commander');await isolated.getByRole('button',{name:'Create local profile',exact:true}).click();await isolated.getByLabel('Your profile ID').waitFor();await idle(isolated);await isolated.getByText('Private sign-in key',{exact:true}).click();const thirdKeyEvent=isolated.waitForEvent('download');await isolated.getByRole('button',{name:'Export private sign-in key',exact:true}).click();tokens[2]=JSON.parse(await readFile(await (await thirdKeyEvent).path(),'utf8')).token;assert.equal((await api('/progress/campaign',tokens[2]).then(r=>r.json())).revision,0);assert.equal((await api('/saves',tokens[2]).then(r=>r.json())).length,0);report.cases.profileIsolation=true;
 await page.getByRole('button',{name:'Editor',exact:true}).click();await page.getByLabel('Editor source map').selectOption('copper-junction');await page.getByLabel('Editable map grid').waitFor();const draftEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Export draft',exact:true}).click();const draftPath=await (await draftEvent).path();await isolated.getByRole('button',{name:'Editor',exact:true}).click();await isolated.getByLabel('Import editor document').setInputFiles(draftPath);await isolated.getByLabel('Editable map grid').waitFor();await idle(isolated);assert.ok(await isolated.getByLabel('Editor draft').locator('option').count()>1);report.cases.portableEditorDocument=true;

 // Whole-browser backup restore: explicit campaign replacement; unrelated records kept.
 await isolated.getByRole('button',{name:'Load operation',exact:true}).click();await isolated.getByLabel('Review browser backup',{exact:true}).setInputFiles(backupFile);await idle(isolated);const record=isolated.locator('.backup-review article').filter({has:isolated.getByText('progress · campaign',{exact:true})});await record.getByRole('combobox').selectOption('restore');await isolated.locator('.backup-review article').filter({hasText:'replays ·'}).getByRole('combobox').selectOption('restore');assert.equal(await localProgress(isolated),undefined);await record.screenshot({path:path.join(work,'portable-campaign-review.png')});await isolated.getByRole('button',{name:'Apply reviewed restore choices',exact:true}).click();await idle(isolated);assert.deepEqual((await localProgress(isolated)).data,earned.data);assert.equal((await api('/progress/campaign',tokens[2]).then(r=>r.json())).revision,0);report.cases.explicitPortableProgressRestore=true;await isolated.getByRole('button',{name:'Replay archive',exact:true}).click();await isolated.locator('.archive-list').getByRole('button',{name:'Watch',exact:true}).click();await isolated.locator('.battlefield-canvas canvas').waitFor({timeout:60000});await isolated.locator('.scene-loading').waitFor({state:'hidden',timeout:60000});assert.deepEqual((await localProgress(isolated)).data,earned.data);await isolated.getByRole('button',{name:'Open pause menu',exact:true}).click();await isolated.getByRole('button',{name:'Return to command center',exact:true}).click();report.cases.portableReplayPreservesProgress=true;await isolated.getByRole('button',{name:'Load operation',exact:true}).click();await isolated.screenshot({path:path.join(work,'portable-backup-restored.png')});assert.deepEqual(report.errors,[]);assert.deepEqual(report.consoleErrors,[]);assert.equal(await isolated.locator('vite-error-overlay').count(),0);report.status='passed';
}catch(error){report.status='failed';report.error=String(error.stack??error);process.exitCode=1;for(const [index,page] of pages.entries()){await page.screenshot({path:path.join(work,`failure-${index}.png`),fullPage:true}).catch(()=>{});await writeFile(path.join(work,`failure-${index}.txt`),await page.locator('body').innerText().catch(()=>''))}}
finally{await writeFile(path.join(work,'result.json'),JSON.stringify(report,null,2));const stable=path.join(root,'work/evidence/campaign-sync-ui');await mkdir(stable,{recursive:true});await copyFile(path.join(work,'result.json'),path.join(stable,'result.json'));await writeFile(path.join(work,'host.log'),log);await browser.close();host.kill('SIGTERM');console.log(JSON.stringify(report,null,2))}
