// Real product UI with three isolated browser profiles and the actual local Go host.
// Playwright supplies repeatable multi-context instrumentation; it does not add product test hooks.
import {chromium} from 'playwright-core';
import {build} from 'esbuild';
import {execFileSync,spawn} from 'node:child_process';
import {mkdir,mkdtemp,writeFile,readFile,copyFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const client=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),root=path.dirname(client),work=await mkdtemp(path.join(tmpdir(),'frontline-map-workshop-')),product=path.join(work,'product'),data=path.join(work,'host-data');
const run=(exe,args,options={})=>execFileSync(exe,args,{cwd:root,stdio:'inherit',...options});
run('go',['build','-trimpath','-o',path.join(work,'frontline'),'./cmd/frontline']);
run(process.execPath,[path.join(client,'node_modules/vite/bin/vite.js'),'build','--config',path.join(client,'vite.config.ts'),'--outDir',product]);
const decoder=path.join(work,'decode.mjs');await build({stdin:{contents:"export {fromBinary} from '@bufbuild/protobuf';export {EnvelopeSchema} from './protocol/frontline_pb';export {applyDelta} from './runtime/snapshot';",resolveDir:path.join(client,'src')},outfile:decoder,bundle:true,platform:'node',format:'esm',target:'es2022'});const {fromBinary,EnvelopeSchema,applyDelta}=await import(pathToFileURL(decoder));
const report={time:new Date().toISOString(),scope:'Actual local map publication and moderation product journeys, not release completion or balance proof.',cases:{},errors:[],evidence:work};
const host=spawn(path.join(work,'frontline'),['-addr','127.0.0.1:0','-data',data,'-static',product,'-maps',path.join(root,'content/maps'),'-missions',path.join(root,'content/missions')],{cwd:root,stdio:['ignore','pipe','pipe']});let log='';const origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Host start timeout '+log)),20000);host.stdout.on('data',bytes=>{log+=bytes;const match=log.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0])}});host.stderr.on('data',bytes=>log+=bytes);host.once('exit',code=>reject(Error('Host exited '+code)))});
const browser=await chromium.launch({headless:true}),contexts=[],pages=[],tokens=[],frames=[];report.browser=browser.version();
async function until(check,message,timeout=30000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw Error(message);await new Promise(resolve=>setTimeout(resolve,100))}}
async function idle(page,allowError=false){await until(async()=>await page.locator('.network-operation').count()===0&&await page.locator('[data-operator-busy]').count()===0,'Request did not finish',60000);if(!allowError&&await page.locator('.network-error').count())throw Error(await page.locator('.network-error').allInnerTexts())}
async function api(route,token,method='GET',body){return fetch(origin+'/api/v1'+route,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined})}
async function back(page){const dialog=page.getByRole('dialog').last();if(await dialog.getByRole('button',{name:'Command center',exact:true}).count())await dialog.getByRole('button',{name:'Command center',exact:true}).click();else{if(await page.getByRole('button',{name:'Open pause menu',exact:true}).isVisible())await page.getByRole('button',{name:'Open pause menu',exact:true}).click();await page.getByRole('button',{name:'Return to command center',exact:true}).click()}await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(page)}
try{
 for(let index=0;index<3;index++){
  const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),frame={};contexts.push(context);pages.push(page);frames.push(frame);
  page.on('pageerror',error=>report.errors.push(error.message));page.on('response',async response=>{if(new URL(response.url()).pathname==='/api/v1/profiles'&&response.request().method()==='POST'&&response.ok()){tokens[index]=(await response.json()).token}});
  page.on('websocket',socket=>socket.on('framereceived',value=>{if(typeof value.payload==='string')return;const message=fromBinary(EnvelopeSchema,new Uint8Array(value.payload)).message;if(message.case==='snapshot')frame.snapshot=message.value;else if(message.case==='delta')frame.snapshot=applyDelta(frame.snapshot,message.value);else if(message.case==='result')frame.result=message.value}));
  await page.goto(origin);await page.getByRole('button',{name:'Explore game modes',exact:true}).click({timeout:60000});await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle(page);
  if(index<3){await page.getByLabel('Commander name',{exact:true}).fill(index===0?'Workshop Author':index===1?'Workshop Reader':'Workshop Observer');await page.getByRole('button',{name:'Create local profile',exact:true}).click();await page.getByLabel('Your profile ID').waitFor();await idle(page)}
 }
 const [author,reader,operator]=pages,map=JSON.parse(await readFile(path.join(root,'content/maps/copper-junction.json'),'utf8'));map.id='workshop-acceptance';map.title='Workshop Acceptance';map.author='Source attribution';map.version='1';const original=JSON.stringify(map);
 await author.getByRole('button',{name:'Maps',exact:true}).click();await idle(author);await author.getByLabel('Upload map file').setInputFiles({name:'workshop.map.json',mimeType:'application/json',buffer:Buffer.from(original)});await idle(author);assert.match(await author.locator('.network-map-upload').innerText(),/Go validation passed/);assert.equal((await api('/maps/mine',tokens[0]).then(r=>r.json())).length,0);await author.getByRole('button',{name:'Upload private map',exact:true}).click();await idle(author);
 assert.equal((await api('/maps').then(r=>r.json())).some(value=>value.id===map.id),false);assert.equal((await api('/maps/'+map.id,tokens[1])).status,404);assert.equal((await api('/maps/mine',tokens[1]).then(r=>r.json())).length,0);report.cases.privateUploadIsolated=true;
 await author.getByRole('button',{name:'Create private map operation',exact:true}).click();await idle(author);const lobbyID=await author.getByLabel('Current lobby ID').inputValue(),code=await author.getByLabel('Current access code').inputValue();
 assert.equal((await api(`/maps/${map.id}?lobby_id=${lobbyID}`,tokens[1])).status,404);
 await reader.getByLabel('Join lobby ID').fill(lobbyID);await reader.getByLabel('Join access code').fill(code);await reader.getByRole('button',{name:'Join by ID',exact:true}).click();await idle(reader);await until(async()=>await reader.locator('.network-map-preview figcaption').innerText().then(value=>value.includes(map.title)),'Admitted private map preview did not load');assert.equal((await api(`/maps/${map.id}?lobby_id=${lobbyID}`,tokens[1])).status,200);report.cases.admittedPrivateMap=true;
 await new Promise(resolve=>setTimeout(resolve,2300));for(const page of [author,reader]){await page.getByRole('button',{name:'Ready to deploy',exact:true}).click();await idle(page)}await until(()=>author.getByRole('button',{name:'Start operation',exact:true}).isEnabled(),'Ready did not permit start');await author.getByRole('button',{name:'Start operation',exact:true}).click();await Promise.all([author,reader].map(page=>page.getByRole('complementary',{name:'Command sidebar'}).waitFor({timeout:60000})));await until(()=>frames[0].snapshot?.tick>130&&frames[1].snapshot?.tick>130,'Private map did not run');report.cases.privateMapPlayed=frames.slice(0,2).map(value=>({player:value.snapshot.player,tick:value.snapshot.tick}));
 const matchID=frames[0].snapshot.matchId??(await api('/lobbies/'+lobbyID,tokens[0]).then(r=>r.json())).lobby.match_id;
 // Author edits while two commanders are active; a fresh browser session must reconnect to the original blueprint.
 await back(author);await author.getByRole('button',{name:'Maps',exact:true}).click();await idle(author);const activeEdit={...map,title:'Workshop Active Edit',version:'2'};await author.getByLabel('Upload map file').setInputFiles({name:'active-revision.map.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(activeEdit))});await idle(author);await author.getByRole('button',{name:'Upload private map',exact:true}).click();await idle(author);
 assert.equal((await api(`/maps/${map.id}?match_id=${matchID}`,tokens[1]).then(r=>r.json())).version,'1');assert.equal((await api(`/maps/${map.id}?match_id=${matchID}`,tokens[2])).status,404);
 await reader.reload();await reader.getByRole('button',{name:'Multiplayer',exact:true}).click({timeout:60000});await idle(reader);await reader.getByRole('button',{name:'Reconnect to operation',exact:true}).click();await reader.getByRole('complementary',{name:'Command sidebar'}).waitFor({timeout:60000});await idle(reader);report.cases.freshReconnectRetainsOriginal=true;
 await operator.getByRole('button',{name:'Observe',exact:true}).click();await operator.getByLabel('Observe match ID').fill(matchID);await operator.getByLabel('Observe access code').fill(code);await operator.getByRole('button',{name:'Open observer feed',exact:true}).click();await operator.getByRole('complementary',{name:'Command sidebar'}).waitFor({timeout:60000});await idle(operator);assert.equal((await api(`/maps/${map.id}?match_id=${matchID}`,tokens[2]).then(r=>r.json())).version,'1');report.cases.observerRequiresGrant=true;await back(operator);
 await author.getByRole('button',{name:'Reconnect to operation',exact:true}).click();await author.getByRole('complementary',{name:'Command sidebar'}).waitFor({timeout:60000});await idle(author);
 for(const page of [author,reader])await page.getByRole('button',{name:'Open pause menu',exact:true}).click();await reader.getByRole('button',{name:'Report an incident',exact:true}).click();await reader.getByLabel('Incident details').fill('Workshop acceptance incident, synthetic evidence.');await reader.getByRole('button',{name:'Record report',exact:true}).click();await idle(reader);
 await author.getByRole('button',{name:'Surrender…',exact:true}).click();await author.getByRole('button',{name:'Confirm surrender',exact:true}).click();await idle(author);await until(()=>frames.some(value=>value.result?.committed),'No durable private result');for(const page of [author,reader]){await back(page);await page.getByRole('button',{name:'Close completed lobby',exact:true}).click();await idle(page)}
 await author.getByRole('button',{name:'Maps',exact:true}).click();await idle(author);await author.getByRole('button',{name:'Publish map',exact:true}).click();await idle(author);await reader.getByRole('button',{name:'Maps',exact:true}).click();await idle(reader);const community=reader.locator('.network-block').filter({has:reader.getByRole('heading',{name:'Community maps on this host',exact:true})});assert.match(await community.innerText(),/Workshop Active Edit/);assert.match(await community.innerText(),/Workshop Author/);report.cases.explicitPublication=true;
 await reader.getByRole('button',{name:'Report published map',exact:true}).click();await reader.getByLabel('Map report details').fill('Synthetic map acceptance review; compare preserved original with revision two.');await reader.getByRole('button',{name:'Record map report',exact:true}).click();await idle(reader);const ownReports=await api('/map-reports',tokens[1]).then(r=>r.json());assert.equal(ownReports.reports.length,1);assert.equal(ownReports.reports[0].owner,undefined);assert.equal((await api('/map-reports',tokens[0]).then(r=>r.json())).reports.length,0);report.cases.reportIsolation=true;
 // A later author revision is private; operator must inspect both versions.
 const revised={...map,title:'Workshop Revised',version:'3'};await author.getByLabel('Upload map file').setInputFiles({name:'workshop-v2.map.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(revised))});await idle(author);await author.getByRole('button',{name:'Upload private map',exact:true}).click();await idle(author);assert.equal((await api('/maps').then(r=>r.json())).some(value=>value.id===map.id),false);
 await operator.getByText('Host operator station',{exact:true}).click();await operator.getByLabel('Host moderator credential').fill(tokens[0]);await operator.getByRole('button',{name:'Unlock operator station',exact:true}).click();await idle(operator,true);assert.match(await operator.locator('.network-error').innerText(),/operator|credential|authorization/i);await operator.getByRole('button',{name:'Dismiss operator error',exact:true}).click();assert.equal(await operator.getByLabel('Host moderator credential').inputValue(),'');
 const credential=(await readFile(path.join(data,'moderator.token'),'utf8')).trim();await operator.getByLabel('Host moderator credential').fill(credential);await operator.getByRole('button',{name:'Unlock operator station',exact:true}).click();await until(()=>operator.getByRole('button',{name:'Lock operator station',exact:true}).isVisible(),'Operator unlock failed');await idle(operator);assert.equal(await operator.getByLabel('Host moderator credential').count(),0);
 await operator.locator('.network-report-list').first().getByRole('button').first().click();await idle(operator);await operator.getByLabel('Incident review decision').selectOption('confirmed');await operator.getByLabel('Incident review note').fill('Synthetic acceptance: inspected completed private replay evidence.');const replayDownload=operator.waitForEvent('download');await operator.getByRole('button',{name:'Download incident replay',exact:true}).click();const downloaded=await replayDownload;assert.ok((await readFile(await downloaded.path())).length>0);await idle(operator);await operator.getByRole('button',{name:'Record incident decision',exact:true}).click();await idle(operator);assert.match(await operator.locator('.network-review').first().innerText(),/confirmed/);report.cases.privateIncidentOperatorReview=true;
 await operator.getByRole('button',{name:'Load map reports',exact:true}).click();await idle(operator);await operator.locator('.network-map-moderation .network-report-list button').first().click();await idle(operator);assert.match(await operator.locator('.network-map-moderation').innerText(),/Workshop Active Edit/);assert.match(await operator.locator('.network-map-moderation').innerText(),/Workshop Revised/);await operator.getByLabel('Map moderation decision').selectOption('removed');await operator.getByLabel('Map moderation note').fill('Synthetic acceptance removal after examining preserved and current content.');await operator.getByRole('button',{name:'Record map decision',exact:true}).click();await idle(operator);await author.getByRole('button',{name:'Refresh map library',exact:true}).click();await idle(author);assert.match(await author.locator('.network-map-card').first().innerText(),/REMOVED BY OPERATOR/);assert.equal(await author.getByRole('button',{name:'Publish map',exact:true}).isDisabled(),true);report.cases.operatorRemoval=true;
 await operator.screenshot({path:path.join(work,'operator-map-review.png'),fullPage:true});await operator.getByLabel('Map moderation decision').selectOption('restored');await operator.getByLabel('Map moderation note').fill('Synthetic acceptance restoration; author must opt into publication again.');await operator.getByRole('button',{name:'Record map decision',exact:true}).click();await idle(operator);await author.getByRole('button',{name:'Refresh map library',exact:true}).click();await idle(author);assert.match(await author.locator('.network-map-card').first().innerText(),/PRIVATE/);assert.equal((await api('/maps').then(r=>r.json())).some(value=>value.id===map.id),false);await author.getByRole('button',{name:'Publish map',exact:true}).click();await idle(author);await reader.getByRole('button',{name:'Refresh map library',exact:true}).click();await idle(reader);assert.match(await community.innerText(),/Workshop Revised/);report.cases.restoreRequiresAuthorPublication=true;
 await community.screenshot({path:path.join(work,'published-map-library.png')});await author.setViewportSize({width:800,height:900});await author.screenshot({path:path.join(work,'map-workshop-compact.png'),fullPage:true});assert.equal(await author.locator('.network-panel').evaluate(el=>el.scrollWidth>el.clientWidth+2),false);
 // Editor handoff preserves the local draft and only prepares a private upload review.
 const beforeEditor=(await api('/maps/mine',tokens[0]).then(r=>r.json())).length;await author.getByRole('button',{name:'Editor',exact:true}).click();await author.getByLabel('Editor source map').selectOption('copper-junction');await author.getByLabel('Editable map grid').waitFor();await author.getByRole('button',{name:'Review host upload',exact:true}).click();await author.getByRole('button',{name:'Upload private map',exact:true}).waitFor({timeout:60000});await idle(author);assert.equal((await api('/maps/mine',tokens[0]).then(r=>r.json())).length,beforeEditor);await author.getByRole('button',{name:'Cancel map upload',exact:true}).click();await author.getByRole('button',{name:'Editor',exact:true}).click();await author.getByLabel('Editable map grid').waitFor();assert.ok(await author.getByLabel('Editor draft').locator('option').count()>1);report.cases.editorHandoffPreservesDraft=true;
 await operator.getByRole('button',{name:'Lock operator station',exact:true}).click();assert.equal(await operator.locator('.network-report-detail').count(),0);assert.equal(await operator.getByLabel('Host moderator credential').inputValue(),'');report.cases.operatorLockClearsEvidence=true;assert.deepEqual(report.errors,[]);report.status='passed';
}catch(error){report.status='failed';report.error=String(error.stack??error);process.exitCode=1;for(const [index,page] of pages.entries()){await page.screenshot({path:path.join(work,`failure-${index}.png`),fullPage:true}).catch(()=>{});await writeFile(path.join(work,`failure-${index}.txt`),await page.locator('body').innerText().catch(()=>''))}}
finally{await browser.close();if(host.exitCode===null){const stopped=new Promise(resolve=>host.once('exit',resolve));host.kill('SIGTERM');await stopped}await writeFile(path.join(work,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2))}
