// Nonvisual multi-context integration harness. All geometry is synthetic test data.
import {chromium} from 'playwright-core';
import {build} from 'esbuild';
import {execFileSync,spawn} from 'node:child_process';
import {copyFile,mkdir,mkdtemp,symlink,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import assert from 'node:assert/strict';
const client=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),root=path.dirname(client),work=path.join(root,'work/multiplayer-matrix'),runtimeDir=path.join(work,'runtime'),evidenceDir=path.join(root,'work/evidence/multiplayer-matrix');
await mkdir(runtimeDir,{recursive:true});await mkdir(evidenceDir,{recursive:true});
const execute=(binary,args,extra={})=>execFileSync(binary,args,{cwd:root,stdio:'inherit',...extra});
execute('go',['build','-trimpath','-o',path.join(work,'frontline'),'./cmd/frontline']);execute('go',['build','-trimpath','-o',path.join(runtimeDir,'frontline.wasm'),'./cmd/wasm'],{env:{...process.env,GOOS:'js',GOARCH:'wasm'}});execute('go',['build','-o',path.join(work,'audit'),'./work/multiplayer-matrix/audit.go']);
const goroot=execFileSync('go',['env','GOROOT'],{cwd:root,encoding:'utf8'}).trim();await copyFile(path.join(goroot,'lib/wasm/wasm_exec.js'),path.join(runtimeDir,'wasm_exec.js'));
await build({entryPoints:[path.join(client,'src/runtime/worker.ts')],outfile:path.join(runtimeDir,'worker.js'),bundle:true,platform:'browser',format:'iife',target:'es2022'});
const staticDir=path.join(work,'static');await mkdir(staticDir,{recursive:true});try{await symlink(runtimeDir,path.join(staticDir,'runtime'),'dir')}catch(error){if(error.code!=='EEXIST')throw error}
await build({stdin:{contents:"export {OfflineTransport} from './offline'; export {OnlineTransport} from './online'; export {LocalAPI} from './api';",resolveDir:path.join(client,'src/runtime'),sourcefile:'matrix-harness.ts'},outfile:path.join(staticDir,'harness.js'),bundle:true,platform:'browser',format:'iife',globalName:'Matrix',target:'es2022'});
await writeFile(path.join(staticDir,'index.html'),'<!doctype html><meta charset="utf-8"><title>Multiplayer runtime test fixture</title><link rel="icon" href="data:,"><script src="/harness.js"></script>');
const points=[{x:8000,y:8000},{x:56000,y:56000},{x:56000,y:8000},{x:8000,y:56000}];
const map={id:'matrix-four-slots',title:'Synthetic four-slot integration fixture',author:'automated test',version:'1',format_version:1,ruleset:'standard-v2',width:64,height:64,tiles:Array.from({length:4096},()=>({terrain:'open',height:0})),spawns:points.map((position,index)=>({position,team:index+1})),shipment:{x:32000,y:32000},fields:[{id:1,position:{x:14000,y:8000},credits:36000000},{id:2,position:{x:49000,y:56000},credits:36000000},{id:3,position:{x:49000,y:8000},credits:36000000},{id:4,position:{x:14000,y:56000},credits:36000000}],stations:[],regions:[],objects:[],required_packs:['2.0.0']};
const mission={id:'matrix-coop',title:'Synthetic cooperative integration fixture',version:'1',map_id:map.id,faction:'US',mode:'coop',default_bases:true,players:[{id:1,controller:'human',faction:'US',name:'First',team:1,credits:6000000},{id:2,controller:'human',faction:'SA',name:'Second',team:1,credits:6000000},{id:3,controller:'script',faction:'IR',name:'Script fixture',team:2,credits:6000000}],objectives:[{id:'timer',text:'Synthetic timer',condition:{kind:'timer',tick:700}}],triggers:[{id:'checkpoint',condition:{kind:'timer',tick:220},actions:[{kind:'checkpoint',text:'matrix-checkpoint'}]}]};
const report={date:new Date().toISOString(),scope:'Actual Go/WASM simulation and separate browser contexts; synthetic maps, not shipping map balance or visual playability.',browserPath:'Browser plugin unavailable; installed Playwright Chromium.',cases:[]};
const selected=process.env.FRONTLINE_MATRIX_CASE;
const browser=await chromium.launch({headless:true});report.browser={name:'chromium',version:browser.version()};
async function host(){
 const directory=await mkdtemp(path.join(tmpdir(),'frontline-matrix-'));await mkdir(path.join(directory,'maps'));await mkdir(path.join(directory,'missions'));await writeFile(path.join(directory,'maps/map.json'),JSON.stringify(map));await writeFile(path.join(directory,'missions/mission.json'),JSON.stringify(mission));
 const child=spawn(path.join(work,'frontline'),['-addr','127.0.0.1:0','-data',path.join(directory,'data'),'-maps',path.join(directory,'maps'),'-missions',path.join(directory,'missions'),'-static',staticDir],{cwd:root,stdio:['ignore','pipe','pipe']});let log='';
 const origin=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Matrix host startup timeout: '+log)),15000);child.stdout.on('data',value=>{log+=value;const found=log.match(/http:\/\/127\.0\.0\.1:\d+/);if(found){clearTimeout(timer);resolve(found[0])}});child.stderr.on('data',value=>log+=value);child.once('exit',code=>{clearTimeout(timer);reject(new Error(`Matrix host exited ${code}: ${log}`))})});
 return {origin,child,log:()=>log,async close(){if(child.exitCode===null){const stopped=new Promise(resolve=>child.once('exit',resolve));child.kill('SIGTERM');await stopped}}};
}
async function run(name,workFn){if(selected&&name!==selected)return;const current={name,status:'running'},server=await host(),contexts=[],errors=[];try{
 const page=async()=>{const context=await browser.newContext();contexts.push(context);const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));await page.goto(server.origin);return page};
 Object.assign(current,await workFn({server,page}));assert.deepEqual(errors,[]);current.status='passed';console.log(`${name}: passed`);
 }catch(error){current.status='failed';current.error=String(error.stack??error);current.hostLog=server.log();current.pageErrors=errors;console.error(`${name}: ${current.error}`);process.exitCode=1}finally{for(const context of contexts)await context.close();await server.close();report.cases.push(current);await writeFile(path.join(evidenceDir,'browser-results.json'),JSON.stringify(report,null,2))}}
function onlineCase(name,mode,humanTeams,ai=[],extra={}){return {name,mode,humanTeams,ai,...extra}}
try{
 for(let bots=0;bots<=3;bots++)await run(`offline-one-human-${bots}-bots`,async({page})=>{
  const p=await page(),result=await p.evaluate(async({map,bots})=>{
   const R=globalThis.Matrix,runtime=new R.OfflineTransport();await runtime.ready;const players=[{id:1,name:'Human',faction:'US',team:1,controller:'human'},...Array.from({length:bots},(_,index)=>({id:index+2,name:`Bot ${index+1}`,faction:['IR','SY','SA'][index],team:index+2,ai:'normal',controller:'ai'}))];
   const info=await runtime.create({map,players,seed:91,ruleset:bots===0?'practice-v1':'standard-v2',skip_countdown:true});let receipts=[];runtime.subscribe(event=>{if(event.type==='order-result')receipts.push(event.result)});const initial=JSON.parse(new TextDecoder().decode((await runtime.save()).data)).state;
   const rig=runtime.current.entities.find(entity=>entity.owner===1&&entity.type.endsWith('.rig'));const movedSequence=await runtime.sendOrders([{kind:'move',entities:[rig.id],position:{x:18000,y:12000}}]);await runtime.step(40);const move=receipts.find(value=>value.sequence===movedSequence&&value.accepted);let foreign;
   if(bots){const enemy=initial.entities.find(entity=>entity.owner===2);try{const sequence=await runtime.sendOrders([{kind:'stop',entities:[enemy.id]}]);await runtime.step(2);foreign=receipts.find(value=>value.sequence===sequence&&!value.accepted)?.code}catch(error){foreign=error.code}}
   while((await runtime.info()).tick<2500&&!(await runtime.info()).finished)await runtime.step(200);
   const saved=await runtime.save(),state=JSON.parse(new TextDecoder().decode(saved.data)).state;const old=new Map(initial.entities.map(entity=>[entity.id,entity]));const ai=state.players.filter(player=>player.ai).map(player=>({id:player.id,spent:player.spent,income:player.income,sequence:player.last_sequence,newEntities:state.entities.filter(entity=>entity.owner===player.id&&!old.has(entity.id)).length,moved:state.entities.filter(entity=>entity.owner===player.id&&old.has(entity.id)&&(entity.position.x!==old.get(entity.id).position.x||entity.position.y!==old.get(entity.id).position.y)).length}));const beforeHash=await runtime.hash();await runtime.load(saved.data,saved.local_players);const exactRestore=(await runtime.hash())===beforeHash;
   const result={players:state.players.length,localPlayers:info.local_players,ruleset:info.metadata.ruleset,moveAccepted:!!move,foreign,ai,tick:state.tick,finished:(await runtime.info()).finished,exactRestore};runtime.dispose();return result;
  },{map,bots});assert.equal(result.players,bots+1);assert.deepEqual(result.localPlayers,[1]);assert.ok(result.moveAccepted&&result.exactRestore);if(bots){assert.equal(result.foreign,'not_owner');assert.equal(result.ai.length,bots);for(const ai of result.ai){assert.ok(ai.spent>0&&ai.sequence>0&&ai.newEntities>0&&ai.moved>0,JSON.stringify(ai))}}else{assert.equal(result.ruleset,'practice-v1');assert.equal(result.finished,false)}return result;
 });
 await run('offline-two-human-coop',async({page})=>{
  const p=await page();const result=await p.evaluate(async({map,mission})=>{const runtime=new Matrix.OfflineTransport();await runtime.ready;const info=await runtime.create({map,mission,seed:44,skip_countdown:true});const commands=[],receipts=[];runtime.subscribe(event=>{if(event.type==='order-result')receipts.push(event.result)});for(const player of [1,2]){await runtime.setPerspective(player);const own=runtime.current.entities.find(entity=>entity.owner===player&&entity.type.endsWith('.rig'));const ally=runtime.current.entities.find(entity=>entity.owner!==player&&entity.owner<=2);let rejected;try{const preview=await runtime.previewOrders([{kind:'stop',entities:[ally.id]}]);rejected=preview.results[0].code}catch(error){rejected=error.code}let actualRejected;try{await runtime.sendOrders([{kind:'stop',entities:[ally.id]}])}catch(error){actualRejected=error.code}const sequence=await runtime.sendOrders([{kind:'move',entities:[own.id],position:{x:own.position.x+2000,y:own.position.y}}]);await runtime.step(2);commands.push({player,sharedVision:!!ally,allyPrivate:!!ally.private,rejected,actualRejected,ownAccepted:receipts.some(result=>result.player===player&&result.sequence===sequence&&result.accepted)})}const saved=await runtime.save();await runtime.load(saved.data,[1,2]);while(!(await runtime.info()).finished)await runtime.step(100);const result={localPlayers:info.local_players,commands,outcome:runtime.current.outcome,mission:runtime.current.mission};runtime.dispose();return result},{map,mission});assert.deepEqual(result.localPlayers,[1,2]);for(const command of result.commands){assert.ok(command.sharedVision);assert.equal(command.allyPrivate,false);assert.equal(command.rejected,'not_owner');assert.equal(command.actualRejected,'not_owner');assert.ok(command.ownAccepted)}assert.equal(result.outcome.winningTeam,1);return result;
 });
 const cases=[onlineCase('online-one-human-custom','custom',[1],[],{pause:true}),onlineCase('online-two-human-two-ai','custom',[1,1],[{faction:'IR',difficulty:'normal',team:2},{faction:'SY',difficulty:'normal',team:2}],{pause:true}),onlineCase('online-three-human-ffa','ffa',[1,2,3]),onlineCase('online-four-human-ffa','ffa',[1,2,3,4]),onlineCase('online-four-human-2v2','2v2',[1,1,2,2]),onlineCase('online-two-human-coop-scenario','coop',[1,1],[],{mission:true,pause:true})];
 for(const scenario of cases)await run(scenario.name,async({page})=>{
  const pages=[];for(let index=0;index<scenario.humanTeams.length;index++){const p=await page();pages.push(p);await p.evaluate(async name=>{globalThis.api=new Matrix.LocalAPI(location.origin);globalThis.profile=(await api.createProfile(name)).profile;globalThis.health=await api.health()},`Matrix human ${index+1}`)}
  const first=pages[0],lobby=await first.evaluate(async({scenario,mapID,missionID})=>scenario.mission?api.coopLobby(missionID,{difficulty:'normal',private:true,pause_enabled:scenario.pause}):api.createLobby({name:scenario.name,map_id:mapID,mode:scenario.mode,private:true,faction:'US',team:scenario.humanTeams[0],ai:scenario.ai,pause_enabled:scenario.pause}),{scenario,mapID:map.id,missionID:mission.id});const id=lobby.lobby.id;
  for(let index=1;index<pages.length;index++)await pages[index].evaluate(({id,code,team,scenario,index})=>api.joinLobby(id,{code,...(scenario.mission?{}:{team,faction:['US','SA','IR','SY'][index]})}),{id,code:lobby.code,team:scenario.humanTeams[index],scenario,index});
  const admission=await first.evaluate(async mapID=>{try{await api.createLobby({name:'Forbidden duplicate',map_id:mapID,mode:'custom',faction:'US'});return 'accepted'}catch(error){return error.code}},map.id);assert.equal(admission,'already_in_lobby');
  const notReady=await first.evaluate(async id=>{try{await api.startLobby(id);return 'accepted'}catch(error){return error.code}},id);assert.equal(notReady,'players_not_ready');const last=pages.at(-1);const missingAssets=await last.evaluate(async id=>{try{await api.readyLobby(id,health,true,false);return 'accepted'}catch(error){return error.code}},id);assert.equal(missingAssets,'content_not_ready');
  for(const p of pages)await p.evaluate(async id=>api.readyLobby(id,health,true,true,(await api.lobby(id)).lobby.revision),id);
  const ready=await first.evaluate(id=>api.lobby(id),id);assert.ok(ready.lobby.slots.every(slot=>slot.ready&&slot.assets_ready));assert.equal(new Set(ready.lobby.slots.map(slot=>slot.color)).size,ready.lobby.slots.length);const started=await first.evaluate(id=>api.startLobby(id),id);const connections=[];for(const p of pages)connections.push(await p.evaluate(id=>api.lobby(id).then(value=>value.connection),id));
  const connect=(p,connection)=>p.evaluate(async connection=>{globalThis.receipts=[];globalThis.statuses=[];globalThis.networkErrors=[];globalThis.matchResult=null;globalThis.online=new Matrix.OnlineTransport(location.origin,connection);online.subscribe(event=>{if(event.type==='order-result')receipts.push(event.result);if(event.type==='status'){globalThis.matchStatus=event.status;statuses.push(event.status)}if(event.type==='result')globalThis.matchResult=event.result;if(event.type==='error')networkErrors.push({code:event.error.code,message:event.error.message})});await online.connect();return {player:online.current.player,tick:online.current.tick}},connection);
  await connect(first,connections[0]);let waitingForAll=true;if(pages.length>1){await first.waitForFunction(()=>globalThis.matchStatus?.waitingForPlayers===true);const before=await first.evaluate(()=>online.current.tick);await new Promise(resolve=>setTimeout(resolve,350));waitingForAll=(await first.evaluate(()=>online.current.tick))===before;assert.ok(waitingForAll);for(let index=1;index<pages.length;index++)await connect(pages[index],connections[index])}
  await Promise.all(pages.map(p=>p.waitForFunction(()=>online.current?.countdown===0,null,{timeout:15000,polling:50})));
  const identity=await Promise.all(pages.map(p=>p.evaluate(()=>{const current=online.current,player=current.players.find(p=>p.id===current.player),allies=current.players.filter(p=>p.id!==current.player&&p.team===player.team);return {profile:profile.id,player:current.player,team:player.team,rig:current.entities.find(entity=>entity.owner===current.player&&entity.type.endsWith('.rig')),owners:[...new Set(current.entities.map(entity=>entity.owner))],allyVisible:allies.every(ally=>current.entities.some(entity=>entity.owner===ally.id)),foreignPrivate:current.entities.some(entity=>entity.owner!==current.player&&!!entity.private),tick:current.tick}})));
  assert.equal(new Set(identity.map(item=>item.profile)).size,pages.length);assert.equal(new Set(identity.map(item=>item.player)).size,pages.length);for(const view of identity){assert.ok(view.rig);assert.ok(view.allyVisible);assert.equal(view.foreignPrivate,false);const allowed=ready.lobby.slots.filter(slot=>slot.team===view.team).map(slot=>slot.player);assert.ok(view.owners.every(owner=>allowed.includes(owner)),JSON.stringify({owners:view.owners,allowed}))}
  const commandResults=[];for(let index=0;index<pages.length;index++){const p=pages[index],own=identity[index].rig,sequence=await p.evaluate(own=>online.sendOrders([{kind:'move',entities:[own.id],position:{x:own.position.x+(own.position.x>32000?-3000:3000),y:own.position.y}}]),own);await p.waitForFunction(sequence=>receipts.some(result=>result.sequence===sequence&&result.accepted),sequence);let notOwner;if(pages.length>1){const foreign=identity[(index+1)%pages.length].rig.id,wrong=await p.evaluate(foreign=>online.sendOrders([{kind:'stop',entities:[foreign]}]),foreign);await p.waitForFunction(sequence=>receipts.some(result=>result.sequence===sequence&&!result.accepted&&result.code==='not_owner'),wrong);notOwner='not_owner'}commandResults.push({player:identity[index].player,accepted:true,notOwner})}
  let pauseVerified=false;if(scenario.pause){await first.evaluate(()=>online.pause());if(pages.length>1){await first.waitForFunction(()=>globalThis.matchStatus?.pauseVotes.length===1&&!globalThis.matchStatus.paused);const before=await first.evaluate(()=>online.current.tick);await first.waitForFunction(before=>online.current.tick>before+4,before);for(const p of pages.slice(1))await p.evaluate(()=>online.pause())}await Promise.all(pages.map(p=>p.waitForFunction(()=>globalThis.matchStatus?.paused===true)));await new Promise(resolve=>setTimeout(resolve,100));const tick=await first.evaluate(()=>online.current.tick);await new Promise(resolve=>setTimeout(resolve,350));assert.equal(await first.evaluate(()=>online.current.tick),tick);await last.evaluate(()=>online.resume());await first.waitForFunction(tick=>online.current.tick>tick,tick);pauseVerified=true}
  const reconnect=await last.evaluate(async()=>{const before=online.current.economy.lastSequence;await online.reconnect();return {player:online.current.player,before,after:online.current.economy.lastSequence,phase:online.phase}});assert.equal(reconnect.player,identity.at(-1).player);assert.equal(reconnect.phase,'connected');assert.ok(reconnect.after>=reconnect.before);
  const tickStart=await first.evaluate(()=>online.current.tick);await first.waitForFunction(tick=>online.current.tick>=tick+45,tickStart);const movement=await Promise.all(pages.map((p,index)=>p.evaluate(old=>{const entity=online.current.entities.find(entity=>entity.id===old.id);return !!entity&&(entity.position.x!==old.position.x||entity.position.y!==old.position.y)},identity[index].rig)));assert.ok(movement.every(Boolean),JSON.stringify(movement));
  let surrendered=[],teamConsensus=false;if(scenario.ai.length){await first.waitForFunction(()=>online.current.tick>=460,null,{timeout:30000});for(const p of pages){await p.evaluate(()=>online.sendOrders([{kind:'surrender'}]));surrendered.push(await p.evaluate(()=>online.current.player))}}else if(scenario.mode==='2v2'){const losing=identity[0].team,indices=identity.map((value,index)=>value.team===losing?index:-1).filter(index=>index>=0);await pages[indices[0]].evaluate(()=>online.sendOrders([{kind:'surrender_vote'}]));await first.waitForFunction(player=>online.current.players.some(value=>value.id===player&&value.surrenderVote&&!value.defeated),identity[indices[0]].player);assert.equal(await first.evaluate(()=>online.current.outcome.finished),false);await pages[indices[1]].evaluate(()=>online.sendOrders([{kind:'surrender_vote'}]));surrendered=indices.map(index=>identity[index].player);teamConsensus=true}else if(!scenario.mission){const lastTeam=identity.at(-1).team;for(let index=0;index<pages.length;index++){if(pages.length>1&&identity[index].team===lastTeam)continue;await pages[index].evaluate(()=>online.sendOrders([{kind:'surrender'}]));surrendered.push(identity[index].player)}}
  await Promise.all(pages.map(p=>p.waitForFunction(()=>globalThis.matchResult?.committed,null,{timeout:40000,polling:100})));
  const results=await Promise.all(pages.map(p=>p.evaluate(()=>({outcome:matchResult.outcome,committed:matchResult.committed,void:matchResult.void}))));for(const result of results){assert.ok(result.committed&&!result.void);assert.deepEqual(result.outcome,results[0].outcome)}
  const expectedWinner=scenario.mission?1:scenario.ai.length?2:pages.length===1?0:identity.at(-1).team;assert.equal(results[0].outcome.winningTeam,expectedWinner);
  const replayBytes=await first.evaluate(async id=>Array.from(await api.replay(id)),started.connection.match_id),replayPath=path.join(evidenceDir,`${scenario.name}.fcr`);await writeFile(replayPath,new Uint8Array(replayBytes));const native=JSON.parse(execFileSync(path.join(work,'audit'),['-replay',replayPath],{cwd:root,encoding:'utf8'}));if(scenario.ai.length)for(const bot of native.players.filter(player=>player.ai)){assert.ok(bot.spent>0&&bot.sequence>0&&bot.new_entities>0&&bot.moved_entities>0,JSON.stringify(bot))}
  const profileReleased=await first.evaluate(async mapID=>{const next=await api.createLobby({name:'After result',map_id:mapID,mode:'custom',faction:'US'});await api.leaveLobby(next.lobby.id);return true},map.id);const errors=await Promise.all(pages.map(p=>p.evaluate(()=>networkErrors)));for(const collection of errors)assert.deepEqual(collection,[]);
  const output={humans:pages.length,ai:scenario.ai.length,mode:scenario.mode,players:ready.lobby.slots.map(slot=>({player:slot.player,team:slot.team,color:slot.color,ai:!!slot.ai,script:!!slot.script})),distinctProfiles:true,admission,profileReleased,missingAssets,notReady,waitingForAll,sharedVision:identity.every(value=>value.allyVisible),foreignPrivate:false,commandResults,movement,pauseVerified,reconnect,surrendered,teamConsensus,outcome:results[0].outcome,native};
  await Promise.all(pages.map(p=>p.evaluate(()=>online.dispose())));return output;
 });
}finally{await browser.close();await writeFile(path.join(evidenceDir,'browser-results.json'),JSON.stringify(report,null,2))}
if(!report.cases.length)throw new Error('No matrix case selected');
