// Actual packaged product UI, isolated local Go host, independent browser profiles.
// Browser plugin is unavailable in this workspace; use the installed Playwright Chromium.
import {chromium} from 'playwright-core';
import {build} from 'esbuild';
import {execFileSync,spawn} from 'node:child_process';
import {copyFile,mkdir,mkdtemp,writeFile,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {pathToFileURL,fileURLToPath} from 'node:url';
import path from 'node:path';
import assert from 'node:assert/strict';
const client=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..'),root=path.dirname(client),work=await mkdtemp(path.join(tmpdir(),'frontline-network-ui-')),product=path.join(work,'product');
const run=(exe,args,options={})=>execFileSync(exe,args,{cwd:root,stdio:'inherit',...options});
run('go',['build','-trimpath','-o',path.join(work,'frontline'),'./cmd/frontline']);
run(process.execPath,[path.join(client,'node_modules/vite/bin/vite.js'),'build','--config',path.join(client,'vite.config.ts'),'--outDir',product]);
await mkdir(path.join(product,'runtime'),{recursive:true});run('go',['build','-trimpath','-o',path.join(product,'runtime/frontline.wasm'),'./cmd/wasm'],{env:{...process.env,GOOS:'js',GOARCH:'wasm'}});
const goroot=execFileSync('go',['env','GOROOT'],{cwd:root,encoding:'utf8'}).trim();await copyFile(path.join(goroot,'lib/wasm/wasm_exec.js'),path.join(product,'runtime/wasm_exec.js'));
await build({entryPoints:[path.join(client,'src/runtime/worker.ts')],outfile:path.join(product,'runtime/worker.js'),bundle:true,platform:'browser',format:'iife',target:'es2022'});
// Passive frame decoder: no test API is injected into the production application.
const decoder=path.join(work,'decode.mjs');await build({stdin:{contents:"export {fromBinary} from '@bufbuild/protobuf';export {EnvelopeSchema,PlayerSnapshotSchema} from './protocol/frontline_pb';export {applyDelta} from './runtime/snapshot';",resolveDir:path.join(client,'src')},outfile:decoder,bundle:true,platform:'node',format:'esm',target:'es2022'});
const {fromBinary,EnvelopeSchema,PlayerSnapshotSchema,applyDelta}=await import(pathToFileURL(decoder));
const report={time:new Date().toISOString(),evidence:work,scope:'Product UI over actual local Go + WASM. Passive WebSocket decoding measures authoritative results. No shipping-map balance or completed release claim.',cases:[],browser:'Browser plugin unavailable; installed Playwright Chromium.'};
const browser=await chromium.launch({headless:true,args:['--host-resolver-rules=MAP frontline-network.test 127.0.0.1','--no-proxy-server']});
const requested=process.env.FRONTLINE_NETWORK_UI_CASE;
const selected=requested?requested.split(','):['2','3','4'];
async function startHost(name){const data=path.join(work,`data-${name}`),child=spawn(path.join(work,'frontline'),['-addr','127.0.0.1:0','-data',data,'-static',product,'-maps',path.join(root,'content/maps'),'-missions',path.join(root,'content/missions')],{cwd:root,stdio:['ignore','pipe','pipe']});let log='';const local=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Host startup timeout '+log)),20000);child.stdout.on('data',bytes=>{log+=bytes;const match=log.match(/http:\/\/127\.0\.0\.1:\d+/);if(match){clearTimeout(timer);resolve(match[0])}});child.stderr.on('data',bytes=>log+=bytes);child.once('exit',code=>{clearTimeout(timer);reject(Error('Host exited '+code+' '+log))})});return {origin:local.replace('127.0.0.1','frontline-network.test'),log:()=>log,close:async()=>{if(child.exitCode===null){const stopped=new Promise(resolve=>child.once('exit',resolve));child.kill('SIGTERM');await stopped}}}}
async function until(check,message,timeout=20000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw Error(message);await new Promise(resolve=>setTimeout(resolve,100))}}
async function noBusy(page){await until(async()=>await page.locator('.network-operation').count()===0,'Network operation did not finish',60000);const error=page.locator('.network-error');if(await error.count())throw Error(await error.innerText())}
async function menu(page){if(await page.getByRole('button',{name:'Open pause menu',exact:true}).isVisible())await page.getByRole('button',{name:'Open pause menu',exact:true}).click();await page.getByRole('region',{name:'Online operation controls'}).first().waitFor()}
async function scenario(count,kind='standard'){
 const record={name:`product-${count}-human-${kind==='standard'?(count===4?'2v2':count===3?'ffa':'custom-social-sync'):kind}`,status:'running'},server=await startHost(`${count}-${kind}`),contexts=[],pages=[],evidence=[],errors=[];
 try{
  for(let index=0;index<count;index++){
   const context=await browser.newContext({viewport:{width:1440,height:1000}});contexts.push(context);const page=await context.newPage(),frames={snapshot:undefined,result:undefined,status:undefined,receipts:[],sockets:0};pages.push(page);evidence.push(frames);
   page.on('response',async response=>{if(response.status()>=400)try{(record.httpErrors??=[]).push({url:new URL(response.url()).pathname,status:response.status(),body:(await response.text()).slice(0,500)})}catch{}});page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error')errors.push(message.text()+' '+message.location().url)});
   page.on('websocket',socket=>{frames.sockets++;socket.on('framereceived',frame=>{try{if(typeof frame.payload==='string')return;const message=fromBinary(EnvelopeSchema,new Uint8Array(frame.payload)).message;if(message.case==='snapshot'){frames.snapshot=message.value;frames.receipts.push(...message.value.results)}else if(message.case==='delta'){frames.snapshot=applyDelta(frames.snapshot,message.value);frames.receipts.push(...frames.snapshot.results)}else if(message.case==='result')frames.result=message.value;else if(message.case==='status')frames.status=message.value;else if(message.case==='orderResult')frames.receipts.push(message.value)}catch(error){errors.push('Passive decoder: '+error.message)}})});
   await page.goto(server.origin);await page.getByRole('button',{name:'Explore game modes',exact:true}).click({timeout:60000});await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await page.getByLabel('Commander name',{exact:true}).fill(`UI Commander ${index+1}`);await noBusy(page);await page.getByRole('button',{name:'Create local profile',exact:true}).click();await page.getByLabel('Your profile ID').waitFor();await noBusy(page);
  }
  const first=pages[0],last=pages.at(-1),profileIDs=await Promise.all(pages.map(page=>page.getByLabel('Your profile ID').inputValue()));assert.equal(new Set(profileIDs).size,count);
  record.insecureOrigin=await first.evaluate(()=>({secure:globalThis.isSecureContext,subtle:!!crypto.subtle,randomUUID:typeof crypto.randomUUID,randomValues:typeof crypto.getRandomValues}));assert.equal(record.insecureOrigin.secure,false);assert.equal(record.insecureOrigin.subtle,false);
  if(count===2){
   await first.getByRole('button',{name:'Contacts',exact:true}).click();await first.getByLabel('Contact profile ID').fill(profileIDs[1]);await first.getByRole('button',{name:'Send friend request',exact:true}).click();await noBusy(first);
   await last.getByRole('button',{name:'Contacts',exact:true}).click();await last.getByRole('button',{name:'Refresh invitations',exact:true}).click();await noBusy(last);await last.getByRole('button',{name:'Accept friend',exact:true}).click();await noBusy(last);await first.getByRole('button',{name:'Refresh invitations',exact:true}).click();await noBusy(first);
   await first.getByRole('button',{name:'Save copies',exact:true}).click();await first.getByRole('button',{name:'Compare saves & settings',exact:true}).click();await noBusy(first);await first.getByLabel('Copy decision settings').selectOption('upload');await first.getByRole('button',{name:'Apply reviewed choices',exact:true}).click();await noBusy(first);assert.match(await first.locator('.network-sync-receipts').innerText(),/copied/);record.explicitSettingsUpload=true;
   await first.getByRole('button',{name:'Operations',exact:true}).click();
  }
  if(kind==='coop'){await first.getByRole('button',{name:'Co-op',exact:true}).click();await first.getByRole('button',{name:'Create co-op lobby',exact:true}).last().click();await noBusy(first)}else{await first.getByLabel('Operation name',{exact:true}).fill(`UI matrix ${count}`);await first.getByLabel('Lobby battlefield').selectOption('industrial-valley');await first.getByLabel('Battle format',{exact:true}).selectOption(count===4?'2v2':count===3?'ffa':'custom');
  if(count===2)await first.getByLabel('Private access code',{exact:true}).check();if(kind==='observer-live')await first.getByLabel('Live observers',{exact:true}).check();await first.getByRole('button',{name:'Create operation',exact:true}).click();await noBusy(first)}const privateCode=await first.getByLabel('Current access code').count()?await first.getByLabel('Current access code').inputValue():'';const lobbyID=await first.getByLabel('Current lobby ID').inputValue();
  if(count===2){await first.getByRole('button',{name:'Contacts',exact:true}).click();await first.getByRole('button',{name:'Invite to lobby',exact:true}).click();await noBusy(first);await last.getByRole('button',{name:'Refresh invitations',exact:true}).click();await noBusy(last);await last.getByRole('button',{name:'Accept invitation',exact:true}).click();await noBusy(last);record.friendInvitation=true}
  else for(let index=1;index<count;index++){await pages[index].getByLabel('Join lobby ID').fill(lobbyID);await pages[index].getByRole('button',{name:'Join by ID',exact:true}).click();await noBusy(pages[index])}
  if(kind==='ai'){await last.getByLabel('Commander 2 team',{exact:true}).selectOption('1');await noBusy(last);for(const faction of ['SY','SA']){await first.getByLabel('Add AI faction').selectOption(faction);await first.getByRole('button',{name:'Add AI commander',exact:true}).click();await noBusy(first)}}const rosterCount=kind==='ai'?4:kind==='coop'?4:count;await until(async()=>await first.locator('.network-commander').count()===rosterCount,'Roster did not fill');
  for(let index=0;index<count;index++){const page=pages[index];await until(async()=>await page.locator('.network-commander').count()===rosterCount,'Incomplete remote roster');if(kind!=='coop')await page.getByLabel(`Commander ${index+1} faction`,{exact:true}).selectOption(['US','IR','SY','SA'][index]);await noBusy(page);if(count===4){await page.getByLabel(`Commander ${index+1} team`,{exact:true}).selectOption(index<2?'1':'2');await noBusy(page)}}
  // Let all clients receive the final configuration revision before readiness.
  await new Promise(resolve=>setTimeout(resolve,2500));
  if(count===2){await first.getByLabel('Chat message',{exact:true}).fill('Private test channel checked');await first.getByRole('button',{name:'Send',exact:true}).click();await noBusy(first);await until(async()=>await last.getByRole('log',{name:'Lobby chat'}).innerText().then(text=>text.includes('Private test channel checked')),'Chat was not delivered');record.chat=true}
  if(count===2&&kind==='standard'){
   await last.getByRole('button',{name:'Contacts',exact:true}).click();await last.getByRole('button',{name:'Mute',exact:true}).first().click();await noBusy(last);assert.equal((await last.getByRole('log',{name:'Lobby chat'}).innerText()).includes('Private test channel checked'),false);await last.getByRole('button',{name:'Unmute',exact:true}).click();await noBusy(last);assert.equal((await last.getByRole('log',{name:'Lobby chat'}).innerText()).includes('Private test channel checked'),true);
   await last.getByRole('button',{name:'Block',exact:true}).first().click();await noBusy(last);assert.equal((await last.getByRole('log',{name:'Lobby chat'}).innerText()).includes('Private test channel checked'),false);await last.getByRole('button',{name:'Unblock',exact:true}).click();await noBusy(last);assert.equal((await last.getByRole('log',{name:'Lobby chat'}).innerText()).includes('Private test channel checked'),true);record.muteBlockHistoryFilters=true;
  }
  for(const page of pages){await page.getByRole('button',{name:'Ready to deploy',exact:true}).click();await noBusy(page)}
  await until(async()=>await first.getByRole('button',{name:'Start operation',exact:true}).isEnabled(),'Full readiness did not enable start');await first.screenshot({path:path.join(work,`lobby-${count}-${kind}.png`),fullPage:true});await first.locator('.network-lobby-heading').scrollIntoViewIfNeeded();await first.screenshot({path:path.join(work,`roster-${count}-${kind}.png`),fullPage:true});await first.locator('.network-map-preview').first().screenshot({path:path.join(work,`map-preview-${count}-${kind}.png`)});
  await first.getByRole('button',{name:'Start operation',exact:true}).click();await Promise.all(pages.map(page=>page.getByRole('complementary',{name:'Command sidebar'}).waitFor({timeout:60000})));await until(()=>evidence.every(value=>value.snapshot?.tick>130),'All commander snapshots did not advance',60000);
  record.players=evidence.map(value=>({player:value.snapshot.player,team:value.snapshot.players.find(player=>player.id===value.snapshot.player).team,privateOwners:[...new Set(value.snapshot.entities.filter(entity=>entity.private).map(entity=>entity.owner))]}));for(const player of record.players)assert.deepEqual(player.privateOwners,[player.player]);
  // Actual product selection and hold command through the Go advisory/send path.
  for(let index=0;index<count;index++){const page=pages[index];await page.getByRole('button',{name:'Build',exact:true}).click();await page.getByRole('button',{name:/^Hold/}).click({timeout:15000});await until(()=>evidence[index].receipts.some(value=>value.accepted),'Owned command not acknowledged')}
  if(count===2){await Promise.all(pages.map(page=>menu(page)));for(const page of pages){await page.getByRole('button',{name:'Request shared pause',exact:true}).click();await noBusy(page)}await until(()=>evidence.every(value=>value.status?.paused),'Shared pause not applied');const tick=evidence[0].snapshot.tick;await new Promise(resolve=>setTimeout(resolve,400));assert.equal(evidence[0].snapshot.tick,tick);record.sharedPause=true;await last.getByRole('button',{name:'Resume / withdraw vote',exact:true}).click();await noBusy(last);await until(()=>evidence[0].snapshot.tick>tick,'Resume did not advance');await last.getByRole('button',{name:'Reconnect',exact:true}).click();await noBusy(last);await until(()=>evidence[1].sockets>=2,'Replacement socket not created');record.reconnected=true;await first.getByRole('button',{name:'Report an incident',exact:true}).click();await first.getByLabel('Incident details').fill('Synthetic UI acceptance report; no real player incident.');await first.getByRole('button',{name:'Record report',exact:true}).click();await noBusy(first);record.localReport=true}
  else await Promise.all(pages.map(page=>menu(page)));
  if(kind.startsWith('observer-')){
   const context=await browser.newContext({viewport:{width:1440,height:1000}});contexts.push(context);const spectator=await context.newPage(),observerFrames=[],observerStatuses=[];pages.push(spectator);spectator.on('pageerror',error=>errors.push(error.message));spectator.on('response',async response=>{if(!response.url().endsWith('/observer')||response.request().method()!=='GET')return;observerStatuses.push(response.status());if(response.status()===200)try{observerFrames.push(fromBinary(PlayerSnapshotSchema,new Uint8Array(await response.body())))}catch{}});
   await spectator.goto(server.origin);await spectator.getByRole('button',{name:'Explore game modes',exact:true}).click({timeout:60000});await spectator.getByRole('button',{name:'Multiplayer',exact:true}).click();await noBusy(spectator);await spectator.getByLabel('Commander name').fill('UI Spectator');await spectator.getByRole('button',{name:'Create local profile',exact:true}).click();await noBusy(spectator);await spectator.getByRole('button',{name:'Observe',exact:true}).click();await spectator.getByLabel('Observe match ID').fill(await first.getByLabel('Current match ID').inputValue());await spectator.getByLabel('Observe access code').fill(privateCode);await spectator.getByLabel('Observer perspective').selectOption('1');await spectator.getByRole('button',{name:'Open observer feed',exact:true}).click();await noBusy(spectator);await spectator.getByRole('complementary',{name:'Command sidebar'}).waitFor({timeout:60000});
   if(kind==='observer-delayed'){await until(()=>observerStatuses.includes(202),'Delayed observer did not buffer');await spectator.locator('.scene-loading').waitFor({state:'hidden',timeout:60000});assert.equal(observerFrames.length,0);assert.equal(await spectator.getByRole('button',{name:'Hold',exact:true}).count(),0);await spectator.screenshot({path:path.join(work,'observer-buffering.png'),fullPage:true})}
   await until(()=>observerFrames.length>0,'Authorized observer snapshot never arrived',150000);const latest=observerFrames.at(-1),hostTick=evidence[0].snapshot.tick;record.observer={delay:kind==='observer-live'?0:2400,tick:latest.tick,hostTick,buffered:observerStatuses.includes(202),player:latest.player,receipts:latest.results.length};if(kind==='observer-delayed')assert.ok(hostTick-latest.tick>=2400);else assert.ok(hostTick-latest.tick<100);assert.equal(latest.player,1);assert.equal(latest.results.length,0);await spectator.getByRole('button',{name:'Open pause menu',exact:true}).click();await spectator.getByRole('region',{name:'Observer feed controls'}).waitFor();assert.equal(await spectator.getByRole('button',{name:'Request shared pause',exact:true}).count(),0);assert.equal(await spectator.getByRole('button',{name:'Surrender…',exact:true}).count(),0);await spectator.getByRole('button',{name:'Reconnect observer feed',exact:true}).click();await noBusy(spectator);await spectator.screenshot({path:path.join(work,`${kind}.png`),fullPage:true});pages.pop();
  }
  const losing=kind==='ai'||kind==='coop'?[0,1]:count===4?[0,1]:Array.from({length:count-1},(_,index)=>index);
  for(const index of losing){const page=pages[index];if(count===4){await page.getByRole('button',{name:'Vote team surrender',exact:true}).click();await noBusy(page);if(index===0){await until(()=>evidence[0].snapshot.players.some(player=>player.id===1&&player.surrenderVote),'First teammate vote was not recorded');assert.equal(evidence[0].snapshot.outcome?.finished,false)}}else{await page.getByRole('button',{name:'Surrender…',exact:true}).click();await page.getByRole('button',{name:'Confirm surrender',exact:true}).click();await noBusy(page)}}
  await until(()=>evidence.some(value=>value.result?.committed),'Host did not commit a result',30000);record.winner=evidence.find(value=>value.result?.committed).result.outcome.winningTeam;assert.ok(evidence.filter(value=>value.result?.committed).every(value=>value.result.outcome.winningTeam===record.winner));await until(async()=>{const visible=await Promise.all(pages.map(page=>page.locator('.network-result').allTextContents()));return visible.every(texts=>texts.some(text=>text.includes(record.winner?`Team ${record.winner} victorious`:'Operation failed')))},'A former participant did not recover the recorded result',30000);record.socketResultRecipients=evidence.filter(value=>value.result?.committed).length;record.visibleRecordedResults=count;record.commandsAccepted=evidence.map(value=>value.receipts.filter(receipt=>receipt.accepted).length);
  await first.screenshot({path:path.join(work,`result-${count}-${kind}.png`),fullPage:true});
  if(kind==='ai'){const debrief=evidence.find(value=>value.snapshot?.debrief)?.snapshot.debrief;record.aiSpent=debrief?.players.filter(player=>player.player>=3).map(player=>Number(player.spent));assert.equal(record.aiSpent?.length,2);assert.ok(record.aiSpent.every(value=>value>0))}
  if(count===2&&kind==='standard'){const panel=first.getByRole('dialog').last();await panel.getByRole('button',{name:'Save match replay',exact:true}).click();await noBusy(first);record.replayStored=true;await panel.getByRole('button',{name:'Create rematch lobby',exact:true}).click();await noBusy(first);await panel.getByRole('button',{name:'Command center',exact:true}).click();await first.getByRole('button',{name:'Multiplayer',exact:true}).click();await first.getByRole('button',{name:'Ready to deploy',exact:true}).waitFor();record.rematch=true;await first.setViewportSize({width:800,height:900});await first.screenshot({path:path.join(work,'network-compact.png'),fullPage:true});record.compactOverflow=await first.locator('.network-panel').evaluate(el=>el.scrollWidth>el.clientWidth+2);assert.equal(record.compactOverflow,false)}
  if(kind==='coop'){
   for(const page of pages){const debrief=page.getByRole('dialog').last().getByRole('button',{name:'Command center',exact:true});if(await debrief.count())await debrief.click();else await page.getByRole('button',{name:'Return to command center',exact:true}).click();await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await until(async()=>await page.getByRole('button',{name:'Close completed lobby',exact:true}).count()>0,'Completed co-op lobby not available');await page.getByRole('button',{name:'Close completed lobby',exact:true}).click();await noBusy(page)}
   await first.getByRole('button',{name:'Co-op',exact:true}).click();await first.getByRole('button',{name:'Refresh checkpoints',exact:true}).click();await noBusy(first);const save=await first.getByLabel('Shared checkpoint',{exact:true}).locator('option').nth(1).getAttribute('value');assert.ok(save);await first.getByLabel('Shared checkpoint',{exact:true}).selectOption(save);await first.getByRole('button',{name:'Resume co-op lobby',exact:true}).click();await noBusy(first);record.restoredCheckpoint=await first.locator('.network-lobby-heading').innerText();const priorSockets=evidence.map(value=>value.sockets);const id=await first.getByLabel('Current lobby ID').inputValue(),code=await first.getByLabel('Current access code').inputValue();await last.getByRole('button',{name:'Operations',exact:true}).click();await last.getByLabel('Join lobby ID').fill(id);await last.getByLabel('Join access code').fill(code);await last.getByRole('button',{name:'Join by ID',exact:true}).click();await noBusy(last);await new Promise(resolve=>setTimeout(resolve,2500));for(const page of pages){await page.getByRole('button',{name:'Ready to deploy',exact:true}).click();await noBusy(page)}await until(async()=>await first.getByRole('button',{name:'Start operation',exact:true}).isEnabled(),'Restored co-op did not reach readiness');await first.getByRole('button',{name:'Start operation',exact:true}).click();await Promise.all(pages.map(page=>page.getByRole('complementary',{name:'Command sidebar'}).waitFor()));await until(()=>evidence.every((value,index)=>value.sockets>priorSockets[index]&&value.snapshot?.mission?.id),'Restored co-op connections did not receive their saved mission');record.sharedCheckpointResumed=true;await first.locator('.scene-loading').waitFor({state:'hidden',timeout:60000});await first.screenshot({path:path.join(work,'coop-restored.png'),fullPage:true});
  }
  record.errors=errors;assert.deepEqual(errors,[]);record.status='passed';console.log(record.name+': passed');
 }catch(error){record.status='failed';record.error=String(error.stack??error);record.errors=errors;record.hostLog=server.log();record.frames=evidence.map(value=>({tick:value.snapshot?.tick,outcome:value.snapshot?.outcome,result:value.result,receipts:value.receipts}));for(const [index,page] of pages.entries()){await page.screenshot({path:path.join(work,`failure-${count}-${kind}-${index}.png`),fullPage:true}).catch(()=>{});await writeFile(path.join(work,`failure-${count}-${kind}-${index}.txt`),await page.locator('body').innerText().catch(()=>''))}console.error(record.name+': '+record.error);process.exitCode=1}
 finally{for(const context of contexts)await context.close();await server.close();report.cases.push(record);await writeFile(path.join(work,'results.json'),JSON.stringify(report,null,2))}
}
try{for(const value of selected)await scenario(/^\d$/.test(value)?Number(value):2,/^\d$/.test(value)?'standard':value)}finally{await browser.close();await writeFile(path.join(work,'results.json'),JSON.stringify(report,null,2));console.log('Network UI evidence: '+work)}
