import 'fake-indexeddb/auto';
import test from 'node:test';
import assert from 'node:assert/strict';
import {SaveSynchronizer} from '../../src/runtime/save-sync';
import {LocalStore} from '../../src/runtime/storage';
import {FakeLocalHost,fixtureSave,inspectFixture} from './account-fixture';
async function fixture(name:string,work:(env:{host:FakeLocalHost;files:LocalStore;sync:SaveSynchronizer;account:Awaited<ReturnType<FakeLocalHost['account']>>['account']})=>Promise<void>){const previous=globalThis.fetch,host=new FakeLocalHost();globalThis.fetch=host.fetch as typeof fetch;const files=new LocalStore(name,inspectFixture);const {account,vault}=await host.account(`${name}-auth`),sync=new SaveSynchronizer(account,files,inspectFixture);try{await work({host,files,sync,account})}finally{globalThis.fetch=previous;await files.close();await vault.close()}}
test('conflict preview displays both timestamps and mission progress, with unchanged large integer engine bytes',async()=>fixture('sync-preview',async({host,files,sync,account})=>{
 await files.putSave('manual','Local',fixtureSave(100));host.seed(account.context!.profileId,'manual',fixtureSave(300));const preview=await sync.preview();const entry=preview.entries[0];assert.equal(entry.comparison,'different');assert.equal(entry.local?.updatedMs!>1000000,true);assert.equal(entry.remote?.updatedMs,1000000);assert.equal(entry.kind==='save'&&entry.local?.mission?.objectives[0].complete,false);assert.equal(entry.kind==='save'&&entry.remote?.mission?.objectives[0].complete,true);assert.equal(host.writes,0);
 const result=await sync.execute(preview,[{key:entry.key,action:'upload'}]);assert.equal(result.status,'completed');assert.equal(result.receipts[0].revision,2);assert.deepEqual(host.saves.get(`${account.context!.profileId}:manual`)!.data,fixtureSave(100).data);assert.match(new TextDecoder().decode(host.saves.get(`${account.context!.profileId}:manual`)!.data),/18446744073709551615/);
}));
test('guest migration previews exact stable copy targets and unsupported local-only items before explicit choices',async()=>fixture('sync-migration',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave());await files.autosave(fixtureSave());await files.putSetting('preferences',{uiScale:100});await files.putProgress('campaign',{version:1,results:[],missions:{}});const preview=await sync.previewMigration({settingsId:'preferences'});assert.equal(preview.mode,'migration');assert.equal(preview.entries.length,3);assert.ok(preview.entries.filter(entry=>entry.kind==='save').every(entry=>entry.remoteId.startsWith('guest-')));assert.equal(preview.unsupported.find(value=>value.kind==='campaign-progress')?.items,1);assert.equal(host.writes,0);
 const target=preview.entries.find(entry=>entry.localId==='one')!;const copied=await sync.execute(preview,preview.entries.map(entry=>({key:entry.key,action:entry.localId==='one'||entry.kind==='settings'?'upload':'skip'})));assert.equal(copied.receipts.filter(value=>value.status==='copied').length,2);assert.ok(host.saves.has(`${account.context!.profileId}:${target.remoteId}`));assert.equal((await files.listSaves()).length,2);assert.deepEqual(host.preferences.get(account.context!.profileId)?.data,{uiScale:100});
}));
test('any local or remote revision change after preview blocks all writes before execution',async()=>fixture('sync-changed',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave());await files.putSave('two','Two',fixtureSave());let preview=await sync.preview();await files.putSave('two','Changed locally',fixtureSave(200),1);await assert.rejects(()=>sync.execute(preview,preview.entries.map(entry=>({key:entry.key,action:'upload'}))),{code:'sync_local_changed'});assert.equal(host.writes,0);
 preview=await sync.preview();host.seed(account.context!.profileId,'two',fixtureSave(300));await assert.rejects(()=>sync.execute(preview,preview.entries.map(entry=>({key:entry.key,action:'upload'}))),{code:'sync_remote_changed'});assert.equal(host.writes,0);
}));
test('copying remote data to a manual local target preserves exact bytes and requires human commander choices',async()=>fixture('sync-download',async({host,files,sync,account})=>{
 host.seed(account.context!.profileId,'host-slot',fixtureSave(500));const preview=await sync.preview({mappings:[{localId:'local-copy',remoteId:'host-slot'}]});const result=await sync.execute(preview,[{key:preview.entries[0].key,action:'download'}]);assert.equal(result.status,'completed');assert.deepEqual((await files.getSave('local-copy'))?.data,fixtureSave(500).data);assert.deepEqual((await files.getSave('local-copy'))?.local_players,[1]);assert.equal(host.writes,0);
 const multi=fixtureSave(),value=JSON.parse(new TextDecoder().decode(multi.data));value.state.players[1].controller='human';multi.data=new TextEncoder().encode(JSON.stringify(value));host.seed(account.context!.profileId,'multi',multi);const next=await sync.preview({mappings:[{localId:'multi-local',remoteId:'multi'}]});await assert.rejects(()=>sync.execute(next,[{key:next.entries[0].key,action:'download'}]),{code:'sync_commander_choice'});await sync.execute(next,[{key:next.entries[0].key,action:'download',localPlayers:[2]}]);assert.deepEqual((await files.getSave('multi-local'))?.local_players,[2]);
}));
test('cancellation after a completed copy stops remaining copies and never rolls back by deleting files',async()=>fixture('sync-cancel',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave());await files.putSave('two','Two',fixtureSave());const preview=await sync.preview(),abort=new AbortController();const report=await sync.execute(preview,preview.entries.map(entry=>({key:entry.key,action:'upload'})),{signal:abort.signal,onProgress(){abort.abort()}});assert.equal(report.status,'canceled');assert.deepEqual(report.receipts.map(item=>item.status),['copied','not-started']);assert.equal(host.saves.size,1);assert.equal((await files.listSaves()).length,2);await assert.rejects(()=>sync.execute(preview,[]),{code:'sync_preview_required'});assert.ok(account.context);
}));
test('an uncertain network write is reported honestly and never retried automatically',async()=>fixture('sync-uncertain',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave());const preview=await sync.preview();host.afterWrite=()=>{throw new TypeError('connection lost after commit')};const report=await sync.execute(preview,[{key:preview.entries[0].key,action:'upload'}]);assert.equal(report.status,'stopped');assert.equal(report.receipts[0].status,'uncertain');assert.equal(host.writes,1);assert.equal(host.saves.get(`${account.context!.profileId}:one`)?.revision,1);assert.equal((await files.listSaves()).length,1);
}));
test('preview tampering cannot redirect targets or authorize another account',async()=>fixture('sync-private',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave());const preview=await sync.preview();preview.entries[0].remoteId='tampered';await sync.execute(preview,[{key:preview.entries[0].key,action:'upload'}]);assert.ok(host.saves.has(`${account.context!.profileId}:one`));assert.equal(host.saves.has(`${account.context!.profileId}:tampered`),false);
 const stale=await sync.preview();await account.create('Another profile');await assert.rejects(()=>sync.execute(stale,[{key:stale.entries[0].key,action:'upload'}]),{code:'account_changed'});
}));
test('incompatible saves remain intact and can only be skipped or mapped to a separate destination',async()=>fixture('sync-incompatible',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave());const future=fixtureSave();future.data=new TextEncoder().encode(new TextDecoder().decode(future.data).replace('"version":1','"version":9'));host.seed(account.context!.profileId,'one',future);const preview=await sync.preview();assert.equal(preview.entries[0].comparison,'unavailable');await assert.rejects(()=>sync.execute(preview,[{key:preview.entries[0].key,action:'upload'}]),{code:'sync_incompatible'});assert.deepEqual(host.saves.get(`${account.context!.profileId}:one`)?.data,future.data);
 const copy=await sync.preview({mappings:[{localId:'one',remoteId:'compatible-copy'}]});await sync.execute(copy,[{key:copy.entries[0].key,action:'upload'}]);assert.deepEqual(host.saves.get(`${account.context!.profileId}:one`)?.data,future.data);assert.equal(host.saves.size,2);
}));
test('settings previews expose missing host timestamps and use both local and host revision checks',async()=>fixture('sync-settings',async({host,files,sync,account})=>{
 await files.putSetting('preferences',{uiScale:100});host.preferences.set(account.context!.profileId,{revision:2,data:{uiScale:120}});const preview=await sync.preview({mappings:[],settingsId:'preferences'});assert.equal(preview.entries[0].remote?.updatedMs,undefined);assert.equal(preview.entries[0].comparison,'different');const result=await sync.execute(preview,[{key:'settings',action:'download'}]);assert.equal(result.receipts[0].revision,2);assert.deepEqual((await files.setting('preferences'))?.data,{uiScale:120});
}));

test('a source edit during upload remains local and the receipt identifies that the reviewed snapshot was copied',async()=>fixture('sync-source-race',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave(100));const preview=await sync.preview();host.beforeWrite=async()=>{host.beforeWrite=undefined;await files.putSave('one','Newer local',fixtureSave(600),1)};
 const report=await sync.execute(preview,[{key:preview.entries[0].key,action:'upload'}]);assert.equal(report.receipts[0].status,'copied');assert.equal(report.receipts[0].sourceChanged,true);assert.deepEqual((await files.getSave('one'))?.data,fixtureSave(600).data);assert.deepEqual(host.saves.get(`${account.context!.profileId}:one`)?.data,fixtureSave(100).data);
}));
test('host CAS still protects a change that occurs after preflight, and pre-start cancellation writes nothing',async()=>fixture('sync-destination-race',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave(100));const preview=await sync.preview();host.beforeWrite=()=>{host.beforeWrite=undefined;host.seed(account.context!.profileId,'one',fixtureSave(700),'Concurrent host save')};
 const report=await sync.execute(preview,[{key:preview.entries[0].key,action:'upload'}]);assert.equal(report.receipts[0].status,'failed');assert.equal(report.receipts[0].error?.code,'save_conflict');assert.deepEqual(host.saves.get(`${account.context!.profileId}:one`)?.data,fixtureSave(700).data);assert.equal(host.writes,0);
 const next=await sync.preview(),abort=new AbortController();abort.abort();await assert.rejects(()=>sync.execute(next,[{key:next.entries[0].key,action:'upload'}],{signal:abort.signal}),{code:'sync_canceled'});assert.equal(host.writes,0);
}));

test('destination names are part of the reviewed copy mapping and obey actual host byte limits',async()=>fixture('sync-name',async({host,files,sync,account})=>{
 const longName='界'.repeat(50);await files.putSave('one',longName,fixtureSave());const first=await sync.preview();await assert.rejects(()=>sync.execute(first,[{key:first.entries[0].key,action:'upload'}]),{code:'sync_name'});assert.equal(host.writes,0);
 const next=await sync.preview({mappings:[{localId:'one',remoteId:'named-copy',uploadName:'Reviewed host title'}]});assert.equal(next.entries[0].kind==='save'&&next.entries[0].uploadName,'Reviewed host title');await sync.execute(next,[{key:next.entries[0].key,action:'upload'}]);assert.equal(host.saves.get(`${account.context!.profileId}:named-copy`)?.name,'Reviewed host title');assert.equal((await files.getSave('one'))?.name,longName);
}));

test('delete/recreate before preflight is detected even if the revision number repeats',async()=>fixture('sync-recreate',async({host,files,sync,account})=>{
 await files.putSave('one','One',fixtureSave(100));host.seed(account.context!.profileId,'one',fixtureSave(200));const preview=await sync.preview();host.seed(account.context!.profileId,'one',fixtureSave(900));await assert.rejects(()=>sync.execute(preview,[{key:preview.entries[0].key,action:'upload'}]),{code:'sync_remote_changed'});assert.equal(host.writes,0);
 const next=await sync.preview();await files.deleteSave('one',1);await files.putSave('one','Recreated local title',fixtureSave(100));await assert.rejects(()=>sync.execute(next,[{key:next.entries[0].key,action:'download'}]),{code:'sync_local_changed'});assert.equal((await files.getSave('one'))?.name,'Recreated local title');
}));
