// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: protocol/frontline.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A WebSocket binary frame contains exactly one Envelope. The server rejects
// text frames, unknown message kinds, oversized frames and incompatible hello.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Envelope_Hello
	//	*Envelope_Orders
	//	*Envelope_OrderResult
	//	*Envelope_Snapshot
	//	*Envelope_Delta
	//	*Envelope_Resume
	//	*Envelope_Result
	//	*Envelope_Error
	//	*Envelope_Ping
	Message       isEnvelope_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_protocol_frontline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessage() isEnvelope_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetOrders() *OrderBatch {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Orders); ok {
			return x.Orders
		}
	}
	return nil
}

func (x *Envelope) GetOrderResult() *OrderResult {
	if x != nil {
		if x, ok := x.Message.(*Envelope_OrderResult); ok {
			return x.OrderResult
		}
	}
	return nil
}

func (x *Envelope) GetSnapshot() *PlayerSnapshot {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Envelope) GetDelta() *StateDelta {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *Envelope) GetResume() *ResumeMatch {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

func (x *Envelope) GetResult() *MatchResult {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *Envelope) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Message.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isEnvelope_Message interface {
	isEnvelope_Message()
}

type Envelope_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type Envelope_Orders struct {
	Orders *OrderBatch `protobuf:"bytes,2,opt,name=orders,proto3,oneof"`
}

type Envelope_OrderResult struct {
	OrderResult *OrderResult `protobuf:"bytes,3,opt,name=order_result,json=orderResult,proto3,oneof"`
}

type Envelope_Snapshot struct {
	Snapshot *PlayerSnapshot `protobuf:"bytes,4,opt,name=snapshot,proto3,oneof"`
}

type Envelope_Delta struct {
	Delta *StateDelta `protobuf:"bytes,5,opt,name=delta,proto3,oneof"`
}

type Envelope_Resume struct {
	Resume *ResumeMatch `protobuf:"bytes,6,opt,name=resume,proto3,oneof"`
}

type Envelope_Result struct {
	Result *MatchResult `protobuf:"bytes,7,opt,name=result,proto3,oneof"`
}

type Envelope_Error struct {
	Error *ProtocolError `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,9,opt,name=ping,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Message() {}

func (*Envelope_Orders) isEnvelope_Message() {}

func (*Envelope_OrderResult) isEnvelope_Message() {}

func (*Envelope_Snapshot) isEnvelope_Message() {}

func (*Envelope_Delta) isEnvelope_Message() {}

func (*Envelope_Resume) isEnvelope_Message() {}

func (*Envelope_Result) isEnvelope_Message() {}

func (*Envelope_Error) isEnvelope_Message() {}

func (*Envelope_Ping) isEnvelope_Message() {}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Simulation    string                 `protobuf:"bytes,2,opt,name=simulation,proto3" json:"simulation,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	MatchId       string                 `protobuf:"bytes,5,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_protocol_frontline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *ClientHello) GetSimulation() string {
	if x != nil {
		return x.Simulation
	}
	return ""
}

func (x *ClientHello) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *ClientHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ClientHello) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

type ResumeMatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hello         *ClientHello           `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	LastTick      uint32                 `protobuf:"varint,2,opt,name=last_tick,json=lastTick,proto3" json:"last_tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeMatch) Reset() {
	*x = ResumeMatch{}
	mi := &file_protocol_frontline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeMatch) ProtoMessage() {}

func (x *ResumeMatch) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeMatch.ProtoReflect.Descriptor instead.
func (*ResumeMatch) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeMatch) GetHello() *ClientHello {
	if x != nil {
		return x.Hello
	}
	return nil
}

func (x *ResumeMatch) GetLastTick() uint32 {
	if x != nil {
		return x.LastTick
	}
	return 0
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint32                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_protocol_frontline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{3}
}

func (x *Ping) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Recoverable   bool                   `protobuf:"varint,3,opt,name=recoverable,proto3" json:"recoverable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_protocol_frontline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{4}
}

func (x *ProtocolError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProtocolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProtocolError) GetRecoverable() bool {
	if x != nil {
		return x.Recoverable
	}
	return false
}

type Vec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"zigzag32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"zigzag32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vec) Reset() {
	*x = Vec{}
	mi := &file_protocol_frontline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vec) ProtoMessage() {}

func (x *Vec) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vec.ProtoReflect.Descriptor instead.
func (*Vec) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{5}
}

func (x *Vec) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vec) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Entities      []uint32               `protobuf:"varint,2,rep,packed,name=entities,proto3" json:"entities,omitempty"`
	Target        uint32                 `protobuf:"varint,3,opt,name=target,proto3" json:"target,omitempty"`
	Position      *Vec                   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Queued        bool                   `protobuf:"varint,6,opt,name=queued,proto3" json:"queued,omitempty"`
	Index         int32                  `protobuf:"varint,7,opt,name=index,proto3" json:"index,omitempty"`
	Points        []*Vec                 `protobuf:"bytes,8,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_protocol_frontline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{6}
}

func (x *Order) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Order) GetEntities() []uint32 {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Order) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Order) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Order) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Order) GetQueued() bool {
	if x != nil {
		return x.Queued
	}
	return false
}

func (x *Order) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Order) GetPoints() []*Vec {
	if x != nil {
		return x.Points
	}
	return nil
}

type OrderBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      uint32                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBatch) Reset() {
	*x = OrderBatch{}
	mi := &file_protocol_frontline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBatch) ProtoMessage() {}

func (x *OrderBatch) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBatch.ProtoReflect.Descriptor instead.
func (*OrderBatch) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{7}
}

func (x *OrderBatch) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OrderBatch) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type OrderResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        uint32                 `protobuf:"varint,1,opt,name=player,proto3" json:"player,omitempty"`
	Sequence      uint32                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Accepted      bool                   `protobuf:"varint,4,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Code          string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	Tick          uint32                 `protobuf:"varint,6,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResult) Reset() {
	*x = OrderResult{}
	mi := &file_protocol_frontline_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResult) ProtoMessage() {}

func (x *OrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResult.ProtoReflect.Descriptor instead.
func (*OrderResult) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{8}
}

func (x *OrderResult) GetPlayer() uint32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *OrderResult) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *OrderResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *OrderResult) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *OrderResult) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *OrderResult) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Simulation    string                 `protobuf:"bytes,1,opt,name=simulation,proto3" json:"simulation,omitempty"`
	Protocol      uint32                 `protobuf:"varint,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	MapVersion    string                 `protobuf:"bytes,4,opt,name=map_version,json=mapVersion,proto3" json:"map_version,omitempty"`
	Ruleset       string                 `protobuf:"bytes,5,opt,name=ruleset,proto3" json:"ruleset,omitempty"`
	Seed          uint64                 `protobuf:"varint,6,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protocol_frontline_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{9}
}

func (x *Metadata) GetSimulation() string {
	if x != nil {
		return x.Simulation
	}
	return ""
}

func (x *Metadata) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Metadata) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *Metadata) GetMapVersion() string {
	if x != nil {
		return x.MapVersion
	}
	return ""
}

func (x *Metadata) GetRuleset() string {
	if x != nil {
		return x.Ruleset
	}
	return ""
}

func (x *Metadata) GetSeed() uint64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type Cooldown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Until         uint32                 `protobuf:"varint,2,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cooldown) Reset() {
	*x = Cooldown{}
	mi := &file_protocol_frontline_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cooldown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cooldown) ProtoMessage() {}

func (x *Cooldown) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cooldown.ProtoReflect.Descriptor instead.
func (*Cooldown) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{10}
}

func (x *Cooldown) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Cooldown) GetUntil() uint32 {
	if x != nil {
		return x.Until
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Research      bool                   `protobuf:"varint,2,opt,name=research,proto3" json:"research,omitempty"`
	Paid          int64                  `protobuf:"varint,3,opt,name=paid,proto3" json:"paid,omitempty"`
	Work          uint32                 `protobuf:"varint,4,opt,name=work,proto3" json:"work,omitempty"`
	Required      uint32                 `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	Supply        int32                  `protobuf:"varint,6,opt,name=supply,proto3" json:"supply,omitempty"`
	Service       uint32                 `protobuf:"varint,7,opt,name=service,proto3" json:"service,omitempty"`
	Started       bool                   `protobuf:"varint,8,opt,name=started,proto3" json:"started,omitempty"`
	Emergency     bool                   `protobuf:"varint,9,opt,name=emergency,proto3" json:"emergency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_protocol_frontline_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{11}
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetResearch() bool {
	if x != nil {
		return x.Research
	}
	return false
}

func (x *Job) GetPaid() int64 {
	if x != nil {
		return x.Paid
	}
	return 0
}

func (x *Job) GetWork() uint32 {
	if x != nil {
		return x.Work
	}
	return 0
}

func (x *Job) GetRequired() uint32 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *Job) GetSupply() int32 {
	if x != nil {
		return x.Supply
	}
	return 0
}

func (x *Job) GetService() uint32 {
	if x != nil {
		return x.Service
	}
	return 0
}

func (x *Job) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *Job) GetEmergency() bool {
	if x != nil {
		return x.Emergency
	}
	return false
}

type Economy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Credits        int64                  `protobuf:"varint,1,opt,name=credits,proto3" json:"credits,omitempty"`
	Energy         int64                  `protobuf:"varint,2,opt,name=energy,proto3" json:"energy,omitempty"`
	Supply         int32                  `protobuf:"varint,3,opt,name=supply,proto3" json:"supply,omitempty"`
	ReservedSupply int32                  `protobuf:"varint,4,opt,name=reserved_supply,json=reservedSupply,proto3" json:"reserved_supply,omitempty"`
	PowerCapacity  int32                  `protobuf:"varint,5,opt,name=power_capacity,json=powerCapacity,proto3" json:"power_capacity,omitempty"`
	PowerDemand    int32                  `protobuf:"varint,6,opt,name=power_demand,json=powerDemand,proto3" json:"power_demand,omitempty"`
	Tier           int32                  `protobuf:"varint,7,opt,name=tier,proto3" json:"tier,omitempty"`
	Income         int64                  `protobuf:"varint,8,opt,name=income,proto3" json:"income,omitempty"`
	RepairReserve  int64                  `protobuf:"varint,9,opt,name=repair_reserve,json=repairReserve,proto3" json:"repair_reserve,omitempty"`
	Upgrades       []string               `protobuf:"bytes,10,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
	Cooldowns      []*Cooldown            `protobuf:"bytes,11,rep,name=cooldowns,proto3" json:"cooldowns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Economy) Reset() {
	*x = Economy{}
	mi := &file_protocol_frontline_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Economy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Economy) ProtoMessage() {}

func (x *Economy) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Economy.ProtoReflect.Descriptor instead.
func (*Economy) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{12}
}

func (x *Economy) GetCredits() int64 {
	if x != nil {
		return x.Credits
	}
	return 0
}

func (x *Economy) GetEnergy() int64 {
	if x != nil {
		return x.Energy
	}
	return 0
}

func (x *Economy) GetSupply() int32 {
	if x != nil {
		return x.Supply
	}
	return 0
}

func (x *Economy) GetReservedSupply() int32 {
	if x != nil {
		return x.ReservedSupply
	}
	return 0
}

func (x *Economy) GetPowerCapacity() int32 {
	if x != nil {
		return x.PowerCapacity
	}
	return 0
}

func (x *Economy) GetPowerDemand() int32 {
	if x != nil {
		return x.PowerDemand
	}
	return 0
}

func (x *Economy) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *Economy) GetIncome() int64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *Economy) GetRepairReserve() int64 {
	if x != nil {
		return x.RepairReserve
	}
	return 0
}

func (x *Economy) GetUpgrades() []string {
	if x != nil {
		return x.Upgrades
	}
	return nil
}

func (x *Economy) GetCooldowns() []*Cooldown {
	if x != nil {
		return x.Cooldowns
	}
	return nil
}

type EntityPrivate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hp            int64                  `protobuf:"varint,1,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxHp         int64                  `protobuf:"varint,2,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Jobs          []*Job                 `protobuf:"bytes,3,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Orders        []*Order               `protobuf:"bytes,4,rep,name=orders,proto3" json:"orders,omitempty"`
	Rally         *Vec                   `protobuf:"bytes,5,opt,name=rally,proto3" json:"rally,omitempty"`
	Cargo         int64                  `protobuf:"varint,6,opt,name=cargo,proto3" json:"cargo,omitempty"`
	Home          uint32                 `protobuf:"varint,7,opt,name=home,proto3" json:"home,omitempty"`
	Ammo          int32                  `protobuf:"varint,8,opt,name=ammo,proto3" json:"ammo,omitempty"`
	Endurance     uint32                 `protobuf:"varint,9,opt,name=endurance,proto3" json:"endurance,omitempty"`
	Charges       int32                  `protobuf:"varint,10,opt,name=charges,proto3" json:"charges,omitempty"`
	ChargeWork    uint32                 `protobuf:"varint,11,opt,name=charge_work,json=chargeWork,proto3" json:"charge_work,omitempty"`
	ServiceWork   uint32                 `protobuf:"varint,12,opt,name=service_work,json=serviceWork,proto3" json:"service_work,omitempty"`
	Experience    int64                  `protobuf:"varint,13,opt,name=experience,proto3" json:"experience,omitempty"`
	Cooldowns     []*Cooldown            `protobuf:"bytes,14,rep,name=cooldowns,proto3" json:"cooldowns,omitempty"`
	Passengers    []uint32               `protobuf:"varint,15,rep,packed,name=passengers,proto3" json:"passengers,omitempty"`
	Container     uint32                 `protobuf:"varint,16,opt,name=container,proto3" json:"container,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityPrivate) Reset() {
	*x = EntityPrivate{}
	mi := &file_protocol_frontline_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityPrivate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityPrivate) ProtoMessage() {}

func (x *EntityPrivate) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityPrivate.ProtoReflect.Descriptor instead.
func (*EntityPrivate) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{13}
}

func (x *EntityPrivate) GetHp() int64 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *EntityPrivate) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *EntityPrivate) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *EntityPrivate) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *EntityPrivate) GetRally() *Vec {
	if x != nil {
		return x.Rally
	}
	return nil
}

func (x *EntityPrivate) GetCargo() int64 {
	if x != nil {
		return x.Cargo
	}
	return 0
}

func (x *EntityPrivate) GetHome() uint32 {
	if x != nil {
		return x.Home
	}
	return 0
}

func (x *EntityPrivate) GetAmmo() int32 {
	if x != nil {
		return x.Ammo
	}
	return 0
}

func (x *EntityPrivate) GetEndurance() uint32 {
	if x != nil {
		return x.Endurance
	}
	return 0
}

func (x *EntityPrivate) GetCharges() int32 {
	if x != nil {
		return x.Charges
	}
	return 0
}

func (x *EntityPrivate) GetChargeWork() uint32 {
	if x != nil {
		return x.ChargeWork
	}
	return 0
}

func (x *EntityPrivate) GetServiceWork() uint32 {
	if x != nil {
		return x.ServiceWork
	}
	return 0
}

func (x *EntityPrivate) GetExperience() int64 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *EntityPrivate) GetCooldowns() []*Cooldown {
	if x != nil {
		return x.Cooldowns
	}
	return nil
}

func (x *EntityPrivate) GetPassengers() []uint32 {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *EntityPrivate) GetContainer() uint32 {
	if x != nil {
		return x.Container
	}
	return 0
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Owner         uint32                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Position      *Vec                   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Facing        int32                  `protobuf:"varint,5,opt,name=facing,proto3" json:"facing,omitempty"`
	Health        int32                  `protobuf:"varint,6,opt,name=health,proto3" json:"health,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Complete      bool                   `protobuf:"varint,8,opt,name=complete,proto3" json:"complete,omitempty"`
	Enabled       bool                   `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Landed        bool                   `protobuf:"varint,10,opt,name=landed,proto3" json:"landed,omitempty"`
	Deployed      bool                   `protobuf:"varint,11,opt,name=deployed,proto3" json:"deployed,omitempty"`
	Concealed     bool                   `protobuf:"varint,12,opt,name=concealed,proto3" json:"concealed,omitempty"`
	Progress      int32                  `protobuf:"varint,13,opt,name=progress,proto3" json:"progress,omitempty"`
	Rank          uint32                 `protobuf:"varint,14,opt,name=rank,proto3" json:"rank,omitempty"`
	Private       *EntityPrivate         `protobuf:"bytes,15,opt,name=private,proto3" json:"private,omitempty"`
	TurretFacing  int32                  `protobuf:"varint,16,opt,name=turret_facing,json=turretFacing,proto3" json:"turret_facing,omitempty"`
	ChannelUntil  uint32                 `protobuf:"varint,17,opt,name=channel_until,json=channelUntil,proto3" json:"channel_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_protocol_frontline_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{14}
}

func (x *Entity) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Entity) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Entity) GetFacing() int32 {
	if x != nil {
		return x.Facing
	}
	return 0
}

func (x *Entity) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Entity) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Entity) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *Entity) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Entity) GetLanded() bool {
	if x != nil {
		return x.Landed
	}
	return false
}

func (x *Entity) GetDeployed() bool {
	if x != nil {
		return x.Deployed
	}
	return false
}

func (x *Entity) GetConcealed() bool {
	if x != nil {
		return x.Concealed
	}
	return false
}

func (x *Entity) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Entity) GetRank() uint32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Entity) GetPrivate() *EntityPrivate {
	if x != nil {
		return x.Private
	}
	return nil
}

func (x *Entity) GetTurretFacing() int32 {
	if x != nil {
		return x.TurretFacing
	}
	return 0
}

func (x *Entity) GetChannelUntil() uint32 {
	if x != nil {
		return x.ChannelUntil
	}
	return 0
}

type PlayerSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Faction           string                 `protobuf:"bytes,3,opt,name=faction,proto3" json:"faction,omitempty"`
	Team              uint32                 `protobuf:"varint,4,opt,name=team,proto3" json:"team,omitempty"`
	Defeated          bool                   `protobuf:"varint,5,opt,name=defeated,proto3" json:"defeated,omitempty"`
	DefeatAt          uint32                 `protobuf:"varint,6,opt,name=defeat_at,json=defeatAt,proto3" json:"defeat_at,omitempty"`
	StrategicProgress int32                  `protobuf:"varint,7,opt,name=strategic_progress,json=strategicProgress,proto3" json:"strategic_progress,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlayerSummary) Reset() {
	*x = PlayerSummary{}
	mi := &file_protocol_frontline_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSummary) ProtoMessage() {}

func (x *PlayerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSummary.ProtoReflect.Descriptor instead.
func (*PlayerSummary) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{15}
}

func (x *PlayerSummary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlayerSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerSummary) GetFaction() string {
	if x != nil {
		return x.Faction
	}
	return ""
}

func (x *PlayerSummary) GetTeam() uint32 {
	if x != nil {
		return x.Team
	}
	return 0
}

func (x *PlayerSummary) GetDefeated() bool {
	if x != nil {
		return x.Defeated
	}
	return false
}

func (x *PlayerSummary) GetDefeatAt() uint32 {
	if x != nil {
		return x.DefeatAt
	}
	return 0
}

func (x *PlayerSummary) GetStrategicProgress() int32 {
	if x != nil {
		return x.StrategicProgress
	}
	return 0
}

type Projectile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         uint32                 `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Weapon        string                 `protobuf:"bytes,3,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Position      *Vec                   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Impact        *Vec                   `protobuf:"bytes,5,opt,name=impact,proto3" json:"impact,omitempty"`
	ImpactAt      uint32                 `protobuf:"varint,6,opt,name=impact_at,json=impactAt,proto3" json:"impact_at,omitempty"`
	Interceptable bool                   `protobuf:"varint,7,opt,name=interceptable,proto3" json:"interceptable,omitempty"`
	Warning       bool                   `protobuf:"varint,8,opt,name=warning,proto3" json:"warning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Projectile) Reset() {
	*x = Projectile{}
	mi := &file_protocol_frontline_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Projectile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Projectile) ProtoMessage() {}

func (x *Projectile) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Projectile.ProtoReflect.Descriptor instead.
func (*Projectile) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{16}
}

func (x *Projectile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Projectile) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Projectile) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

func (x *Projectile) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Projectile) GetImpact() *Vec {
	if x != nil {
		return x.Impact
	}
	return nil
}

func (x *Projectile) GetImpactAt() uint32 {
	if x != nil {
		return x.ImpactAt
	}
	return 0
}

func (x *Projectile) GetInterceptable() bool {
	if x != nil {
		return x.Interceptable
	}
	return false
}

func (x *Projectile) GetWarning() bool {
	if x != nil {
		return x.Warning
	}
	return false
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vec                   `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Remaining     int64                  `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_protocol_frontline_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{17}
}

func (x *Field) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Field) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Field) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type Station struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Position      *Vec                   `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Owner         uint32                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Station) Reset() {
	*x = Station{}
	mi := &file_protocol_frontline_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Station) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Station) ProtoMessage() {}

func (x *Station) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Station.ProtoReflect.Descriptor instead.
func (*Station) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{18}
}

func (x *Station) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Station) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Station) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

type Memory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Owner         uint32                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Position      *Vec                   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Seen          uint32                 `protobuf:"varint,5,opt,name=seen,proto3" json:"seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Memory) Reset() {
	*x = Memory{}
	mi := &file_protocol_frontline_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Memory) ProtoMessage() {}

func (x *Memory) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Memory.ProtoReflect.Descriptor instead.
func (*Memory) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{19}
}

func (x *Memory) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Memory) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Memory) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Memory) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Memory) GetSeen() uint32 {
	if x != nil {
		return x.Seen
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Owner         uint32                 `protobuf:"varint,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Entity        uint32                 `protobuf:"varint,5,opt,name=entity,proto3" json:"entity,omitempty"`
	Position      *Vec                   `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	Value         int64                  `protobuf:"varint,7,opt,name=value,proto3" json:"value,omitempty"`
	Scope         string                 `protobuf:"bytes,8,opt,name=scope,proto3" json:"scope,omitempty"`
	Text          string                 `protobuf:"bytes,9,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_protocol_frontline_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{20}
}

func (x *Event) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Event) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *Event) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Event) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Event) GetEntity() uint32 {
	if x != nil {
		return x.Entity
	}
	return 0
}

func (x *Event) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Event) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Event) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Outcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finished      bool                   `protobuf:"varint,1,opt,name=finished,proto3" json:"finished,omitempty"`
	Draw          bool                   `protobuf:"varint,2,opt,name=draw,proto3" json:"draw,omitempty"`
	WinningTeam   uint32                 `protobuf:"varint,3,opt,name=winning_team,json=winningTeam,proto3" json:"winning_team,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Tick          uint32                 `protobuf:"varint,5,opt,name=tick,proto3" json:"tick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Outcome) Reset() {
	*x = Outcome{}
	mi := &file_protocol_frontline_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Outcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Outcome) ProtoMessage() {}

func (x *Outcome) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Outcome.ProtoReflect.Descriptor instead.
func (*Outcome) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{21}
}

func (x *Outcome) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *Outcome) GetDraw() bool {
	if x != nil {
		return x.Draw
	}
	return false
}

func (x *Outcome) GetWinningTeam() uint32 {
	if x != nil {
		return x.WinningTeam
	}
	return 0
}

func (x *Outcome) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Outcome) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

type PlayerSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *Metadata              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Tick          uint32                 `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Countdown     uint32                 `protobuf:"varint,3,opt,name=countdown,proto3" json:"countdown,omitempty"`
	Player        uint32                 `protobuf:"varint,4,opt,name=player,proto3" json:"player,omitempty"`
	Economy       *Economy               `protobuf:"bytes,5,opt,name=economy,proto3" json:"economy,omitempty"`
	Players       []*PlayerSummary       `protobuf:"bytes,6,rep,name=players,proto3" json:"players,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,7,rep,name=entities,proto3" json:"entities,omitempty"`
	Projectiles   []*Projectile          `protobuf:"bytes,8,rep,name=projectiles,proto3" json:"projectiles,omitempty"`
	Fields        []*Field               `protobuf:"bytes,9,rep,name=fields,proto3" json:"fields,omitempty"`
	Stations      []*Station             `protobuf:"bytes,10,rep,name=stations,proto3" json:"stations,omitempty"`
	Explored      []bool                 `protobuf:"varint,11,rep,packed,name=explored,proto3" json:"explored,omitempty"`
	Visible       []bool                 `protobuf:"varint,12,rep,packed,name=visible,proto3" json:"visible,omitempty"`
	Memory        []*Memory              `protobuf:"bytes,13,rep,name=memory,proto3" json:"memory,omitempty"`
	Events        []*Event               `protobuf:"bytes,14,rep,name=events,proto3" json:"events,omitempty"`
	Results       []*OrderResult         `protobuf:"bytes,15,rep,name=results,proto3" json:"results,omitempty"`
	ShipmentAt    uint32                 `protobuf:"varint,16,opt,name=shipment_at,json=shipmentAt,proto3" json:"shipment_at,omitempty"`
	Outcome       *Outcome               `protobuf:"bytes,17,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Salvage       []*Salvage             `protobuf:"bytes,18,rep,name=salvage,proto3" json:"salvage,omitempty"`
	Zones         []*Zone                `protobuf:"bytes,19,rep,name=zones,proto3" json:"zones,omitempty"`
	Indicators    []*StructureIndicator  `protobuf:"bytes,20,rep,name=indicators,proto3" json:"indicators,omitempty"`
	Mission       *MissionProgress       `protobuf:"bytes,21,opt,name=mission,proto3" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerSnapshot) Reset() {
	*x = PlayerSnapshot{}
	mi := &file_protocol_frontline_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerSnapshot) ProtoMessage() {}

func (x *PlayerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerSnapshot) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{22}
}

func (x *PlayerSnapshot) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PlayerSnapshot) GetTick() uint32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *PlayerSnapshot) GetCountdown() uint32 {
	if x != nil {
		return x.Countdown
	}
	return 0
}

func (x *PlayerSnapshot) GetPlayer() uint32 {
	if x != nil {
		return x.Player
	}
	return 0
}

func (x *PlayerSnapshot) GetEconomy() *Economy {
	if x != nil {
		return x.Economy
	}
	return nil
}

func (x *PlayerSnapshot) GetPlayers() []*PlayerSummary {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *PlayerSnapshot) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *PlayerSnapshot) GetProjectiles() []*Projectile {
	if x != nil {
		return x.Projectiles
	}
	return nil
}

func (x *PlayerSnapshot) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *PlayerSnapshot) GetStations() []*Station {
	if x != nil {
		return x.Stations
	}
	return nil
}

func (x *PlayerSnapshot) GetExplored() []bool {
	if x != nil {
		return x.Explored
	}
	return nil
}

func (x *PlayerSnapshot) GetVisible() []bool {
	if x != nil {
		return x.Visible
	}
	return nil
}

func (x *PlayerSnapshot) GetMemory() []*Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *PlayerSnapshot) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *PlayerSnapshot) GetResults() []*OrderResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PlayerSnapshot) GetShipmentAt() uint32 {
	if x != nil {
		return x.ShipmentAt
	}
	return 0
}

func (x *PlayerSnapshot) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *PlayerSnapshot) GetSalvage() []*Salvage {
	if x != nil {
		return x.Salvage
	}
	return nil
}

func (x *PlayerSnapshot) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

func (x *PlayerSnapshot) GetIndicators() []*StructureIndicator {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *PlayerSnapshot) GetMission() *MissionProgress {
	if x != nil {
		return x.Mission
	}
	return nil
}

// state contains current permitted non-entity fields and only changed entities;
// removed_entities includes deaths and lost vision without revealing which.
type StateDelta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaselineTick    uint32                 `protobuf:"varint,1,opt,name=baseline_tick,json=baselineTick,proto3" json:"baseline_tick,omitempty"`
	State           *PlayerSnapshot        `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	RemovedEntities []uint32               `protobuf:"varint,3,rep,packed,name=removed_entities,json=removedEntities,proto3" json:"removed_entities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StateDelta) Reset() {
	*x = StateDelta{}
	mi := &file_protocol_frontline_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateDelta) ProtoMessage() {}

func (x *StateDelta) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateDelta.ProtoReflect.Descriptor instead.
func (*StateDelta) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{23}
}

func (x *StateDelta) GetBaselineTick() uint32 {
	if x != nil {
		return x.BaselineTick
	}
	return 0
}

func (x *StateDelta) GetState() *PlayerSnapshot {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *StateDelta) GetRemovedEntities() []uint32 {
	if x != nil {
		return x.RemovedEntities
	}
	return nil
}

type MatchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Outcome       *Outcome               `protobuf:"bytes,2,opt,name=outcome,proto3" json:"outcome,omitempty"`
	Committed     bool                   `protobuf:"varint,3,opt,name=committed,proto3" json:"committed,omitempty"`
	Void          bool                   `protobuf:"varint,4,opt,name=void,proto3" json:"void,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_protocol_frontline_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{24}
}

func (x *MatchResult) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *MatchResult) GetOutcome() *Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *MatchResult) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *MatchResult) GetVoid() bool {
	if x != nil {
		return x.Void
	}
	return false
}

type Salvage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         uint32                 `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Position      *Vec                   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Value         int64                  `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Until         uint32                 `protobuf:"varint,5,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Salvage) Reset() {
	*x = Salvage{}
	mi := &file_protocol_frontline_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Salvage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salvage) ProtoMessage() {}

func (x *Salvage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salvage.ProtoReflect.Descriptor instead.
func (*Salvage) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{25}
}

func (x *Salvage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Salvage) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Salvage) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Salvage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Salvage) GetUntil() uint32 {
	if x != nil {
		return x.Until
	}
	return 0
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Owner         uint32                 `protobuf:"varint,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Position      *Vec                   `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Radius        int32                  `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	Start         uint32                 `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Until         uint32                 `protobuf:"varint,6,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_protocol_frontline_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{26}
}

func (x *Zone) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Zone) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *Zone) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Zone) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *Zone) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Zone) GetUntil() uint32 {
	if x != nil {
		return x.Until
	}
	return 0
}

type StructureIndicator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         uint32                 `protobuf:"varint,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Position      *Vec                   `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructureIndicator) Reset() {
	*x = StructureIndicator{}
	mi := &file_protocol_frontline_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructureIndicator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructureIndicator) ProtoMessage() {}

func (x *StructureIndicator) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructureIndicator.ProtoReflect.Descriptor instead.
func (*StructureIndicator) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{27}
}

func (x *StructureIndicator) GetOwner() uint32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *StructureIndicator) GetPosition() *Vec {
	if x != nil {
		return x.Position
	}
	return nil
}

type ObjectiveProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Optional      bool                   `protobuf:"varint,3,opt,name=optional,proto3" json:"optional,omitempty"`
	Failure       bool                   `protobuf:"varint,4,opt,name=failure,proto3" json:"failure,omitempty"`
	Complete      bool                   `protobuf:"varint,5,opt,name=complete,proto3" json:"complete,omitempty"`
	Progress      uint32                 `protobuf:"varint,6,opt,name=progress,proto3" json:"progress,omitempty"`
	Required      uint32                 `protobuf:"varint,7,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectiveProgress) Reset() {
	*x = ObjectiveProgress{}
	mi := &file_protocol_frontline_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectiveProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectiveProgress) ProtoMessage() {}

func (x *ObjectiveProgress) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectiveProgress.ProtoReflect.Descriptor instead.
func (*ObjectiveProgress) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{28}
}

func (x *ObjectiveProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectiveProgress) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ObjectiveProgress) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *ObjectiveProgress) GetFailure() bool {
	if x != nil {
		return x.Failure
	}
	return false
}

func (x *ObjectiveProgress) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *ObjectiveProgress) GetProgress() uint32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *ObjectiveProgress) GetRequired() uint32 {
	if x != nil {
		return x.Required
	}
	return 0
}

type MissionProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Difficulty     string                 `protobuf:"bytes,3,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Checkpoint     string                 `protobuf:"bytes,4,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	CheckpointTick uint32                 `protobuf:"varint,5,opt,name=checkpoint_tick,json=checkpointTick,proto3" json:"checkpoint_tick,omitempty"`
	Objectives     []*ObjectiveProgress   `protobuf:"bytes,6,rep,name=objectives,proto3" json:"objectives,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MissionProgress) Reset() {
	*x = MissionProgress{}
	mi := &file_protocol_frontline_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MissionProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionProgress) ProtoMessage() {}

func (x *MissionProgress) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_frontline_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MissionProgress.ProtoReflect.Descriptor instead.
func (*MissionProgress) Descriptor() ([]byte, []int) {
	return file_protocol_frontline_proto_rawDescGZIP(), []int{29}
}

func (x *MissionProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MissionProgress) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MissionProgress) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *MissionProgress) GetCheckpoint() string {
	if x != nil {
		return x.Checkpoint
	}
	return ""
}

func (x *MissionProgress) GetCheckpointTick() uint32 {
	if x != nil {
		return x.CheckpointTick
	}
	return 0
}

func (x *MissionProgress) GetObjectives() []*ObjectiveProgress {
	if x != nil {
		return x.Objectives
	}
	return nil
}

var File_protocol_frontline_proto protoreflect.FileDescriptor

const file_protocol_frontline_proto_rawDesc = "" +
	"\n" +
	"\x18protocol/frontline.proto\x12\ffrontline.v1\"\xf3\x03\n" +
	"\bEnvelope\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.frontline.v1.ClientHelloH\x00R\x05hello\x122\n" +
	"\x06orders\x18\x02 \x01(\v2\x18.frontline.v1.OrderBatchH\x00R\x06orders\x12>\n" +
	"\forder_result\x18\x03 \x01(\v2\x19.frontline.v1.OrderResultH\x00R\vorderResult\x12:\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x1c.frontline.v1.PlayerSnapshotH\x00R\bsnapshot\x120\n" +
	"\x05delta\x18\x05 \x01(\v2\x18.frontline.v1.StateDeltaH\x00R\x05delta\x123\n" +
	"\x06resume\x18\x06 \x01(\v2\x19.frontline.v1.ResumeMatchH\x00R\x06resume\x123\n" +
	"\x06result\x18\a \x01(\v2\x19.frontline.v1.MatchResultH\x00R\x06result\x123\n" +
	"\x05error\x18\b \x01(\v2\x1b.frontline.v1.ProtocolErrorH\x00R\x05error\x12(\n" +
	"\x04ping\x18\t \x01(\v2\x12.frontline.v1.PingH\x00R\x04pingB\t\n" +
	"\amessage\"\x9d\x01\n" +
	"\vClientHello\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1e\n" +
	"\n" +
	"simulation\x18\x02 \x01(\tR\n" +
	"simulation\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x19\n" +
	"\bmatch_id\x18\x05 \x01(\tR\amatchId\"[\n" +
	"\vResumeMatch\x12/\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.frontline.v1.ClientHelloR\x05hello\x12\x1b\n" +
	"\tlast_tick\x18\x02 \x01(\rR\blastTick\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\rR\x05nonce\"_\n" +
	"\rProtocolError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\vrecoverable\x18\x03 \x01(\bR\vrecoverable\"!\n" +
	"\x03Vec\x12\f\n" +
	"\x01x\x18\x01 \x01(\x11R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x11R\x01y\"\xeb\x01\n" +
	"\x05Order\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1a\n" +
	"\bentities\x18\x02 \x03(\rR\bentities\x12\x16\n" +
	"\x06target\x18\x03 \x01(\rR\x06target\x12-\n" +
	"\bposition\x18\x04 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06queued\x18\x06 \x01(\bR\x06queued\x12\x14\n" +
	"\x05index\x18\a \x01(\x05R\x05index\x12)\n" +
	"\x06points\x18\b \x03(\v2\x11.frontline.v1.VecR\x06points\"U\n" +
	"\n" +
	"OrderBatch\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\rR\bsequence\x12+\n" +
	"\x06orders\x18\x02 \x03(\v2\x13.frontline.v1.OrderR\x06orders\"\x9b\x01\n" +
	"\vOrderResult\x12\x16\n" +
	"\x06player\x18\x01 \x01(\rR\x06player\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\rR\bsequence\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\x12\x1a\n" +
	"\baccepted\x18\x04 \x01(\bR\baccepted\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12\x12\n" +
	"\x04tick\x18\x06 \x01(\rR\x04tick\"\xb8\x01\n" +
	"\bMetadata\x12\x1e\n" +
	"\n" +
	"simulation\x18\x01 \x01(\tR\n" +
	"simulation\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\rR\bprotocol\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12\x1f\n" +
	"\vmap_version\x18\x04 \x01(\tR\n" +
	"mapVersion\x12\x18\n" +
	"\aruleset\x18\x05 \x01(\tR\aruleset\x12\x12\n" +
	"\x04seed\x18\x06 \x01(\x04R\x04seed\"0\n" +
	"\bCooldown\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05until\x18\x02 \x01(\rR\x05until\"\xe3\x01\n" +
	"\x03Job\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bresearch\x18\x02 \x01(\bR\bresearch\x12\x12\n" +
	"\x04paid\x18\x03 \x01(\x03R\x04paid\x12\x12\n" +
	"\x04work\x18\x04 \x01(\rR\x04work\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\rR\brequired\x12\x16\n" +
	"\x06supply\x18\x06 \x01(\x05R\x06supply\x12\x18\n" +
	"\aservice\x18\a \x01(\rR\aservice\x12\x18\n" +
	"\astarted\x18\b \x01(\bR\astarted\x12\x1c\n" +
	"\temergency\x18\t \x01(\bR\temergency\"\xeb\x02\n" +
	"\aEconomy\x12\x18\n" +
	"\acredits\x18\x01 \x01(\x03R\acredits\x12\x16\n" +
	"\x06energy\x18\x02 \x01(\x03R\x06energy\x12\x16\n" +
	"\x06supply\x18\x03 \x01(\x05R\x06supply\x12'\n" +
	"\x0freserved_supply\x18\x04 \x01(\x05R\x0ereservedSupply\x12%\n" +
	"\x0epower_capacity\x18\x05 \x01(\x05R\rpowerCapacity\x12!\n" +
	"\fpower_demand\x18\x06 \x01(\x05R\vpowerDemand\x12\x12\n" +
	"\x04tier\x18\a \x01(\x05R\x04tier\x12\x16\n" +
	"\x06income\x18\b \x01(\x03R\x06income\x12%\n" +
	"\x0erepair_reserve\x18\t \x01(\x03R\rrepairReserve\x12\x1a\n" +
	"\bupgrades\x18\n" +
	" \x03(\tR\bupgrades\x124\n" +
	"\tcooldowns\x18\v \x03(\v2\x16.frontline.v1.CooldownR\tcooldowns\"\x81\x04\n" +
	"\rEntityPrivate\x12\x0e\n" +
	"\x02hp\x18\x01 \x01(\x03R\x02hp\x12\x15\n" +
	"\x06max_hp\x18\x02 \x01(\x03R\x05maxHp\x12%\n" +
	"\x04jobs\x18\x03 \x03(\v2\x11.frontline.v1.JobR\x04jobs\x12+\n" +
	"\x06orders\x18\x04 \x03(\v2\x13.frontline.v1.OrderR\x06orders\x12'\n" +
	"\x05rally\x18\x05 \x01(\v2\x11.frontline.v1.VecR\x05rally\x12\x14\n" +
	"\x05cargo\x18\x06 \x01(\x03R\x05cargo\x12\x12\n" +
	"\x04home\x18\a \x01(\rR\x04home\x12\x12\n" +
	"\x04ammo\x18\b \x01(\x05R\x04ammo\x12\x1c\n" +
	"\tendurance\x18\t \x01(\rR\tendurance\x12\x18\n" +
	"\acharges\x18\n" +
	" \x01(\x05R\acharges\x12\x1f\n" +
	"\vcharge_work\x18\v \x01(\rR\n" +
	"chargeWork\x12!\n" +
	"\fservice_work\x18\f \x01(\rR\vserviceWork\x12\x1e\n" +
	"\n" +
	"experience\x18\r \x01(\x03R\n" +
	"experience\x124\n" +
	"\tcooldowns\x18\x0e \x03(\v2\x16.frontline.v1.CooldownR\tcooldowns\x12\x1e\n" +
	"\n" +
	"passengers\x18\x0f \x03(\rR\n" +
	"passengers\x12\x1c\n" +
	"\tcontainer\x18\x10 \x01(\rR\tcontainer\"\xf0\x03\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\rR\x05owner\x12-\n" +
	"\bposition\x18\x04 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x16\n" +
	"\x06facing\x18\x05 \x01(\x05R\x06facing\x12\x16\n" +
	"\x06health\x18\x06 \x01(\x05R\x06health\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x1a\n" +
	"\bcomplete\x18\b \x01(\bR\bcomplete\x12\x18\n" +
	"\aenabled\x18\t \x01(\bR\aenabled\x12\x16\n" +
	"\x06landed\x18\n" +
	" \x01(\bR\x06landed\x12\x1a\n" +
	"\bdeployed\x18\v \x01(\bR\bdeployed\x12\x1c\n" +
	"\tconcealed\x18\f \x01(\bR\tconcealed\x12\x1a\n" +
	"\bprogress\x18\r \x01(\x05R\bprogress\x12\x12\n" +
	"\x04rank\x18\x0e \x01(\rR\x04rank\x125\n" +
	"\aprivate\x18\x0f \x01(\v2\x1b.frontline.v1.EntityPrivateR\aprivate\x12#\n" +
	"\rturret_facing\x18\x10 \x01(\x05R\fturretFacing\x12#\n" +
	"\rchannel_until\x18\x11 \x01(\rR\fchannelUntil\"\xc9\x01\n" +
	"\rPlayerSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\afaction\x18\x03 \x01(\tR\afaction\x12\x12\n" +
	"\x04team\x18\x04 \x01(\rR\x04team\x12\x1a\n" +
	"\bdefeated\x18\x05 \x01(\bR\bdefeated\x12\x1b\n" +
	"\tdefeat_at\x18\x06 \x01(\rR\bdefeatAt\x12-\n" +
	"\x12strategic_progress\x18\a \x01(\x05R\x11strategicProgress\"\x81\x02\n" +
	"\n" +
	"Projectile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\rR\x05owner\x12\x16\n" +
	"\x06weapon\x18\x03 \x01(\tR\x06weapon\x12-\n" +
	"\bposition\x18\x04 \x01(\v2\x11.frontline.v1.VecR\bposition\x12)\n" +
	"\x06impact\x18\x05 \x01(\v2\x11.frontline.v1.VecR\x06impact\x12\x1b\n" +
	"\timpact_at\x18\x06 \x01(\rR\bimpactAt\x12$\n" +
	"\rinterceptable\x18\a \x01(\bR\rinterceptable\x12\x18\n" +
	"\awarning\x18\b \x01(\bR\awarning\"d\n" +
	"\x05Field\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x03R\tremaining\"^\n" +
	"\aStation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\rR\x05owner\"\x85\x01\n" +
	"\x06Memory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\rR\x05owner\x12-\n" +
	"\bposition\x18\x04 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x12\n" +
	"\x04seen\x18\x05 \x01(\rR\x04seen\"\xdc\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\rR\x05owner\x12\x16\n" +
	"\x06entity\x18\x05 \x01(\rR\x06entity\x12-\n" +
	"\bposition\x18\x06 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x14\n" +
	"\x05value\x18\a \x01(\x03R\x05value\x12\x14\n" +
	"\x05scope\x18\b \x01(\tR\x05scope\x12\x12\n" +
	"\x04text\x18\t \x01(\tR\x04text\"\x88\x01\n" +
	"\aOutcome\x12\x1a\n" +
	"\bfinished\x18\x01 \x01(\bR\bfinished\x12\x12\n" +
	"\x04draw\x18\x02 \x01(\bR\x04draw\x12!\n" +
	"\fwinning_team\x18\x03 \x01(\rR\vwinningTeam\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x12\n" +
	"\x04tick\x18\x05 \x01(\rR\x04tick\"\xba\a\n" +
	"\x0ePlayerSnapshot\x122\n" +
	"\bmetadata\x18\x01 \x01(\v2\x16.frontline.v1.MetadataR\bmetadata\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\rR\x04tick\x12\x1c\n" +
	"\tcountdown\x18\x03 \x01(\rR\tcountdown\x12\x16\n" +
	"\x06player\x18\x04 \x01(\rR\x06player\x12/\n" +
	"\aeconomy\x18\x05 \x01(\v2\x15.frontline.v1.EconomyR\aeconomy\x125\n" +
	"\aplayers\x18\x06 \x03(\v2\x1b.frontline.v1.PlayerSummaryR\aplayers\x120\n" +
	"\bentities\x18\a \x03(\v2\x14.frontline.v1.EntityR\bentities\x12:\n" +
	"\vprojectiles\x18\b \x03(\v2\x18.frontline.v1.ProjectileR\vprojectiles\x12+\n" +
	"\x06fields\x18\t \x03(\v2\x13.frontline.v1.FieldR\x06fields\x121\n" +
	"\bstations\x18\n" +
	" \x03(\v2\x15.frontline.v1.StationR\bstations\x12\x1e\n" +
	"\bexplored\x18\v \x03(\bB\x02\x10\x01R\bexplored\x12\x1c\n" +
	"\avisible\x18\f \x03(\bB\x02\x10\x01R\avisible\x12,\n" +
	"\x06memory\x18\r \x03(\v2\x14.frontline.v1.MemoryR\x06memory\x12+\n" +
	"\x06events\x18\x0e \x03(\v2\x13.frontline.v1.EventR\x06events\x123\n" +
	"\aresults\x18\x0f \x03(\v2\x19.frontline.v1.OrderResultR\aresults\x12\x1f\n" +
	"\vshipment_at\x18\x10 \x01(\rR\n" +
	"shipmentAt\x12/\n" +
	"\aoutcome\x18\x11 \x01(\v2\x15.frontline.v1.OutcomeR\aoutcome\x12/\n" +
	"\asalvage\x18\x12 \x03(\v2\x15.frontline.v1.SalvageR\asalvage\x12(\n" +
	"\x05zones\x18\x13 \x03(\v2\x12.frontline.v1.ZoneR\x05zones\x12@\n" +
	"\n" +
	"indicators\x18\x14 \x03(\v2 .frontline.v1.StructureIndicatorR\n" +
	"indicators\x127\n" +
	"\amission\x18\x15 \x01(\v2\x1d.frontline.v1.MissionProgressR\amission\"\x90\x01\n" +
	"\n" +
	"StateDelta\x12#\n" +
	"\rbaseline_tick\x18\x01 \x01(\rR\fbaselineTick\x122\n" +
	"\x05state\x18\x02 \x01(\v2\x1c.frontline.v1.PlayerSnapshotR\x05state\x12)\n" +
	"\x10removed_entities\x18\x03 \x03(\rR\x0fremovedEntities\"\x8b\x01\n" +
	"\vMatchResult\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12/\n" +
	"\aoutcome\x18\x02 \x01(\v2\x15.frontline.v1.OutcomeR\aoutcome\x12\x1c\n" +
	"\tcommitted\x18\x03 \x01(\bR\tcommitted\x12\x12\n" +
	"\x04void\x18\x04 \x01(\bR\x04void\"\x8a\x01\n" +
	"\aSalvage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\rR\x05owner\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x03R\x05value\x12\x14\n" +
	"\x05until\x18\x05 \x01(\rR\x05until\"\xa3\x01\n" +
	"\x04Zone\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\rR\x05owner\x12-\n" +
	"\bposition\x18\x03 \x01(\v2\x11.frontline.v1.VecR\bposition\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x05R\x06radius\x12\x14\n" +
	"\x05start\x18\x05 \x01(\rR\x05start\x12\x14\n" +
	"\x05until\x18\x06 \x01(\rR\x05until\"Y\n" +
	"\x12StructureIndicator\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\rR\x05owner\x12-\n" +
	"\bposition\x18\x02 \x01(\v2\x11.frontline.v1.VecR\bposition\"\xc1\x01\n" +
	"\x11ObjectiveProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\boptional\x18\x03 \x01(\bR\boptional\x12\x18\n" +
	"\afailure\x18\x04 \x01(\bR\afailure\x12\x1a\n" +
	"\bcomplete\x18\x05 \x01(\bR\bcomplete\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\rR\bprogress\x12\x1a\n" +
	"\brequired\x18\a \x01(\rR\brequired\"\xe1\x01\n" +
	"\x0fMissionProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x03 \x01(\tR\n" +
	"difficulty\x12\x1e\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\tR\n" +
	"checkpoint\x12'\n" +
	"\x0fcheckpoint_tick\x18\x05 \x01(\rR\x0echeckpointTick\x12?\n" +
	"\n" +
	"objectives\x18\x06 \x03(\v2\x1f.frontline.v1.ObjectiveProgressR\n" +
	"objectivesB$Z\"frontlinecommand/protocol;protocolb\x06proto3"

var (
	file_protocol_frontline_proto_rawDescOnce sync.Once
	file_protocol_frontline_proto_rawDescData []byte
)

func file_protocol_frontline_proto_rawDescGZIP() []byte {
	file_protocol_frontline_proto_rawDescOnce.Do(func() {
		file_protocol_frontline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_frontline_proto_rawDesc), len(file_protocol_frontline_proto_rawDesc)))
	})
	return file_protocol_frontline_proto_rawDescData
}

var file_protocol_frontline_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_protocol_frontline_proto_goTypes = []any{
	(*Envelope)(nil),           // 0: frontline.v1.Envelope
	(*ClientHello)(nil),        // 1: frontline.v1.ClientHello
	(*ResumeMatch)(nil),        // 2: frontline.v1.ResumeMatch
	(*Ping)(nil),               // 3: frontline.v1.Ping
	(*ProtocolError)(nil),      // 4: frontline.v1.ProtocolError
	(*Vec)(nil),                // 5: frontline.v1.Vec
	(*Order)(nil),              // 6: frontline.v1.Order
	(*OrderBatch)(nil),         // 7: frontline.v1.OrderBatch
	(*OrderResult)(nil),        // 8: frontline.v1.OrderResult
	(*Metadata)(nil),           // 9: frontline.v1.Metadata
	(*Cooldown)(nil),           // 10: frontline.v1.Cooldown
	(*Job)(nil),                // 11: frontline.v1.Job
	(*Economy)(nil),            // 12: frontline.v1.Economy
	(*EntityPrivate)(nil),      // 13: frontline.v1.EntityPrivate
	(*Entity)(nil),             // 14: frontline.v1.Entity
	(*PlayerSummary)(nil),      // 15: frontline.v1.PlayerSummary
	(*Projectile)(nil),         // 16: frontline.v1.Projectile
	(*Field)(nil),              // 17: frontline.v1.Field
	(*Station)(nil),            // 18: frontline.v1.Station
	(*Memory)(nil),             // 19: frontline.v1.Memory
	(*Event)(nil),              // 20: frontline.v1.Event
	(*Outcome)(nil),            // 21: frontline.v1.Outcome
	(*PlayerSnapshot)(nil),     // 22: frontline.v1.PlayerSnapshot
	(*StateDelta)(nil),         // 23: frontline.v1.StateDelta
	(*MatchResult)(nil),        // 24: frontline.v1.MatchResult
	(*Salvage)(nil),            // 25: frontline.v1.Salvage
	(*Zone)(nil),               // 26: frontline.v1.Zone
	(*StructureIndicator)(nil), // 27: frontline.v1.StructureIndicator
	(*ObjectiveProgress)(nil),  // 28: frontline.v1.ObjectiveProgress
	(*MissionProgress)(nil),    // 29: frontline.v1.MissionProgress
}
var file_protocol_frontline_proto_depIdxs = []int32{
	1,  // 0: frontline.v1.Envelope.hello:type_name -> frontline.v1.ClientHello
	7,  // 1: frontline.v1.Envelope.orders:type_name -> frontline.v1.OrderBatch
	8,  // 2: frontline.v1.Envelope.order_result:type_name -> frontline.v1.OrderResult
	22, // 3: frontline.v1.Envelope.snapshot:type_name -> frontline.v1.PlayerSnapshot
	23, // 4: frontline.v1.Envelope.delta:type_name -> frontline.v1.StateDelta
	2,  // 5: frontline.v1.Envelope.resume:type_name -> frontline.v1.ResumeMatch
	24, // 6: frontline.v1.Envelope.result:type_name -> frontline.v1.MatchResult
	4,  // 7: frontline.v1.Envelope.error:type_name -> frontline.v1.ProtocolError
	3,  // 8: frontline.v1.Envelope.ping:type_name -> frontline.v1.Ping
	1,  // 9: frontline.v1.ResumeMatch.hello:type_name -> frontline.v1.ClientHello
	5,  // 10: frontline.v1.Order.position:type_name -> frontline.v1.Vec
	5,  // 11: frontline.v1.Order.points:type_name -> frontline.v1.Vec
	6,  // 12: frontline.v1.OrderBatch.orders:type_name -> frontline.v1.Order
	10, // 13: frontline.v1.Economy.cooldowns:type_name -> frontline.v1.Cooldown
	11, // 14: frontline.v1.EntityPrivate.jobs:type_name -> frontline.v1.Job
	6,  // 15: frontline.v1.EntityPrivate.orders:type_name -> frontline.v1.Order
	5,  // 16: frontline.v1.EntityPrivate.rally:type_name -> frontline.v1.Vec
	10, // 17: frontline.v1.EntityPrivate.cooldowns:type_name -> frontline.v1.Cooldown
	5,  // 18: frontline.v1.Entity.position:type_name -> frontline.v1.Vec
	13, // 19: frontline.v1.Entity.private:type_name -> frontline.v1.EntityPrivate
	5,  // 20: frontline.v1.Projectile.position:type_name -> frontline.v1.Vec
	5,  // 21: frontline.v1.Projectile.impact:type_name -> frontline.v1.Vec
	5,  // 22: frontline.v1.Field.position:type_name -> frontline.v1.Vec
	5,  // 23: frontline.v1.Station.position:type_name -> frontline.v1.Vec
	5,  // 24: frontline.v1.Memory.position:type_name -> frontline.v1.Vec
	5,  // 25: frontline.v1.Event.position:type_name -> frontline.v1.Vec
	9,  // 26: frontline.v1.PlayerSnapshot.metadata:type_name -> frontline.v1.Metadata
	12, // 27: frontline.v1.PlayerSnapshot.economy:type_name -> frontline.v1.Economy
	15, // 28: frontline.v1.PlayerSnapshot.players:type_name -> frontline.v1.PlayerSummary
	14, // 29: frontline.v1.PlayerSnapshot.entities:type_name -> frontline.v1.Entity
	16, // 30: frontline.v1.PlayerSnapshot.projectiles:type_name -> frontline.v1.Projectile
	17, // 31: frontline.v1.PlayerSnapshot.fields:type_name -> frontline.v1.Field
	18, // 32: frontline.v1.PlayerSnapshot.stations:type_name -> frontline.v1.Station
	19, // 33: frontline.v1.PlayerSnapshot.memory:type_name -> frontline.v1.Memory
	20, // 34: frontline.v1.PlayerSnapshot.events:type_name -> frontline.v1.Event
	8,  // 35: frontline.v1.PlayerSnapshot.results:type_name -> frontline.v1.OrderResult
	21, // 36: frontline.v1.PlayerSnapshot.outcome:type_name -> frontline.v1.Outcome
	25, // 37: frontline.v1.PlayerSnapshot.salvage:type_name -> frontline.v1.Salvage
	26, // 38: frontline.v1.PlayerSnapshot.zones:type_name -> frontline.v1.Zone
	27, // 39: frontline.v1.PlayerSnapshot.indicators:type_name -> frontline.v1.StructureIndicator
	29, // 40: frontline.v1.PlayerSnapshot.mission:type_name -> frontline.v1.MissionProgress
	22, // 41: frontline.v1.StateDelta.state:type_name -> frontline.v1.PlayerSnapshot
	21, // 42: frontline.v1.MatchResult.outcome:type_name -> frontline.v1.Outcome
	5,  // 43: frontline.v1.Salvage.position:type_name -> frontline.v1.Vec
	5,  // 44: frontline.v1.Zone.position:type_name -> frontline.v1.Vec
	5,  // 45: frontline.v1.StructureIndicator.position:type_name -> frontline.v1.Vec
	28, // 46: frontline.v1.MissionProgress.objectives:type_name -> frontline.v1.ObjectiveProgress
	47, // [47:47] is the sub-list for method output_type
	47, // [47:47] is the sub-list for method input_type
	47, // [47:47] is the sub-list for extension type_name
	47, // [47:47] is the sub-list for extension extendee
	0,  // [0:47] is the sub-list for field type_name
}

func init() { file_protocol_frontline_proto_init() }
func file_protocol_frontline_proto_init() {
	if File_protocol_frontline_proto != nil {
		return
	}
	file_protocol_frontline_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Orders)(nil),
		(*Envelope_OrderResult)(nil),
		(*Envelope_Snapshot)(nil),
		(*Envelope_Delta)(nil),
		(*Envelope_Resume)(nil),
		(*Envelope_Result)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_frontline_proto_rawDesc), len(file_protocol_frontline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_frontline_proto_goTypes,
		DependencyIndexes: file_protocol_frontline_proto_depIdxs,
		MessageInfos:      file_protocol_frontline_proto_msgTypes,
	}.Build()
	File_protocol_frontline_proto = out.File
	file_protocol_frontline_proto_goTypes = nil
	file_protocol_frontline_proto_depIdxs = nil
}
