import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';import {createHash} from 'node:crypto';import path from 'node:path';import {pathToFileURL} from 'node:url';
import {build} from '../../../client/node_modules/esbuild/lib/main.js';
const root=process.cwd(),candidate=path.join(root,'work/claude/presentation-polish-v1/source/client/src/render'),out=path.resolve(process.argv[2]??'work/evidence/presentation-privacy-review/cpu-v1-01');await mkdir(out);
const sha=bytes=>createHash('sha256').update(bytes).digest('hex'),audit=JSON.parse(await readFile('work/claude/authoring-20260929/presentation/run-20260929T144314691446Z.model-audit.json','utf8'));
assert.equal(audit.status,'completed-exact-model');const source=await readFile(path.join(candidate,'terrain.ts'));assert.equal(sha(source),audit.outputs['work/claude/presentation-polish-v1/source/client/src/render/terrain.ts']);
const pins={};for(const file of ['terrain.ts','terrain-surface.ts','terrain-materials.ts','iso.ts'])pins[file]=sha(await readFile(path.join(candidate,file)));
const adapter=path.resolve('client/tests/render/terrain-fog-cost-pixi.mjs');pins.adapter=sha(await readFile(adapter));
await build({stdin:{contents:source.toString()+'\nexport {TerrainSurface,surfaceFogOpacity};export {Texture as TestTexture} from "pixi.js";',resolveDir:candidate,sourcefile:'frozen-terrain.ts',loader:'ts'},outfile:path.join(out,'candidate.mjs'),bundle:true,format:'esm',platform:'node',plugins:[{name:'existing-nonrendering-buffer-observer',setup(b){b.onResolve({filter:/^pixi\.js$/},()=>({path:adapter}))}}]});
const mod=await import(pathToFileURL(path.join(out,'candidate.mjs')));globalThis.document={createElement(name){assert.equal(name,'canvas');return {width:0,height:0,getContext(){return {createImageData(w,h){return {data:new Uint8ClampedArray(w*h*4)}},putImageData(){},fillRect(){}}}}}};
const publicMap={width:17,height:17,tiles:Array.from({length:289},()=>({height:0,terrain:'open'}))};Object.defineProperty(publicMap,'entities',{get(){throw Error('Hidden actor read')}});
const baker=new mod.TerrainBaker(publicMap,{}),surface=new mod.TerrainSurface(publicMap),fragments=baker.surfaceFragments(0,0,mod.TestTexture.WHITE,surface),cases=[];
const originalGeometry=JSON.stringify(fragments.map(f=>({triangles:f.triangles,bounds:f.bounds,depth:f.depth,positions:[...f.mesh.geometry.positions],uvs:[...f.mesh.geometry.uvs],indices:[...f.mesh.geometry.indices]})));
const tileOpacity=(tile,v,e)=>v[tile]?0:e[tile]?175:255;
function pointAlpha(x,y,v,e){let alpha=0;for(let yy=0;yy<17;yy++)for(let xx=0;xx<17;xx++)if(x>=xx*1000&&x<=(xx+1)*1000&&y>=yy*1000&&y<=(yy+1)*1000)alpha=Math.max(alpha,tileOpacity(yy*17+xx,v,e));return alpha}
// Independent point-square rule, not the candidate's cached topology/function.
function oracle(triangle,v,e){const base=mod.surfaceFogOpacity(triangle,v,e);return triangle.vertices.map((p,j)=>{let a=base;if(base===0){a=pointAlpha(p.x,p.y,v,e);if(triangle.kind==='top'&&j===0){const x=triangle.tile%17,y=Math.floor(triangle.tile/17);const sum=[[x,y],[x+1,y],[x+1,y+1],[x,y+1]].reduce((n,[xx,yy])=>n+pointAlpha(xx*1000,yy*1000,v,e),0);a=Math.max(a,Math.min(128,sum/4))}}return a})}
const uploads=()=>fragments.reduce((n,f)=>n+f.fog.geometry.attributes.aUV.buffer.updates,0);
function apply(name,v,e,stable=false,hidden=false){const before=uploads();for(const f of fragments){f.setVisible(!hidden);f.setFog(v,e);const expected=new Float32Array(f.triangles.length*6);let any=false;f.triangles.forEach((t,i)=>oracle(t,v,e).forEach((a,j)=>{expected[i*6+j*2]=a===0?0:(a+.75)/256;expected[i*6+j*2+1]=.5;any ||=a!==0}));assert.deepEqual(f.fog.geometry.uvs,expected,name);assert.deepEqual(f.fog.geometry.attributes.aUV.buffer.uploaded,expected,name+' uploaded');assert.equal(f.fog.visible,!hidden&&any);assert.equal(f.mesh.visible,!hidden)}if(stable)assert.equal(uploads(),before,name+' should not upload');cases.push({name,uploadDelta:uploads()-before,hidden})}
let v=Array(289).fill(true),e=[...v];
apply('all visible',v,e);apply('same values fresh perspective',v.slice(),e.slice(),true);
const tile=270,far=288,target=fragments.find(f=>f.triangles.some(t=>t.id===`t${tile}.0`)),i=target.triangles.findIndex(t=>t.id===`t${tile}.0`);
v[far]=false;apply('far diagonal remembered while fragment hidden',v,e,false,true);assert.equal(target.fog.geometry.uvs[i*6],(175/4+.75)/256);
apply('show remembered unchanged',v,e,true);e[far]=false;apply('far diagonal becomes unknown in same arrays',v,e);assert.equal(target.fog.geometry.uvs[i*6],(255/4+.75)/256);
apply('same unknown values fresh perspective',v.slice(),e.slice(),true);v[far]=true;apply('same array returns visible',v,e);assert.equal(target.fog.geometry.uvs[i*6],0);
apply('explored bit irrelevant on visible tile',v,Array(289).fill(true),true);apply('rewind missing vectors',[],[]);apply('unchanged missing hidden',[],[],true,true);apply('missing restored',[],[],true);
let seed=191;for(let n=0;n<20;n++){for(let j=0;j<289;j++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;v[j]=(seed&3)===0;e[j]=(seed&4)!==0}if(n%5===0){v.length=272;e.length=276;delete v[270];delete e[271]}apply('in-place mixed public state '+n,v,e,false,n%3===0);apply('identical current public state '+n,v.slice(),e.slice(),true,n%3===0)}
const accessed=new Set();const publicOnly=new Proxy(Array(289).fill(false),{get(t,key){assert.match(String(key),/^\d+$/);assert(Number(key)>=0&&Number(key)<289);accessed.add(Number(key));return t[key]}});for(const f of fragments)f.setFog(publicOnly,publicOnly);assert(accessed.has(far));
assert.equal(JSON.stringify(fragments.map(f=>({triangles:f.triangles,bounds:f.bounds,depth:f.depth,positions:[...f.mesh.geometry.positions],uvs:[...f.mesh.geometry.uvs],indices:[...f.mesh.geometry.indices]}))),originalGeometry);
const owned=[...new Set(fragments.flatMap(f=>[f.mesh.texture,f.fog.texture]))].filter(t=>t!==mod.TestTexture.WHITE);for(const f of fragments)f.dispose();baker.disposeSurfaceResources();assert(fragments.every(f=>f.mesh.destroyed&&f.fog.destroyed&&f.mesh.geometry.destroyed&&f.fog.geometry.destroyed));assert(owned.every(t=>t.destroyed));
for(const [name,digest]of Object.entries(pins))assert.equal(sha(await readFile(name==='adapter'?adapter:path.join(candidate,name))),digest);
const result={status:'passed',scope:'Frozen v1 actual TerrainBaker cache/Float32/upload path with non-rendering Pixi adapter; no browser/GPU/alpha-pixel/performance acceptance',pins,cases,farDiagonal:{tile,far,rememberedCentre:175/4,unknownCentre:255/4,outsideChunk:true},publicIndicesRead:accessed.size,geometryUnchanged:true,ownedDisposed:true,helperSHA256:sha(await readFile(new URL(import.meta.url)))};await writeFile(path.join(out,'result.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({status:result.status,cases:cases.length,publicIndicesRead:accessed.size}));
