import {chromium} from '../../../client/node_modules/playwright-core/index.mjs';
import {createServer} from 'node:http';import {readFile,writeFile,mkdir} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
const args=process.argv.slice(2),get=(key,fallback)=>args.includes(key)?args[args.indexOf(key)+1]:fallback;
if(!args.includes('--execute'))throw Error('Prepared only. Pass --execute after the root releases browser/power execution.');
const input=path.resolve(get('--input','work/audio-generation-retry-v1/browser-prepared-v1')),output=path.resolve(get('--output',`work/audio-generation-retry-v1/browser-${new Date().toISOString().replace(/[:.]/g,'-')}`)),executable=get('--executable');
assert(executable,'Pass a verified explicit Chromium/Chrome executable.');await mkdir(output,{recursive:true});
const hash=bytes=>createHash('sha256').update(bytes).digest('hex'),prepared=JSON.parse(await readFile(path.join(input,'prepared.json'),'utf8'));
for(const [name,file]of Object.entries(prepared.files)){const data=await readFile(path.join(input,name));assert.equal(hash(data),file.sha256);assert.equal(data.length,file.bytes)}
const source=Object.fromEntries(prepared.clips.map(clip=>[clip.label,clip]));let mode='A',holdNext=false,held,sequence=0;
const served=[],requests=[],requestFailures=[],httpErrors=[],consoleErrors=[],pageErrors=[],checks=[],expectedCanceled=new Set();let browser,page;
const server=createServer(async(req,res)=>{const url=new URL(req.url,'http://local'),record={id:++sequence,path:url.pathname,mode,startedAt:new Date().toISOString()};served.push(record);try{
 let data,type='application/octet-stream';
 if(url.pathname==='/art/audio/index.json'){data=Buffer.from(JSON.stringify(mode==='invalid'?{invalid:true}:source[mode].index));type='application/json'}
 else if(/^\/art\/audio\/review\/clip\.(ogg|mp3)$/.test(url.pathname)){
  const codec=url.pathname.endsWith('.mp3')?'mp3':'ogg',clip=source[mode==='invalid'?'A':mode];data=await readFile(path.join(input,clip.files.find(file=>file.codec===codec).file));type=codec==='mp3'?'audio/mpeg':'audio/ogg';
  if(holdNext){holdNext=false;record.held=true;held={record,release:undefined};await new Promise(resolve=>{held.release=resolve;res.on('close',resolve)})}
 }else{const name=url.pathname==='/'?'index.html':url.pathname.slice(1);if(!['index.html','fixture.js','fixture.js.map'].includes(name)){res.writeHead(404);res.end();return}data=await readFile(path.join(input,name));type=name.endsWith('.js')?'text/javascript':name.endsWith('.html')?'text/html':'application/json'}
 record.bytes=data.length;record.sha256=hash(data);if(res.destroyed){record.canceledBeforeWrite=true;return}res.writeHead(200,{'content-type':type,'content-length':data.length,'cache-control':'no-store'});res.end(data);record.finished=true;
 }catch(error){record.error=String(error);if(!res.destroyed){res.writeHead(500);res.end()}}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
const result={status:'running',scope:'Real AudioContext with exact existing clips. Test-only server switches same-URL descriptors and holds one request; no subjective listening, gameplay, GPU or performance claim.',preparedSHA256:hash(await readFile(path.join(input,'prepared.json'))),executable,executableSHA256:hash(await readFile(executable)),checks};
const wait=async predicate=>{const end=Date.now()+10000;while(!predicate()){assert(Date.now()<end,'Server checkpoint timed out');await new Promise(resolve=>setTimeout(resolve,10))}};
const api=(name,...args)=>page.evaluate(({name,args})=>window.audioReview[name](...args),{name,args});
try{
 browser=await chromium.launch({executablePath:executable,headless:false,args:['--mute-audio']});result.browser=browser.version();const context=await browser.newContext({viewport:{width:960,height:640}});page=await context.newPage();
 const byRequest=new Map(),ordinals=new Map();page.on('request',request=>{const key=request.method()+' '+request.url(),ordinal=(ordinals.get(key)??0)+1;ordinals.set(key,ordinal);const value={id:requests.length+1,url:request.url(),method:request.method(),ordinal};byRequest.set(request,value);requests.push(value)});
 page.on('requestfailed',request=>requestFailures.push({...byRequest.get(request),failure:request.failure(),at:new Date().toISOString()}));page.on('response',response=>{if(response.status()>=400)httpErrors.push({url:response.url(),status:response.status()})});page.on('pageerror',error=>pageErrors.push(String(error.stack??error)));page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});
 await page.goto(origin);await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.click('#gesture');assert.equal((await api('state')).statistics.context,'absent');await api('syntheticGesture');assert.equal((await api('state')).statistics.context,'absent');checks.push({name:'denied-and-synthetic-gesture',pass:true});
 await page.click('#consent');await page.click('#gesture');await page.waitForFunction(()=>window.audioReview.state().statistics.context==='running');const a=await api('load');assert(Math.abs(a.duration-source.A.original.duration)<.15);checks.push({name:'actual-A-decode',buffer:a});
 mode='B';await api('reload');const b=await api('load');assert.notEqual(a.id,b.id);assert.notEqual(a.pcmSHA256,b.pcmSHA256);assert(Math.abs(b.duration-source.B.original.duration)<.15);checks.push({name:'cached-sameURL-change',buffer:b});
 mode='invalid';const before=await api('state');await api('reload');assert.deepEqual((await api('state')).descriptor,before.descriptor);assert.equal((await api('load')).id,b.id);checks.push({name:'failed-index-keeps-B',pass:true});
 mode='A';await api('reload');await api('reset');holdNext=true;await api('queue','held-A');await wait(()=>held?.record.held);const pendingRequest=requests.filter(request=>request.url===origin+'/art/audio/review/clip.ogg').at(-1);assert(pendingRequest);expectedCanceled.add(pendingRequest.id);
 mode='B';await api('reload');await page.waitForFunction(()=>window.audioReview.state().pending.status==='rejected');held.release();const after=await api('load');assert.equal(after.pcmSHA256,b.pcmSHA256);checks.push({name:'pending-original-HTTP-canceled-on-change',heldServerRequest:held.record.id,expectedBrowserRequest:pendingRequest.id,buffer:after,pending:(await api('state')).pending});
 await page.click('#play');await page.waitForFunction(()=>window.audioReview.state().statistics.sources>0);const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();await page.waitForFunction(()=>window.audioReview.state().statistics.context==='suspended');assert.equal((await api('state')).statistics.sources,0);await other.close();await page.bringToFront();await page.click('#gesture');await page.waitForFunction(()=>window.audioReview.state().statistics.context==='running');checks.push({name:'actual-tab-focus-suspend-and-trusted-resume',pass:true});
 await page.click('#withdraw');await page.waitForFunction(()=>window.audioReview.state().statistics.context==='suspended');assert.equal((await api('state')).statistics.buffers,0);await api('dispose');await page.waitForFunction(()=>window.audioReview.state().closedContext==='closed');await page.click('#gesture');assert.equal((await api('state')).statistics.context,'absent');result.cleanup=await api('state');checks.push({name:'withdrawal-and-context-dispose',pass:true});
 result.nativeTrace=await api('trace');result.bodyIntegrity=[];for(const record of result.nativeTrace.records){const records=served.filter(value=>value.path===new URL(record.url).pathname),exact=records[record.ordinal-1];assert(exact,'Native trace has no exact served ordinal');if(exact.held){assert(record.signalAbortOrder||record.fetchError||record.readError,'Held request must have actual cancellation evidence');continue}assert.equal(record.bytesRead,exact.bytes);assert.equal(record.sha256,exact.sha256);assert(record.eofOrder);assert.equal(record.status,200);assert.equal(record.redirected,false);result.bodyIntegrity.push({url:record.url,ordinal:record.ordinal,servedId:exact.id,bytes:record.bytesRead,sha256:record.sha256,eofOrder:record.eofOrder})}assert.deepEqual(result.nativeTrace.faults,[]);assert.equal(result.nativeTrace.overflow,0);await page.screenshot({path:path.join(output,'completed.png')});result.functional='passed';
}catch(error){result.functional='failed';result.error=String(error.stack??error);if(page){result.state=await api('state').catch(()=>undefined);result.nativeTrace=await api('trace').catch(()=>undefined);await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{})}}
finally{
 held?.release?.();if(page){await api('dispose').catch(()=>{});result.nativeTraceAfterDispose=await api('trace').catch(()=>undefined)}await browser?.close();await new Promise(resolve=>server.close(resolve));
 result.requests=requests;result.requestFailures=requestFailures;result.expectedIntentionalCancelRequestIds=[...expectedCanceled];result.unexpectedRequestFailures=requestFailures.filter(failure=>!expectedCanceled.has(failure.id));result.httpErrors=httpErrors;result.consoleErrors=consoleErrors;result.pageErrors=pageErrors;result.served=served;
 result.status=result.functional==='passed'&&!result.unexpectedRequestFailures.length&&!httpErrors.length&&!consoleErrors.length&&!pageErrors.length?'passed':'failed';result.closedAt=new Date().toISOString();await writeFile(path.join(output,'browser.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({output,status:result.status,checks:checks.length,unexpectedRequestFailures:result.unexpectedRequestFailures.length}));if(result.status!=='passed')process.exitCode=1;
}
