// One static Canvas browser; actual ArtLibrary/verified generations, unchanged pixels.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,realpath} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {chromium} from '../../client/node_modules/playwright-core/index.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(here,'../..');
const [preparedName,buildName,runName,exe]=process.argv.slice(2);for(const name of [preparedName,buildName,runName])assert(/^[a-z0-9-]+$/.test(name??''));
const prepared=path.join(here,preparedName),build=path.join(prepared,buildName),out=path.join(here,runName);await mkdir(out);
const sha=b=>createHash('sha256').update(b).digest('hex'),report={status:'running',started:new Date().toISOString(),roles:[],diagnostics:{page:[],console:[],http:[],request:[]},scope:'Static actual ArtLibrary.cameo, exact current53 masks/beauty and real verified generation loads. No world, Go, gameplay, audio or performance claim. Browser plugin/skill absent; existing Playwright.'};
let browser,server,context;let fatal;const served=[];const deadline=Date.now()+180000;
async function bounded(work,ms){let timer;try{return await Promise.race([work,new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('Bounded UI role deadline exceeded')),ms)})])}finally{clearTimeout(timer)}}
const html='<!doctype html><html><head><meta charset="utf-8"><title>Frontline Command — UI mask audit loading</title><style>body{background:#8c806b;color:#171713;margin:12px;font:12px sans-serif}h1{font-size:18px;margin:0 0 8px}h2{font-size:15px;margin:4px 0}.palette{display:flex;gap:8px;position:relative;padding-top:22px;margin-bottom:6px;align-items:center}.palette p{position:absolute;top:0;margin:0}.cell{display:flex;align-items:center;justify-content:center;width:200px;min-height:192px}.cell img{max-width:none;max-height:none}#contact{width:850px}</style></head><body><h1>Actual current53 compositor — original / normalized team masks</h1><section id="contact"></section><script type="module" src="/fixture.js"></script></body></html>';
async function verify(){const prep=JSON.parse(await readFile(path.join(prepared,'preparation.json')));assert.equal(prep.status,'prepared');for(const [name,hash]of Object.entries(prep.sourcePins))assert.equal(sha(await readFile(path.join(prepared,name))),hash,name);for(const [name,hash]of Object.entries(prep.inputs))assert.equal(sha(await readFile(path.join(repo,name))),hash,name);assert.equal(sha(await readFile(path.join(prepared,'routes.json'))),prep.routesSHA256);assert.equal(sha(await readFile(path.join(prepared,'config.json'))),prep.configSHA256);const original=JSON.parse(await readFile(path.join(repo,'work/art/ui-team-normalization-audit-v1/normalized-current53-v1/result.json')));for(const [name,hash]of Object.entries(original.protected_original_sha256))assert.equal(sha(await readFile(path.join(repo,name))),hash,name);const built=JSON.parse(await readFile(path.join(build,'receipt.json')));assert.equal(built.status,'passed');assert.equal(sha(await readFile(path.join(prepared,'preparation.json'))),built.preparationSHA256);assert.equal(sha(await readFile(path.join(build,'fixture.js'))),built.bundleSHA256);return {preparationSHA256:built.preparationSHA256,bundleSHA256:built.bundleSHA256,sourceFiles:Object.keys(prep.sourcePins).length,inputFiles:Object.keys(prep.inputs).length,protectedOriginals:Object.keys(original.protected_original_sha256).length}}
try{
 const helper=await readFile(fileURLToPath(import.meta.url));await writeFile(path.join(out,'browser.mjs'),helper);report.driverSHA256=sha(helper);report.initialGuard=await verify();const routes=JSON.parse(await readFile(path.join(prepared,'routes.json'))),config=JSON.parse(await readFile(path.join(prepared,'config.json')));
 report.maskCounts={all:config.maskCount,runtime2x:config.runtimeMaskCount,new:80,reused:132};report.numerical=config.numerical;
 server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');assert.equal(req.method,'GET');assert(!url.search&&!url.hash);if(url.pathname==='/'){res.setHeader('Content-Type','text/html');res.end(html);return}if(url.pathname==='/favicon.ico'){res.writeHead(204).end();return}if(url.pathname==='/fixture.js'){res.setHeader('Content-Type','text/javascript');res.end(await readFile(path.join(build,'fixture.js')));return}const route=routes[url.pathname];assert(route,`Undeclared path ${url.pathname}`);const full=route.prepared?path.join(prepared,route.prepared):path.join(repo,route.source);const bytes=await readFile(full);assert.equal(sha(bytes),route.sha256);assert.equal(bytes.length,route.bytes);served.push({ordinal:served.length+1,path:url.pathname,sha256:route.sha256,bytes:bytes.length});res.writeHead(200,{'Content-Type':url.pathname.endsWith('.png')?'image/png':'application/json','Content-Length':bytes.length,'Cache-Control':'no-store'});res.end(bytes)}catch(error){served.push({path:req.url,error:String(error)});res.writeHead(404).end()}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));report.url=`http://127.0.0.1:${server.address().port}`;
 const executable=await realpath(exe??chromium.executablePath());report.executable=executable;report.executableSHA256=sha(await readFile(executable));browser=await chromium.launch({executablePath:executable,headless:true});report.browserVersion=browser.version();
 context=await browser.newContext({viewport:{width:900,height:1040},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',error=>report.diagnostics.page.push(String(error?.stack??error)));page.on('console',msg=>{if(['error','warning'].includes(msg.type()))report.diagnostics.console.push({type:msg.type(),text:msg.text()})});page.on('response',res=>{if(res.status()>=400)report.diagnostics.http.push({url:res.url(),status:res.status()})});page.on('requestfailed',req=>report.diagnostics.request.push({url:req.url(),method:req.method(),type:req.resourceType(),error:req.failure()?.errorText}));
 await page.goto(report.url);await page.waitForFunction(()=>!!window.uiMaskAudit);assert.equal(await page.title(),'Frontline Command — current53 UI audit ready');assert((await page.locator('h1').innerText()).includes('Actual current53'));
 for(const role of config.roles){assert(Date.now()<deadline,'Three-minute static course deadline exceeded');const result=await bounded(page.evaluate(id=>window.uiMaskAudit.runRole(id),role.id),20000);assert.equal(result.results.length,8);assert.equal(result.cleanup.length,2);report.roles.push(result);await page.locator('#contact').screenshot({path:path.join(out,`${role.group}-${role.id}-native.png`)});await writeFile(path.join(out,'progress.json'),JSON.stringify({roles:report.roles.length,last:role.id},null,2)+'\n')}
 assert.equal(report.roles.length,53);assert.equal(report.roles.flatMap(x=>x.results).length,424);report.domCleanup=await page.evaluate(()=>window.uiMaskAudit.clear());assert.deepEqual(report.domCleanup,{canvases:0,images:0});report.functional='passed';
}catch(error){fatal=error;report.functional=report.functional??'failed';report.failure=String(error?.stack??error)}finally{
 for(const resource of [context,browser])try{await resource?.close()}catch(error){(report.closeFailures??=[]).push(String(error));fatal??=error}
 if(server?.listening)await new Promise(resolve=>server.close(resolve));report.closed=true;
 try{report.finalGuard=await verify()}catch(error){report.finalGuardFailure=String(error);fatal??=error}
 report.served=served;report.serverErrors=served.filter(row=>row.error);const diagnosticCount=Object.values(report.diagnostics).reduce((n,rows)=>n+rows.length,0);report.unexpectedDiagnostics=diagnosticCount;report.status=!fatal&&diagnosticCount===0&&report.serverErrors.length===0?'passed':'failed';report.finished=new Date().toISOString();await writeFile(path.join(out,'result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({out,status:report.status,functional:report.functional,roles:report.roles.length,diagnosticCount,failure:report.failure}));if(report.status!=='passed')process.exitCode=1;
}
