// One bounded same-package paid opening, never a full multiplayer acceptance.
// Root owns the sole browser lane. --build-only cannot launch a process.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {parseArgs} from 'node:util';
import path from 'node:path';
import {installCurrentLoaderObserver,auditCurrentLoaderBodies,limits,publicURL} from './observer.mjs';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),prepared=path.join(root,'work/multiplayer-current-loader-v1/prepared-02');
const {values:args}=parseArgs({options:{out:{type:'string'},'build-only':{type:'boolean',default:false},'lock-sha':{type:'string'},executable:{type:'string'},headless:{type:'boolean',default:false},conditions:{type:'string',default:'Shared host; instrumented correctness only, no performance or deadline-cause claim.'}}});
assert(args.out&&/^[a-f0-9]{64}$/.test(args['lock-sha']??''),'Use --out NEW_DIRECTORY --lock-sha EXACT_SHA');const out=path.resolve(args.out);await mkdir(out);
const sha=bytes=>createHash('sha256').update(bytes).digest('hex'),json=value=>JSON.stringify(value,(_k,v)=>typeof v==='bigint'?v.toString():v,2),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const lockBytes=await readFile(path.join(here,'source-lock.json'));assert.equal(sha(lockBytes),args['lock-sha']);const lock=JSON.parse(lockBytes);
async function sourceGuard(){for(const [file,digest]of Object.entries(lock.files))assert.equal(sha(await readFile(path.resolve(here,file))),digest,'Diagnostic input changed: '+file);assert.equal(sha(await readFile(path.join(here,'source-lock.json'))),args['lock-sha'])}
await sourceGuard();
const {verifyPrepared}=await import(pathToFileURL(path.join(prepared,'source/multiplayer-current-loader-integrity.mjs'))),checked=await verifyPrepared(prepared);assert.equal(checked.receiptSHA256,'e7637f6546778c4bc38c79d4f00317860c69c405b627cfa5415e4dac444875f2');
const build=checked.build,product=build.product,packBytes=await readFile(path.join(product,'assets/packs/base.json')),manifest=JSON.parse(packBytes),packDescriptor={path:'/assets/packs/base.json',bytes:packBytes.length,sha256:sha(packBytes)};
const preflight={status:'author-preflight-only',sourceLockSHA256:args['lock-sha'],preparedSHA256:checked.receiptSHA256,sourceInputs:Object.keys(lock.files).length,preparedInputs:checked.verified,productReceiptSHA256:build.sourceReceiptSHA256,packSHA256:sha(packBytes),limits};
await writeFile(path.join(out,'preflight.json'),json(preflight));if(args['build-only']){await sourceGuard();console.log(json(preflight));process.exit(0)}
const require=createRequire(path.join(root,'client/package.json')),{chromium}=await import(pathToFileURL(require.resolve('playwright-core')));
const {MatrixCommander,acceptanceCase,assertLobby}=await import(pathToFileURL(path.join(prepared,'source/multiplayer-current-loader-contract.mjs'))),config=acceptanceCase('1h3ai');
const {fromBinary,EnvelopeSchema,applyDelta}=await import(pathToFileURL(path.join(prepared,'decode.mjs')));
const report={status:'running',scope:'Exact frozen current-loader App build03, one real local profile plus three deterministic normal Go bots; readiness and one ordinary paid power building only. Intentionally nonterminal; no full-match/reconnect/result/replay/1–4/endurance/performance claim. Observation changes scheduling; every raw failure retains its strict result.',started:new Date().toISOString(),preflight,product:build.product,conditions:args.conditions,configuration:config,limits,pageErrors:[],consoleErrors:[],httpErrors:[],requestFailures:[],commands:[],boundaries:[],sourceFiles:lock.files};
let phase='startup',host,browser,context,page,collector,origin,view,hostLog='',globalTimer;
const receipts=new Map(),sockets=new Set();
const save=()=>writeFile(path.join(out,'browser.json'),json(report));
async function until(check,message,timeout=30000){const start=Date.now();while(!await check()){if(Date.now()-start>timeout)throw Error(message);await sleep(100)}}
async function idle(){await until(async()=>await page.locator('.network-operation,.loading-screen').count()===0,'App remained busy',90000);assert.equal(await page.locator('.network-error').count(),0);assert.equal(await page.getByRole('dialog',{name:'Command interrupted',exact:true}).count(),0)}
async function capture(name){await page.screenshot({path:path.join(out,name+'.png')});await collector.capture(name)}
try{
 const data=path.join(out,'host-data');await mkdir(data);host=spawn(path.join(prepared,'frontline'),['-addr','127.0.0.1:0','-data',data,'-static',product,'-maps',path.join(product,'content/maps'),'-missions',path.join(product,'content/missions')],{cwd:root,env:{...process.env,GOMAXPROCS:'1'},stdio:['ignore','pipe','pipe']});report.hostPID=host.pid;
 host.closed=new Promise(resolve=>{host.once('exit',(code,signal)=>resolve({code,signal}));host.once('error',error=>{report.pageErrors.push({phase:'host-start',message:String(error)});resolve({error:String(error)})})});
 host.stdout.on('data',b=>hostLog+=b);host.stderr.on('data',b=>hostLog+=b);await until(()=>{origin=hostLog.match(/http:\/\/127\.0\.0\.1:\d+/)?.[0];return !!origin},'Host startup failed');report.origin=origin;
 const executable=args.executable?path.resolve(args.executable):chromium.executablePath();report.executable={path:executable,sha256:sha(await readFile(executable))};browser=await chromium.launch({headless:args.headless,executablePath:executable});report.browser=browser.version();
 context=await browser.newContext({viewport:{width:1600,height:900}});page=await context.newPage();page.setDefaultTimeout(30000);
 globalTimer=setTimeout(()=>{report.globalDeadline={seconds:240,phase,time:new Date().toISOString()};void context.close().catch(error=>report.pageErrors.push({phase:'deadline-close',message:String(error)}))},240000);
 const stamp=()=>({phase,clientTick:view?.tick});collector=await installCurrentLoaderObserver(page,{origin,stamp});await writeFile(path.join(out,'observer-source.js'),collector.source);report.observerSourceSHA256=sha(collector.source);
 page.on('pageerror',error=>report.pageErrors.push({...stamp(),message:error.message,stack:error.stack}));page.on('crash',()=>report.pageErrors.push({...stamp(),message:'page-crash'}));page.on('console',message=>{if(message.type()==='error')report.consoleErrors.push({...stamp(),message:message.text(),location:{...message.location(),url:publicURL(message.location().url)}})});
 page.on('requestfailed',request=>report.requestFailures.push({...stamp(),url:publicURL(request.url()),message:request.failure()?.errorText}));page.on('response',response=>{if(response.status()>=400)report.httpErrors.push({...stamp(),url:publicURL(response.url()),status:response.status()})});
 page.on('websocket',socket=>{sockets.add(socket);socket.on('close',()=>sockets.delete(socket));socket.on('framereceived',frame=>{if(typeof frame.payload==='string')return;try{const message=fromBinary(EnvelopeSchema,new Uint8Array(frame.payload)).message;if(message.case==='snapshot')view=message.value;else if(message.case==='delta')view=applyDelta(view,message.value);else if(message.case==='orderResult')receipts.set(`${message.value.sequence}:${message.value.index}`,message.value);if(view){assert.equal(view.player,1);assert(view.entities.every(e=>!e.private||e.owner===1),'Foreign private state');for(const result of view.results)receipts.set(`${result.sequence}:${result.index}`,result)}}catch(error){report.pageErrors.push({...stamp(),kind:'decoder',message:String(error)})}})});
 phase='normal-profile-and-lobby';await page.goto(origin);await page.getByRole('button',{name:'Explore game modes',exact:true}).click();await page.getByRole('button',{name:'Multiplayer',exact:true}).click();await idle();
 await page.getByLabel('Commander name',{exact:true}).fill('Current loader diagnostic');await page.getByRole('button',{name:'Create local profile',exact:true}).click();await page.getByLabel('Your profile ID').waitFor();await idle();
 const profile=await page.getByLabel('Your profile ID').inputValue();report.profile=profile;
 await page.getByLabel('Operation name',{exact:true}).fill('Bounded current-loader opening');await page.getByLabel('Lobby battlefield',{exact:true}).selectOption(config.map);await page.getByLabel('Battle format',{exact:true}).selectOption(config.mode);await page.getByLabel('Host faction',{exact:true}).selectOption('US');await page.getByRole('button',{name:'Create operation',exact:true}).click();await idle();
 for(const faction of config.botFactions){await page.getByLabel('Add AI faction',{exact:true}).selectOption(faction);await page.getByLabel('Add AI difficulty',{exact:true}).selectOption('normal');await page.getByRole('button',{name:'Add AI commander',exact:true}).click();await idle()}
 phase='four-faction-readiness';assert(await page.getByRole('button',{name:'Start operation',exact:true}).isDisabled());await page.getByRole('button',{name:'Ready to deploy',exact:true}).click();await idle();await until(()=>page.getByRole('button',{name:'Start operation',exact:true}).isEnabled(),'Readiness never completed');
 const ready=JSON.parse(await page.evaluate(()=>window.multiplayerCombat.info()));report.readyRoster=assertLobby(config,ready.lobby,[profile],{ready:true});report.readyAssets=ready.assets;await capture('ready');
 await page.getByRole('button',{name:'Start operation',exact:true}).click();await page.getByRole('complementary',{name:'Command sidebar',exact:true}).waitFor();await page.locator('.scene-loading').waitFor({state:'hidden'});await until(()=>view?.tick>130,'Ordinary countdown did not finish',60000);
 phase='ordinary-paid-opening';const map=JSON.parse(await readFile(path.join(product,'content/maps',config.map+'.json'))),catalog=JSON.parse(await page.evaluate(()=>window.multiplayerCombat.catalog()));report.openingBefore=view;await writeFile(path.join(out,'opening-before.json'),json(view));
 const commander=new MatrixCommander({player:1,map,catalog,view:()=>view,record:value=>{if(value.kind==='stale-intention')(report.staleIntentions??=[]).push(value)},advice:(ids,orders,independent)=>page.evaluate(({ids,orders,independent})=>window.multiplayerCombat.advice(ids,orders,independent),{ids,orders,independent}),send:async(orders,note)=>{
  const tick=view.tick,sequence=await page.evaluate(orders=>window.multiplayerCombat.send(orders),orders);await until(()=>orders.every((_order,index)=>receipts.has(`${sequence}:${index}`)),'Missing Go order receipts',10000);const results=orders.map((_order,index)=>receipts.get(`${sequence}:${index}`));report.commands.push({tick,sequence,orders,note,results});return results;
 }});
 const openingStart=Date.now();while(!view.entities.some(e=>e.owner===1&&e.type==='power'&&e.complete)){assert(Date.now()-openingStart<90000,'Paid opening exceeded90 seconds');assert(view.tick<2400,'Opening exceeded bounded120 simulation seconds');assert(!view.outcome.finished,'Unexpected early terminal match');await commander.step();await sleep(1800)}
 assert(report.commands.some(c=>c.orders.some((order,index)=>order.kind==='build'&&order.type==='power'&&c.results[index]?.accepted)),'No ordinary paid power receipt');assert(!view.outcome.finished);report.openingAfter=view;await writeFile(path.join(out,'opening-after.json'),json(view));await capture('paid-opening');
 phase='normal-menu-cleanup';report.beforeMenu=await page.evaluate(()=>window.multiplayerCombat.lifetime());await page.getByRole('button',{name:'Open pause menu',exact:true}).click();await page.getByRole('region',{name:'Online operation controls'}).first().waitFor();await page.getByRole('button',{name:'Return to command center',exact:true}).click();
 await until(async()=>{const state=await page.evaluate(()=>window.multiplayerCombat.lifetime());report.afterMenu=state;return state.phase==='menu'&&!state.transportPresent&&state.frameSubscribers===0&&state.art.residentPages===0&&state.art.residentBytes===0&&state.art.pickingBytes===0&&sockets.size===0},'Menu did not release battlefield resources');
 assert.equal(report.afterMenu.appInstance,report.beforeMenu.appInstance);assert.equal(report.afterMenu.timeOrigin,report.beforeMenu.timeOrigin);report.remainingSockets=sockets.size;await capture('menu');report.functionalStatus='passed-bounded-nonterminal-opening';
}catch(error){report.functionalStatus='failed';report.failure=String(error.stack??error);if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});if(view)await writeFile(path.join(out,'failure-authorized-view.json'),json(view))}
finally{
 clearTimeout(globalTimer);phase='closing';if(collector)await collector.capture('before-context-close');await context?.close().catch(error=>report.pageErrors.push({phase,message:String(error)}));await browser?.close().catch(error=>report.pageErrors.push({phase,message:String(error)}));
 if(host){if(host.exitCode===null&&host.signalCode===null)host.kill('SIGTERM');report.hostExit=await host.closed}report.closedAt=new Date().toISOString();await writeFile(path.join(out,'host.log'),hostLog);
 if(collector){report.nativeSnapshot=collector.ledger.snapshot();report.bodyDiagnostic=auditCurrentLoaderBodies({snapshot:report.nativeSnapshot,manifest,origin,packDescriptor,playwrightFailures:report.requestFailures,pageErrors:report.pageErrors,consoleErrors:report.consoleErrors,httpErrors:report.httpErrors});report.rawDiagnosticStatus=report.bodyDiagnostic.rawStatus;report.bodyStatus=report.bodyDiagnostic.bodyStatus}
 try{await sourceGuard();const final=await verifyPrepared(prepared);assert.equal(final.receiptSHA256,checked.receiptSHA256);report.inputGuard={status:'passed',sourceInputs:Object.keys(lock.files).length,preparedInputs:final.verified}}catch(error){report.inputGuard={status:'failed',error:String(error)}}
 report.status=report.functionalStatus==='passed-bounded-nonterminal-opening'&&report.rawDiagnosticStatus==='passed'&&report.bodyStatus==='passed-for-supported-static-readers'&&report.inputGuard.status==='passed'&&report.hostExit?.code===0&&!report.globalDeadline?'passed':'failed';await save();
 console.log(json({out,status:report.status,functional:report.functionalStatus,raw:report.rawDiagnosticStatus,body:report.bodyStatus,rawFailures:report.requestFailures.length,exactBodyFailureFacts:report.bodyDiagnostic?.exactBodyFailureFacts.length,closedAt:report.closedAt}));if(report.status!=='passed')process.exitCode=1;
}
