// Original scenario scripts by Codex during the authorized Claude quota takeover.
// Helpers remain Claude Opus 5.5 work. No hidden player-stat or economy changes.
import {MissionBuilder,cr,tile,sec,min,dur,all,any,atLeast,holdFor,timer,waveTimer,tagAlive,tagDestroyed,tagOwned,tagOperational,tagInRegion,tagConcealed,countType,noneOf,regionEntered,regionHeld,stat,stations,fieldRemaining,objectiveDone,eventCount,eventValue,convoyDone,neutralized,spawn,warn,checkpoint,attack,recover,startConvoy,initial,NORMAL_UP,HARD} from './lib/missionkit.mjs';
const air={US:'US.airfield',IR:'IR.drone_hub',SY:'SY.workshop_air',SA:'SA.airfield'};
const operations={US:'Clear Horizon',IR:'Iron Signal',SY:'Open Road',SA:'Shieldline'};
const commanders={US:'Commander Mara Vale',IR:'Commander Arman Vey',SY:'Commander Leila Dar',SA:'Commander Sami Nadir'};
const factions={US:'Union Expeditionary Group',IR:'Signal Directorate',SY:'Road Coalition',SA:'Southern Shield Command'};
const enemyFaction={US:'IR',IR:'SA',SY:'US',SA:'SY'};
const p=(x,y)=>tile(x,y);
const attackTag=(owner,tag,target_tag)=>({kind:'attack_tag',owner,tag,target_tag});
function add(m,tag,type,owner,x,y,count=1,difficulties){m.spawnInitial(initial(tag,type,owner,p(x,y),count,difficulties));return m}
function obj(m,id,text,condition,extra={}){m.objective({id,text,condition,...extra});return id}
function opt(m,id,text,condition){return obj(m,id,text,condition,{optional:true,atEnd:true})}
function fail(m,id,text,condition){return obj(m,id,text,condition,{failure:true})}
function mark(m,id,text,region){m.marker({id,text,region});}
function cp(m,id,condition,text){m.trigger({id:`checkpoint-${id}`,condition,actions:[checkpoint(id),warn(text)],speaker:'Operations'});}
function base(m,f,owner=1,advanced=1,origin=[20,104],prefix='home',supply=true){
 const [x,y]=origin;
 add(m,`${prefix}-hq`,'hq',owner,x,y);add(m,`${prefix}-power`,'power',owner,x-8,y-1);
 if(supply){add(m,`${prefix}-supply`,'supply',owner,x+6,y-8);add(m,`${prefix}-haulers`,`${f}.hauler`,owner,x+3,y-5,2)}
 add(m,`${prefix}-barracks`,'barracks',owner,x-7,y+7);add(m,`${prefix}-rig`,`${f}.rig`,owner,x-4,y+3);
 if(advanced>=2){add(m,`${prefix}-factory`,'factory',owner,x+8,y+7);add(m,`${prefix}-radar`,'radar',owner,x,y+11);add(m,`${prefix}-power-two`,'power',owner,x-9,y-6);add(m,`${prefix}-service`,air[f],owner,x+12,y-1)}
 if(advanced>=3){add(m,`${prefix}-tech`,'tech',owner,x+15,y+8);add(m,`${prefix}-power-three`,'power',owner,x-9,y+3);add(m,`${prefix}-depot`,'depot',owner,x+15,y+13)}
}
function army(m,f,owner=1,tier=1,origin=[27,103],prefix='starting'){
 const [x,y]=origin;add(m,`${prefix}-rifles`,`${f}.rifle`,owner,x,y,4);add(m,`${prefix}-at`,`${f}.at`,owner,x+2,y+5,2);add(m,`${prefix}-recon`,`${f}.recon`,owner,x-3,y-6);add(m,`${prefix}-engineers`,`${f}.engineer`,owner,x-8,y+3,2);
 if(tier>=2){add(m,`${prefix}-armor`,`${f}.tank`,owner,x+5,y+3,2);add(m,`${prefix}-aa`,`${f}.aa`,owner,x+5,y-5);add(m,`${prefix}-repair`,`${f}.repair`,owner,x-2,y+8)}
 if(tier>=3){add(m,`${prefix}-artillery`,`${f}.artillery`,owner,x+9,y+2);add(m,`${prefix}-launcher`,`${f}.launcher`,owner,x+9,y+8)}
}
function enemy(m,f,tier=2){base(m,f,2,tier,[106,22],'enemy');add(m,'enemy-guard',`${f}.rifle`,2,97,37,3);add(m,'enemy-at',`${f}.at`,2,112,40,2);add(m,'enemy-hard-guard',`${f}.tank`,2,100,41,1,HARD)}
function pressure(m,f,times,target='base',owner=4,prefix=''){
 times.forEach((seconds,i)=>{
 const x=i%2?83:100,y=i%2?20:52;
 m.trigger({id:`${prefix}pressure-warning-${i+1}`,condition:timer(sec(Math.max(10,seconds*.8-25))),speaker:'Watch',actions:[warn(`Hostile column ${i+1} is approaching ${i%2?'the northwestern pass':'the eastern road'}. Expected entry varies with difficulty; screen the marked approach.`)]});
 m.trigger({id:`${prefix}pressure-${i+1}`,condition:waveTimer(sec(seconds)),actions:[spawn(`${prefix}wave-${i+1}-rifles`,`${f}.rifle`,owner,p(x,y),3),spawn(`${prefix}wave-${i+1}-car`,`${f}.car`,owner,p(x+4,y+3),1,NORMAL_UP),spawn(`${prefix}wave-${i+1}-armor`,`${f}.tank`,owner,p(x-3,y+5),1,HARD),attack(owner,target),warn(`Column ${i+1} has entered. Its approach is ${i%2?'northwest':'east'}.`)],speaker:'Watch',wave:`Finite scripted enemy column ${i+1}: 3 rifles; normal adds 1 car, hard also adds 1 tank. Only enemy timing is scaled. Entry (${x},${y}).`});
 });
}
function lossOfBase(m,f){fail(m,'no-command-assets','Lose all HQs, production structures and engineering rigs.',all(noneOf('hq',1),noneOf('barracks',1),noneOf('factory',1),noneOf(air[f],1),noneOf(`${f}.rig`,1)));}
function recovery(m,tag,type,region,x,y,count=1){add(m,tag,type,3,x,y,count);m.trigger({id:`recover-${tag}`,condition:all(regionEntered(region,1),tagAlive(tag)),actions:[recover(tag,1),warn(`Contact restored: ${tag.replaceAll('-',' ')} now follows your orders.`)],speaker:'Field team'});mark(m,tag,'Recover allied team',region);}
function relays(m,kind='radar',owner=4){for(const [i,x,y] of [[1,50,82],[2,85,65],[3,103,39]]){add(m,`relay-${i}`,kind,owner,x,y);add(m,`relay-guard-${i}`,`${enemyFaction[m.meta.faction]}.rifle`,owner,x+5,y-3,2);mark(m,`relay-${i}`,`Military relay ${i}`,`site${i}`)}}
function allRelays(owner=1){return all(...[1,2,3].map(i=>tagOwned(`relay-${i}`,owner)))}
function productionTargets(m,f){
 add(m,'forward-command','hq',4,83,20);add(m,'forward-factory','factory',4,76,24);add(m,'forward-barracks','barracks',4,82,29);add(m,'forward-power','power',4,88,27);add(m,'forward-guard',`${f}.tank`,4,83,34,2);
 return all(...['enemy-hq','enemy-factory','enemy-barracks','enemy-service','forward-command','forward-factory','forward-barracks'].map(tag=>neutralized(tag,1)));
}
const lessons={
 US:['Ground fundamentals and allied recovery.','Infantry screens and early aircraft escort.','Recon before aircraft; continuous relay control.','Air service slots, replacement homes and paid repair.','Airlift support for several ground fronts.','Synchronize ground/air assault and preserve supply access.'],
 IR:['Ground observer positioning.','Drone sight, recall and launch-vehicle escort.','Expand before finite supplies run out.','Mixed defenses and service capacity.','Bank missile charges against finite interception.','Screen artillery with ground units and observer sight.'],
 SY:['Small squads, cover and recovery.','Technical mobility and finite salvage.','Concealment and recon counters.','Safehouse preparation and threatened exits.','Protect interruptible engineers and sabotage teams.','Combine mortar/rocket threats and temporary raids.'],
 SA:['Mechanized formation fundamentals.','AA cover and a visible paid-repair budget.','Split protection across resource positions.','Mobile interceptors, deployment and charge limits.','Relocate under indirect fire; protect repair support.','Move coverage forward and maintain supply corridors.'],
};
const briefings={
 US:[
 'Reach the two isolated Ranger teams west and east of the junction. Build a supply center and deliver cargo. Recovering their original squads transfers control; it does not duplicate them. An intact rig is stranded at the old workshop.',
 'Three marked haulers must cross the valley. Move them through either the western approach or the eastern approach and on to the exit depot. At least one must arrive; preserve all three for the optional objective. You have an early airfield and one gunship, with standard service and costs.',
 'Capture both marked military radars with engineers, then continuously hold either one for four minutes. Keep recon ahead of aircraft. Losing a captured radar resets only its hold timer, not the capture achievement.',
 'Two airfields are exposed. Keep at least one operational until twelve minutes have elapsed. Shift service assignments and protect power. Evacuate the marked wing to the backup site after it has needed paid repairs and has completed service.',
 'Three command relays coordinate the hostile line. Destroy or capture all three in any order. An airlift can bring infantry to an exposed flank, but it cannot capture buildings by itself. Preserve every transport you deploy.',
 'Destroy or capture the command and production structures of two bases, while holding both marked sections of the supply corridor. A live strategic site operates under normal energy, sight and cost rules: neutralize it before it actually launches for the optional objective.'
 ],
 IR:[
 'Establish supply and put a recon team on the forward observation position. Keep it stationary long enough to observe the road. The original recon team is irreplaceable for the optional objective, even though replacement scouts remain available.',
 'Escort both marked launch vehicles to the depot. Two starting drones provide sight; send both through at least one complete service cycle and keep them alive. Missiles, drones and repair all keep their standard costs.',
 'The starting field contains only 6,000 credits. Secure both expansion positions before that finite field empties. This is the only reduced starting-field budget. Capture both military supply stations as an optional achievement.',
 'Three dispersed service sites support the network. Keep at least two continuously operational for twelve minutes; disabled sites interrupt the hold; low power slows service by the normal rules. Do not lose a drone after emergency service loss. Protect the approaches instead of relying entirely on aircraft.',
 'Neutralize three military outposts. Launchers can store charges, but every missile still costs credits. Complete the operation with at most 1,200 credits spent on missiles. Screens and artillery remain available when a target has interception.',
 'Break the layered eastern line and destroy or capture its command base. Keep the original observation teams alive and deployed at two forward positions when you finish. Drone sight alone cannot absorb a ground counterattack.'
 ],
 SY:[
 'A small coalition patrol has no production base. Reach the intact engineering rig, take control and construct a workshop economy. Two separated mechanic teams can also be recovered. These are existing allies, not free reinforcements.',
 'Escort four marked trucks through either branch to the far depot. One surviving truck is enough to keep the route open; every loss still reduces the convoy. Three marked hostile tanks carry a finite authored salvage opportunity; destroy them and collect at least 300 credits of salvage.',
 'Hold any two of the three marked expansion approaches continuously for three minutes. Enemy recon can reveal concealed scouts, so use cover with escape routes. Keep the marked scout concealed for one full minute before its observation mark is awarded.',
 'Keep both original safehouses and the original factory operational until ten minutes. Evacuate the marked threatened team from the forward safehouse area to the rear safe region. Transit preparation and exits obey normal rules; a ground evacuation is also valid.',
 'Capture all three communication buildings; destroying one loses the operation. Protect engineers and use sabotage to open a window. The forward factory is optional, but it must survive under your ownership at victory.',
 'Two production bases block the supply route. Neutralize their command and production buildings. Temporary raids remain paid, limited operations; finish without a canceled or blocked raid deployment. Normal combat losses still count in the debrief.'
 ],
 SA:[
 'Establish a supply center, deliver cargo and secure the marked assembly area. Preserve both original APCs. Use infantry and mobile cover together rather than feeding vehicles down a single lane.',
 'Escort the three marked trucks through both contested sectors, then to the depot. At least one must finish. Keep total paid repair spending at or below 700 credits for the optional objective; free hidden recovery is not provided.',
 'Control both separated supply positions simultaneously and build a second supply center. Hold both military stations simultaneously at victory for the optional objective. Leaving the main force unsupported opens the road to counters.',
 'Defend both outposts and the fixed interceptor battery for ten minutes. A marked enemy missile detachment has normal ammunition costs and reloads, and receives a timed attack order. Intercept at least one of its missiles without losing any original defended building for the optional objective.',
 'Capture all three relays while hostile artillery covers their approaches. Hull-down does not stop indirect fire. Keep the original Service vehicle alive, and protect engineers while they capture.',
 'Neutralize the command complex and its forward production base. Keep both connected, marked supply-route sections under control and maintain two supply centers at victory for the optional objective. The permanent road network can be contested but cannot be destroyed.'
 ],
};

export function campaignMissions(layouts){return layouts.filter(l=>l.faction).map(l=>{
 const f=l.faction,n=l.order,ef=enemyFaction[f];
 const m=new MissionBuilder({id:l.missionId,title:l.missionTitle,map_id:l.map.id,faction:f,mode:'campaign',order:n,operation:`Operation ${operations[f]}`,theater:'The fictional Aster Reach',lesson:lessons[f][n-1],designRef:`19.${{US:2,IR:3,SY:4,SA:5}[f]}`,briefing:briefings[f][n-1],debrief:`${l.missionTitle}: the operational goal is complete. Review losses, objective state and recorded orders before continuing Operation ${operations[f]}.`,rules_notice:'Scenario: authored starting assets, finite warned enemy columns, and mission-specific objectives. Standard unit stats, Supply, paid production, service, power, capture and combat rules apply. Difficulty changes enemy budgets, composition and entry timing only.',briefingLines:[[commanders[f],briefings[f][n-1]],['Operations',lessons[f][n-1]]],victoryLines:[[commanders[f],`${l.missionTitle} is complete. Keep the route secure; the next operation will depend on what we learned here.`]],defeatLines:[[commanders[f],'We can no longer meet this operation’s requirements. Return to the last checkpoint and change the approach.']]});
 m.player({id:1,faction:f,name:factions[f],team:1,controller:'human',credits:cr(n===1?6000:8000)}).player({id:2,faction:ef,name:'Vanguard Garrison',team:2,controller:'ai',ai:'normal',credits:cr(1200+n*500)}).player({id:3,faction:f,name:'Isolated Allied Teams',team:1,controller:'script',credits:0}).player({id:4,faction:ef,name:'Vanguard Detachments',team:2,controller:'script',credits:cr(4500)});
 if(!(f==='SY'&&n===1)){base(m,f,1,n===1?1:n>=4?3:2,[20,104],'home',n!==1);army(m,f,1,n===1?1:2);lossOfBase(m,f)}else{army(m,f,1,1);fail(m,'lost-patrol','Lose the patrol before recovering the rig.',all(tagDestroyed('starting-rifles'),tagDestroyed('starting-engineers'),noneOf('SY.rig',1)));fail(m,'lost-recovery-rig','Lose the irreplaceable recovery rig before the workshop is established.',all(tagDestroyed('recovered-rig'),noneOf('factory',1)));}
 enemy(m,ef,n>=4?3:2);
 const waveTimes=n===1?[240,480]:n===4?[150,300,450,600]:[180,360,540];pressure(m,ef,waveTimes);
 if(f==='US')switch(n){
 case 1:
 recovery(m,'ranger-west','US.rifle','recovery1',39,83);recovery(m,'ranger-east','US.rifle','recovery2',77,82);recovery(m,'intact-rig','US.rig','recoveryRig',49,62);
 obj(m,'supply','Build a supply center and deliver two cargo loads.',all(countType('supply',1,1),eventCount('cargo_delivered',{owner:1,count:2})));
 obj(m,'reconnect','Reconnect both isolated Ranger teams.',all(tagOwned('ranger-west',1),tagOwned('ranger-east',1)));opt(m,'engineering-rescue','Recover the intact engineering rig and keep it alive.',tagOwned('intact-rig',1));
 fail(m,'lost-rangers','Lose either isolated team before reconnecting it.',any(tagDestroyed('ranger-west'),tagDestroyed('ranger-east')));cp(m,'first-contact',any(tagOwned('ranger-west',1),tagOwned('ranger-east',1)),'One team is back on net. Reconnect the other team and finish the supply line.');break;
 case 2:
 add(m,'convoy','US.hauler',1,17,113,3);add(m,'escort-gunship','US.gunship',1,31,91);
 obj(m,'branch','Escort at least one convoy truck through either marked branch.',any(tagInRegion('convoy','site1'),tagInRegion('convoy','site2')));obj(m,'exit','Deliver at least one convoy truck to the exit depot.',all(objectiveDone('branch'),tagInRegion('convoy','exit')));opt(m,'all-trucks','Preserve all three original convoy trucks.',tagAlive('convoy',{count:3}));fail(m,'convoy-lost','Lose all convoy trucks.',tagDestroyed('convoy'));cp(m,'valley-entry',objectiveDone('branch'),'The convoy has cleared a branch. Keep aircraft service capacity ready for the final stretch.');break;
 case 3:
 relays(m);m.initial=m.initial.filter(s=>!s.tag.endsWith('-3'));m.markers=m.markers.filter(mark=>mark.id!=='relay-3');
 obj(m,'capture-relays','Capture both marked military radars.',all(tagOwned('relay-1',1),tagOwned('relay-2',1)));obj(m,'relay-hold','Hold either captured radar continuously for four minutes.',all(objectiveDone('capture-relays'),any(holdFor(tagOwned('relay-1',1),240),holdFor(tagOwned('relay-2',1),240))));opt(m,'scout-preserved','Finish without losing a scout.',eventCount('destroyed',{owner:1,type:'US.recon',count:0,compare:'at_most'}));fail(m,'relay-destroyed','Lose either required relay to destruction.',any(tagDestroyed('relay-1'),tagDestroyed('relay-2')));cp(m,'two-relays',objectiveDone('capture-relays'),'Both relays are captured. The four-minute hold is now the priority.');break;
 case 4:
 add(m,'backup-airfield','US.airfield',1,50,82);add(m,'backup-power','power',1,45,87);add(m,'wing-one','US.strike',1,32,94);add(m,'wing-two','US.strike',1,34,94);add(m,'escort-fighter','US.fighter',1,33,90);
 obj(m,'airfields-survive','Keep at least one airfield operational through twelve minutes.',all(timer(min(12)),any(tagOperational('home-service'),tagOperational('backup-airfield'))));fail(m,'airfields-lost','Lose both original airfields.',all(tagDestroyed('home-service'),tagDestroyed('backup-airfield')));opt(m,'wing-evacuated','Evacuate both marked aircraft to the backup site, service each and repair battle damage on the wing.',all(...['wing-one','wing-two'].map(t=>all(tagInRegion(t,'site1'),eventCount('aircraft_serviced',{tag:t,owner:1,count:1}))),any(...['wing-one','wing-two'].map(t=>eventValue('repair_spent',{tag:t,owner:1,amount:1})))));cp(m,'six-minute-line',timer(min(6)),'Halfway through the pressure window. Reassign homes before an airfield is lost.');break;
 case 5:
 relays(m);add(m,'airlift','US.airlift',1,32,94);obj(m,'disable-relays','Destroy or capture all three command relays in any order.',all(...[1,2,3].map(i=>neutralized(`relay-${i}`,1))));opt(m,'no-transport-loss','Finish without losing any airlift transport.',eventCount('destroyed',{owner:1,type:'US.airlift',count:0,compare:'at_most'}));cp(m,'first-front',any(...[1,2,3].map(i=>neutralized(`relay-${i}`,1))),'One command link is down. Move infantry support to whichever front opens next.');break;
 case 6:{
 const bases=productionTargets(m,ef);add(m,'enemy-strategic','strategic',2,96,12);add(m,'enemy-site-power','power',2,90,15,2);add(m,'assault-strike','US.strike',1,32,94,2);
 obj(m,'two-bases','Neutralize both production bases while holding both supply-corridor sections.',all(bases,regionHeld('corridor1',1),regionHeld('corridor2',1)));opt(m,'site-before-launch','Neutralize the strategic site before any launch from it.',all(neutralized('enemy-strategic',1),eventCount('strategic_activated',{owner:2,tag:'enemy-strategic',count:0,compare:'at_most'})));cp(m,'forward-base',neutralized('forward-command',1),'The forward command post is neutralized. Keep both supply sections guarded while the main base falls.');break;}
 }
 if(f==='IR')switch(n){
 case 1:
 obj(m,'observation-base','Establish supply and observe the first ridge for twenty seconds.',all(countType('supply',1,1),eventCount('cargo_delivered',{owner:1,count:2}),holdFor(all({...regionEntered('site1',1),type:'IR.recon'},regionHeld('site1',1)),20)));opt(m,'recon-survives','Keep the original recon team alive.',tagAlive('starting-recon'));cp(m,'observation-contact',{...regionEntered('site1',1),type:'IR.recon'},'Your observers have reached the ridge. Protect their position and complete the supply link.');break;
 case 2:
 add(m,'launch-convoy','IR.launcher',1,14,115,2);add(m,'survey-one','IR.isr',1,31,91);add(m,'survey-two','IR.isr',1,34,91);
 obj(m,'launchers-arrive','Escort both marked launch vehicles to the exit depot.',tagInRegion('launch-convoy','exit',{count:2}));opt(m,'recover-drones','Keep and fully service both starting drones.',all(tagAlive('survey-one'),tagAlive('survey-two'),eventCount('aircraft_serviced',{tag:'survey-one',count:1}),eventCount('aircraft_serviced',{tag:'survey-two',count:1})));fail(m,'launchers-lost','Lose either marked launch vehicle.',eventCount('destroyed',{tag:'launch-convoy',owner:1,count:1}));cp(m,'launchers-midway',tagInRegion('launch-convoy','site2',{count:2}),'Both launchers have reached the middle road. Recall drones before they exhaust their safe return window.');break;
 case 3:
 obj(m,'two-fields','Control both marked expansion fields before the starting field empties.',all(regionHeld('site1',1),regionHeld('site2',1)));opt(m,'two-stations','Own both military supply stations at victory.',stations(1,2));fail(m,'field-empty','The starting field is exhausted before both expansions are secured.',fieldRemaining(l.map.fields[0].id,0,'at_most'));cp(m,'first-expansion',any(regionHeld('site1',1),regionHeld('site2',1)),'One expansion is secure. Split protection carefully: the starting reserve is finite.');break;
 case 4:
 add(m,'network-two','IR.drone_hub',1,50,82);add(m,'network-three','radar',1,85,65);add(m,'network-power','power',1,45,87);add(m,'network-power-three','power',1,89,61);add(m,'survey-one','IR.isr',1,32,94);add(m,'network-strike','IR.strike',1,34,94,2);
 obj(m,'network-hold','Keep any two of the three network sites operational continuously for twelve minutes.',holdFor(atLeast(2,tagOperational('home-service'),tagOperational('network-two'),tagOperational('network-three')),720));fail(m,'network-destroyed','Lose two original network sites.',atLeast(2,tagDestroyed('home-service'),tagDestroyed('network-two'),tagDestroyed('network-three')));opt(m,'no-emergency-loss','Finish without losing a drone or losing its service capacity.',all(...['IR.isr','IR.fighter','IR.strike','IR.gunship'].map(type=>eventCount('destroyed',{owner:1,type,count:0,compare:'at_most'})),eventCount('service_lost',{owner:1,count:0,compare:'at_most'})));cp(m,'network-half',timer(min(6)),'Six minutes elapsed. An inoperative site can reset the continuous hold; check the objective timer.');break;
 case 5:
 relays(m,'outpost');add(m,'volley-launchers','IR.launcher',1,33,94,2);add(m,'battery','abm',4,85,70);add(m,'battery-power','power',4,90,65);
 obj(m,'outposts-disabled','Destroy or capture all three marked military outposts.',all(...[1,2,3].map(i=>neutralized(`relay-${i}`,1))));opt(m,'missile-budget','Spend at most 1,200 credits on missiles.',eventValue('missile_spent',{owner:1,amount:cr(1200),compare:'at_most'}));cp(m,'first-outpost',any(...[1,2,3].map(i=>neutralized(`relay-${i}`,1))),'One outpost is neutralized. Remaining missile budget is a ceiling, not a supply grant.');break;
 case 6:
 relays(m,'turret');add(m,'observer-west','IR.recon',1,17,109);add(m,'observer-east','IR.recon',1,17,111);add(m,'network-drone','IR.isr',1,32,94);add(m,'assault-artillery','IR.artillery',1,37,103,2);add(m,'assault-launcher','IR.launcher',1,38,109);
 obj(m,'command-base','Neutralize the command base after breaking two outer defense positions.',all(neutralized('enemy-hq',1),atLeast(2,...[1,2,3].map(i=>neutralized(`relay-${i}`,1)))));opt(m,'observer-network','Keep both original observers alive at the two forward observation sites.',all(tagInRegion('observer-west','site1'),tagInRegion('observer-east','site2')));cp(m,'outer-line',atLeast(2,...[1,2,3].map(i=>neutralized(`relay-${i}`,1))),'Two outer positions have fallen. Reposition observers before the command-base assault.');break;
 }
 if(f==='SY')switch(n){
 case 1:
 recovery(m,'recovered-rig','SY.rig','recoveryRig',49,62);recovery(m,'mechanics-west','SY.engineer','recovery1',39,83,2);recovery(m,'mechanics-east','SY.engineer','recovery2',77,82,2);
 obj(m,'rig-recovered','Recover the intact engineering rig.',tagOwned('recovered-rig',1));obj(m,'workshop-base','Establish HQ, supply, barracks and a vehicle workshop, then deliver cargo.',all(countType('hq',1,1),countType('supply',1,1),countType('barracks',1,1),countType('factory',1,1),eventCount('cargo_delivered',{owner:1,count:1})));opt(m,'mechanic-teams','Recover both separated mechanic teams and keep them alive.',all(tagOwned('mechanics-west',1,2),tagOwned('mechanics-east',1,2)));cp(m,'rig-contact',objectiveDone('rig-recovered'),'The rig is yours. Establish the HQ first; regular prerequisites and construction costs remain in force.');break;
 case 2:
 add(m,'trail-trucks','SY.hauler',1,14,115,4);add(m,'marked-salvage','US.tank',4,50,82,3);add(m,'technical-screen','SY.car',1,33,94,2);
 obj(m,'branch','Escort a truck through either branch.',any(tagInRegion('trail-trucks','site1'),tagInRegion('trail-trucks','site2')));obj(m,'trail-open','Deliver a marked truck to the exit depot.',all(objectiveDone('branch'),tagInRegion('trail-trucks','exit')));opt(m,'limited-salvage','Collect at least 300 credits of salvage, from hostile vehicle wrecks.',stat(1,'salvage',cr(300)));fail(m,'trail-trucks-lost','Lose all four marked trucks.',tagDestroyed('trail-trucks'));cp(m,'trail-branch',objectiveDone('branch'),'The convoy has cleared one route. Recover exposed salvage only while the trucks have cover.');m.exception('Three marked hostile tanks are a finite normal salvage source. No mission action creates or replenishes crates.');break;
 case 3:
 add(m,'concealed-scout','SY.recon',1,42,111);obj(m,'two-approaches','Hold any two approaches continuously for three minutes.',holdFor(atLeast(2,regionHeld('site1',1),regionHeld('site2',1),regionHeld('site3',1)),180));obj(m,'scout-mark','Optional: keep the marked scout concealed for one uninterrupted minute.',holdFor(tagConcealed('concealed-scout'),60),{optional:true});cp(m,'approach-held',any(regionHeld('site1',1),regionHeld('site2',1),regionHeld('site3',1)),'One approach is held. A second must remain secure for the full three-minute count.');break;
 case 4:
 add(m,'safehouse-front','SY.safehouse',1,50,82);add(m,'safehouse-rear','SY.safehouse',1,37,105);add(m,'evacuation-team','SY.rifle',1,50,85,2);
 obj(m,'open-doors','Keep both safehouses and the factory operational through ten minutes.',all(timer(min(10)),tagOperational('safehouse-front'),tagOperational('safehouse-rear'),tagOperational('home-factory')));fail(m,'doors-lost','Lose either original safehouse or the original factory.',any(tagDestroyed('safehouse-front'),tagDestroyed('safehouse-rear'),tagDestroyed('home-factory')));opt(m,'evacuation','Evacuate both marked squads to the rear safe region.',tagInRegion('evacuation-team','safe',{count:2}));cp(m,'evacuation-contact',tagInRegion('evacuation-team','safe',{count:2}),'The team has reached the rear. Keep the original network operational until the pressure window closes.');break;
 case 5:
 relays(m);add(m,'capture-factory','factory',4,50,88);obj(m,'communications','Capture all three communication buildings.',allRelays());opt(m,'factory-captured','Capture the marked factory and preserve it under your control.',tagOwned('capture-factory',1));fail(m,'communications-destroyed','Destroy any required communication building.',any(...[1,2,3].map(i=>tagDestroyed(`relay-${i}`))));cp(m,'first-communications',any(...[1,2,3].map(i=>tagOwned(`relay-${i}`,1))),'First relay secured. Protect engineers during every capture channel.');break;
 case 6:{const bases=productionTargets(m,ef);add(m,'raid-site','strategic',1,37,95);add(m,'raid-safehouse','SY.safehouse',1,50,82);add(m,'raid-power','power',1,11,116);obj(m,'road-cleared','Neutralize both blocking production bases.',bases);opt(m,'no-lost-raid','Finish without a canceled or blocked temporary-raid deployment.',all(eventCount('raid_canceled',{owner:1,count:0,compare:'at_most'}),eventCount('raid_exit_blocked',{owner:1,count:0,compare:'at_most'})));cp(m,'forward-road',neutralized('forward-command',1),'The forward road is open. Protect any safehouse preparing a raid while pressure shifts to the main base.');break;}
 }
 if(f==='SA')switch(n){
 case 1:
 add(m,'original-apcs','SA.apc',1,31,99,2);obj(m,'arrival-base','Establish supply, deliver cargo and hold the assembly area for thirty seconds.',all(countType('supply',1,1),eventCount('cargo_delivered',{owner:1,count:2}),regionHeld('site1',1,1,30)));opt(m,'apcs-preserved','Keep both original APCs alive.',tagAlive('original-apcs',{count:2}));cp(m,'assembly-contact',regionHeld('site1',1),'The assembly area is clear. Hold it while supply comes online.');break;
 case 2:
 add(m,'shield-convoy','SA.hauler',1,14,115,3);obj(m,'sector-one','Escort the convoy through the first contested sector.',tagInRegion('shield-convoy','site1'));obj(m,'sector-two','Escort it through the second contested sector.',all(objectiveDone('sector-one'),tagInRegion('shield-convoy','site2')));obj(m,'convoy-exit','Deliver a marked truck to the exit depot.',all(objectiveDone('sector-two'),tagInRegion('shield-convoy','exit')));opt(m,'repair-budget','Spend no more than 700 credits on repairs.',eventValue('repair_spent',{owner:1,amount:cr(700),compare:'at_most'}));fail(m,'convoy-destroyed','Lose all marked convoy trucks.',tagDestroyed('shield-convoy'));cp(m,'first-sector',objectiveDone('sector-one'),'First sector clear. Move the AA screen before exposing the next convoy segment.');break;
 case 3:
 obj(m,'distant-supply','Control both marked supply positions and operate two supply centers.',all(regionHeld('site1',1),regionHeld('site2',1),countType('supply',1,2)));opt(m,'stations-together','Hold both military stations simultaneously at victory.',stations(1,2));cp(m,'first-depot',any(regionHeld('site1',1),regionHeld('site2',1)),'One depot approach is secure. Do not leave its protection behind when taking the second.');break;
 case 4:
 add(m,'outpost-west','outpost',1,50,82);add(m,'outpost-east','outpost',1,85,65);add(m,'fixed-battery','abm',1,66,65);add(m,'battery-power','power',1,61,69);add(m,'mobile-aegis','SA.mobile_abm',1,57,83);add(m,'marked-missile-wave','SY.launcher',4,100,52,2);
 m.trigger({id:'marked-missile-warning',condition:timer(sec(150)),speaker:'Watch',actions:[warn('The marked eastern missile detachment advances at three minutes. Deploy interceptors with charged magazines; interception spends credits.')]});m.trigger({id:'marked-missile-advance',condition:timer(sec(180)),actions:[attack(4,'site2')]});m.trigger({id:'marked-missile-target',condition:timer(sec(181)),actions:[attackTag(4,'marked-missile-wave','outpost-east')]});
 obj(m,'intercept-window','Keep both outposts and the fixed battery operational through ten minutes.',all(timer(min(10)),tagOperational('outpost-west'),tagOperational('outpost-east'),tagOperational('fixed-battery')));fail(m,'defended-assets-lost','Lose either original outpost or the fixed battery.',any(tagDestroyed('outpost-west'),tagDestroyed('outpost-east'),tagDestroyed('fixed-battery')));opt(m,'clean-interception','Intercept a missile from the marked detachment without losing an original defended building.',all(eventCount('missile_intercepted',{owner:4,count:1}),...['home-hq','home-power','home-supply','home-barracks','home-factory','home-radar','home-service','outpost-west','outpost-east','fixed-battery'].map(t=>tagAlive(t))));cp(m,'window-half',timer(min(5)),'Half the defense window remains. Interceptor magazines and paid reloads are finite.');break;
 case 5:
 relays(m);add(m,'indirect-battery','SY.artillery',4,100,52,2);m.trigger({id:'indirect-orders',condition:timer(sec(30)),actions:[attack(4,'site2')]});obj(m,'three-positions','Capture all three marked relays.',allRelays());opt(m,'service-preserved','Keep the original Service vehicle alive.',tagAlive('starting-repair'));fail(m,'relay-destroyed','Lose any required relay to destruction.',any(...[1,2,3].map(i=>tagDestroyed(`relay-${i}`))));cp(m,'first-position',any(...[1,2,3].map(i=>tagOwned(`relay-${i}`,1))),'A relay is secured. Move support out of indirect-fire lanes before the next capture.');break;
 case 6:{const bases=productionTargets(m,ef);add(m,'advance-service','SA.repair',1,35,94);add(m,'advance-aegis','SA.mobile_abm',1,38,104);obj(m,'shieldline','Neutralize the command complex and forward production base.',bases);opt(m,'connected-routes','Keep both permanent supply corridors controlled and maintain two supply centers.',all(regionHeld('corridor1',1),regionHeld('corridor2',1),countType('supply',1,2)));cp(m,'forward-shield',neutralized('forward-command',1),'The forward base is down. Establish coverage before the final relocation.');break;}
 }
 m.exception('All mission starting assets are listed in the opening state. Allied recovery transfers existing actors and preserves caps. Scripted enemy columns are finite, announced scenario exceptions; they are not paid AI production.');
 return {builder:m,layout:l};
});}

export function tutorialMissions(layouts){
 const titles=['Give an Order','Operate a Base','Read the Counter','Defend the Sky','Command a Match'];
 const instructions=[
  'Select the marked infantry and move to the training marker. Attack the hostile target, stop at the second marker, assign a control group and set a barracks rally point. Try a blocked order to learn where the rejection appears. The world objectives verify movement, combat and production; selection, groups, rally and rejection prompts are local input lessons.',
  'Gather cargo, protect your haulers, construct power and produce a squad. A strike team threatens the old HQ: preserve the factory, purchase an emergency rig there after the original HQ falls, then rebuild. Use paid repairs on a damaged vehicle. Scenario starting power is deliberately insufficient; build generation before adding more consumers.',
  'Rifles punish anti-armor infantry, cars threaten exposed rifles, and anti-armor teams stop heavier vehicles. Move rifle squads into cover, defeat both marked targets, reveal the covered scout with recon and unload two squads from the APC at the training position.',
  'Service the marked aircraft, defeat the hostile aircraft with ground AA or fighters, and intercept the tactical missile detachment. Leave the marked danger area when warned. Ground AA does not intercept tactical missiles; the fixed ABM does, using paid finite charges.',
  'Win a short battle using standard unit, economy, fog and combat rules. Build forces and neutralize the opposing command and production buildings. Practice your chosen faction’s command ability once; finish by reviewing the debrief and replay. Each faction’s authored training assets and ability instructions use its normal roster.'
 ];
 return titles.map((title,i)=>{
 const n=i+1,l=layouts.find(l=>l.faction==='US'&&l.order===[1,4,5,6,2][i]),id=`tutorial-${n}-${title.toLowerCase().replaceAll(' ','-')}`;
 const m=new MissionBuilder({id,title,map_id:l.map.id,faction:'US',mode:'tutorial',order:n,lesson:title,designRef:'18.4',briefing:instructions[i],debrief:`${title} complete. Review the objective record and replay before moving on. Tutorials never gate multiplayer.`,rules_notice:'Training scenario. Standard gameplay rules; authored initial assets and finite hostile exercises. Local selection/control-group/interface steps need the tutorial presentation controller and are not claimed as Go-verified input.',briefingLines:[['Instructor Vale',instructions[i]]],victoryLines:[['Instructor Vale','Exercise complete. The same rules apply in skirmish and multiplayer.']],defeatLines:[['Instructor Vale','Restart the checkpoint and keep the required training assets alive.']]});
 m.player({id:1,faction:'US',name:'Trainee',team:1,controller:'human',credits:cr(8000)}).player({id:2,faction:'IR',name:'Training Opposition',team:2,controller:n===5?'ai':'script',ai:n===5?'easy':'',credits:cr(2500)}).player({id:3,faction:'US',name:'Training Stores',team:1,controller:'script',credits:0}).player({id:4,faction:'SY',name:'Exercise Detachment',team:2,controller:'script',credits:cr(3000)});
 base(m,'US',1,n===1?1:3);army(m,'US',1,n>=3?2:1);lossOfBase(m,'US');
 if(n===1){
  m.marker({id:'training-move',text:'First movement marker',region:'training-move',objective:'move'});m.marker({id:'order-drill',text:'Second training marker',region:'site1',objective:'production'});
  add(m,'order-target','IR.rifle',2,49,82);obj(m,'move','Move the marked infantry into the training area.',tagInRegion('starting-rifles','training-move'));
  obj(m,'attack','Destroy the hostile training target.',all(objectiveDone('move'),tagDestroyed('order-target')));obj(m,'production','Produce a new rifle squad, then move the original group into the second marker.',all(eventCount('unit_ready',{owner:1,type:'US.rifle',count:1}),tagInRegion('starting-rifles','site1')));
  fail(m,'original-order-team-lost','Lose every member of the marked order-training group.',tagDestroyed('starting-rifles'));
  opt(m,'original-team','Preserve all four original rifle squads.',tagAlive('starting-rifles',{count:4}));cp(m,'first-order',objectiveDone('move'),'Movement confirmed. Attack the target and follow the remaining control prompts.');
  m.presentationSteps=[{id:'select',kind:'select',text:'Select one unit, then drag-select the squad.'},{id:'move',kind:'move',objective:'move'},{id:'attack',kind:'attack',objective:'attack'},{id:'stop',kind:'stop',text:'Issue Stop and watch the order marker disappear.'},{id:'group',kind:'control_group',text:'Assign a control group and recall it.'},{id:'rally',kind:'rally',text:'Set a barracks rally point before producing a squad.'},{id:'blocked',kind:'rejected_order',text:'Select your rig, choose a power station, and try placing it over your HQ. Read the occupied-site explanation; the rejected placement spends no credits.'}];
 }else if(n===2){
  // Initial three power stations otherwise over-supply this lesson. Removing
  // the extra generators creates real low power without altering rules.
  m.initial=m.initial.filter(s=>!['home-power-two','home-power-three'].includes(s.tag));
  add(m,'old-hq-threat','IR.tank',2,50,82,2);m.trigger({id:'hq-pressure-warning',condition:timer(sec(90)),speaker:'Instructor',actions:[warn('The old HQ will be attacked at two minutes. Keep the factory and 4,700 credits for an emergency rig plus replacement HQ safe.')]});m.trigger({id:'hq-pressure',condition:timer(sec(120)),actions:[attack(2,'base')]});m.trigger({id:'hq-targeted-raid',condition:timer(sec(121)),actions:[attackTag(2,'old-hq-threat','home-hq')]});
  obj(m,'base-cycle','Deliver cargo, build a power station and produce a squad.',all(eventCount('cargo_delivered',{owner:1,count:2}),eventCount('construction_complete',{owner:1,type:'power',count:1}),eventCount('unit_ready',{owner:1,type:'US.rifle',count:1})));
  obj(m,'rebuild','Replace the original HQ after its loss, using an emergency rig produced by the factory.',all(tagDestroyed('home-hq'),eventCount('emergency_rig_ready',{owner:1,count:1}),eventCount('construction_complete',{owner:1,type:'hq',count:1}),countType('hq',1,1)));
  obj(m,'repair','Spend credits repairing actual battle damage.',eventValue('repair_spent',{owner:1,amount:1}));opt(m,'hauler-protected','Keep both original haulers alive.',tagAlive('home-haulers',{count:2}));cp(m,'base-cycle',objectiveDone('base-cycle'),'The base cycle works. Protect the factory during the HQ attack. Purchase its 1,200-credit emergency rig, then construct a 3,500-credit replacement HQ and use paid recovery on damaged units.');
 }else if(n===3){
  m.marker({"id":"transport-assembly","text":"Transport boarding area","region":"training-move","objective":"transport"});m.marker({"id":"transport-destination","text":"Forward unload marker","region":"site1","objective":"transport"});m.marker({"id":"counter-cover","text":"Infantry cover marker","region":"training-cover","objective":"cover"});
  add(m,'counter-infantry','IR.at',2,50,82,3);add(m,'counter-armor','IR.tank',2,85,65);add(m,'covered-observer','SY.recon',4,43,111);add(m,'training-apc','US.apc',1,33,94);add(m,'transport-team','US.rifle',1,30,94,2);
  obj(m,'cover','Move two original rifle squads into the marked cover.',tagInRegion('starting-rifles','training-cover',{count:2}));obj(m,'counters','Defeat the anti-armor infantry and the tank.',all(tagDestroyed('counter-infantry'),tagDestroyed('counter-armor')));obj(m,'detection','Find and defeat the covered scout.',tagDestroyed('covered-observer'));obj(m,'transport','Bring both marked transport squads to the forward marker outside a carrier.',tagInRegion('transport-team','site1',{count:2}));fail(m,'transport-team-lost','Lose either marked transport squad before delivery.',eventCount('destroyed',{owner:1,tag:'transport-team',count:1}));
  opt(m,'apc-survives','Preserve the training APC.',tagAlive('training-apc'));cp(m,'cover-lesson',objectiveDone('cover'),'Cover confirmed. Use recon against concealment and unload infantry before asking it to capture or fire.');
  m.presentationSteps=[{id:'board',kind:'board',text:'Board both marked squads into the APC.'},{id:'unload',kind:'unload',text:'Move the APC and unload at the forward marker.',objective:'transport'}];
 }else if(n===4){
  m.marker({"id":"exercise-warning","text":"Exercise warning marker","region":"site1","objective":"enter-mark"});m.marker({"id":"exercise-return","text":"Return to base","region":"base","objective":"evade"});
  add(m,'training-aircraft','US.strike',1,31,94);add(m,'training-fighter','US.fighter',1,34,94);add(m,'training-battery','abm',1,50,82);add(m,'battery-power','power',1,45,87);add(m,'missile-target','SY.launcher',4,85,65);add(m,'missile-spotter','SY.recon',4,80,65);add(m,'enemy-drone-hub','IR.drone_hub',2,85,75);add(m,'enemy-drone-power','power',2,90,76);add(m,'hostile-aircraft','IR.strike',2,85,75);m.trigger({id:'air-threat',condition:timer(sec(30)),actions:[attack(2,'site1'),attack(4,'site1'),warn('Move the marked infantry out of the warning area and back to base. Interceptors protect against missiles; AA protects against aircraft.')],speaker:'Instructor'});
  m.trigger({id:'missile-targeted-exercise',condition:timer(sec(31)),actions:[attackTag(4,'missile-target','training-battery')]});
  // The hostile aircraft may die before the launcher fires. Reacquire with the
  // launcher's own sight through a normal attack-move; never grant hidden sight.
  m.trigger({id:'missile-reacquire-after-air-defense',condition:all(objectiveDone('air-defense'),eventCount('missile_intercepted',{owner:4,count:0,compare:'at_most'})),actions:[attack(4,'site1')]});
  fail(m,'service-aircraft-lost','Lose the marked strike aircraft before completing service.',all(tagDestroyed('training-aircraft'),eventCount('aircraft_serviced',{owner:1,tag:'training-aircraft',count:0,compare:'at_most'})));fail(m,'missile-exercise-lost','Destroy the missile source before intercepting its missile.',all(tagDestroyed('missile-target'),eventCount('missile_intercepted',{owner:4,count:0,compare:'at_most'})));fail(m,'evade-team-lost','Lose the marked infantry group before its movement exercise.',tagDestroyed('starting-rifles'));
  obj(m,'service','Complete service on the marked strike aircraft.',eventCount('aircraft_serviced',{tag:'training-aircraft',owner:1,count:1}));obj(m,'air-defense','Destroy the hostile aircraft.',tagDestroyed('hostile-aircraft'));obj(m,'missile-defense','Intercept one tactical missile.',eventCount('missile_intercepted',{owner:4,count:1}));obj(m,'evade','Move the marked rifle group to the danger marker, then return after the warning.',all(timer(sec(30)),objectiveDone('enter-mark'),tagInRegion('starting-rifles','base')));obj(m,'enter-mark','Move the marked rifle group to the exercise warning marker.',tagInRegion('starting-rifles','site1'));opt(m,'wing-safe','Keep both original aircraft alive.',all(tagAlive('training-aircraft'),tagAlive('training-fighter')));cp(m,'service-cycle',objectiveDone('service'),'Aircraft service is complete. Observe the distinct missile and air-defense counters.');
 }else{
  enemy(m,'IR',2);obj(m,'short-battle','Neutralize opposing command and production.',all(...['enemy-hq','enemy-barracks','enemy-factory','enemy-service'].map(t=>neutralized(t,1))));obj(m,'faction-ability','Practice one command ability.',eventCount('ability_activated',{owner:1,count:1}));opt(m,'command-intact','Keep the original HQ alive.',tagAlive('home-hq'));cp(m,'ability-used',objectiveDone('faction-ability'),'Ability confirmed. Use the debrief and replay to inspect the battle when you finish.');pressure(m,'SY',[240,480]);
 }
 if(n===5){
  const abilityHelp={US:'Select the HQ and use Recon Sweep on explored terrain (35 Energy).',IR:'Select the starting Survey Drone and use Drone Recall (45 Energy), or Relay Boost while airborne (35 Energy).',SY:'Select command and use Disperse around visible infantry (45 Energy).',SA:'Select the active HQ and use Emergency Power (45 Energy).'};
  m.variants=['US','IR','SY','SA'].map(f=>{
   const v=new MissionBuilder({...m.meta,faction:f});base(v,f,1,3);army(v,f,1,2);if(f==='IR')add(v,'tutorial-survey','IR.isr',1,32,94);
   lossOfBase(v,f);obj(v,'short-battle','Neutralize opposing command and production.',all(...['enemy-hq','enemy-barracks','enemy-factory','enemy-service'].map(t=>neutralized(t,1))));obj(v,'faction-ability','Practice the chosen faction’s command ability.',eventCount('ability_activated',{owner:1,count:1}));opt(v,'command-intact','Keep the original HQ alive.',tagAlive('home-hq'));cp(v,'ability-used',objectiveDone('faction-ability'),'Ability confirmed. Use the debrief and replay to inspect the battle when you finish.');pressure(v,'SY',[240,480]);
   return {faction:f,briefing:instructions[4]+' '+abilityHelp[f],initial:v.initial,objectives:v.objectives,triggers:v.triggers};
  });
  const us=m.variants[0];m.initial=[...m.initial.filter(s=>s.owner!==1),...us.initial];m.objectives=us.objectives;m.triggers=us.triggers;m.meta.briefing=us.briefing;
  m.variantPresentation=Object.entries(abilityHelp).map(([faction,instruction])=>({faction,instruction}));
 }
 if(n<5){m.trigger({id:'advanced-exercise',condition:waveTimer(sec(600)),actions:[spawn('advanced-opposition','SY.rifle',4,p(100,52),2,NORMAL_UP),spawn('hard-exercise','SY.car',4,p(105,52),1,HARD),warn('The late exercise detachment has entered the eastern road.'),attack(4,'base')],speaker:'Instructor',wave:'A finite late exercise column changes enemy composition and timing only; no training rule bonuses are applied.'});}
 m.exception('Interface steps and their browser-local input records are separate from Go mission objectives. World completion alone does not certify selection, control groups, rally feedback or boarding input.');
 return {builder:m,layout:l};
 });
}

export function coopMissions(layouts){return ['convoy-union','twin-outposts'].map((id,i)=>{
 const l=layouts.find(l=>l.map.id===id),convoy=i===0;
 const briefing=convoy?'Two independent allied economies escort three sequential two-truck convoys. Choose the northern or southern route at each checkpoint. Either commander can Hold; after a manual hold both must approve Advance. The visible countdown protects route decisions. A completed convoy unlocks one forward repair position for each owner, not free combat reinforcements. At least one truck from each convoy must arrive.':'Your HQs start on opposite sides of the river. Each commander must keep an HQ alive. Reopen the central connection, then neutralize the command and production structures of both hostile bases. Warned finite detachments enter the northwestern and northeastern roads. Each economy, service slot and army remains owned by its commander.';
 const m=new MissionBuilder({id,title:convoy?'Convoy Union':'Twin Outposts',map_id:id,faction:'US',mode:'coop',order:i+1,operation:'Joint Route Command',theater:'The fictional Aster Reach',lesson:convoy?'Shared convoy approvals and independent economies.':'Reconnect separated economies before the joint assault.',designRef:'19.6',briefing,debrief:convoy?'All three convoys have arrived. Independent command and shared route decisions kept the corridor operating.':'Both hostile production bases are neutralized. The river corridor is open and each commander retains a command center.',rules_notice:'Two human slots, or one human plus a configured AI ally. Shared mission objectives; independent resources, ownership and service. Authored finite enemy waves are announced. Saves belong to the offline host or authoritative server.',briefingLines:[['Joint Command',briefing]],victoryLines:[['Joint Command','The joint operation is complete. Review both commanders’ losses and convoy decisions.']],defeatLines:[['Joint Command','The joint requirements can no longer be met. Restore the last shared checkpoint.']]});
 m.player({id:1,faction:'US',name:'Western Command',team:1,controller:'human',credits:cr(8000)}).player({id:2,faction:'SA',name:'Eastern Command',team:1,controller:'human',credits:cr(8000)}).player({id:3,faction:convoy?'US':'IR',name:convoy?'Union Convoys':'Northern Garrison',team:convoy?1:2,controller:convoy?'script':'ai',ai:convoy?'':'normal',credits:convoy?0:cr(5000)}).player({id:4,faction:'SY',name:'Eastern Garrison',team:2,controller:'ai',ai:'normal',credits:cr(5000)});
 base(m,'US',1,2,[20,106],'west');army(m,'US',1,2,[27,105],'west-force');base(m,'SA',2,2,[convoy?46:106,106],'east');army(m,'SA',2,2,[convoy?49:107,103],'east-force');
 base(m,'SY',4,2,[106,22],'opponent-east');
 fail(m,'western-hq-lost','Western Command loses its final HQ.',noneOf('hq',1));fail(m,'eastern-hq-lost','Eastern Command loses its final HQ.',noneOf('hq',2));
 if(convoy){
  const routes=[['route-junction','north-branch','north-merge','convoy-exit'],['route-junction','south-branch','south-merge','convoy-exit']];
  add(m,'convoy-one','US.hauler',3,17,117,2);
  for(const [j,name] of [[1,'one'],[2,'two'],[3,'three']]){m.convoy({id:`convoy-${j}`,tag:`convoy-${name}`,routes,countdown:dur(10)});obj(m,`arrival-${j}`,`Deliver convoy ${j} to the exit.`,convoyDone(`convoy-${j}`));fail(m,`convoy-${j}-lost`,`Lose every truck in convoy ${j}.`,tagDestroyed(`convoy-${name}`));}
  m.trigger({id:'first-convoy-ready',condition:timer(sec(20)),actions:[startConvoy('convoy-1'),warn('Convoy one is ready. Approve Advance, or Hold while an escort clears the chosen branch.')],speaker:'Convoy control'});
  m.trigger({id:'second-convoy-ready',condition:convoyDone('convoy-1'),actions:[checkpoint('first-arrival'),spawn('convoy-two','US.hauler',3,p(17,117),2),spawn('western-forward-repair','depot',1,p(53,78)),spawn('eastern-forward-repair','depot',2,p(64,78)),startConvoy('convoy-2'),warn('First delivery complete. Two separately owned forward repair depots are now available. Convoy two is ready.')],speaker:'Convoy control'});
  m.trigger({id:'third-convoy-ready',condition:convoyDone('convoy-2'),actions:[checkpoint('second-arrival'),spawn('convoy-three','US.hauler',3,p(17,117),2),startConvoy('convoy-3'),warn('Second delivery complete. Prepare the final convoy and review the route before approving Advance.')],speaker:'Convoy control'});
  opt(m,'all-convoy-trucks','Preserve all six original convoy trucks.',all(tagAlive('convoy-one',{count:2}),tagAlive('convoy-two',{count:2}),tagAlive('convoy-three',{count:2})));
  m.exception('Completed convoy one unlocks exactly two authored repair depots, one per human owner. Repairs still cost the owning player credits. Convoy trucks are script-controlled original cargo actors and never grant combat units.');
  pressure(m,'SY',[160,320,480,640],'route-junction',4);
 }else{
  base(m,'IR',3,2,[22,22],'opponent-west');
  obj(m,'reconnection','Control the contested central connection for thirty seconds.',holdFor(any(regionHeld('central-connection',1),regionHeld('central-connection',2)),30));
  const targets=['opponent-west-hq','opponent-west-barracks','opponent-west-factory','opponent-west-service','opponent-east-hq','opponent-east-barracks','opponent-east-factory','opponent-east-service'];
  obj(m,'joint-assault','Neutralize both hostile production bases after reconnecting.',all(objectiveDone('reconnection'),...targets.map(t=>any(tagDestroyed(t),tagOwned(t,1),tagOwned(t,2)))));
  opt(m,'original-hqs','Keep both original HQs alive.',all(tagAlive('west-hq'),tagAlive('east-hq')));cp(m,'river-reconnected',objectiveDone('reconnection'),'The central connection is open. Refit both forces before the joint assault.');
  cp(m,'final-assault',all(objectiveDone('reconnection'),any(regionHeld('corridor-west',1),regionHeld('corridor-west',2)),any(regionHeld('corridor-east',1),regionHeld('corridor-east',2))),'Both corridor approaches are secure. The final assault checkpoint is available.');pressure(m,'SY',[180,360,540],'base-two',4);pressure(m,'IR',[210,390,570],'base-one',3,'north-');

 }
 return {builder:m,layout:l};
});}
