// Test-only successor. Original offline-upgrade failure and inputs stay immutable.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,mkdtemp,rm,realpath,symlink} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../../',import.meta.url)),require=createRequire(path.join(root,'client/package.json'));
const {build}=require('esbuild'),{chromium}=require('playwright-core');
const argv=process.argv.slice(2),args={};assert.equal(argv.length%2,0);for(let i=0;i<argv.length;i+=2){assert(['--out','--build-only','--consumer','--lock','--lock-sha'].includes(argv[i]));assert(!Object.hasOwn(args,argv[i]));args[argv[i]]=argv[i+1]}assert(args['--out']);assert(args['--build-only']===undefined||['true','false'].includes(args['--build-only']));
const out=path.resolve(args['--out']);await mkdir(out,{recursive:false});
const defaultLockSHA='4859c10adaee194242b5f257d19cd4d02961d42a16278b560a69f7d417726037';
const explicit=['--consumer','--lock','--lock-sha'].filter(key=>args[key]!==undefined);assert(explicit.length===0||explicit.length===3,'A successor requires explicit consumer, lock and expected SHA together');
const source=await realpath(path.resolve(args['--consumer']??path.join(root,'work/art-generation-consumer-v1/frozen-v1/client'))),lockFile=path.resolve(args['--lock']??path.join(root,'work/art-generation-consumer-v1/source-lock-v1.json')),lockSHA=args['--lock-sha']??defaultLockSHA,product=path.join(root,'work/art/effects-opus-v2/integration-v25/product');assert(/^[a-f0-9]{64}$/.test(lockSHA));
const sha=bytes=>createHash('sha256').update(bytes).digest('hex'),json=value=>JSON.stringify(value,null,2)+'\n';
const report={status:'preflight',started:new Date().toISOString(),scope:'Actual frozen private ArtLibrary + installer + service worker, tiny declared real-PNG packs. No full App, Go gameplay, complete art roster, stock-browser, reference performance or release claim.',cases:[],pageErrors:[],httpErrors:[],requestFailures:[],requests:[],console:[]};
const guards=new Map(),pin=async(file,expected)=>{const bytes=await readFile(file);assert.equal(sha(bytes),expected,file);guards.set(file,expected);return bytes};
let context,noWorker,server,temp,origin,phase='preflight',generation='A',mode='online',fault,held;
const record=(name,data)=>report.cases.push({name,...data});
const wait=async(fn,label)=>{const end=Date.now()+30000;while(Date.now()<end){const value=await fn();if(value)return value;await new Promise(resolve=>setTimeout(resolve,20))}throw Error('Timed out: '+label)};
try{
 const lockBytes=await pin(lockFile,lockSHA),lock=JSON.parse(lockBytes);
 for(const [file,hash]of Object.entries(lock.files)){assert(file.startsWith('source/'));await pin(path.join(path.dirname(source),file.slice('source/'.length)),hash)}
 const productReceipt=JSON.parse(await pin(path.join(path.dirname(product),'build.json'),'6c4f6f675983c3ab428546487ee419212a2b798aa66c513cd5913058084524f0'));
 const originalPack=JSON.parse(await pin(path.join(product,'assets/packs/base.json'),'120fd4095f8da3cd15f51e5b2d97ffd0b5bbd9a666502685b5b153219841dcba'));
 const descriptors=new Map(originalPack.files.map(file=>[file.path,file]));
 const fromProduct=async url=>{const file=descriptors.get(url);assert(file,url);return pin(path.join(product,url.slice(1)),file.sha256)};
 const artID='building.US.aa_post',artDir='/art/sprites/'+artID+'/',meta=JSON.parse(await fromProduct(artDir+artID+'.sprite.json')),art={};
 for(const [name,index]of [['A',0],['B',1],['C',1]]){const atlasPath=artDir+artID+'@1x.beauty.'+index+'.json',atlas=JSON.parse(await fromProduct(atlasPath)),pngPath=artDir+atlas.meta.image,png=await fromProduct(pngPath),frame=/^(.*)\/d(\d+)_f(\d+)$/.exec(Object.keys(atlas.frames)[0]);assert(frame);art[name]={atlasPath,pngPath,png,atlas:{...atlas,meta:{...atlas.meta,image:'page.png'}},meta:{...meta,atlases:{'1x':{beauty:['atlas.json']},'2x':{beauty:['atlas.json']}}},frame:{state:frame[1],direction:Number(frame[2]),index:Number(frame[3])}}}
 assert.equal(sha(art.A.png),'b27d656eef21e02d034ac63f297e24b85d00e80caff6beb35fef29d962c8392f');assert.equal(sha(art.B.png),'be32a13bc1dff9054e9d3eb6931471e62167b33066aff404970b1d3117da16d8');assert.deepEqual(art.A.atlas.meta.size,art.B.atlas.meta.size);
 const fixture=fileURLToPath(new URL('fixture.ts',import.meta.url)),driver=fileURLToPath(import.meta.url);for(const file of [fixture,driver])guards.set(file,sha(await readFile(file)));
 temp=await mkdtemp(path.join(tmpdir(),'frontline-generation-v1-'));
 const frozenResolve={name:'exact-private-consumer-v1',setup(builder){builder.onResolve({filter:/^\.\.\/\.\.\/src\//},args=>{assert.equal(args.importer,fixture);const rel=args.path.slice('../../src/'.length);return {path:path.join(source,'src',rel+(path.extname(rel)?'':'.ts'))}})}};
 await build({entryPoints:[fixture],outfile:path.join(out,'fixture.js'),bundle:true,format:'iife',platform:'browser',target:'es2022',nodePaths:[path.join(root,'client/node_modules')],plugins:[frozenResolve]});
 await build({entryPoints:[path.join(source,'src/runtime/service-worker.ts')],outfile:path.join(out,'service-worker.js'),bundle:true,format:'iife',platform:'browser',target:'es2022'});
 const bundle=await readFile(path.join(out,'fixture.js'),'utf8'),worker=await readFile(path.join(out,'service-worker.js'));
 const typeDir=path.join(temp,'typecheck');await mkdir(path.join(typeDir,'tests/generation'),{recursive:true});await symlink(path.join(source,'src'),path.join(typeDir,'src'),'dir');await symlink(path.join(root,'client/node_modules'),path.join(typeDir,'node_modules'),'dir');await writeFile(path.join(typeDir,'tests/generation/fixture.ts'),await readFile(fixture));await writeFile(path.join(typeDir,'tsconfig.json'),json({compilerOptions:{target:'ES2022',module:'ESNext',moduleResolution:'bundler',lib:['ES2022','DOM','DOM.Iterable'],strict:true,skipLibCheck:true,noEmit:true,allowJs:true,types:['vite/client']},include:['tests/generation/fixture.ts']}));
 let typeOutput='';try{typeOutput=execFileSync(process.execPath,[path.join(root,'client/node_modules/typescript/bin/tsc'),'-p',path.join(typeDir,'tsconfig.json')],{encoding:'utf8',maxBuffer:2<<20})}catch(error){await writeFile(path.join(out,'typecheck.log'),String(error.stdout??'')+String(error.stderr??''));throw error}await writeFile(path.join(out,'typecheck.log'),typeOutput);
 const variants={};
 for(const name of ['A','B','C']){const index={format_version:1,version:'fixture-'+name,packs:[{id:'2.0.0',version:'fixture-'+name,manifest_url:'/assets/packs/base.json'}],maps:[],missions:[]};const bodies={
 '/generation-shell.html':`<!doctype html><title>Cached ${name}</title><link rel="icon" href="data:,"><h1>Cached exact generation ${name}</h1><script>document.documentElement.dataset.generation='${name}'</script>`,
 '/content/index.json':json(index),'/upgrade/shared.txt':'exact '+name,'/upgrade/hold.bin':'held '+name,
 '/art/index.json':json({format:1,sprites:{[artID]:'offline-upgrade/sprite.json'},terrain:[],portraits:[],chrome:[],icons:false,emblems:false}),
 '/art/offline-upgrade/sprite.json':json(art[name].meta),'/art/offline-upgrade/atlas.json':json(art[name].atlas),'/art/offline-upgrade/page.png':art[name].png};if(name==='A')bodies['/upgrade/retired.txt']='only A';const manifest={id:'2.0.0',version:'fixture-'+name,files:Object.entries(bodies).map(([url,bytes])=>({path:url,sha256:sha(bytes),bytes:Buffer.byteLength(bytes)}))};variants[name]={manifest,bodies}}
 await writeFile(path.join(out,'fixture-manifests.json'),json(Object.fromEntries(Object.entries(variants).map(([name,item])=>[name,item.manifest]))));for(const file of [fixture,driver])await writeFile(path.join(out,path.basename(file)),await readFile(file));
 report.identity={consumerLockSHA256:sha(lockBytes),consumerSource:source,consumerCapturedFiles:Object.keys(lock.files).length,productBuildSHA256:'6c4f6f675983c3ab428546487ee419212a2b798aa66c513cd5913058084524f0',productSourceDigest:productReceipt.sourceDigest,driverSHA256:guards.get(driver),fixtureSHA256:guards.get(fixture),bundleSHA256:sha(bundle),workerSHA256:sha(worker),art:Object.fromEntries(Object.entries(art).map(([name,item])=>[name,{pngPath:item.pngPath,pngSHA256:sha(item.png),atlasPath:item.atlasPath,frame:item.frame,scope:'Unmodified real PNG; atlas/meta paths relocated to same declared test URL, one beauty page. Loader identity only.'}]))};
 if(args['--build-only']==='true'){report.status='compiled-and-types-passed-only';report.browserLaunched=false;report.serverLaunched=false}else{
  const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.json':'application/json','.png':'image/png','.txt':'text/plain'};
  server=createServer((request,response)=>{const url=new URL(request.url,'http://fixture'),pathname=url.pathname,download=request.headers['x-frontline-pack-download']==='1',entry={phase,generation,mode,path:pathname,download,received:new Date().toISOString()};report.requests.push(entry);response.on('finish',()=>{entry.finished=new Date().toISOString();entry.status=response.statusCode});response.on('close',()=>{entry.closed=new Date().toISOString();entry.writableFinished=response.writableFinished});
   let body;if(pathname==='/generation-harness.html')body='<!doctype html><title>Generation coherence diagnostics</title><link rel="icon" href="data:,"><h1>Verified generation consumer</h1>';else if(pathname==='/service-worker.js')body=worker;else if(pathname==='/reference/A.png')body=art.A.png;else if(pathname==='/reference/B.png')body=art.B.png;else if(mode==='offline'){response.writeHead(503,{'Content-Type':'text/plain'});response.end('Deliberate network unavailable');return}else if(pathname==='/assets/packs/base.json')body=json(variants[generation].manifest);else body=variants[generation].bodies[pathname];
   if(body===undefined){response.writeHead(404);response.end('Unlisted');return}body=Buffer.from(body);
   const send=()=>{if(response.destroyed)return;response.writeHead(200,{'Content-Type':mime[path.extname(pathname)]??'application/octet-stream','Content-Length':body.length,'Cache-Control':'no-store'});response.end(body)};
   if(fault&&fault.path===pathname&&fault.download===download){entry.fault=fault.kind;if(fault.kind==='hold'){assert(!held);held={send,path:pathname,entry};return}if(fault.kind==='interrupt'){response.destroy();return}if(fault.kind==='corrupt')body=Buffer.alloc(body.length,88);if(fault.kind==='truncate')body=body.subarray(0,body.length-1)}send();
  });await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;report.origin=origin;
  const attach=async(c,label)=>{await c.addInitScript({content:bundle});c.on('page',page=>{const starts=new WeakMap();page.on('request',request=>starts.set(request,{phase,mode,at:new Date().toISOString()}));page.on('pageerror',error=>report.pageErrors.push({phase,label,message:String(error)}));page.on('console',message=>{if(['error','warning'].includes(message.type()))report.console.push({phase,label,type:message.type(),text:message.text()})});page.on('response',response=>{if(response.status()>=400)report.httpErrors.push({...(starts.get(response.request())??{}),observedPhase:phase,label,url:response.url(),status:response.status()})});page.on('requestfailed',request=>report.requestFailures.push({...(starts.get(request)??{}),observedPhase:phase,label,url:request.url(),reason:request.failure()?.errorText}))});return c};
  const launch=async()=>{const c=await chromium.launchPersistentContext(path.join(temp,'profile'),{headless:true,viewport:{width:1280,height:720}});(report.launches??=[]).push({version:c.browser()?.version(),executable:chromium.executablePath(),persistentRestart:!!report.launches?.length,scope:'Bundled Chromium; not branded Chrome/Edge or stock Firefox/Safari'});return attach(c,'persistent')};
  context=await launch();let a=await context.newPage(),b=await context.newPage();for(const page of [a,b])await page.goto(origin+'/generation-harness.html');const capabilities=await a.evaluate(()=>window.generationQA.register());assert(capabilities.secure&&capabilities.locks);await b.evaluate(()=>window.generationQA.register());report.capabilities=capabilities;
  const install=(page,name,key='install')=>page.evaluate(({pack,key})=>window.generationQA.install(pack,key),{pack:variants[name].manifest,key});
  const state=page=>page.evaluate(()=>window.generationQA.state());
  const active=async(page,name)=>{mode='offline';try{const value=await page.evaluate(()=>window.generationQA.read('/upgrade/shared.txt'));assert.equal(value.status,200);assert.equal(value.text,'exact '+name);return value}finally{mode='online'}};
  const create=(page,name)=>page.evaluate(({name,id})=>window.generationQA.create(name,id),{name,id:artID});
  const frame=(page,name,which)=>page.evaluate(({name,frame})=>window.generationQA.frame(name,frame),{name,frame:art[which].frame});
  const evict=async(page,name)=>{const result=await page.evaluate(name=>window.generationQA.evict(name),name);assert.equal(result.statistics.residentPages,0);assert.equal(result.statistics.pickingBytes,0);assert.equal(result.oldPickingLive,false);return result};
  const expectPixels=(result,expected,version)=>{assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.sha256,expected);assert.equal(result.generation.version,'fixture-'+version);assert.equal(result.statistics.residentPages,1);assert.equal(result.picking,true);assert(result.statistics.pickingBytes>0);assert.deepEqual(result.errors,[])};
  phase='reference-real-PNG';const expectedA=await a.evaluate(()=>window.generationQA.reference('/reference/A.png')),expectedB=await a.evaluate(()=>window.generationQA.reference('/reference/B.png'));assert.notEqual(expectedA,expectedB);record(phase,{expectedA,expectedB,resources:await a.evaluate(()=>window.generationQA.resources())});
  phase='install-and-capture-A';const installedA=await install(a,'A');assert(installedA.ok);const capturedA=await create(a,'oldA');assert.equal(capturedA.generation.version,'fixture-A');assert.equal(capturedA.statistics.residentPages,0);record(phase,{installedA,capturedA});
  for(const kind of ['corrupt','truncate','interrupt','quota-file','quota-manifest','quota-ready']){phase=kind+'-B';generation='B';const before=await state(a);fault={path:'/upgrade/shared.txt',download:true,kind};let result;if(kind.startsWith('quota-'))result=await a.evaluate(({pack,path})=>window.generationQA.quota(pack,path),{pack:variants.B.manifest,path:kind==='quota-manifest'?'/__frontline_pack_manifest__':kind==='quota-ready'?'/__frontline_pack_ready__':'/upgrade/shared.txt'});else result=await install(a,'B');fault=undefined;assert.equal(result.ok,false);if(kind.startsWith('quota-'))assert.equal(result.injected,1);assert.equal(result.error.code,kind==='corrupt'?'content_corrupt':kind==='truncate'?'content_size_mismatch':'content_cache_failed');assert.deepEqual((await state(a)).names,before.names);await active(a,'A');record(phase,result)}
  phase='cancel-B-held-download';fault={path:'/upgrade/hold.bin',download:true,kind:'hold'};await a.evaluate(pack=>window.generationQA.startInstall(pack,'cancel'),variants.B.manifest);await wait(()=>held,'cancel B held');await a.evaluate(()=>window.generationQA.abort('cancel'));let result=await wait(()=>a.evaluate(()=>window.generationQA.result('cancel')),'cancel complete');assert.equal(result.error.code,'download_canceled');held.send();held=undefined;fault=undefined;await active(a,'A');record(phase,result);
  phase='pending-A-across-other-tab-B';await a.evaluate(()=>window.generationQA.holdCache('/art/offline-upgrade/page.png'));await a.evaluate(frame=>window.generationQA.startFrame('oldA',frame,'pending-A'),art.A.frame);await wait(()=>a.evaluate(()=>window.generationQA.cacheHeld()),'actual A Cache.match response held');const installedB=await install(b,'B');assert(installedB.ok);generation='B';await a.evaluate(()=>window.generationQA.releaseCache());const pendingA=await wait(()=>a.evaluate(()=>window.generationQA.result('pending-A')),'pending A admitted');expectPixels(pendingA,expectedA,'A');await active(a,'B');const newB=await create(b,'newB'),pixelsB=await frame(b,'newB','B');expectPixels(pixelsB,expectedB,'B');record(phase,{installedB,pendingA,newB,pixelsB});
  phase='evict-reload-A-host-B';const evictedA=await evict(a,'oldA'),reloadedA=await frame(a,'oldA','A');expectPixels(reloadedA,expectedA,'A');const imageA=await a.evaluate(()=>window.generationQA.image('oldA','/art/offline-upgrade/page.png')),imageB=await b.evaluate(()=>window.generationQA.image('newB','/art/offline-upgrade/page.png'));assert(imageA.ok&&imageB.ok);assert.equal(imageA.sha256,expectedA);assert.equal(imageB.sha256,expectedB);assert.equal(imageA.resources.blobURLs,0);assert.equal(imageB.resources.blobURLs,0);record(phase,{evictedA,reloadedA,imageA,imageB});
  phase='unchanged-B-reuse';const beforeDownloads=report.requests.filter(request=>request.download).length;result=await install(a,'B');assert(result.ok);assert.equal(report.requests.filter(request=>request.download).length,beforeDownloads);assert.equal(result.value.cacheName,installedB.value.cacheName);record(phase,result);
  phase='rollback-A-retained-B';result=await install(a,'A');assert(result.ok);await active(b,'A');const evictedB=await evict(b,'newB'),retainedB=await frame(b,'newB','B');expectPixels(retainedB,expectedB,'B');const beforeCancel=await state(a),canceled=await a.evaluate(pack=>window.generationQA.canceled(pack),variants.B.manifest);assert.equal(canceled.error.code,'download_canceled');assert.deepEqual(await state(a),beforeCancel);record(phase,{rollback:result,evictedB,retainedB,canceled});
  phase='concurrent-completion-C-after-B';generation='C';fault={path:'/upgrade/hold.bin',download:true,kind:'hold'};await a.evaluate(pack=>window.generationQA.startInstall(pack,'slow-C'),variants.C.manifest);await wait(()=>held,'C held');fault=undefined;const earlier=await install(b,'B');assert(earlier.ok);held.send();held=undefined;const later=await wait(()=>a.evaluate(()=>window.generationQA.result('slow-C')),'C done');assert(later.ok&&later.value.installedAt>earlier.value.installedAt);await active(b,'C');record(phase,{earlier,later});
  phase='cancel-real-other-tab-lock';await b.evaluate(()=>window.generationQA.holdLock('2.0.0'));await a.evaluate(pack=>window.generationQA.startInstall(pack,'wait-A'),variants.A.manifest);await wait(async()=>{const locks=await a.evaluate(()=>window.generationQA.locks());return locks.pending.some(lock=>lock.name.endsWith('activate:2.0.0'))},'actual Web Lock queue');await a.evaluate(()=>window.generationQA.abort('wait-A'));result=await wait(()=>a.evaluate(()=>window.generationQA.result('wait-A')),'lock cancellation');assert.equal(result.error.code,'download_canceled');await b.evaluate(()=>window.generationQA.releaseLock());await active(a,'C');record(phase,result);
  phase='retired-A-file-not-resurrected';mode='offline';const retired=await a.evaluate(()=>window.generationQA.read('/upgrade/retired.txt'));mode='online';assert.equal(retired.status,503);record(phase,retired);
  phase='explicit-A-removal-fails-closed';await a.evaluate(name=>window.generationQA.remove(name),installedA.value.cacheName);await evict(a,'oldA');const afterRemoval=await frame(a,'oldA','A');assert.equal(afterRemoval.ok,false);assert.equal(afterRemoval.statistics.residentPages,0);assert.equal(afterRemoval.statistics.pickingBytes,0);assert.equal(afterRemoval.errors.at(-1).code,'asset_generation_unavailable');record(phase,afterRemoval);
  phase='no-worker-online-byte-change';noWorker=await attach(await context.browser().newContext({viewport:{width:1280,height:720}}),'no-worker');const plain=await noWorker.newPage();await plain.goto(origin+'/generation-harness.html');assert.equal(await plain.evaluate(()=>navigator.serviceWorker.controller),null);assert.deepEqual(await plain.evaluate(()=>caches.keys()),[]);generation='A';const onlineA=await create(plain,'onlineA');assert.equal(onlineA.generation.version,'fixture-A');generation='B';const bitmapBefore=await plain.evaluate(()=>window.generationQA.resources().bitmapCreated),changed=await frame(plain,'onlineA','A');assert.equal(changed.ok,false);assert(['asset_integrity','asset_size'].includes(changed.errors.at(-1).code));assert.equal(changed.resources.bitmapCreated,bitmapBefore);assert.equal(changed.statistics.residentPages,0);record(phase,{onlineA,changed,noServiceWorker:true,noCache:true});
  phase='pending-network-A-host-swap';generation='A';await create(plain,'pendingOnlineA');fault={path:'/art/offline-upgrade/page.png',download:false,kind:'hold'};await plain.evaluate(frame=>window.generationQA.startFrame('pendingOnlineA',frame,'network-A'),art.A.frame);await wait(()=>held,'actual native A response held');generation='B';fault=undefined;held.send();held=undefined;const networkA=await wait(()=>plain.evaluate(()=>window.generationQA.result('network-A')),'A native completed');expectPixels(networkA,expectedA,'A');record(phase,networkA);
  phase='dispose-pending-network';generation='A';await create(plain,'disposePending');fault={path:'/art/offline-upgrade/page.png',download:false,kind:'hold'};await plain.evaluate(frame=>window.generationQA.startFrame('disposePending',frame,'dispose-frame'),art.A.frame);await wait(()=>held,'native pending page before dispose');const disposed=await plain.evaluate(()=>window.generationQA.dispose('disposePending'));held.send();held=undefined;fault=undefined;assert.equal(disposed.statistics.residentPages,0);assert.equal(disposed.statistics.pickingBytes,0);assert.equal(disposed.resources.blobURLs,0);const pendingDisposed=await wait(()=>plain.evaluate(()=>window.generationQA.result('dispose-frame')),'disposed page settled');assert.equal(pendingDisposed.ok,false);record(phase,{disposed,pendingDisposed});
  phase='dispose-all-generations';const cleanA=await a.evaluate(()=>window.generationQA.disposeAll()),cleanB=await b.evaluate(()=>window.generationQA.disposeAll()),cleanPlain=await plain.evaluate(()=>window.generationQA.disposeAll());for(const clean of [cleanA,cleanB,cleanPlain]){assert.equal(clean.bitmapLive,0);assert.equal(clean.blobURLs,0);assert.equal(clean.blobBytes,0);assert.equal(clean.canvases,0)}record(phase,{cleanA,cleanB,cleanPlain});await noWorker.close();noWorker=undefined;
  phase='cold-restart-offline-C';generation='C';await context.close();context=await launch();await context.setOffline(true);a=await context.newPage();await a.goto(origin+'/generation-shell.html');assert.equal(await a.locator('html').getAttribute('data-generation'),'C');const cold=await create(a,'coldC'),coldPixels=await frame(a,'coldC','C');expectPixels(coldPixels,expectedB,'C');assert.equal(cold.generation.version,'fixture-C');await a.screenshot({path:path.join(out,'cold-C.png')});const coldClean=await a.evaluate(()=>window.generationQA.disposeAll());assert.equal(coldClean.bitmapLive,0);assert.equal(coldClean.blobURLs,0);record(phase,{cold,coldPixels,coldClean,scope:'Persistent browser restart offline, actual default ArtLibrary exact stored index+manifest+PNG; tiny cached document only, not full App.'});
  assert.deepEqual(report.pageErrors,[]);report.httpClassification=report.httpErrors.map(error=>({...error,expected:error.phase==='retired-A-file-not-resurrected'&&error.status===503&&new URL(error.url).pathname==='/upgrade/retired.txt'}));assert(report.httpClassification.every(error=>error.expected),'Unclassified HTTP errors');
  report.failureClassification=report.requestFailures.map(error=>({...error,expected:(error.phase==='interrupt-B'&&new URL(error.url).pathname==='/upgrade/shared.txt')||(error.phase==='cancel-B-held-download'&&new URL(error.url).pathname==='/upgrade/hold.bin')||(error.phase==='dispose-pending-network'&&new URL(error.url).pathname==='/art/offline-upgrade/page.png')}));assert(report.failureClassification.every(error=>error.expected),'Unclassified request failure; native integrity does not automatically excuse a browser error');report.status='tiny-generation-and-transaction-gates-passed';
 }
}catch(error){report.status='failed';report.phase=phase;report.failure=String(error.stack??error);process.exitCode=1}
finally{held?.send();await noWorker?.close();await context?.close();if(server?.listening){server.closeAllConnections();await new Promise(resolve=>server.close(resolve))}if(temp)await rm(temp,{recursive:true,force:true});try{for(const [file,hash]of guards)assert.equal(sha(await readFile(file)),hash,file);report.inputsVerifiedAfter=guards.size}catch(error){report.status='failed';report.drift=String(error);process.exitCode=1}report.closedAt=new Date().toISOString();await writeFile(path.join(out,'receipt.json'),json(report));console.log(json({out,status:report.status,cases:report.cases.length,failure:report.failure}))}
