// Browser plugin unavailable. Parent owns execution; build-only starts nothing.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {readFile,writeFile,mkdir,mkdtemp,rm,realpath} from 'node:fs/promises';
import path from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {chromium,firefox,webkit} from 'playwright-core';
const root=fileURLToPath(new URL('../../../',import.meta.url)),args={},argv=process.argv.slice(2);assert.equal(argv.length%2,0);
for(let i=0;i<argv.length;i+=2){assert(['--product','--out','--engine','--build-only','--full-pack'].includes(argv[i]));assert(!Object.hasOwn(args,argv[i]));args[argv[i]]=argv[i+1]}
assert(args['--product']&&args['--out']);for(const key of ['--build-only','--full-pack'])assert(args[key]===undefined||['true','false'].includes(args[key]));const engine=args['--engine']??'chromium';assert(['chromium','firefox','webkit'].includes(engine));
const product=await realpath(path.resolve(args['--product'])),out=path.resolve(args['--out']);await mkdir(out,{recursive:false});const sha=b=>createHash('sha256').update(b).digest('hex'),json=v=>JSON.stringify(v,null,2)+'\n';
const report={status:'preflight',started:new Date().toISOString(),product,engine,scope:'Real browser transaction mechanics with small declared fixture packs; optional separate full v25 cold App startup. No cross-platform/reference-performance/final-release claim.',cases:[],errors:[],responses:[],requests:[],failures:[],fullPackRequested:args['--full-pack']==='true'};
const guards=new Map();let context,server,temp,profile,origin,mode='online',generation='A',fault,held,phase='preflight',workerScript='previous';
const pin=async(file,hash)=>{const b=await readFile(file);assert.equal(sha(b),hash,file);guards.set(file,hash);return b};
const record=(name,value)=>{report.cases.push({name,...value})};
try{
 const buildFile=path.join(path.dirname(product),'build.json'),buildBytes=await pin(buildFile,'6c4f6f675983c3ab428546487ee419212a2b798aa66c513cd5913058084524f0'),receipt=JSON.parse(buildBytes),source=path.join(path.dirname(product),'source/client');
 assert.equal(receipt.sourceDigest,'d297183a44bf211a1d19862809985c3669a5ab7fd3b4b71f34b0cdd290e91253');
 for(const [rel,h]of Object.entries(receipt.sourceFiles))await pin(path.join(source,rel),h);
 for(const rel of ['src/runtime/cache.ts','src/runtime/offline-response.ts','src/runtime/service-worker.ts'])assert.equal(sha(await readFile(path.join(root,'client',rel))),receipt.sourceFiles[rel],'Current committed installer differs from frozen v25');
 const previousWorkerPath=path.join(root,'work/art/effects-opus-v2/integration-v24/product/service-worker.js'),previousWorker=await readFile(previousWorkerPath);guards.set(previousWorkerPath,sha(previousWorker));assert.notEqual(sha(previousWorker),sha(await readFile(path.join(product,'service-worker.js'))));
 const packBytes=await pin(path.join(product,'assets/packs/base.json'),receipt.pack),fullPack=JSON.parse(packBytes),files=new Map(fullPack.files.map(f=>[f.path,f]));assert(fullPack.version.startsWith('content-v1-'));
 const productIndex=JSON.parse(await readFile(path.join(product,'content/index.json'))),mapDescriptor=productIndex.maps.find(m=>m.kind==='skirmish'),mapBytes=await pin(path.join(product,mapDescriptor.url.slice(1)),mapDescriptor.sha256),baseMap=JSON.parse(mapBytes);
 const fixture=fileURLToPath(new URL('fixture.ts',import.meta.url)),observer=path.join(root,'client/tests/stock-browser/observe.mjs');temp=await mkdtemp(path.join(tmpdir(),'frontline-offline-upgrade-'));profile=path.join(temp,'profile');
 const resolve={name:'exact-frozen-v25',setup(b){b.onResolve({filter:/^\.\.\/\.\.\/src\//},a=>{if(a.importer!==fixture&&a.importer!==observer)return;const rel=a.path.slice('../../src/'.length);return {path:path.join(source,'src',rel+(path.extname(rel)?'':'.ts'))}})}};
 for(const [entry,name]of [[fixture,'fixture.js'],[observer,'observe.js']]){await build({entryPoints:[entry],outfile:path.join(temp,name),bundle:true,format:'iife',platform:'browser',target:'es2022',nodePaths:[path.join(root,'client/node_modules')],plugins:[resolve]});await writeFile(path.join(out,name),await readFile(path.join(temp,name)))}
 const bundle=await readFile(path.join(temp,'fixture.js'),'utf8'),observation=await readFile(path.join(temp,'observe.js'),'utf8'),variants={};
 for(const v of ['A','B','C']){
  const map={...baseMap,id:'offline-fixture',title:'Offline fixture '+v,required_packs:['offline-qa']},mapText=json(map),index={format_version:1,version:'fixture-'+v,packs:[{id:'offline-qa',version:'fixture-'+v,manifest_url:'/assets/packs/fixture.json'}],maps:[{id:map.id,version:map.version,title:map.title,author:map.author,players:map.spawns.length,kind:'skirmish',url:'/content/maps/offline-fixture.json',sha256:sha(mapText),bytes:Buffer.byteLength(mapText),required_packs:['offline-qa']}],missions:[]};
  const bodies={'/upgrade-shell.html':`<!doctype html><title>Offline ${v}</title><h1>Cached ${v}</h1><script>document.documentElement.dataset.generation='${v}'</script>`,'/content/index.json':json(index),'/content/maps/offline-fixture.json':mapText,'/upgrade/shared.txt':'exact '+v,'/upgrade/hold.bin':'held '+v};if(v==='A')bodies['/upgrade/retired.txt']='retired A';
  const manifest={id:'offline-qa',version:'fixture-'+v,files:Object.entries(bodies).map(([p,s])=>({path:p,bytes:Buffer.byteLength(s),sha256:sha(s)}))};variants[v]={bodies,manifest};
 }
 await writeFile(path.join(out,'fixture-manifests.json'),json(Object.fromEntries(Object.entries(variants).map(([v,x])=>[v,x.manifest]))));await writeFile(path.join(out,'driver.mjs'),await readFile(fileURLToPath(import.meta.url)));await writeFile(path.join(out,'fixture.ts'),await readFile(fixture));
 report.identity={buildSHA256:sha(buildBytes),sourceDigest:receipt.sourceDigest,packSHA256:sha(packBytes),packVersion:fullPack.version,fullBytes:fullPack.files.reduce((n,f)=>n+f.bytes,0),fixtureSHA256:sha(await readFile(fixture)),driverSHA256:sha(await readFile(fileURLToPath(import.meta.url))),bundleSHA256:sha(bundle),workerSHA256:files.get('/service-worker.js').sha256,previousWorkerSHA256:sha(previousWorker)};
 if(args['--build-only']==='true'){report.status='compiled-only';report.noBrowserOrHost=true}else{
  const mime={'.html':'text/html','.js':'text/javascript','.json':'application/json','.wasm':'application/wasm','.png':'image/png','.svg':'image/svg+xml','.ogg':'audio/ogg','.mp3':'audio/mpeg','.woff2':'font/woff2','.txt':'text/plain'};
  server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://fixture'),p=decodeURIComponent(u.pathname);assert(!p.split('/').includes('..'));report.requests.push({phase,path:p,download:req.headers['x-frontline-pack-download']==='1'});
   if(p==='/upgrade-harness.html'){res.setHeader('Content-Type','text/html');res.end('<!doctype html><title>Offline transaction diagnostics</title><link rel="icon" href="data:,"><h1>Exact installer transaction diagnostics</h1>');return}
   if(mode==='offline'){res.statusCode=503;res.end('deliberate network unavailable');return}
   let body;if(p==='/service-worker.js'&&workerScript==='previous')body=previousWorker;else if(variants[generation].bodies[p]!==undefined&&mode!=='product')body=Buffer.from(variants[generation].bodies[p]);else{const f=files.get(p==='/'?'/index.html':p);if(!f){res.statusCode=404;res.end('unlisted');return}body=await readFile(path.join(product,(p==='/'?'/index.html':p).slice(1)));assert.equal(sha(body),f.sha256)}
   const send=()=>{res.setHeader('Content-Type',mime[path.extname(p)]??'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(body)};
   if(fault?.path===p&&req.headers['x-frontline-pack-download']==='1'){if(fault.kind==='hold'){held={send,path:p};return}if(fault.kind==='interrupt'){res.destroy();return}if(fault.kind==='corrupt')body=Buffer.alloc(body.length,88)}send();
  }catch(e){res.statusCode=500;res.end(String(e))}});await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;report.origin=origin;
  const launch=async()=>{const c=await({chromium,firefox,webkit})[engine].launchPersistentContext(profile,{headless:true,viewport:{width:1280,height:720}});await c.addInitScript({content:bundle});c.on('page',p=>{p.on('pageerror',e=>report.errors.push({phase,message:String(e)}));p.on('response',r=>{if(r.status()>=400)report.responses.push({phase,mode,url:r.url(),status:r.status()})});p.on('requestfailed',r=>report.failures.push({phase,mode,url:r.url(),reason:r.failure()?.errorText}))});return c};
  const wait=async(fn,label)=>{const deadline=Date.now()+30000;while(Date.now()<deadline){const value=await fn();if(value)return value;await new Promise(r=>setTimeout(r,20))}throw Error('Timed out: '+label)};
  context=await launch();let a=await context.newPage(),b=await context.newPage();for(const p of [a,b])await p.goto(origin+'/upgrade-harness.html');const cap=await a.evaluate(()=>window.offlineUpgradeQA.register());assert(cap.secure&&cap.locks,'Genuine Web Locks capability required; no simulated fallback pass');await b.evaluate(()=>window.offlineUpgradeQA.register());report.capabilities=cap;
  const install=(p,v,name='install')=>p.evaluate(({pack,name})=>window.offlineUpgradeQA.install(pack,name),{pack:variants[v].manifest,name});const state=p=>p.evaluate(()=>window.offlineUpgradeQA.state());const read=(p,url)=>p.evaluate(url=>window.offlineUpgradeQA.read(url),url);const active=async(p,v)=>{mode='offline';const r=await read(p,'/upgrade/shared.txt');assert.equal(r.status,200);assert.equal(r.text,'exact '+v);mode='online';return r};
  phase='install-A';let result=await install(a,'A');assert(result.ok);record(phase,result);await a.evaluate(()=>window.offlineUpgradeQA.retainIndex());
  phase='actual-previous-worker-upgrade';generation='B';const oldWorkerUpgrade=await install(b,'B');assert(oldWorkerUpgrade.ok);mode='offline';const oldFallback=await read(a,'/upgrade/retired.txt');assert.equal(oldFallback.status,200);assert.equal(oldFallback.text,'retired A');const oldTab=await a.evaluate(()=>window.offlineUpgradeQA.retainedMap('offline-fixture'));assert.equal(oldTab.error.code,'content_integrity');mode='online';workerScript='current';const update=await a.evaluate(()=>window.offlineUpgradeQA.updateWorker());mode='offline';assert.equal((await read(a,'/upgrade/retired.txt')).status,503);mode='online';record(phase,{previousWorkerSHA256:sha(previousWorker),oldFallback,oldTab,update,scope:'Exact previous worker diagnostic demonstrates retired-path resurrection before update; new worker refuses it. Installer helper is current v25 in both tabs.'});
  await install(a,'A');await a.evaluate(name=>window.offlineUpgradeQA.remove(name),oldWorkerUpgrade.value.cacheName);await active(a,'A');
  for(const kind of ['corrupt','interrupt','quota']){phase=kind+'-B';generation='B';fault={path:'/upgrade/shared.txt',kind};const before=await state(a);result=kind==='quota'?await a.evaluate(pack=>window.offlineUpgradeQA.quota(pack,'/upgrade/shared.txt'),variants.B.manifest):await install(a,'B');fault=undefined;assert.equal(result.ok,false);assert.equal(result.error.code,kind==='corrupt'?'content_corrupt':kind==='quota'?'content_cache_failed':'content_cache_failed');assert.deepEqual((await state(a)).names,before.names,'Failed staging cache remains');await active(a,'A');record(phase,result)}
  phase='cancel-B';generation='B';fault={path:'/upgrade/hold.bin',kind:'hold'};await a.evaluate(pack=>window.offlineUpgradeQA.start(pack,'cancel'),variants.B.manifest);await wait(()=>held,'held B request');await a.evaluate(()=>window.offlineUpgradeQA.abort('cancel'));result=await wait(()=>a.evaluate(()=>window.offlineUpgradeQA.result('cancel')),'canceled install');assert.equal(result.error.code,'download_canceled');held.send();held=undefined;fault=undefined;await active(a,'A');record(phase,result);
  phase='install-B-stale-A-tab';generation='B';result=await install(b,'B');assert(result.ok);await active(a,'B');mode='offline';const stale=await a.evaluate(()=>window.offlineUpgradeQA.retainedMap('offline-fixture'));assert.equal(stale.error.code,'content_integrity');assert.equal(stale.validatorCalls,0);assert.equal((await read(a,'/upgrade/retired.txt')).status,503);const fresh=await b.evaluate(()=>window.offlineUpgradeQA.retainIndex());assert.equal(fresh.version,'fixture-B');const newMap=await b.evaluate(()=>window.offlineUpgradeQA.retainedMap('offline-fixture'));assert.equal(newMap.validatorCalls,1);assert.match(newMap.error.message,/tiny_fixture_validation_boundary/);await a.evaluate(()=>window.offlineUpgradeQA.refreshIndex());const refreshedOldTab=await a.evaluate(()=>window.offlineUpgradeQA.retainedMap('offline-fixture'));assert.equal(refreshedOldTab.validatorCalls,1);mode='online';record(phase,{result,stale,newIndexVersion:fresh.version,newMap,refreshedOldTab,artMetadataPairing:'Not established; actual ArtLibrary lacks per-file expected hashes and remains a separately reported stale-tab risk'});
  phase='unchanged-B';const count=report.requests.filter(r=>r.download).length;result=await install(a,'B');assert(result.ok);assert.equal(report.requests.filter(r=>r.download).length,count);record(phase,result);
  phase='rollback-A';result=await install(a,'A');assert(result.ok);await active(b,'A');const before=await state(a);result=await a.evaluate(pack=>window.offlineUpgradeQA.canceled(pack),variants.B.manifest);assert.equal(result.error.code,'download_canceled');assert.deepEqual(await state(a),before);record(phase,{canceledRollback:result});
  phase='concurrent-completion';generation='C';fault={path:'/upgrade/hold.bin',kind:'hold'};await a.evaluate(pack=>window.offlineUpgradeQA.start(pack,'slow'),variants.C.manifest);await wait(()=>held,'slow C download');fault=undefined;const interim=await install(b,'B');assert(interim.ok);held.send();held=undefined;result=await wait(()=>a.evaluate(()=>window.offlineUpgradeQA.result('slow')),'slow C completed');assert(result.ok&&result.value.installedAt>interim.value.installedAt);await active(b,'C');record(phase,{earlier:interim,later:result});
  phase='cancel-real-lock-wait';await b.evaluate(()=>window.offlineUpgradeQA.hold('offline-qa'));await a.evaluate(pack=>window.offlineUpgradeQA.start(pack,'waiting'),variants.A.manifest);await wait(async()=>{const q=await a.evaluate(()=>window.offlineUpgradeQA.locks());return q.pending.some(x=>x.name.endsWith('activate:offline-qa'))},'real other-tab activation wait');await a.evaluate(()=>window.offlineUpgradeQA.abort('waiting'));result=await wait(()=>a.evaluate(()=>window.offlineUpgradeQA.result('waiting')),'lock waiter canceled');assert.equal(result.error.code,'download_canceled');await b.evaluate(()=>window.offlineUpgradeQA.unlock());await active(a,'C');record(phase,result);
  phase='legacy-tie';let caches=(await state(a)).installed.filter(x=>['fixture-A','fixture-B'].includes(x.version));await a.evaluate(names=>window.offlineUpgradeQA.tie(names,Date.now()+10000),caches.map(x=>x.cacheName));caches=caches.sort((x,y)=>x.cacheName<y.cacheName?-1:1);await active(a,caches[0].version.slice(-1));result=await install(b,caches[1].version.slice(-1));assert(result.ok);await active(a,caches[1].version.slice(-1));record(phase,result);
  phase='cold-tiny-cache';generation='B';await install(a,'B');await context.close();context=await launch();await context.setOffline(true);a=await context.newPage();await a.goto(origin+'/upgrade-shell.html');assert.equal(await a.locator('html').getAttribute('data-generation'),'B');await a.screenshot({path:path.join(out,'cold-tiny.png')});record(phase,{browserRestarted:true,offline:true,generation:'B',scope:'Tiny self-contained cached document, no Go gameplay claim'});
  if(args['--full-pack']==='true'){
   phase='full-v25-install';await context.setOffline(false);mode='product';await a.goto(origin+'/upgrade-harness.html');await a.evaluate(()=>window.offlineUpgradeQA.clear());result=await a.evaluate(pack=>window.offlineUpgradeQA.install(pack,'full'),fullPack);assert(result.ok);record(phase,{...result,bytes:report.identity.fullBytes});
   await context.close();context=await launch();await context.addInitScript({content:observation});await context.setOffline(true);phase='full-v25-cold-App';a=await context.newPage();await a.goto(origin+'/');await a.getByRole('button',{name:'Explore game modes',exact:true}).click();await a.getByRole('navigation',{name:'Main menu'}).getByRole('button',{name:'Skirmish',exact:true}).click();await a.getByLabel('Battlefield',{exact:true}).selectOption('copper-junction');await a.getByLabel('AI commanders',{exact:true}).selectOption('1');await a.getByLabel('Difficulty',{exact:true}).selectOption('easy');const baseline=await a.evaluate(()=>window.__stockQA.read().workers.filter(w=>w.live).length);await a.getByRole('button',{name:'Deploy forces',exact:true}).click();await a.locator('.battlefield-canvas canvas').waitFor({timeout:120000});await a.waitForFunction(()=>window.__stockQA.read().latest?.tick>120,null,{timeout:120000});await a.getByRole('button',{name:'Open pause menu'}).click();await a.getByRole('button',{name:'Save operation',exact:true}).click();await a.waitForFunction(()=>window.__stockQA.read().saves.length>0);const actual=await a.evaluate(()=>window.__stockQA.read());assert.equal(actual.latest.metadata.simulation,'0.3.4');assert(actual.saves.at(-1).hash);assert.deepEqual(actual.errors,[]);await a.screenshot({path:path.join(out,'full-cold-Go.png')});await a.getByRole('button',{name:'Return to command center',exact:true}).click();await a.getByRole('navigation',{name:'Main menu'}).waitFor();await a.waitForFunction(n=>!document.querySelector('.battlefield-canvas canvas')&&window.__stockQA.read().workers.filter(w=>w.live).length===n,baseline);record(phase,{browserRestarted:true,offline:true,latest:actual.latest,saves:actual.saves,scope:'Actual cold full App + deterministic bot startup and manual Go save, not complete gameplay/audio review'});
  }
  assert.deepEqual(report.errors,[]);report.responseClassification=report.responses.map(r=>({...r,expected:r.mode==='offline'&&r.status===503&&new URL(r.url).pathname==='/upgrade/retired.txt'}));assert(report.responseClassification.every(r=>r.expected),'Unexpected effective HTTP error');report.failureClassification=report.failures.map(r=>({...r,expected:(r.phase==='interrupt-B'&&new URL(r.url).pathname==='/upgrade/shared.txt')||(r.phase==='cancel-B'&&new URL(r.url).pathname==='/upgrade/hold.bin')||(['cold-tiny-cache','full-v25-cold-App'].includes(r.phase)&&new URL(r.url).origin===origin)}));assert(report.failureClassification.every(r=>r.expected),'Unexpected request failure');report.status='passed';report.artStaleTabGate='OPEN: transaction/model coherence does not certify retained old atlas metadata against newly loaded pages';
 }
}catch(e){report.status='failed';report.phase=phase;report.failure=String(e.stack??e);process.exitCode=1}
finally{if(held)held.send();await context?.close();if(server?.listening)await new Promise(r=>server.close(r));if(temp)await rm(temp,{recursive:true,force:true});try{for(const [p,h]of guards)assert.equal(sha(await readFile(p)),h);report.inputsVerifiedAfter=guards.size}catch(e){report.status='failed';report.drift=String(e);process.exitCode=1}report.closedAt=new Date().toISOString();await writeFile(path.join(out,'receipt.json'),json(report));console.log(json({out,status:report.status,failure:report.failure,cases:report.cases.length}))}
