import {chromium,firefox,webkit} from 'playwright-core';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
const output=new URL('../../../work/evidence/audio-runtime/',import.meta.url);await mkdir(output,{recursive:true});
function wave(seconds=2){const rate=24000,n=rate*seconds,bytes=Buffer.alloc(44+n*2);bytes.write('RIFF');bytes.writeUInt32LE(bytes.length-8,4);bytes.write('WAVEfmt ',8);bytes.writeUInt32LE(16,16);bytes.writeUInt16LE(1,20);bytes.writeUInt16LE(1,22);bytes.writeUInt32LE(rate,24);bytes.writeUInt32LE(rate*2,28);bytes.writeUInt16LE(2,32);bytes.writeUInt16LE(16,34);bytes.write('data',36);bytes.writeUInt32LE(n*2,40);for(let i=0;i<n;i++)bytes.writeInt16LE(Math.round(Math.sin(i*2*Math.PI*200/rate)*2000),44+i*2);return bytes}
const bytes=wave(),sha256=createHash('sha256').update(bytes).digest('hex'),variant=id=>({url:`/art/audio/test/${id}.wav`,caption:id,duration:2,bytes:bytes.length,sha256}),entry=(id,bus,priority=0,loop=false)=>({bus,priority,loop,cooldown_ms:0,variants:[variant(id)]});
const manifest={format:1,sample_rate:24000,entries:{'sfx.test':entry('effect','effects'),'sfx.engine_test':entry('engine','effects',0,true),'sfx.ui_click':entry('ui','ui'),'vo.routine':entry('routine','voice',10),'vo.critical':entry('critical','voice',100),'vo.late':entry('late','voice',100),'music.calm':entry('calm','music',0,true),'music.tension':entry('tension','music',0,true),'music.combat':entry('combat','music',0,true)}};
const browserType=({chromium,firefox,webkit})[process.env.FRONTLINE_AUDIO_BROWSER??'chromium'];const browser=await browserType.launch({headless:true}),errors=[],results={date:new Date().toISOString(),browser:`${browserType.name()} ${browser.version()} / actual WebAudio`,fixture:'Synthetic PCM diagnostic signal; not a listening-quality review',checks:{}};
try{const page=await browser.newPage({viewport:{width:1280,height:720}});page.on('pageerror',error=>errors.push(error.message));await page.routeWebSocket('**',socket=>socket.onMessage(()=>{}));await page.route('**/art/audio/index.json',route=>route.fulfill({json:manifest}));await page.route('**/art/audio/test/*.wav',route=>route.fulfill({contentType:'audio/wav',body:bytes}));await page.goto('http://127.0.0.1:5173/tests/audio/index.html');await page.evaluate(async()=>{const {AudioMixer}=await import('/src/audio/mixer.ts');window.preferences={audioConsent:false,audio:{master:.8,music:.6,effects:.8,voice:.9,ui:.6},captions:true};window.mixer=new AudioMixer(window.preferences);mixer.attach();await mixer.loadIndex();mixer.state.subscribe(()=>document.querySelector('#captions').textContent=mixer.state.get().captions.map(c=>c.text).join(' / '))});await page.click('#gesture');assert.equal(await page.evaluate(()=>mixer.statistics.context),'absent');await page.evaluate(()=>{mixer.play('vo.routine');window.preferences={...preferences,audioConsent:true};mixer.update(preferences);window.dispatchEvent(new PointerEvent('pointerdown'))});assert.equal(await page.evaluate(()=>mixer.statistics.context),'absent');results.checks.consent='Denied and synthetic events create no context; captions still work';await page.click('#gesture');await page.waitForFunction(()=>mixer.statistics.context==='running');await page.evaluate(()=>mixer.play('vo.routine'));await page.waitForFunction(()=>mixer.statistics.sources>0);const signal=await page.evaluate(async()=>{const analyser=mixer.context.createAnalyser();mixer.master.connect(analyser);await new Promise(resolve=>setTimeout(resolve,150));const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);analyser.disconnect();return Math.max(...data.map(Math.abs))});assert.ok(signal>0&&Number.isFinite(signal));results.checks.actualOutput={peak:signal};
await page.evaluate(()=>{preferences={...preferences,audio:{master:.4,music:.3,effects:.2,voice:.1,ui:0}};mixer.update(preferences)});await page.waitForFunction(()=>Math.abs(mixer.statistics.gains.master-.4)<1e-6);const gains=await page.evaluate(()=>mixer.statistics.gains);for(const [name,value]of Object.entries({master:.4,music:.3,effects:.2,voice:.1,ui:0}))assert.ok(Math.abs(gains[name]-value)<1e-6);results.checks.buses=gains;
await page.evaluate(()=>mixer.play('vo.critical'));await page.waitForFunction(()=>[...mixer.sources].some(s=>s.bus==='voice'&&s.priority===100));assert.equal(await page.evaluate(()=>[...mixer.sources].filter(s=>s.bus==='voice'&&s.priority===10).length),0);await page.evaluate(()=>mixer.play('vo.routine'));assert.equal(await page.evaluate(()=>[...mixer.sources].filter(s=>s.bus==='voice').length),1);results.checks.priority='Critical source interrupts routine; lower-priority speech cannot displace it';
await page.evaluate(()=>{preferences={...preferences,audio:{...preferences.audio,master:0}};mixer.update(preferences);mixer.play('vo.critical',{key:'muted-warning',cooldown:6000});mixer.play('vo.critical',{key:'muted-warning',cooldown:6000})});assert.ok(await page.locator('#captions').innerText().then(text=>text.includes('critical')));const before=await page.evaluate(()=>mixer.captionID);await page.evaluate(()=>mixer.play('vo.critical',{key:'muted-warning',cooldown:6000}));assert.equal(await page.evaluate(()=>mixer.captionID),before);results.checks.mutedCaptions='Critical caption immediate at master zero; duplicate warning bundled';
await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForFunction(()=>mixer.statistics.context==='suspended');assert.equal(await page.evaluate(()=>mixer.statistics.sources),0);await page.click('#gesture');await page.waitForFunction(()=>mixer.statistics.context==='running');results.checks.focus='Blur suspends output and clears transient sources; trusted gesture resumes';
await page.evaluate(()=>{mixer.reset();preferences={...preferences,audio:{...preferences.audio,master:.8}};mixer.update(preferences);mixer.music(['music.calm','music.tension','music.combat'],[1,0,0])});await page.waitForFunction(()=>mixer.musicSources.length===3);await page.evaluate(()=>mixer.music(['music.calm','music.tension','music.combat'],[0,0,1]));await page.waitForTimeout(1200);assert.ok(await page.evaluate(()=>mixer.musicSources[2].gain.gain.value>.8));results.checks.music='Three actual looping sources share start origin; combat layer crossfade changes gains';
await page.evaluate(()=>mixer.continuous(Array.from({length:8},(_,i)=>({key:`actor:${i}`,id:'sfx.engine_test',gain:.1,pan:i%2?.5:-.5}))));await page.waitForFunction(()=>mixer.statistics.continuous===4);assert.equal(await page.evaluate(()=>mixer.continuousRequests.size),4);assert.ok(await page.evaluate(()=>[...mixer.continuousSources.values()].every(source=>Math.abs(source.panner.pan.value)===.5)));await page.evaluate(()=>mixer.continuous([{key:'actor:2',id:'sfx.engine_test',gain:.07,pan:0}]));assert.equal(await page.evaluate(()=>mixer.statistics.continuous),1);await page.evaluate(()=>mixer.continuous([]));assert.equal(await page.evaluate(()=>mixer.statistics.continuous),0);results.checks.continuous='Eight requests capped to four real sources; stereo placement applies; removing/fogging requests stops sources immediately';
await page.evaluate(()=>{mixer.music([]);mixer.play('sfx.test')});await page.waitForFunction(()=>mixer.pending.size===0);await page.context().setOffline(true);await page.evaluate(()=>{mixer.stopTransient();mixer.play('sfx.test')});await page.waitForFunction(()=>mixer.statistics.sources>0);results.checks.offline='Decoded cached effect plays with browser network disabled';await page.context().setOffline(false);
let release;const late=new Promise(resolve=>release=resolve);await page.route('**/art/audio/test/late.wav',async route=>{await late;await route.fulfill({contentType:'audio/wav',body:bytes}).catch(()=>{})});await page.evaluate(()=>{mixer.stopTransient();mixer.play('vo.late')});await page.waitForFunction(()=>mixer.statistics.pending===1);await page.evaluate(()=>mixer.reset());release();await page.waitForTimeout(200);assert.equal(await page.evaluate(()=>mixer.statistics.sources),0);assert.equal(await page.evaluate(()=>mixer.statistics.decodedBytes),0);results.checks.lateLoad='Reset aborts pending load and no old source/buffer appears';
for(let i=0;i<3;i++){await page.evaluate(()=>mixer.play('sfx.test'));await page.waitForFunction(()=>mixer.statistics.sources>0);await page.evaluate(()=>mixer.reset());assert.equal(await page.evaluate(()=>mixer.statistics.decodedBytes),0);assert.equal(await page.evaluate(()=>mixer.statistics.sources),0)}results.checks.cleanup='Three consecutive generations return to zero sources and buffers';await page.evaluate(()=>{preferences={...preferences,audioConsent:false};mixer.update(preferences)});await page.waitForFunction(()=>mixer.statistics.context==='suspended');await page.evaluate(()=>mixer.dispose());await page.click('#gesture');assert.equal(await page.evaluate(()=>mixer.statistics.context),'absent');results.checks.withdrawal='Consent withdrawal suspends; disposal removes gesture listeners and closes context';assert.deepEqual(errors,[]);results.status='passed';
}catch(error){results.status='failed';results.error=String(error.stack??error);results.diagnostics=await browser.contexts()[0]?.pages()[0]?.evaluate(()=>({state:window.mixer?.state.get(),stats:window.mixer?.statistics,index:!!window.mixer?.manifest})).catch(()=>{});process.exitCode=1}finally{results.errors=errors;await writeFile(new URL(`${browserType.name()}-results.json`,output),JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify(results,null,2))}
