// Actual product interaction check against the local dev/preview server.
import {chromium} from 'playwright-core';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),evidence=path.join(root,'work/evidence/product-ui');await mkdir(evidence,{recursive:true});
const browser=await chromium.launch({headless:true}),errors=[],failed=[],results={date:new Date().toISOString(),url:process.env.FRONTLINE_UI_URL??'http://127.0.0.1:5173',browser:browser.version(),browserPlugin:'Browser skill not installed; existing Playwright used.',checks:{}};
try{
 const page=await browser.newPage({viewport:{width:1600,height:900}});page.on('pageerror',error=>errors.push(error.message));page.on('response',response=>{if(response.status()>=400)failed.push(`${response.status()} ${response.url()}`)});
 await page.goto(results.url);assert.equal(await page.title(),'Frontline Command');await page.getByRole('button',{name:'Explore game modes'}).waitFor({timeout:30000});await page.screenshot({path:path.join(evidence,'first-run-1600.png')});await page.getByRole('button',{name:'Explore game modes'}).click();results.checks.firstRun='passed';
 await page.getByRole('button',{name:'Deploy to skirmish'}).click();await page.screenshot({path:path.join(evidence,'skirmish-1600.png')});await page.getByRole('button',{name:'Deploy forces'}).click();await page.locator('.battlefield-canvas canvas').waitFor({timeout:30000});await page.locator('.countdown').waitFor({state:'hidden',timeout:15000});await page.getByRole('button',{name:'Build',exact:true}).click();
 await page.locator('.production-cameo').filter({hasText:'Power station'}).click();await page.mouse.move(530,560);await page.waitForTimeout(350);await page.screenshot({path:path.join(evidence,'placement.png')});await page.mouse.click(530,560);await page.waitForFunction(()=>document.querySelector('.resource-shoulder b')?.textContent==='5,500');results.checks.build='Power station submitted through UI; authoritative credits6000→5500';
 await page.getByRole('button',{name:'HQ',exact:true}).click();const rig=page.locator('.production-cameo').filter({hasText:'Engineering rig'});await rig.waitFor({timeout:10000});await rig.click();await page.waitForFunction(()=>document.querySelector('.production-queue')?.textContent?.includes('Engineering rig'));results.checks.train='HQ job appears in authoritative production queue';
 await page.getByRole('button',{name:'Open pause menu'}).click();await page.getByRole('button',{name:'Save operation',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.notice')?.textContent?.includes('Saved: Copper Junction'));results.checks.save='Manual operation stored with Go validation';
 const balance=await page.locator('.resource-shoulder b').innerText();await page.getByRole('button',{name:'Return to command center'}).click();await page.getByRole('button',{name:'Load operation',exact:true}).click();await page.locator('.archive-row').filter({hasText:'Copper Junction'}).first().getByRole('button',{name:'Load',exact:true}).click();await page.locator('.battlefield-canvas canvas').waitFor({timeout:30000});await page.waitForTimeout(500);assert.equal(await page.locator('.resource-shoulder b').innerText(),balance);results.checks.restore='Saved paid economy restored into actual battlefield';
 await page.getByRole('button',{name:'Build',exact:true}).click();await page.waitForTimeout(700);await page.screenshot({path:path.join(evidence,'battle-1600.png')});
 for(const size of [{width:1600,height:900},{width:1280,height:720}]){await page.setViewportSize(size);await page.waitForTimeout(300);const area=await page.evaluate(()=>{const sidebar=document.querySelector('.command-sidebar').getBoundingClientRect(),tray=document.querySelector('.selection-tray').getBoundingClientRect(),shoulder=document.querySelector('.resource-shoulder').getBoundingClientRect();return 1-(sidebar.width*sidebar.height+tray.width*tray.height+shoulder.width*shoulder.height)/(innerWidth*innerHeight)});assert.ok(area>=.7,`Unobstructed battlefield must remain70%, got${area}`);results.checks[`${size.width}x${size.height}`]={unobstructedWorld:area};await page.screenshot({path:path.join(evidence,`battle-${size.width}.png`)})}
 await page.getByRole('button',{name:'Open pause menu'}).click();await page.getByRole('button',{name:'Options',exact:true}).click();await page.getByLabel('Interface scale',{exact:true}).selectOption('1.5');await page.waitForTimeout(300);await page.screenshot({path:path.join(evidence,'options-scale150-1280.png')});results.checks.scale150='Options modal remains scrollable and operable';
 assert.equal(await page.locator('vite-error-overlay').count(),0);assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);results.checks.console='No page exceptions or failed HTTP responses';results.status='passed';
}catch(error){const failedPage=browser.contexts()[0]?.pages()[0];if(failedPage){results.body=await failedPage.locator('body').innerText();await failedPage.screenshot({path:path.join(evidence,'failure.png')})}results.status='failed';results.error=String(error.stack??error);process.exitCode=1}finally{results.errors=errors;results.failedRequests=failed;await writeFile(path.join(evidence,'smoke-results.json'),JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify(results,null,2))}
