import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import {pathToFileURL,fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';import {build} from '../../../client/node_modules/esbuild/lib/main.js';import {Container,Graphics} from '../../../client/node_modules/pixi.js/lib/index.mjs';
const work=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(work,'../../..'),base=path.join(root,'work/renderer-performance-browser-v1/prepared/candidate/src'),pixi=path.join(root,'client/node_modules/pixi.js/lib/index.mjs'),sha=b=>createHash('sha256').update(b).digest('hex'),results=[];
// Real Pixi ownership/Graphics; only Text metrics are a deterministic Node stub.
// Native font rasterization and exact pixels remain a separate browser gate.
const textStub=`export * from ${JSON.stringify(pixi)};import {Container,ObservablePoint} from ${JSON.stringify(pixi)};export class Text extends Container{constructor(o){super();this.text=o.text;this.style=o.style;this.anchor=new ObservablePoint({_onUpdate(){}},0,0)}get width(){return this.text.length*this.style.fontSize*.55}get height(){return this.style.fontSize*1.2}}`;
let clock=0;const warn=console.warn,group=console.groupCollapsed,end=console.groupEnd;const warnings=[];console.warn=(...a)=>warnings.push(a.map(String).join(' '));console.groupCollapsed=(...a)=>warnings.push(a.map(String).join(' '));console.groupEnd=()=>{};
const snapshots=[],violations=[],addChild=Container.prototype.addChild;Container.prototype.addChild=function(...children){if(!this.allowChildren)violations.push(this.constructor.name);return addChild.apply(this,children)};
try{for(const variant of ['baseline','candidate']){
 const source=await readFile(variant==='baseline'?path.join(base,'render/battlefield.ts'):path.join(work,'candidate-battlefield.ts'),'utf8'),out=path.join(work,`${variant}-probe.mjs`);
 await build({stdin:{contents:"export {BattlefieldRenderer} from './render/battlefield';export {TerrainSurface} from './render/terrain-surface';",resolveDir:base,loader:'ts'},outfile:out,platform:'node',format:'esm',bundle:true,nodePaths:[path.join(root,'client/node_modules')],plugins:[{name:'real-pixi-fixed-text-metrics',setup(b){b.onResolve({filter:/^pixi\.js$/},()=>({path:'pixi-probe',namespace:'probe'}));b.onResolve({filter:/\/pixi\.js\/lib\/index\.mjs$/},a=>({path:a.path,external:true}));b.onLoad({filter:/.*/,namespace:'probe'},()=>({contents:textStub,loader:'js'}));b.onLoad({filter:/render\/battlefield\.ts$/},()=>({contents:source,loader:'ts'}))}}]});
 const {BattlefieldRenderer,TerrainSurface}=await import(pathToFileURL(out).href);
 for(const scale of [.85,1,1.5]){
  const map={width:16,height:16,tiles:Array.from({length:256},()=>({terrain:'open',height:2}))},surface=new TerrainSurface(map),memory=(id,x,y,type='power',seen=100)=>({id,type,position:{x:x*1000,y:y*1000},footprintWidth:3,footprintHeight:3,footprintType:'',seen,owner:2});
  const snapshot={tick:200,entities:[{id:6}],visible:Array(256).fill(false),explored:Array(256).fill(true),memory:[memory(1,5,5),memory(2,8,5,'hq'),memory(3,1,1),memory(4,2,1),memory(5,3,1,'power',300),memory(6,4,1)]};snapshot.explored[17]=false;snapshot.visible[18]=true;const original=structuredClone(snapshot),ground=new Container(),scene={snapshot,options:{map,catalog:{buildings:new Map([['power',{width:3,height:3,role:'power'}],['hq',{width:4,height:4,role:'hq'}]])}},settings:{uiScale:scale},surface,memoryKey:'',memories:[],memoryLabels:[],ground};
  const warningBefore=warnings.length,violationBefore=violations.length;BattlefieldRenderer.prototype.updateMemories.call(scene);const newWarnings=warnings.slice(warningBefore),newViolations=violations.slice(violationBefore);assert.equal(newViolations.length,variant==='baseline'?2:0);assert.equal(scene.memories.length,2);assert.equal(scene.memoryLabels.length,2);assert.deepEqual(snapshot,original);
  const shape=(g)=>g.context.instructions.map(i=>({action:i.action,data:{...Object.fromEntries(Object.entries(i.data).filter(([k])=>!['style','path'].includes(k))),style:i.data.style&&Object.fromEntries(Object.entries(i.data.style).filter(([k])=>!['texture','matrix'].includes(k))),path:i.data.path?.instructions}}));
  const rows=scene.memories.map((holder,i)=>{const label=scene.memoryLabels[i],g=variant==='baseline'?holder:holder.children[0];assert(g instanceof Graphics);assert.equal(label.eventMode,'none');assert.equal(label.parent,holder);if(variant==='candidate'){assert(holder instanceof Container&&!(holder instanceof Graphics));assert.deepEqual(holder.children,[g,label]);assert.equal(g.children.length,0);assert.equal(holder.alpha,.55);assert.equal(g.alpha,1)}const text=label.children[1];return {x:holder.x,y:holder.y,z:holder.zIndex,effectiveShapeAlpha:variant==='baseline'?g.alpha:holder.alpha*g.alpha,effectiveTagAlpha:holder.alpha*label.alpha,tagPosition:{x:label.x,y:label.y},text:text.text,style:text.style,anchor:{x:text.anchor.x,y:text.anchor.y},geometry:shape(g),plate:shape(label.children[0])}});
  const unchangedRoots=[...scene.memories];BattlefieldRenderer.prototype.updateMemories.call(scene);assert.deepEqual(scene.memories,unchangedRoots,'Unchanged knowledge reuses roots');
  const children=scene.memories.flatMap(r=>[r,...r.children,...r.children.flatMap(c=>c.children)]);scene.snapshot={...snapshot,memory:[]};BattlefieldRenderer.prototype.updateMemories.call(scene);assert.equal(ground.children.length,0);assert.equal(scene.memories.length,0);assert.equal(scene.memoryLabels.length,0);assert(children.every(c=>c.destroyed),'Replaced remembered roots and descendants are released');
  ground.destroy({children:true});results.push({variant,scale,sourceSHA256:sha(source),visibleRememberedRoots:2,hiddenOrCurrentOrFutureExcluded:4,snapshotUnchanged:true,unchangedRootIdentity:true,disposedDescendants:children.length,warnings:newWarnings,nonContainerChildAdditions:newViolations.length});snapshots.push({variant,scale,rows});
 }
}
const before=snapshots.filter(x=>x.variant==='baseline'),after=snapshots.filter(x=>x.variant==='candidate');for(let i=0;i<before.length;i++)assert.deepEqual(after[i].rows,before[i].rows,'Geometry, retained physical depth, text/plate metrics and inherited alpha exact');assert(results.filter(x=>x.variant==='candidate').every(x=>x.warnings.length===0));assert(results.some(x=>x.variant==='baseline'&&x.warnings.some(s=>s.includes('Only Containers'))));
}finally{Container.prototype.addChild=addChild;console.warn=warn;console.groupCollapsed=group;console.groupEnd=end}
const report={status:'PASS_SOURCE_OWNERSHIP_AND_LIFETIME',scope:'Actual updateMemories method, TerrainSurface, drawStructure, real Pixi Container/Graphics; deterministic Text metrics only. No native pixel or font acceptance.',results};await writeFile(path.join(work,'result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
