// Code generated by go run ./gen; DO NOT EDIT.
package viewproto

import (
	"frontlinecommand/pkg/content"
	"frontlinecommand/pkg/sim"
	pb "frontlinecommand/protocol"
)

func toCombatFeedback(v sim.CombatFeedback) *pb.CombatFeedback {
	return &pb.CombatFeedback{
		Weapon:         text(v.Weapon),
		Outcome:        text(v.Outcome),
		TargetArmor:    text(v.TargetArmor),
		CoverMitigated: v.CoverMitigated,
	}
}
func toConvoyProgress(v sim.ConvoyState) *pb.ConvoyProgress {
	return &pb.ConvoyProgress{
		Id:             text(v.ID),
		Active:         v.Active,
		Completed:      v.Completed,
		Held:           v.Held,
		Moving:         v.Moving,
		Route:          v.Route,
		Waypoint:       v.Waypoint,
		CountdownUntil: uint32(v.CountdownUntil),
		Approved:       list(v.Approved, func(v sim.PlayerID) uint32 { return uint32(v) }),
	}
}
func toCooldown(v sim.Cooldown) *pb.Cooldown {
	return &pb.Cooldown{
		Id:    text(v.ID),
		Until: uint32(v.Until),
	}
}
func toDebrief(v sim.Debrief) *pb.Debrief {
	return &pb.Debrief{
		Players:       list(v.Players, func(v sim.DebriefPlayer) *pb.DebriefPlayer { return toDebriefPlayer(v) }),
		Events:        list(v.Events, func(v sim.DebriefEvent) *pb.DebriefEvent { return toDebriefEvent(v) }),
		OmittedEvents: v.OmittedEvents,
	}
}
func toDebriefEvent(v sim.DebriefEvent) *pb.DebriefEvent {
	return &pb.DebriefEvent{
		Tick:   uint32(v.Tick),
		Kind:   text(v.Kind),
		Player: uint32(v.Player),
		Type:   text(v.Type),
		Text:   text(v.Text),
	}
}
func toDebriefPlayer(v sim.DebriefPlayer) *pb.DebriefPlayer {
	return &pb.DebriefPlayer{
		Player:              uint32(v.Player),
		Name:                text(v.Name),
		Faction:             text(v.Faction),
		Team:                v.Team,
		Color:               v.Color,
		Defeated:            v.Defeated,
		Credits:             v.Credits,
		Income:              v.Income,
		Spent:               v.Spent,
		LostValue:           v.LostValue,
		UnitsSurviving:      v.UnitsSurviving,
		StructuresSurviving: v.StructuresSurviving,
		ExploredTiles:       v.ExploredTiles,
		Metrics:             toPlayerTelemetry(v.Metrics),
	}
}
func toEconomy(v sim.EconomyView) *pb.Economy {
	return &pb.Economy{
		Credits:        v.Credits,
		Energy:         v.Energy,
		Supply:         v.Supply,
		ReservedSupply: v.ReservedSupply,
		PowerCapacity:  v.PowerCapacity,
		PowerDemand:    v.PowerDemand,
		Tier:           v.Tier,
		Income:         v.Income,
		RepairReserve:  v.RepairReserve,
		Upgrades:       list(v.Upgrades, func(v string) string { return text(v) }),
		Cooldowns:      list(v.Cooldowns, func(v sim.Cooldown) *pb.Cooldown { return toCooldown(v) }),
		LastSequence:   v.LastSequence,
	}
}
func toEconomySample(v sim.EconomySample) *pb.EconomySample {
	return &pb.EconomySample{
		Tick:     uint32(v.Tick),
		Credits:  v.Credits,
		Income:   v.Income,
		Spent:    v.Spent,
		Supply:   v.Supply,
		Stations: v.Stations,
	}
}
func toEntity(v sim.EntityView) *pb.Entity {
	return &pb.Entity{
		Id:              uint32(v.ID),
		Type:            text(v.Type),
		Owner:           uint32(v.Owner),
		Position:        toVec(v.Position),
		Facing:          v.Facing,
		Health:          v.Health,
		State:           text(v.State),
		Complete:        v.Complete,
		Enabled:         v.Enabled,
		Landed:          v.Landed,
		Deployed:        v.Deployed,
		Concealed:       v.Concealed,
		Progress:        v.Progress,
		Rank:            v.Rank,
		Private:         optional(v.Private, func(v sim.EntityPrivate) *pb.EntityPrivate { return toEntityPrivate(v) }),
		TurretFacing:    v.TurretFacing,
		ChannelUntil:    uint32(v.ChannelUntil),
		MapObject:       v.MapObject,
		FootprintWidth:  v.FootprintWidth,
		FootprintHeight: v.FootprintHeight,
		FootprintType:   text(v.FootprintType),
		Effects:         list(v.Effects, func(v sim.StatusEffect) *pb.StatusEffect { return toStatusEffect(v) }),
	}
}
func toEntityPrivate(v sim.EntityPrivate) *pb.EntityPrivate {
	return &pb.EntityPrivate{
		Hp:                    v.HP,
		MaxHp:                 v.MaxHP,
		Jobs:                  list(v.Jobs, func(v sim.Job) *pb.Job { return toJob(v) }),
		Orders:                list(v.Orders, func(v sim.Order) *pb.Order { return toOrder(v) }),
		Rally:                 toVec(v.Rally),
		Cargo:                 v.Cargo,
		Home:                  uint32(v.Home),
		Ammo:                  v.Ammo,
		Endurance:             v.Endurance,
		Charges:               v.Charges,
		ChargeWork:            v.ChargeWork,
		ServiceWork:           v.ServiceWork,
		Experience:            v.Experience,
		Cooldowns:             list(v.Cooldowns, func(v sim.Cooldown) *pb.Cooldown { return toCooldown(v) }),
		Passengers:            list(v.Passengers, func(v sim.ID) uint32 { return uint32(v) }),
		Container:             uint32(v.Container),
		RepeatSortie:          v.RepeatSortie,
		AmbushReady:           v.AmbushReady,
		MissionOrigin:         text(v.MissionOrigin),
		EmergencyTakeoffUntil: pointer(uint32(v.EmergencyTakeoffUntil)),
		Ranges:                optional(v.Ranges, func(v sim.EntityRanges) *pb.EntityRanges { return toEntityRanges(v) }),
		Field:                 v.Field,
		Depot:                 uint32(v.Depot),
		PinnedField:           v.PinnedField,
		PinnedDepot:           uint32(v.PinnedDepot),
		RetreatWhenAttacked:   v.RetreatWhenAttacked,
		Retreating:            v.Retreating,
		HarvestQueuePosition:  v.HarvestQueuePosition,
		HarvestQueueLength:    v.HarvestQueueLength,
		ShahedCommitted:       v.ShahedCommitted,
		ReconObserve:          v.ReconObserve,
	}
}
func toEntityRanges(v sim.EntityRanges) *pb.EntityRanges {
	return &pb.EntityRanges{
		SightRadius:     v.SightRadius,
		DetectionRadius: v.DetectionRadius,
		AirborneSight:   v.AirborneSight,
		BuildRadius:     v.BuildRadius,
		Interception:    optional(v.Interception, func(v sim.InterceptionView) *pb.InterceptionView { return toInterceptionView(v) }),
	}
}
func toEvent(v sim.Event) *pb.Event {
	return &pb.Event{
		Id:       v.ID,
		Tick:     uint32(v.Tick),
		Kind:     text(v.Kind),
		Owner:    uint32(v.Owner),
		Entity:   uint32(v.Entity),
		Position: toVec(v.Position),
		Value:    v.Value,
		Scope:    text(v.Scope),
		Text:     text(v.Text),
		Combat:   optional(v.Combat, func(v sim.CombatFeedback) *pb.CombatFeedback { return toCombatFeedback(v) }),
	}
}
func toField(v sim.FieldView) *pb.Field {
	return &pb.Field{
		Id:        v.ID,
		Position:  toVec(v.Position),
		Remaining: v.Remaining,
	}
}
func toFieldObservation(v sim.FieldObservation) *pb.FieldObservation {
	return &pb.FieldObservation{
		Id:        v.ID,
		Position:  toVec(v.Position),
		Remaining: v.Remaining,
		Seen:      uint32(v.Seen),
	}
}
func toInterceptionAssignment(v sim.InterceptionAssignment) *pb.InterceptionAssignment {
	return &pb.InterceptionAssignment{
		Projectile:  uint32(v.Projectile),
		Impact:      toVec(v.Impact),
		InterceptAt: uint32(v.InterceptAt),
	}
}
func toInterceptionView(v sim.InterceptionView) *pb.InterceptionView {
	return &pb.InterceptionView{
		Radius:           v.Radius,
		Capacity:         v.Capacity,
		Active:           v.Active,
		Ready:            v.Ready,
		RechargeRequired: v.RechargeRequired,
		RechargeRate:     v.RechargeRate,
		NextChargeTicks:  optional(v.NextChargeTicks, func(v uint32) *uint32 { return pointer(v) }),
		FireReadyAt:      uint32(v.FireReadyAt),
		Assignments:      list(v.Assignments, func(v sim.InterceptionAssignment) *pb.InterceptionAssignment { return toInterceptionAssignment(v) }),
	}
}
func toJob(v sim.Job) *pb.Job {
	return &pb.Job{
		Type:      text(v.Type),
		Research:  v.Research,
		Paid:      v.Paid,
		Work:      v.Work,
		Required:  v.Required,
		Supply:    v.Supply,
		Service:   uint32(v.Service),
		Started:   v.Started,
		Emergency: v.Emergency,
	}
}
func toMemory(v sim.Memory) *pb.Memory {
	return &pb.Memory{
		Id:              uint32(v.ID),
		Type:            text(v.Type),
		Owner:           uint32(v.Owner),
		Position:        toVec(v.Position),
		Seen:            uint32(v.Seen),
		FootprintWidth:  v.FootprintWidth,
		FootprintHeight: v.FootprintHeight,
		FootprintType:   text(v.FootprintType),
	}
}
func toMetadata(v sim.Metadata) *pb.Metadata {
	return &pb.Metadata{
		Simulation:  text(v.Simulation),
		Protocol:    v.Protocol,
		ContentHash: text(v.ContentHash),
		MapVersion:  text(v.MapVersion),
		Ruleset:     text(v.Ruleset),
		Seed:        v.Seed,
	}
}
func toMissionProgress(v sim.MissionView) *pb.MissionProgress {
	return &pb.MissionProgress{
		Id:             text(v.ID),
		Title:          text(v.Title),
		Difficulty:     text(v.Difficulty),
		Checkpoint:     text(v.Checkpoint),
		CheckpointTick: uint32(v.CheckpointTick),
		Objectives:     list(v.Objectives, func(v sim.ObjectiveView) *pb.ObjectiveProgress { return toObjectiveProgress(v) }),
		Convoys:        list(v.Convoys, func(v sim.ConvoyState) *pb.ConvoyProgress { return toConvoyProgress(v) }),
		Version:        text(v.Version),
		PublicTasks:    list(v.PublicTasks, func(v sim.MissionTaskView) *pb.MissionPublicTask { return toMissionPublicTask(v) }),
	}
}
func toMissionPublicTask(v sim.MissionTaskView) *pb.MissionPublicTask {
	return &pb.MissionPublicTask{
		Id:        text(v.ID),
		Objective: text(v.Objective),
		Kind:      text(v.Kind),
		Marker:    text(v.Marker),
		Region:    text(v.Region),
		Team:      v.Team,
		Min:       toVec(v.Min),
		Max:       toVec(v.Max),
	}
}
func toObjectiveProgress(v sim.ObjectiveView) *pb.ObjectiveProgress {
	return &pb.ObjectiveProgress{
		Id:       text(v.ID),
		Text:     text(v.Text),
		Optional: v.Optional,
		Failure:  v.Failure,
		Complete: v.Complete,
		Progress: v.Progress,
		Required: v.Required,
	}
}
func toOperationWarning(v sim.OperationWarning) *pb.OperationWarning {
	return &pb.OperationWarning{
		Kind:     text(v.Kind),
		Owner:    uint32(v.Owner),
		Position: toVec(v.Position),
		At:       uint32(v.At),
		Source:   uint32(v.Source),
		Exits:    list(v.Exits, func(v content.Point) *pb.Vec { return toVec(v) }),
		Splash:   optional(v.Splash, func(v int32) *int32 { return pointer(v) }),
	}
}
func toOrder(v sim.Order) *pb.Order {
	return &pb.Order{
		Kind:     text(v.Kind),
		Entities: list(v.Entities, func(v sim.ID) uint32 { return uint32(v) }),
		Target:   uint32(v.Target),
		Position: toVec(v.Position),
		Type:     text(v.Type),
		Queued:   v.Queued,
		Index:    v.Index,
		Points:   list(v.Points, func(v content.Point) *pb.Vec { return toVec(v) }),
	}
}
func toOrderResult(v sim.OrderResult) *pb.OrderResult {
	return &pb.OrderResult{
		Player:           uint32(v.Player),
		Sequence:         v.Sequence,
		Index:            v.Index,
		Accepted:         v.Accepted,
		Code:             text(v.Code),
		Tick:             uint32(v.Tick),
		EligibleEntities: list(v.EligibleEntities, func(v sim.ID) uint32 { return uint32(v) }),
		AppliedCount:     uint32(v.AppliedCount),
	}
}
func toOutcome(v sim.Outcome) *pb.Outcome {
	return &pb.Outcome{
		Finished:    v.Finished,
		Draw:        v.Draw,
		WinningTeam: v.WinningTeam,
		Reason:      text(v.Reason),
		Tick:        uint32(v.Tick),
	}
}
func toPlayerSnapshot(v sim.View) *pb.PlayerSnapshot {
	return &pb.PlayerSnapshot{
		Metadata:    toMetadata(v.Metadata),
		Tick:        uint32(v.Tick),
		Countdown:   v.Countdown,
		Player:      uint32(v.Player),
		Economy:     toEconomy(v.Economy),
		Players:     list(v.Players, func(v sim.PlayerSummary) *pb.PlayerSummary { return toPlayerSummary(v) }),
		Entities:    list(v.Entities, func(v sim.EntityView) *pb.Entity { return toEntity(v) }),
		Projectiles: list(v.Projectiles, func(v sim.ProjectileView) *pb.Projectile { return toProjectile(v) }),
		Fields:      list(v.Fields, func(v sim.FieldView) *pb.Field { return toField(v) }),
		Stations:    list(v.Stations, func(v sim.StationView) *pb.Station { return toStation(v) }),
		Explored:    list(v.Explored, func(v bool) bool { return v }),
		Visible:     list(v.Visible, func(v bool) bool { return v }),
		Memory:      list(v.Memory, func(v sim.Memory) *pb.Memory { return toMemory(v) }),
		Events:      list(v.Events, func(v sim.Event) *pb.Event { return toEvent(v) }),
		Results:     list(v.Results, func(v sim.OrderResult) *pb.OrderResult { return toOrderResult(v) }),
		ShipmentAt:  uint32(v.ShipmentAt),
		Outcome:     toOutcome(v.Outcome),
		Salvage:     list(v.Salvage, func(v sim.Salvage) *pb.Salvage { return toSalvage(v) }),
		Zones:       list(v.Zones, func(v sim.ZoneView) *pb.Zone { return toZone(v) }),
		Indicators:  list(v.Indicators, func(v sim.StructureIndicator) *pb.StructureIndicator { return toStructureIndicator(v) }),
		Mission:     optional(v.Mission, func(v sim.MissionView) *pb.MissionProgress { return toMissionProgress(v) }),
		Rubble:      list(v.Rubble, func(v uint32) uint32 { return v }),
		Warnings:    list(v.Warnings, func(v sim.OperationWarning) *pb.OperationWarning { return toOperationWarning(v) }),
		Debrief:     optional(v.Debrief, func(v sim.Debrief) *pb.Debrief { return toDebrief(v) }),
		KnownFields: list(v.KnownFields, func(v sim.FieldObservation) *pb.FieldObservation { return toFieldObservation(v) }),
	}
}
func toPlayerSummary(v sim.PlayerSummary) *pb.PlayerSummary {
	return &pb.PlayerSummary{
		Id:                uint32(v.ID),
		Name:              text(v.Name),
		Faction:           text(v.Faction),
		Team:              v.Team,
		Defeated:          v.Defeated,
		DefeatAt:          uint32(v.DefeatAt),
		StrategicProgress: v.StrategicProgress,
		SurrenderVote:     v.SurrenderVote,
		Color:             v.Color,
	}
}
func toPlayerTelemetry(v sim.PlayerTelemetry) *pb.PlayerTelemetry {
	return &pb.PlayerTelemetry{
		Player:               uint32(v.Player),
		UnitsProduced:        list(v.UnitsProduced, func(v sim.ProductionCount) *pb.ProductionCount { return toProductionCount(v) }),
		BuildingsConstructed: list(v.BuildingsConstructed, func(v sim.ProductionCount) *pb.ProductionCount { return toProductionCount(v) }),
		UnitsLost:            v.UnitsLost,
		BuildingsLost:        v.BuildingsLost,
		RepairSpent:          v.RepairSpent,
		MissileSpent:         v.MissileSpent,
		InterceptorsFired:    v.InterceptorsFired,
		StationControlTicks:  v.StationControlTicks,
		Timeline:             list(v.Timeline, func(v sim.EconomySample) *pb.EconomySample { return toEconomySample(v) }),
	}
}
func toProductionCount(v sim.ProductionCount) *pb.ProductionCount {
	return &pb.ProductionCount{
		Type:  text(v.Type),
		Count: v.Count,
	}
}
func toProjectile(v sim.ProjectileView) *pb.Projectile {
	return &pb.Projectile{
		Id:              uint32(v.ID),
		Owner:           uint32(v.Owner),
		Weapon:          text(v.Weapon),
		Position:        toVec(v.Position),
		Impact:          toVec(v.Impact),
		ImpactAt:        uint32(v.ImpactAt),
		Interceptable:   v.Interceptable,
		Warning:         v.Warning,
		Splash:          pointer(v.Splash),
		PositionVisible: pointer(v.PositionVisible),
	}
}
func toSalvage(v sim.Salvage) *pb.Salvage {
	return &pb.Salvage{
		Id:       uint32(v.ID),
		Owner:    uint32(v.Owner),
		Position: toVec(v.Position),
		Value:    v.Value,
		Until:    uint32(v.Until),
	}
}
func toStation(v sim.StationView) *pb.Station {
	return &pb.Station{
		Id:       uint32(v.ID),
		Position: toVec(v.Position),
		Owner:    uint32(v.Owner),
	}
}
func toStatusEffect(v sim.StatusEffect) *pb.StatusEffect {
	return &pb.StatusEffect{
		Kind:  text(v.Kind),
		Until: uint32(v.Until),
	}
}
func toStructureIndicator(v sim.StructureIndicator) *pb.StructureIndicator {
	return &pb.StructureIndicator{
		Owner:    uint32(v.Owner),
		Position: toVec(v.Position),
	}
}
func toVec(v content.Point) *pb.Vec {
	return &pb.Vec{
		X: v.X,
		Y: v.Y,
	}
}
func toZone(v sim.ZoneView) *pb.Zone {
	return &pb.Zone{
		Kind:     text(v.Kind),
		Owner:    uint32(v.Owner),
		Position: toVec(v.Position),
		Radius:   v.Radius,
		Start:    uint32(v.Start),
		Until:    uint32(v.Until),
	}
}
