// Actual frozen App, persistent isolated browser, full pack and a cold offline
// restart. No game/source edits, synthetic simulation calls or deploy.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir,realpath,rm} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'../..'),require=createRequire(path.join(root,'client/package.json'));
const {chromium}=require('playwright-core'),{build}=require('esbuild');
const args=process.argv.slice(2),execute=args.includes('--execute'),run=args.find(x=>/^run-\d+$/.test(x));assert(run,'Supply a new run-N');
const out=path.join(here,run);await mkdir(out);const product=path.join(root,'work/art-generation-consumer-v1/app-v3-build-03/product'),source=path.join(product,'../source/client');
const sha=b=>createHash('sha256').update(b).digest('hex'),pins=new Map(),pin=async(file,expected)=>{const b=await readFile(file),digest=sha(b);if(expected)assert.equal(digest,expected,file);pins.set(file,digest);return b};
const report={started:new Date().toISOString(),status:'preflight',scope:'Full frozen generation-consumer-v3 App with incomplete v25+36 art. Ordinary UI, real Go WASM, complete CacheStorage pack, persistent-browser cold restart with HTTP server closed/offline. No final art, combat victory, multiplayer or release claim.',checks:[],pageErrors:[],consoleErrors:[],requestFailures:[],httpErrors:[],served:{}};
const save=()=>writeFile(path.join(out,'result.json'),JSON.stringify(report,null,2)+'\n'),pause=ms=>new Promise(r=>setTimeout(r,ms));
let phase='preflight',context,page,server,origin,profile=path.join(out,'profile'),pack,listed,observer,executable;
async function until(fn,label,ms=90000){const start=Date.now();for(;;){const result=await fn();if(result)return result;if(Date.now()-start>ms)throw Error(label);await pause(100)}}
async function idle(){await until(async()=>{assert.equal(await page.getByRole('heading',{name:'Command interrupted',exact:true}).count(),0,await page.locator('body').innerText());return await page.locator('.loading-screen').count()===0},'App remained busy',180000)}
const read=(large=false)=>page.evaluate(large=>window.__stockQA.read(large),large);
async function record(label,data={}){report.checks.push({label,at:new Date().toISOString(),...data});await save()}
async function menu(name){await page.getByRole('navigation',{name:'Main menu'}).getByRole('button',{name,exact:true}).click();await idle()}
async function scene(){await page.locator('.battlefield-canvas canvas').waitFor();await until(async()=>await page.locator('.scene-loading,.loading-screen').count()===0,'Scene remained loading',180000);await idle()}
async function paused(){await page.getByRole('button',{name:'Open pause menu',exact:true}).click();await page.getByRole('dialog').waitFor();await until(async()=>(await read()).clock?.paused===true,'Worker did not pause');await idle()}
async function leave(){if(!await page.getByRole('dialog').count())await paused();await page.getByRole('dialog').getByRole('button',{name:'Return to command center',exact:true}).click();await idle();await page.getByRole('navigation',{name:'Main menu'}).waitFor();await until(async()=>{const life=await page.evaluate(()=>window.multiplayerCombat.lifetime());return life.phase==='menu'&&!life.transportPresent&&life.frameSubscribers===0&&life.art.residentPages===0},'Session resources retained');await record('menu-cleanup')}
async function launch(offline=false){context=await chromium.launchPersistentContext(profile,{executablePath:executable,headless:false,viewport:{width:1600,height:900},offline,args:['--mute-audio']});await context.addInitScript({content:observer});page=await context.newPage();page.setDefaultTimeout(90000);report.browser=context.browser()?.version();page.on('pageerror',e=>report.pageErrors.push({phase,message:e.message}));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({phase,message:m.text(),location:m.location()})});page.on('requestfailed',r=>report.requestFailures.push({phase,url:r.url(),message:r.failure()?.errorText}));page.on('response',r=>{if(r.status()>=400)report.httpErrors.push({phase,url:r.url(),status:r.status()})});}
try{
 await pin(fileURLToPath(import.meta.url));const receipt=JSON.parse(await pin(path.join(product,'../build.json'),'f714d2d6c761dc9b389f91034f361e4662f0c420e42905b1229b1ee76d7cd445'));
 for(const [name,digest]of Object.entries(receipt.sourceFiles))await pin(path.join(source,name),digest);
 const packBytes=await pin(path.join(product,'assets/packs/base.json'),receipt.product.packSHA256);pack=JSON.parse(packBytes);listed=new Map(pack.files.map(f=>[f.path,f]));listed.set('/assets/packs/base.json',{bytes:packBytes.length,sha256:sha(packBytes)});
 const {verifyProduct}=await import(pathToFileURL(path.join(root,'scripts/package-integrity.mjs')).href);report.product=await verifyProduct(product);await pin(path.join(root,'scripts/package-integrity.mjs'));
 const identity=JSON.parse(await pin(path.join(root,'work/tools/browsers/20260929-prerequisites/executables.json'))),app=identity['Google Chrome.app'];assert(app?.executable&&app.executable_sha256);executable=app.executable;await pin(executable,app.executable_sha256);report.executable=app;
 const observe=path.join(root,'client/tests/stock-browser/observe.mjs');await pin(observe);
 const built=await build({entryPoints:[observe],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022',nodePaths:[path.join(root,'client/node_modules')],plugins:[{name:'frozen-protocol',setup(b){b.onResolve({filter:/^\.\.\/\.\.\/src\//},a=>a.importer===observe?{path:path.join(source,'src',a.path.slice('../../src/'.length)+'.ts')}:undefined)}}]});observer=built.outputFiles[0].text;await writeFile(path.join(out,'observer.js'),observer);report.observerSHA256=sha(observer);
 if(!execute){report.status='prepared-only';report.noBrowserOrServer=true}else{
  const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.wasm':'application/wasm','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp','.ttf':'font/ttf','.woff2':'font/woff2','.ogg':'audio/ogg','.mp3':'audio/mpeg','.md':'text/markdown'};
  server=createServer(async(req,res)=>{try{assert(['GET','HEAD'].includes(req.method));const route=decodeURIComponent(new URL(req.url,'http://local').pathname),key=route==='/'?'/index.html':route,item=listed.get(key);assert(item,'Unlisted '+key);const file=await realpath(path.join(product,key.slice(1)));assert(file.startsWith(product+path.sep));const bytes=await readFile(file);assert.equal(bytes.length,item.bytes);assert.equal(sha(bytes),item.sha256);report.served[key]={bytes:bytes.length,sha256:item.sha256};res.setHeader('Content-Type',mime[path.extname(key)]??'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(req.method==='HEAD'?undefined:bytes)}catch(error){report.httpErrors.push({phase,url:req.url,serverError:String(error)});res.statusCode=404;res.end('Frozen resource unavailable')}});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;report.origin=origin;
  phase='online-solo';await launch();await page.goto(origin);await page.getByRole('button',{name:'Explore game modes',exact:true}).click();await idle();await menu('Options');await page.getByLabel('Art quality',{exact:true}).selectOption('standard');await menu('Skirmish');await page.getByLabel('Battlefield',{exact:true}).selectOption('copper-junction');await page.getByLabel('AI commanders',{exact:true}).selectOption('1');await page.getByLabel('Difficulty',{exact:true}).selectOption('easy');await page.getByRole('button',{name:'Deploy forces',exact:true}).click();await scene();await until(async()=>(await read()).latest?.tick>120,'Real Go countdown');
  await page.locator('.sidebar-utilities').getByRole('button',{name:'HQ',exact:true}).click();await page.getByRole('tab',{name:'vehicles',exact:true}).click();const before=(await read()).latest,ids=before.entities.filter(e=>e.owner===before.player&&e.type==='US.rig').map(e=>e.id);await page.locator('.production-cameo').filter({hasText:'Engineering rig'}).click();await until(async()=>{const v=(await read()).latest;return v.entities.some(e=>e.owner===v.player&&e.type==='US.rig'&&!ids.includes(e.id)&&e.complete)},'Paid rig completion');await record('ordinary-paid-production');
  await paused();await page.getByRole('dialog').getByRole('button',{name:'Save operation',exact:true}).click();await idle();await until(async()=> (await page.locator('.notice').innerText()).includes('Saved: '),'Save notice');const savedName=(await page.locator('.notice span').innerText()).slice(7),manual=(await read(true)).saves.at(-1);report.savedName=savedName;assert(manual?.hash&&manual.engine);report.saved={tick:manual.tick,hash:manual.hash};await writeFile(path.join(out,'manual.engine.json'),manual.engine);await page.getByRole('dialog').getByRole('button',{name:'Archive replay',exact:true}).click();await idle();await leave();
  phase='install-full-pack';await menu('Installed content');await page.getByRole('button',{name:'Install',exact:true}).click();await idle();await page.getByText('Available offline',{exact:true}).waitFor();
  report.cache=await page.evaluate(async expected=>{const names=await caches.keys(),valid=[];for(const name of names){const cache=await caches.open(name),ready=await cache.match('/__frontline_pack_ready__');if(!ready)continue;const marker=await ready.json();if(marker.version!==expected.version)continue;const failures=[];let bytes=0;for(const file of expected.files){const response=await cache.match(file.path);if(!response){failures.push(file.path+':missing');continue}const body=await response.arrayBuffer(),hex=[...new Uint8Array(await crypto.subtle.digest('SHA-256',body))].map(v=>v.toString(16).padStart(2,'0')).join('');if(body.byteLength!==file.bytes||hex!==file.sha256)failures.push(file.path+':changed');bytes+=body.byteLength}const manifest=await cache.match('/__frontline_pack_manifest__');valid.push({name,marker,files:expected.files.length,bytes,failures,keys:(await cache.keys()).length,manifestPresent:!!manifest})}return{valid,controller:navigator.serviceWorker.controller?.scriptURL}},pack);assert.equal(report.cache.valid.length,1);assert.deepEqual(report.cache.valid[0].failures,[]);assert.equal(report.cache.valid[0].keys,pack.files.length+2);assert(report.cache.valid[0].manifestPresent&&report.cache.controller);await record('full-cache-byte-verification',{files:pack.files.length,bytes:report.cache.valid[0].bytes});await page.screenshot({path:path.join(out,'installed.png')});
  await context.close();context=undefined;server.closeAllConnections();await new Promise(r=>server.close(r));report.serverClosedBeforeRestart=true;
  phase='cold-offline-boot';await launch(true);await page.goto(origin);await idle();assert.equal(await page.evaluate(()=>navigator.onLine),false);await menu('Load operation');const row=page.locator('.archive-row').filter({has:page.locator('strong').filter({hasText:savedName})}).first();await row.getByRole('button',{name:'Load',exact:true}).click();await scene();const loaded=await until(async()=>(await read()).replies.find(r=>r.method==='load'&&r.ok),'Real cold load');assert.equal(loaded.result.tick,manual.tick);await until(async()=>(await read()).saves.some(s=>s.hash===manual.hash&&s.tick===manual.tick),'Exact cold loaded hash');await record('cold-offline-save-loaded',report.saved);await page.screenshot({path:path.join(out,'cold-save.png')});await leave();
  phase='cold-offline-replay';await menu('Replay archive');await page.locator('.archive-row').filter({hasText:'Copper Junction'}).getByRole('button',{name:'Watch',exact:true}).click();await scene();const timeline=page.getByLabel('Replay timeline',{exact:true});assert.equal(Number(await timeline.getAttribute('max')),manual.tick);await timeline.focus();await timeline.press('End');await until(async()=>(await read()).latest?.tick===manual.tick,'Cold replay end');assert.equal(await page.locator('.production-cameo').count(),0);await timeline.press('Home');await until(async()=>(await read()).latest?.tick===0,'Cold replay opening');await record('cold-offline-replay-seek');await page.screenshot({path:path.join(out,'cold-replay.png')});await leave();report.observation=await read(true);
  assert.equal(report.observation.overflow,false);for(const name of ['errors','consoleErrors','httpErrors'])assert.deepEqual(report.observation[name],[],name);assert.deepEqual(report.pageErrors,[]);assert.deepEqual(report.consoleErrors,[]);assert.deepEqual(report.httpErrors,[]);report.functionalStatus='passed';report.status=report.requestFailures.length?'strict-failed-raw-request-diagnostics':'passed';if(report.requestFailures.length)process.exitCode=1;
 }
}catch(error){report.status='failed';report.failedPhase=phase;report.error=String(error.stack??error);process.exitCode=1;if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});}
finally{if(context)await context.close();if(server?.listening){server.closeAllConnections();await new Promise(r=>server.close(r))}for(const [file,digest]of pins)assert.equal(sha(await readFile(file)),digest,'Input changed:'+file);report.inputsVerifiedAfter=pins.size;report.inputs=Object.fromEntries(pins);report.closedAt=new Date().toISOString();await save();if(execute)await rm(profile,{recursive:true,force:true});console.log(JSON.stringify({out,status:report.status,phase,error:report.error,rawFailures:report.requestFailures.length}));}
