import test from 'node:test';
import assert from 'node:assert/strict';
import {budgets,controls,hash,verifyAdmission,verifyConfig,paidPowerProof,withoutControlBodies} from './course.mjs';
function admission(){const files=['/runtime/frontline.wasm','/runtime/worker.js','/runtime/version.json','/art/index.json','/content/index.json'].map(path=>({path,bytes:3,sha256:'a'.repeat(64)})),packBytes=Buffer.from(JSON.stringify({id:'base',version:'v1',files})),config={format:1,product:'/product',artifact:'/package/version.json',artifactSHA256:'b'.repeat(64),packSHA256:hash(packBytes),protocolFile:'/source/pb.ts',protocolSHA256:'c'.repeat(64),executable:'/chrome',executableSHA256:'d'.repeat(64),map:'copper-junction',quality:'standard',artScope:'Incomplete current art, explicit bounded course only'},artifact={source_inputs:{sha256:'f'.repeat(64)},presentation_inputs:{sha256:'e'.repeat(64)},product_pack:{packSHA256:config.packSHA256,files:5,bytes:15}};return {config,artifact,packBytes}}
test('selected ordinary-build artifact must bind exact product pack before any launch',()=>{assert.equal(verifyAdmission(admission()).files,5);const a=admission();a.artifact.product_pack.packSHA256='0'.repeat(64);assert.throws(()=>verifyAdmission(a),/Root ordinary-build/);const b=admission();delete b.artifact.presentation_inputs;assert.throws(()=>verifyAdmission(b),/source identities/)});
test('all preflight/course/memory budgets and selected controls remain finite',()=>{assert.equal(budgets.courseMs,240000);assert.equal(budgets.preflightMs,120000);assert.equal(controls.length,4);for(const c of controls)assert(c.bytes<=budgets.maxControlBytes);const c=admission().config;delete c.protocolSHA256;assert.throws(()=>verifyConfig(c))});
test('art body beyond fixed hash cap, duplicate or unsafe URL is rejected',()=>{
 for(const modify of [p=>p.files[3].bytes=64*1024**2+1,p=>p.files.push(p.files[3]),p=>p.files[3].path='/art/../secret']){const a=admission(),p=JSON.parse(a.packBytes);modify(p);a.packBytes=Buffer.from(JSON.stringify(p));a.config.packSHA256=a.artifact.product_pack.packSHA256=hash(a.packBytes);assert.throws(()=>verifyAdmission(a))}
});
test('control filtering removes only exact control URLs and preserves global observer faults',()=>{const s={faults:['overflow'],network:[{url:'http://local/art/a.png'},{url:'http://local'+controls[0].path}],failures:[{url:'http://local/art/a.png'}],traces:[{faults:['missing-snapshot'],records:[{url:'http://local'+controls[0].path},{url:'http://local/art/a.png'}]}]};const v=withoutControlBodies(s);assert.equal(v.network.length,1);assert.equal(v.failures.length,1);assert.equal(v.traces[0].records.length,1);assert.deepEqual(v.faults,s.faults);assert.deepEqual(v.traces[0].faults,s.traces[0].faults)});
function paid(){const power={id:2,type:'power',owner:1,complete:true,position:{x:3000,y:4000}};return {opening:{player:1,entities:[]},observation:{requests:[{method:'submit',batch:{sequence:1,orders:[{kind:'build',type:'power',position:power.position}]}}],results:[{player:1,sequence:1,index:0,accepted:true,tick:125}],latest:{entities:[power]},powerRule:{cost:700000},saves:[{hash:'hash',tick:800,ownedPower:[{...power,paid:700000}]}]}}}
test('paid construction needs matching accepted order, new owner structure and saved real price',()=>{const a=paid();assert.equal(paidPowerProof(a.observation,a.opening).paid,700000);for(const change of [v=>v.observation.results[0].accepted=false,v=>v.observation.saves[0].ownedPower[0].paid=0,v=>v.observation.requests.push(v.observation.requests[0]),v=>v.opening.entities.push(v.observation.latest.entities[0]),v=>v.observation.saves[0].ownedPower[0].position={x:0,y:0}]){const b=paid();change(b);assert.throws(()=>paidPowerProof(b.observation,b.opening))}});
