import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,realpath} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {spawn,execFileSync} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {WebDriver,WebDriverError,until,control,find,click,select} from './w3c.mjs';
const root=fileURLToPath(new URL('../../../',import.meta.url));
const flags=process.argv.slice(2),args={};assert.equal(flags.length%2,0,'Use paired --product --out --browser firefox|safari [--author-preflight true] [--driver-port N]');
for(let i=0;i<flags.length;i+=2){assert(['--product','--out','--browser','--author-preflight','--driver-port'].includes(flags[i]));assert(!Object.hasOwn(args,flags[i]));args[flags[i]]=flags[i+1]}
assert(args['--product']&&args['--out']);const browser=args['--browser']??'firefox';assert(['firefox','safari'].includes(browser));assert(args['--author-preflight']===undefined||['true','false'].includes(args['--author-preflight']));
const preflight=args['--author-preflight']==='true',product=await realpath(path.resolve(args['--product'])),out=path.resolve(args['--out']),driverPort=Number(args['--driver-port']??(browser==='firefox'?4445:4446));assert(Number.isSafeInteger(driverPort)&&driverPort>1024&&driverPort<65536);await mkdir(path.dirname(out),{recursive:true});await mkdir(out);
const sha=bytes=>createHash('sha256').update(bytes).digest('hex'),write=(name,data)=>writeFile(path.join(out,name),typeof data==='string'?data:JSON.stringify(data,null,2)+'\n');
const prerequisite=path.join(root,'work/tools/browsers/20260929-prerequisites'),report={started:new Date().toISOString(),status:'preflight',browser,product,preflight,checks:[],httpErrors:[],served:{},scope:'Genuine stock browser, full immutable v23 App, ordinary solo versus Go bot. UI input only; passive worker/view/export observations. OS download dispatch intercepted; no paid-opening completion, combat victory, full audio, offline install, performance, long-session or release claim.'};
let wd,server,child,driverLog='',phase='preflight',observerBytes,baseline=0;
const guards=new Map(),pin=async(file,expected)=>{const b=await readFile(file);assert.equal(sha(b),expected,'Frozen input changed: '+file);guards.set(file,expected);return b};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const record=async(label,data)=>{report.checks.push({label,time:new Date().toISOString(),...data});await write('result.json',report)};
try{
 const buildFile=path.join(product,'../build.json'),receiptBytes=await pin(buildFile,'0debf4ba46647aa0af24d95ba216463f2ef0025e67b850ffa1749543fbe91777'),receipt=JSON.parse(receiptBytes),source=path.join(product,'../source/client');
 for(const[name,digest]of Object.entries(receipt.sourceFiles))await pin(path.join(source,name),digest);
 const packBytes=await pin(path.join(product,'assets/packs/base.json'),receipt.pack),pack=JSON.parse(packBytes),listed=new Map(pack.files.map(f=>[f.path,f]));
 report.productCore={};for(const key of ['/index.html','/runtime/version.json','/runtime/frontline.wasm','/runtime/worker.js','/runtime/wasm_exec.js']){const item=listed.get(key);assert(item);const bytes=await pin(path.join(product,key.slice(1)),item.sha256);assert.equal(bytes.length,item.bytes);report.productCore[key]=item}
 const identity=JSON.parse(await readFile(path.join(prerequisite,'executables.json'))),verification=JSON.parse(await readFile(path.join(prerequisite,'verification.json'))),safari=JSON.parse(await readFile(path.join(prerequisite,'safari.json')));
 const app=identity[browser==='firefox'?'Firefox.app':'Safari.app'],driver=browser==='firefox'?identity.geckodriver.executable:'/usr/bin/safaridriver';
 await pin(app.executable,browser==='firefox'?app.executable_sha256:safari[app.executable].sha256);await pin(driver,browser==='firefox'?identity.geckodriver.sha256:safari['/usr/bin/safaridriver'].sha256);
 const appPath=app.executable.split('/Contents/')[0];execFileSync('codesign',['--verify','--deep','--strict',appPath],{stdio:'pipe'});execFileSync('codesign',['--verify','--strict',driver],{stdio:'pipe'});
 report.identity={buildSHA256:sha(receiptBytes),sourceDigest:receipt.sourceDigest,packSHA256:sha(packBytes),runtime:JSON.parse(await readFile(path.join(product,'runtime/version.json'))),app,driver,appSignature:browser==='firefox'?verification.apps['Firefox.app'].commands.signature:safari['safari-signature'],driverSignature:browser==='firefox'?verification.geckodriver.signature:safari['driver-signature']};
 const observe=fileURLToPath(new URL('observe.mjs',import.meta.url));
 const built=await build({entryPoints:[observe],bundle:true,write:false,format:'iife',platform:'browser',target:'es2022',nodePaths:[path.join(root,'client/node_modules')],plugins:[{name:'frozen-protocol',setup(b){b.onResolve({filter:/^\.\.\/\.\.\/src\//},a=>a.importer===observe?{path:path.join(source,'src',a.path.slice('../../src/'.length)+'.ts')}:undefined)}}]});observerBytes=built.outputFiles[0].contents;await writeFile(path.join(out,'observer.js'),observerBytes);
 report.identity.observerBundleSHA256=sha(observerBytes);report.identity.sources={};for(const name of ['product-smoke.mjs','observe.mjs','w3c.mjs']){const bytes=await readFile(new URL(name,import.meta.url));report.identity.sources[name]=sha(bytes);await writeFile(path.join(out,name),bytes)}
 const appSource=await readFile(path.join(source,'src/ui/App.tsx'),'utf8');for(const needle of ['Explore game modes','Deploy forces','Save operation','Archive replay','Return to command center'])assert(appSource.includes(needle),`UI contract missing ${needle}`);
 if(preflight){report.status='author-preflight-passed';report.noBrowserOrHostStarted=true}else{
  const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript','.css':'text/css','.wasm':'application/wasm','.json':'application/json','.png':'image/png','.svg':'image/svg+xml','.webp':'image/webp','.woff2':'font/woff2','.ogg':'audio/ogg','.mp3':'audio/mpeg','.ico':'image/x-icon'};
  server=createServer(async(req,res)=>{try{assert(['GET','HEAD'].includes(req.method));const route=decodeURIComponent(new URL(req.url,'http://local').pathname);if(route==='/__qa/observe.js'){res.setHeader('content-type','text/javascript');res.end(observerBytes);return}const key=route==='/'?'/index.html':route,item=listed.get(key);assert(item,'Unlisted product file '+key);const file=await realpath(path.join(product,key.slice(1)));assert(file.startsWith(product+path.sep));let bytes=await readFile(file);assert.equal(bytes.length,item.bytes);assert.equal(sha(bytes),item.sha256);report.served[key]={bytes:bytes.length,sha256:item.sha256};if(key==='/index.html'){const html=bytes.toString();assert(html.includes('<head>'));bytes=Buffer.from(html.replace('<head>','<head><script src="/__qa/observe.js"></script>'))}res.setHeader('content-type',mime[path.extname(key)]??'application/octet-stream');res.setHeader('cache-control','no-store');res.end(req.method==='HEAD'?undefined:bytes)}catch(error){report.httpErrors.push({phase,url:req.url,error:String(error)});res.statusCode=404;res.end('Frozen product resource unavailable')}});
  await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;report.origin=origin;
  // Port ownership is checked without borrowing or killing another driver.
  const probe=createServer();await new Promise((r,j)=>{probe.once('error',j);probe.listen(driverPort,'127.0.0.1',r)});await new Promise(r=>probe.close(r));
  const driverArgs=browser==='firefox'?['--host','127.0.0.1','--port',String(driverPort),'--log','info']:['--port',String(driverPort)];
  phase='driver-start';child=spawn(driver,driverArgs,{stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>driverLog+=b);child.stderr.on('data',b=>driverLog+=b);child.on('error',e=>driverLog+='\n'+e.stack);report.driverCommand=[driver,...driverArgs];
  wd=new WebDriver(`http://127.0.0.1:${driverPort}`);await until(async()=>{if(child.exitCode!==null)throw Error(`Driver exited ${child.exitCode}: ${driverLog}`);try{return await wd.request('GET','/status')}catch(e){if(e instanceof WebDriverError)throw e;return false}},'local driver readiness',{timeout:15000});
  const capabilities={browserName:browser,acceptInsecureCerts:false,pageLoadStrategy:'normal',strictFileInteractability:false,...(browser==='firefox'?{'moz:firefoxOptions':{binary:app.executable,args:[],prefs:{'browser.shell.checkDefaultBrowser':false}}}:{})};
  phase='new-session';report.requestedCapabilities=capabilities;await wd.create(capabilities);report.actualCapabilities=wd.capabilities;assert.equal(wd.capabilities.browserName.toLowerCase(),browser);assert.equal(wd.capabilities.browserVersion,app.version,'Driver launched a different browser version');
  await wd.call('POST','/timeouts',{implicit:0,pageLoad:120000,script:30000});await wd.call('POST','/window/rect',{width:1600,height:1000,x:0,y:0});
  await wd.navigate(origin);phase='welcome';await control(wd,'[role="dialog"]',{text:undefined});await click(wd,'button',{text:'Explore game modes'});
  const read=(large=false)=>wd.execute('return window.__stockQA.read(arguments[0]);',large),snapshot=async()=>{const d=await read();assert(d.latest,'No actual Go perspective frame');return d.latest};
  const btn=(text,scope)=>click(wd,'button',{text,scope});
  const idle=()=>until(async()=>{const s=await wd.execute('return {loading:!!document.querySelector(".loading-screen"),error:[...document.querySelectorAll("[role=dialog]")].find(n=>n.textContent.includes("Command interrupted"))?.innerText};');assert(!s.error,s.error);return !s.loading},'product idle',{timeout:120000});
  const scene=async()=>{await control(wd,'.battlefield-canvas canvas');await until(()=>wd.execute('return !document.querySelector(".scene-loading,.loading-screen")'),'battlefield assets',{timeout:120000});await idle()};
  const shot=async(label)=>{await writeFile(path.join(out,label+'.png'),Buffer.from(await wd.screenshot(),'base64'));await write(label+'.txt',await wd.execute('return document.body.innerText;'));await record(label,{tick:(await read()).latest?.tick,geometry:await wd.execute('return {width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,canvases:document.querySelectorAll("canvas").length};')})};
  const pauseMenu=async()=>{await click(wd,'button[aria-label="Open pause menu"]');await control(wd,'[role="dialog"]');await until(async()=>(await read()).clock?.paused===true,'real worker paused');await idle()};
  const leave=async()=>{if(!await find(wd,'[role="dialog"]'))await pauseMenu();await btn('Return to command center','[role="dialog"]');await idle();await control(wd,'nav[aria-label="Main menu"]');await until(async()=>{const d=await read();return d.workers.filter(w=>w.live).length===baseline&&await wd.execute('return !document.querySelector(".battlefield-canvas canvas,.replay-controls,.targeting-hint")')},'session/menu cleanup');await record('menu-cleanup',{liveGoWorkers:baseline})};
  const menu=text=>btn(text,'nav[aria-label="Main menu"]');
  await idle();baseline=(await read()).workers.filter(w=>w.live).length;await shot('welcome-completed');
  phase='settings';await menu('Options');await select(wd,'select[aria-label="Health bars"]','always');await select(wd,'select[aria-label="Art quality"]','standard');await select(wd,'select[aria-label="Interface scale"]','1.15');await btn('Reload saved preferences');await idle();assert.equal(await wd.execute('return document.querySelector(arguments[0]).value;','select[aria-label="Health bars"]'),'always');assert.equal(await wd.execute('return document.querySelector(arguments[0]).value;','select[aria-label="Interface scale"]'),'1.15');await shot('settings-persisted');await select(wd,'select[aria-label="Interface scale"]','1');
  phase='skirmish';await menu('Skirmish');await select(wd,'select[aria-label="Battlefield"]','copper-junction');await select(wd,'select[aria-label="AI commanders"]','1');await select(wd,'select[aria-label="Difficulty"]','easy');await btn('Deploy forces');await scene();await until(async()=>!(await snapshot()).countdown,'ordinary countdown',{timeout:30000});
  const initial=await snapshot(),created=(await read()).create;assert.equal(created.ruleset,'standard-v2');assert.equal(created.players.length,2);assert.equal(created.players[0].faction,'US');assert.equal(created.players[1].ai,'easy');assert(Number.isSafeInteger(created.seed)&&created.seed>0);await record('ordinary-solo-created',{config:created,player:initial.player});
  const rig=initial.entities.find(e=>e.owner===initial.player&&e.type==='US.rig');assert(rig);await btn('Build','.sidebar-utilities');await until(()=>wd.execute('return document.querySelector(".selection-tray h2")?.textContent==="Engineering rig"'),'ordinary rig selection');
  const target={x:rig.position.x+2000,y:rig.position.y+2000},map=created.map;
  const radar=await wd.execute('return document.querySelector(arguments[0]).getBoundingClientRect().toJSON();','[aria-label="Tactical minimap"]');const span=map.width+map.height,s=Math.min((radar.width-12)/span,(radar.height-12)/(span*.5)),ox=(radar.width-span*s)/2+map.height*s,oy=(radar.height-span*s*.5)/2;
  await wd.pointer(radar.x+ox+(target.x-target.y)*s/1000,radar.y+oy+(target.x+target.y)*s/2000);await btn('Move','.command-grid');const canvas=await wd.execute('return document.querySelector(".battlefield-canvas canvas").getBoundingClientRect().toJSON();');await wd.pointer(canvas.x+canvas.width/2,canvas.y+canvas.height/2);
  await until(async()=>{const d=await read(),request=d.requests.find(r=>r.method==='submit'&&r.batch.orders.some(o=>o.kind==='move'&&o.entities.includes(rig.id)));return request&&d.results.some(r=>r.sequence===request.batch.sequence&&r.accepted)},'accepted real move');await until(async()=>{const e=(await snapshot()).entities.find(e=>e.id===rig.id);return e&&Math.hypot(e.position.x-rig.position.x,e.position.y-rig.position.y)>500},'actual owned rig movement');await shot('accepted-move');
  phase='paid-production';await btn('HQ','.sidebar-utilities');await click(wd,'button[role="tab"][aria-label="vehicles"]');const before=await snapshot(),oldIDs=new Set(before.entities.filter(e=>e.owner===before.player&&e.type==='US.rig').map(e=>e.id));await click(wd,'.production-cameo',{text:'Engineering rig'});
  await until(async()=>{const d=await read(),request=d.requests.find(r=>r.method==='submit'&&r.batch.orders.some(o=>o.kind==='train'&&o.type==='US.rig'));return request&&d.results.some(r=>r.sequence===request.batch.sequence&&r.accepted)},'accepted paid train');
  const job=await until(async()=>{const f=await snapshot();return f.entities.flatMap(e=>e.private?.jobs??[]).find(j=>j.type==='US.rig'&&j.started)},'real paid production start');assert(BigInt(job.paid??0)>0n,'Queued job was not paid');await record('paid-job-started',{job});
  const produced=await until(async()=>{const f=await snapshot();return f.entities.find(e=>e.owner===f.player&&e.type==='US.rig'&&!oldIDs.has(e.id)&&e.complete)},'ordinary completed rig',{timeout:90000});await record('paid-rig-completed',{id:produced.id});await shot('paid-production-completed');
  phase='pause-save';await pauseMenu();const tick=(await snapshot()).tick;await pause(500);assert.equal((await snapshot()).tick,tick);await record('pause-holds-tick',{tick});await btn('Resume operation','[role="dialog"]');await until(async()=>(await snapshot()).tick>tick,'ordinary resume');await pauseMenu();await btn('Save operation','[role="dialog"]');await idle();const notice=await until(()=>wd.execute('return document.querySelector(".notice span")?.textContent?.startsWith("Saved: ")?document.querySelector(".notice span").textContent:null;'),'manual save notice');const savedName=notice.slice(7);const manual=(await read(true)).saves.at(-1);assert(manual?.hash&&manual.engine);await write('manual-save.engine.json',manual.engine);await btn('Archive replay','[role="dialog"]');await idle();await until(()=>wd.execute('return document.querySelector(".notice")?.textContent.includes("Replay stored in your local archive.");'),'replay archived');await shot('manual-save-and-replay');await leave();
  phase='export-import-load';await menu('Load operation');const row=await until(()=>wd.execute('return [...document.querySelectorAll(".archive-row")].find(n=>n.querySelector("strong")?.textContent===arguments[0])??null;',savedName),'manual archive row');
  const rowButton=async(element,text)=>{const button=await wd.execute('return [...arguments[0].querySelectorAll("button")].find(n=>n.textContent.trim()===arguments[1]);',element,text);assert(button);await wd.click(button)};
  await rowButton(row,'Export');const exported=await until(async()=>(await read(true)).exports.find(e=>e.ready&&e.name.endsWith('.save.json')),'actual save export blob');const exportBytes=Buffer.from(exported.base64,'base64'),wrapper=JSON.parse(exportBytes);assert.equal(wrapper.hash,manual.hash);assert.equal(wrapper.engine,manual.engine);assert.equal(wrapper.name,savedName);const exportPath=path.join(out,'exported.save.json');await writeFile(exportPath,exportBytes);await record('export-exact',{bytes:exportBytes.length,sha256:sha(exportBytes),hash:wrapper.hash,osDownloadDispatch:false});
  const fileInput=await control(wd,'input[aria-label="Import save"]',{visible:false});await wd.keys(fileInput,exportPath);await idle();await until(()=>wd.execute('return [...document.querySelectorAll(".archive-row strong")].filter(n=>n.textContent===arguments[0]).length===2;',savedName),'import preserved original and added copy');
  // Both identical archive records are valid; click the second matching row and
  // verify exact input bytes/authoritative load reply, not its generated UUID.
  const copy=await wd.execute('return [...document.querySelectorAll(".archive-row")].filter(n=>n.querySelector("strong")?.textContent===arguments[0])[1];',savedName);await rowButton(copy,'Load');await scene();const loaded=(await read()).replies.filter(r=>r.method==='load').at(-1),loadRequest=(await read(true)).requests.filter(r=>r.method==='load').at(-1);assert.equal(loadRequest.engine,manual.engine);assert.equal(loaded.result.tick,manual.tick);assert.equal(loaded.firstFrame.tick,manual.tick);await until(async()=>(await read()).saves.some(s=>s.worker===loaded.worker&&s.hash===manual.hash&&s.tick===manual.tick),'loaded opening save preserved authoritative hash');await record('load-preserved',{tick:manual.tick,hash:manual.hash});await shot('imported-save-loaded');await leave();
  phase='replay';await menu('Replay archive');const replayRow=await until(()=>wd.execute('return [...document.querySelectorAll(".archive-row")].find(n=>n.querySelector("strong")?.textContent==="Copper Junction")??null;'),'replay row');await rowButton(replayRow,'Export');const replayExport=await until(async()=>(await read(true)).exports.find(e=>e.ready&&e.name.endsWith('.replay.json')),'actual replay export blob');await writeFile(path.join(out,'exported.replay.json'),Buffer.from(replayExport.base64,'base64'));await rowButton(replayRow,'Watch');await scene();const timeline=await control(wd,'input[aria-label="Replay timeline"]');const end=Number(await wd.execute('return arguments[0].max;',timeline));assert.equal(end,manual.tick,'Replay end differs from paused saved state');await wd.keys(timeline,'\uE010');await idle();await until(async()=>{const d=await read(),r=d.replies.filter(r=>r.method==='seekReplay').at(-1);return r?.ok&&r.result.tick===end&&(await snapshot()).tick===end},'actual replay end seek');
  const count=(await read()).methods.submit??0;assert.equal(await wd.execute('return document.querySelectorAll(".production-cameo").length'),0);await btn('Build','.sidebar-utilities');await wd.pointer(canvas.x+canvas.width/2,canvas.y+canvas.height/2,2);await pause(300);assert.equal((await read()).methods.submit??0,count,'Read-only replay submitted an order');await shot('replay-end-read-only');await wd.keys(timeline,'\uE011');await idle();await until(async()=>(await snapshot()).tick===0,'replay rewound to actual opening');await record('replay-opening',{tick:0});await pauseMenu();assert.equal(await find(wd,'button',{text:'Save operation',scope:'[role="dialog"]'}),null);await btn('Return to command center','[role="dialog"]');await idle();await until(async()=>(await read()).workers.filter(w=>w.live).length===baseline,'replay worker cleanup');await shot('final-menu');
  const final=await read(true);report.observation=final;assert(!final.overflow,'Observation limit exceeded');for(const key of ['errors','consoleErrors','httpErrors'])assert.deepEqual(final[key],[],key);assert.deepEqual(report.httpErrors,[]);const rejected=final.results.filter(r=>r.player===1&&!r.accepted);assert.deepEqual(rejected,[],'Ordinary UI order rejected');assert.equal(await wd.execute('return document.querySelectorAll(".battlefield-canvas canvas,.replay-controls,.targeting-hint").length'),0);report.status='passed';
 }
}catch(error){report.status=phase==='driver-start'||phase==='new-session'?'setup-failed':'failed';report.failedPhase=phase;report.error=String(error.stack??error);if(error instanceof WebDriverError)report.webdriverError={status:error.status,value:error.value,method:error.method,path:error.path};process.exitCode=1;if(wd?.sessionID){await writeFile(path.join(out,'failure.png'),Buffer.from(await wd.screenshot().catch(()=>''),'base64')).catch(()=>{});report.observation=await wd.execute('return window.__stockQA?.read(true);').catch(()=>null);await write('failure.txt',await wd.execute('return document.body.innerText;').catch(()=>''))}}
finally{
 if(wd?.sessionID)try{await wd.close();report.sessionDeleted=true}catch(e){report.sessionCleanupError=String(e);report.status='failed';process.exitCode=1}
 if(child&&child.exitCode===null){child.kill('SIGTERM');await Promise.race([new Promise(r=>child.once('exit',r)),pause(3000)]);if(child.exitCode===null){child.kill('SIGKILL');report.forcedDriverTermination=true}}
 if(server?.listening){server.closeAllConnections();await new Promise(r=>server.close(r))}
 await write('webdriver.log',driverLog);report.webdriverCommands=wd?.commands??[];
 try{for(const[file,digest]of guards)assert.equal(sha(await readFile(file)),digest,'Frozen input changed: '+file);report.inputsVerifiedAfter=guards.size}catch(e){report.identityFailure=String(e);report.status='failed';process.exitCode=1}
 report.closedAt=new Date().toISOString();await write('result.json',report);console.log(JSON.stringify({status:report.status,out,phase,error:report.error},null,2));
}
