import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import type {Application} from '../app/application';
import {useObservable} from '../app/store';
import {OfflineTransport,type ReplayCommandPage} from '../runtime';
import {formatClock} from '../content/labels';
import {Icon,Modal} from './primitives';
export function ReplayDock({app,host}:{app:Application;host:HTMLElement|null}){
 const state=useObservable(app.state),info=state.session.info,[position,setPosition]=useState<number>(),[log,setLog]=useState(false),[page,setPage]=useState<ReplayCommandPage>(),[offset,setOffset]=useState(0);
 useEffect(()=>{if(!log)return;const runtime=app.sessions.transport;if(!(runtime instanceof OfflineTransport))return;let active=true;void runtime.replayCommands(offset,50).then(result=>{if(active)setPage(result)}).catch(error=>app.error(error));return()=>{active=false}},[app,log,offset]);
 const seek=(tick:number)=>void app.task('Seeking replay…',async()=>{app.audioDirector.discontinuity();await app.sessions.seekReplay(tick);setPosition(undefined)});
 const controls=<section className="replay-controls console" aria-label="Replay controls"><button aria-label={state.paused?'Play replay':'Pause replay'} onClick={()=>void (state.paused?app.sessions.resume():app.sessions.pause()).catch(error=>app.error(error))}><Icon id={state.paused?'i-play':'i-pause'}/>{state.paused?'Play':'Pause'}</button><label>Timeline<input aria-label="Replay timeline" type="range" min={info?.replay_start??0} max={info?.replay_end??1} value={position??state.snapshot?.tick??0} onChange={event=>setPosition(Number(event.target.value))} onPointerUp={event=>seek(Number(event.currentTarget.value))} onKeyUp={event=>{if(['ArrowLeft','ArrowRight','Home','End','PageUp','PageDown'].includes(event.key))seek(Number(event.currentTarget.value))}}/></label><span>{formatClock(position??state.snapshot?.tick??0)} / {formatClock(info?.replay_end??0)}</span><label>Speed<select aria-label="Replay speed" value={state.speed} onChange={event=>void app.sessions.setSpeed(Number(event.target.value) as .75|1|1.5)}>{[.75,1,1.5].map(speed=><option key={speed} value={speed}>{speed}×</option>)}</select></label><label>Perspective<select aria-label="Replay perspective" value={state.snapshot?.player??info?.local_players[0]} onChange={event=>void app.sessions.setPerspective(Number(event.target.value)).catch(error=>app.error(error))}>{info?.local_players.map(id=><option value={id} key={id}>{state.snapshot?.players.find(player=>player.id===id)?.name??`Player ${id}`} · fog</option>)}</select></label><button onClick={()=>setLog(true)}>Order log</button></section>;
 return <>{host&&createPortal(controls,host)}{log&&<Modal title="Replay command log" wide onClose={()=>setLog(false)}><p className="muted">Recorded requests are shown in submission order. Execution can reject an order; consult the replayed result and battlefield. {info?.metadata?.simulation} · {info?.metadata?.ruleset} · map {info?.metadata?.map_version}</p><div className="replay-log">{page?.commands.map((command,index)=><div key={`${offset}-${index}`}><button onClick={()=>seek(command.tick)}>{formatClock(command.tick)}</button><span>Player {command.player}</span><span>{command.orders.map(order=>`${order.kind.replaceAll('_',' ')}${order.type?` ${state.catalog?.name(order.type)??order.type}`:''}`).join(' · ')}</span></div>)}</div><div className="button-row"><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><button disabled={!page?.next} onClick={()=>setOffset(page!.next)}>Next</button></div></Modal>}</>;
}
